ChibiOS/HAL: USB Driver
USB Driver
HAL » Normal Drivers
Generic USB Driver.
Detailed Description
Generic USB Driver.
This module implements a generic USB (Universal Serial Bus) driver supporting device-mode operations.
Precondition
In order to use the USB driver the HAL_USE_USB option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
USB Operations
The USB driver is quite complex and USB is complex in itself, it is recommended to study the USB specification before trying to use the driver.
USB Implementation
The USB driver abstracts the inner details of the underlying USB hardware. The driver works asynchronously and communicates with the application using callbacks. The application is responsible of the descriptors and strings required by the USB device class to be implemented and of the handling of the specific messages sent over the endpoint zero. Standard messages are handled internally to the driver. The application can use hooks in order to handle custom messages or override the handling of the default handling of standard messages.
USB Endpoints
USB endpoints are the objects that the application uses to exchange data with the host. There are two kind of endpoints:
IN endpoints are used by the application to transmit data to the host.
OUT endpoints are used by the application to receive data from the host.
The driver invokes a callback after finishing an IN or OUT transaction. States diagram for OUT endpoints in transaction mode:
States diagram for IN endpoints in transaction mode:
USB Callbacks
The USB driver uses callbacks in order to interact with the application. There are several kinds of callbacks to be handled:
Driver events callback. As example errors, suspend event, reset event etc.
Messages Hook callback. This hook allows the application to implement handling of custom messages or to override the default handling of standard messages on endpoint zero.
Descriptor Requested callback. When the driver endpoint zero handler receives a GET DESCRIPTOR message and needs to send a descriptor to the host it queries the application using this callback.
Start of Frame callback. This callback is invoked each time a SOF packet is received.
Endpoint callbacks. Each endpoint informs the application about I/O conditions using those callbacks.
Macros
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
#define USB_SET_ADDRESS_MODE USB_EARLY_SET_ADDRESS
The address can be changed immediately upon packet reception.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
#define STM32_USB_USE_OTG1 FALSE
OTG1 driver enable switch.
#define STM32_USB_USE_OTG2 FALSE
OTG2 driver enable switch.
#define STM32_USB_OTG1_IRQ_PRIORITY 14
OTG1 interrupt priority level setting.
#define STM32_USB_OTG2_IRQ_PRIORITY 14
OTG2 interrupt priority level setting.
#define STM32_USB_OTG1_RX_FIFO_SIZE 512
OTG1 RX shared FIFO size.
#define STM32_USB_OTG2_RX_FIFO_SIZE 1024
OTG2 RX shared FIFO size.
#define STM32_USE_USB_OTG2_HS TRUE
Enables HS mode on OTG2 else FS mode.
#define STM32_USB_OTG_THREAD_PRIO LOWPRIO
Dedicated data pump threads priority.
#define STM32_USB_OTG_THREAD_STACK_SIZE 128
Dedicated data pump threads stack size.
#define STM32_USB_OTGFIFO_FILL_BASEPRI 0
Exception priority level during TXFIFOs operations.
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
#define USB_MAX_ENDPOINTS STM32_OTG2_ENDPOINTS
Maximum endpoint address.
#define usb_lld_get_transaction_size(usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
#define usb_lld_connect_bus(usbp) ((usbp)->otg->GCCFG |= GCCFG_VBUSBSEN)
Connects the USB device.
#define usb_lld_disconnect_bus(usbp) ((usbp)->otg->GCCFG &= ~GCCFG_VBUSBSEN)
Disconnect the USB device.
#define usb_lld_wakeup_host(usbp)
Start of host wake-up procedure.
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
#define USB_SET_ADDRESS_MODE USB_EARLY_SET_ADDRESS
The address can be changed immediately upon packet reception.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
#define STM32_USB_USE_OTG1 FALSE
OTG1 driver enable switch.
#define STM32_USB_USE_OTG2 FALSE
OTG2 driver enable switch.
#define STM32_USB_OTG1_IRQ_PRIORITY 14
OTG1 interrupt priority level setting.
#define STM32_USB_OTG2_IRQ_PRIORITY 14
OTG2 interrupt priority level setting.
#define STM32_USB_OTG1_RX_FIFO_SIZE 512
OTG1 RX shared FIFO size.
#define STM32_USB_OTG2_RX_FIFO_SIZE 1024
OTG2 RX shared FIFO size.
#define STM32_USE_USB_OTG2_HS TRUE
Enables HS mode on OTG2 else FS mode.
#define STM32_USB_OTG_THREAD_PRIO LOWPRIO
Dedicated data pump threads priority.
#define STM32_USB_OTG_THREAD_STACK_SIZE 128
Dedicated data pump threads stack size.
#define STM32_USB_OTGFIFO_FILL_BASEPRI 0
Exception priority level during TXFIFOs operations.
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
#define USB_MAX_ENDPOINTS STM32_OTG2_ENDPOINTS
Maximum endpoint address.
#define usb_lld_get_transaction_size(usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
#define usb_lld_connect_bus(usbp) ((usbp)->otg->GCCFG |= GCCFG_VBUSBSEN)
Connects the USB device.
#define usb_lld_disconnect_bus(usbp) ((usbp)->otg->GCCFG &= ~GCCFG_VBUSBSEN)
Disconnect the USB device.
#define usb_lld_wakeup_host(usbp)
Start of host wake-up procedure.
#define STM32_OTG1_FIFO_MEM_SIZE 320
OTG_FS FIFO memory size in words.
#define STM32_OTG2_FIFO_MEM_SIZE 1024
OTG_HS FIFO memory size in words.
#define OTG_FS_ADDR 0x50000000
OTG_FS registers block memory address.
#define OTG_HS_ADDR 0x40040000
OTG_HS registers block memory address.
#define OTG_FS ((stm32_otg_t *)OTG_FS_ADDR)
Accesses to the OTG_FS registers block.
#define OTG_HS ((stm32_otg_t *)OTG_HS_ADDR)
Accesses to the OTG_HS registers block.
#define USB_MAX_ENDPOINTS USB_ENDOPOINTS_NUMBER
Maximum endpoint address.
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
#define USB_SET_ADDRESS_MODE USB_LATE_SET_ADDRESS
This device requires the address change after the status packet.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
#define STM32_USB_USE_USB1 FALSE
USB1 driver enable switch.
#define STM32_USB_LOW_POWER_ON_SUSPEND FALSE
Enables the USB device low power mode on suspend.
#define STM32_USB_USB1_HP_IRQ_PRIORITY 13
USB1 interrupt priority level setting.
#define STM32_USB_USB1_LP_IRQ_PRIORITY 14
USB1 interrupt priority level setting.
#define STM32_USB_USE_ISOCHRONOUS FALSE
Enables isochronous support.
#define STM32_USB_USE_FAST_COPY FALSE
Use faster copy for packets.
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
#define usb_lld_get_frame_number(usbp) (STM32_USB->FNR & FNR_FN_MASK)
Returns the current frame number.
#define usb_lld_get_transaction_size(usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
#define usb_lld_connect_bus(usbp) (STM32_USB->BCDR |= USB_BCDR_DPPU)
Connects the USB device.
#define usb_lld_disconnect_bus(usbp) (STM32_USB->BCDR &= ~USB_BCDR_DPPU)
Disconnect the USB device.
#define usb_lld_wakeup_host(usbp)
Start of host wake-up procedure.
#define USB_ENDOPOINTS_NUMBER 7
Number of the available endpoints.
#define STM32_USB_BASE USB_BASE
USB registers block numeric address.
#define STM32_USBRAM_BASE USB_PMAADDR
USB RAM numeric address.
#define STM32_USB ((stm32_usb_t *)STM32_USB_BASE)
Pointer to the USB registers block.
#define STM32_USBRAM ((stm32_usb_pma_t *)STM32_USBRAM_BASE)
Pointer to the USB RAM.
#define EPR_TOGGLE_MASK
Mask of all the toggling bits in the EPR register.
#define USB_GET_DESCRIPTOR(ep)
Returns an endpoint descriptor pointer.
#define USB_ADDR2PTR(addr)
Converts from a PMA address to a physical address.
#define USB_USE_WAIT FALSE
Enables synchronous APIs.
GOTGCTL register bit definitions
#define GOTGCTL_BSVLD (1U<<19)
#define GOTGCTL_ASVLD (1U<<18)
#define GOTGCTL_DBCT (1U<<17)
#define GOTGCTL_CIDSTS (1U<<16)
#define GOTGCTL_EHEN (1U<<12)
#define GOTGCTL_DHNPEN (1U<<11)
#define GOTGCTL_HSHNPEN (1U<<10)
#define GOTGCTL_HNPRQ (1U<<9)
#define GOTGCTL_HNGSCS (1U<<8)
#define GOTGCTL_BVALOVAL (1U<<7)
#define GOTGCTL_BVALOEN (1U<<6)
#define GOTGCTL_AVALOVAL (1U<<5)
#define GOTGCTL_AVALOEN (1U<<4)
#define GOTGCTL_VBVALOVAL (1U<<3)
#define GOTGCTL_VBVALOEN (1U<<2)
#define GOTGCTL_SRQ (1U<<1)
#define GOTGCTL_SRQSCS (1U<<0)
GOTGINT register bit definitions
#define GOTGINT_DBCDNE (1U<<19)
#define GOTGINT_ADTOCHG (1U<<18)
#define GOTGINT_HNGDET (1U<<17)
#define GOTGINT_HNSSCHG (1U<<9)
#define GOTGINT_SRSSCHG (1U<<8)
#define GOTGINT_SEDET (1U<<2)
GAHBCFG register bit definitions
#define GAHBCFG_PTXFELVL (1U<<8)
#define GAHBCFG_TXFELVL (1U<<7)
#define GAHBCFG_DMAEN (1U<<5)
#define GAHBCFG_HBSTLEN_MASK (15U<<1)
#define GAHBCFG_HBSTLEN(n) ((n)<<1)
#define GAHBCFG_GINTMSK (1U<<0)
GUSBCFG register bit definitions
#define GUSBCFG_CTXPKT (1U<<31)
#define GUSBCFG_FDMOD (1U<<30)
#define GUSBCFG_FHMOD (1U<<29)
#define GUSBCFG_TRDT_MASK (15U<<10)
#define GUSBCFG_TRDT(n) ((n)<<10)
#define GUSBCFG_HNPCAP (1U<<9)
#define GUSBCFG_SRPCAP (1U<<8)
#define GUSBCFG_PHYSEL (1U<<6)
#define GUSBCFG_TOCAL_MASK (7U<<0)
#define GUSBCFG_TOCAL(n) ((n)<<0)
GRSTCTL register bit definitions
#define GRSTCTL_AHBIDL (1U<<31)
#define GRSTCTL_TXFNUM_MASK (31U<<6)
#define GRSTCTL_TXFNUM(n) ((n)<<6)
#define GRSTCTL_TXFFLSH (1U<<5)
#define GRSTCTL_RXFFLSH (1U<<4)
#define GRSTCTL_FCRST (1U<<2)
#define GRSTCTL_HSRST (1U<<1)
#define GRSTCTL_CSRST (1U<<0)
GINTSTS register bit definitions
#define GINTSTS_WKUPINT (1U<<31)
#define GINTSTS_SRQINT (1U<<30)
#define GINTSTS_DISCINT (1U<<29)
#define GINTSTS_CIDSCHG (1U<<28)
#define GINTSTS_PTXFE (1U<<26)
#define GINTSTS_HCINT (1U<<25)
#define GINTSTS_HPRTINT (1U<<24)
#define GINTSTS_IPXFR (1U<<21)
#define GINTSTS_IISOOXFR (1U<<21)
#define GINTSTS_IISOIXFR (1U<<20)
#define GINTSTS_OEPINT (1U<<19)
#define GINTSTS_IEPINT (1U<<18)
#define GINTSTS_EOPF (1U<<15)
#define GINTSTS_ISOODRP (1U<<14)
#define GINTSTS_ENUMDNE (1U<<13)
#define GINTSTS_USBRST (1U<<12)
#define GINTSTS_USBSUSP (1U<<11)
#define GINTSTS_ESUSP (1U<<10)
#define GINTSTS_GONAKEFF (1U<<7)
#define GINTSTS_GINAKEFF (1U<<6)
#define GINTSTS_NPTXFE (1U<<5)
#define GINTSTS_RXFLVL (1U<<4)
#define GINTSTS_SOF (1U<<3)
#define GINTSTS_OTGINT (1U<<2)
#define GINTSTS_MMIS (1U<<1)
#define GINTSTS_CMOD (1U<<0)
GINTMSK register bit definitions
#define GINTMSK_WKUM (1U<<31)
#define GINTMSK_SRQM (1U<<30)
#define GINTMSK_DISCM (1U<<29)
#define GINTMSK_CIDSCHGM (1U<<28)
#define GINTMSK_PTXFEM (1U<<26)
#define GINTMSK_HCM (1U<<25)
#define GINTMSK_HPRTM (1U<<24)
#define GINTMSK_IPXFRM (1U<<21)
#define GINTMSK_IISOOXFRM (1U<<21)
#define GINTMSK_IISOIXFRM (1U<<20)
#define GINTMSK_OEPM (1U<<19)
#define GINTMSK_IEPM (1U<<18)
#define GINTMSK_EOPFM (1U<<15)
#define GINTMSK_ISOODRPM (1U<<14)
#define GINTMSK_ENUMDNEM (1U<<13)
#define GINTMSK_USBRSTM (1U<<12)
#define GINTMSK_USBSUSPM (1U<<11)
#define GINTMSK_ESUSPM (1U<<10)
#define GINTMSK_GONAKEFFM (1U<<7)
#define GINTMSK_GINAKEFFM (1U<<6)
#define GINTMSK_NPTXFEM (1U<<5)
#define GINTMSK_RXFLVLM (1U<<4)
#define GINTMSK_SOFM (1U<<3)
#define GINTMSK_OTGM (1U<<2)
#define GINTMSK_MMISM (1U<<1)
GRXSTSR register bit definitions
#define GRXSTSR_PKTSTS_MASK (15U<<17)
#define GRXSTSR_PKTSTS(n) ((n)<<17)
#define GRXSTSR_OUT_GLOBAL_NAK GRXSTSR_PKTSTS(1)
#define GRXSTSR_OUT_DATA GRXSTSR_PKTSTS(2)
#define GRXSTSR_OUT_COMP GRXSTSR_PKTSTS(3)
#define GRXSTSR_SETUP_COMP GRXSTSR_PKTSTS(4)
#define GRXSTSR_SETUP_DATA GRXSTSR_PKTSTS(6)
#define GRXSTSR_DPID_MASK (3U<<15)
#define GRXSTSR_DPID(n) ((n)<<15)
#define GRXSTSR_BCNT_MASK (0x7FF<<4)
#define GRXSTSR_BCNT(n) ((n)<<4)
#define GRXSTSR_CHNUM_MASK (15U<<0)
#define GRXSTSR_CHNUM(n) ((n)<<0)
#define GRXSTSR_EPNUM_MASK (15U<<0)
#define GRXSTSR_EPNUM(n) ((n)<<0)
GRXSTSP register bit definitions
#define GRXSTSP_PKTSTS_MASK (15<<17)
#define GRXSTSP_PKTSTS(n) ((n)<<17)
#define GRXSTSP_OUT_GLOBAL_NAK GRXSTSP_PKTSTS(1)
#define GRXSTSP_OUT_DATA GRXSTSP_PKTSTS(2)
#define GRXSTSP_OUT_COMP GRXSTSP_PKTSTS(3)
#define GRXSTSP_SETUP_COMP GRXSTSP_PKTSTS(4)
#define GRXSTSP_SETUP_DATA GRXSTSP_PKTSTS(6)
#define GRXSTSP_DPID_MASK (3U<<15)
#define GRXSTSP_DPID(n) ((n)<<15)
#define GRXSTSP_BCNT_MASK (0x7FF<<4)
#define GRXSTSP_BCNT_OFF 4
#define GRXSTSP_BCNT(n) ((n)<<4)
#define GRXSTSP_CHNUM_MASK (15U<<0)
#define GRXSTSP_CHNUM(n) ((n)<<0)
#define GRXSTSP_EPNUM_MASK (15U<<0)
#define GRXSTSP_EPNUM_OFF 0
#define GRXSTSP_EPNUM(n) ((n)<<0)
GRXFSIZ register bit definitions
#define GRXFSIZ_RXFD_MASK (0xFFFF<<0)
#define GRXFSIZ_RXFD(n) ((n)<<0)
DIEPTXFx register bit definitions
#define DIEPTXF_INEPTXFD_MASK (0xFFFFU<<16)
#define DIEPTXF_INEPTXFD(n) ((n)<<16)
#define DIEPTXF_INEPTXSA_MASK (0xFFFF<<0)
#define DIEPTXF_INEPTXSA(n) ((n)<<0)
GCCFG register bit definitions
#define GCCFG_NOVBUSSENS (1U<<21)
#define GCCFG_SOFOUTEN (1U<<20)
#define GCCFG_VBUSBSEN (1U<<19)
#define GCCFG_VBUSASEN (1U<<18)
#define GCCFG_VBDEN (1U<<21)
#define GCCFG_PWRDWN (1U<<16)
HPTXFSIZ register bit definitions
#define HPTXFSIZ_PTXFD_MASK (0xFFFFU<<16)
#define HPTXFSIZ_PTXFD(n) ((n)<<16)
#define HPTXFSIZ_PTXSA_MASK (0xFFFFU<<0)
#define HPTXFSIZ_PTXSA(n) ((n)<<0)
HCFG register bit definitions
#define HCFG_FSLSS (1U<<2)
#define HCFG_FSLSPCS_MASK (3U<<0)
#define HCFG_FSLSPCS_48 (1U<<0)
#define HCFG_FSLSPCS_6 (2U<<0)
HFIR register bit definitions
#define HFIR_FRIVL_MASK (0xFFFFU<<0)
#define HFIR_FRIVL(n) ((n)<<0)
HFNUM register bit definitions
#define HFNUM_FTREM_MASK (0xFFFFU<<16)
#define HFNUM_FTREM(n) ((n)<<16)
#define HFNUM_FRNUM_MASK (0xFFFFU<<0)
#define HFNUM_FRNUM(n) ((n)<<0)
HPTXSTS register bit definitions
#define HPTXSTS_PTXQTOP_MASK (0xFFU<<24)
#define HPTXSTS_PTXQTOP(n) ((n)<<24)
#define HPTXSTS_PTXQSAV_MASK (0xFF<<16)
#define HPTXSTS_PTXQSAV(n) ((n)<<16)
#define HPTXSTS_PTXFSAVL_MASK (0xFFFF<<0)
#define HPTXSTS_PTXFSAVL(n) ((n)<<0)
HAINT register bit definitions
#define HAINT_HAINT_MASK (0xFFFFU<<0)
#define HAINT_HAINT(n) ((n)<<0)
HAINTMSK register bit definitions
#define HAINTMSK_HAINTM_MASK (0xFFFFU<<0)
#define HAINTMSK_HAINTM(n) ((n)<<0)
HPRT register bit definitions
#define HPRT_PSPD_MASK (3U<<17)
#define HPRT_PSPD_FS (1U<<17)
#define HPRT_PSPD_LS (2U<<17)
#define HPRT_PTCTL_MASK (15<<13)
#define HPRT_PTCTL(n) ((n)<<13)
#define HPRT_PPWR (1U<<12)
#define HPRT_PLSTS_MASK (3U<<11)
#define HPRT_PLSTS_DM (1U<<11)
#define HPRT_PLSTS_DP (1U<<10)
#define HPRT_PRST (1U<<8)
#define HPRT_PSUSP (1U<<7)
#define HPRT_PRES (1U<<6)
#define HPRT_POCCHNG (1U<<5)
#define HPRT_POCA (1U<<4)
#define HPRT_PENCHNG (1U<<3)
#define HPRT_PENA (1U<<2)
#define HPRT_PCDET (1U<<1)
#define HPRT_PCSTS (1U<<0)
HCCHAR register bit definitions
#define HCCHAR_CHENA (1U<<31)
#define HCCHAR_CHDIS (1U<<30)
#define HCCHAR_ODDFRM (1U<<29)
#define HCCHAR_DAD_MASK (0x7FU<<22)
#define HCCHAR_DAD(n) ((n)<<22)
#define HCCHAR_MCNT_MASK (3U<<20)
#define HCCHAR_MCNT(n) ((n)<<20)
#define HCCHAR_EPTYP_MASK (3U<<18)
#define HCCHAR_EPTYP(n) ((n)<<18)
#define HCCHAR_EPTYP_CTL (0U<<18)
#define HCCHAR_EPTYP_ISO (1U<<18)
#define HCCHAR_EPTYP_BULK (2U<<18)
#define HCCHAR_EPTYP_INTR (3U<<18)
#define HCCHAR_LSDEV (1U<<17)
#define HCCHAR_EPDIR (1U<<15)
#define HCCHAR_EPNUM_MASK (15U<<11)
#define HCCHAR_EPNUM(n) ((n)<<11)
#define HCCHAR_MPS_MASK (0x7FFU<<0)
#define HCCHAR_MPS(n) ((n)<<0)
HCINT register bit definitions
#define HCINT_DTERR (1U<<10)
#define HCINT_FRMOR (1U<<9)
#define HCINT_BBERR (1U<<8)
#define HCINT_TRERR (1U<<7)
#define HCINT_ACK (1U<<5)
#define HCINT_NAK (1U<<4)
#define HCINT_STALL (1U<<3)
#define HCINT_AHBERR (1U<<2)
#define HCINT_CHH (1U<<1)
#define HCINT_XFRC (1U<<0)
HCINTMSK register bit definitions
#define HCINTMSK_DTERRM (1U<<10)
#define HCINTMSK_FRMORM (1U<<9)
#define HCINTMSK_BBERRM (1U<<8)
#define HCINTMSK_TRERRM (1U<<7)
#define HCINTMSK_NYET (1U<<6)
#define HCINTMSK_ACKM (1U<<5)
#define HCINTMSK_NAKM (1U<<4)
#define HCINTMSK_STALLM (1U<<3)
#define HCINTMSK_AHBERRM (1U<<2)
#define HCINTMSK_CHHM (1U<<1)
#define HCINTMSK_XFRCM (1U<<0)
HCTSIZ register bit definitions
#define HCTSIZ_DPID_MASK (3U<<29)
#define HCTSIZ_DPID_DATA0 (0U<<29)
#define HCTSIZ_DPID_DATA2 (1U<<29)
#define HCTSIZ_DPID_DATA1 (2U<<29)
#define HCTSIZ_DPID_MDATA (3U<<29)
#define HCTSIZ_DPID_SETUP (3U<<29)
#define HCTSIZ_PKTCNT_MASK (0x3FFU<<19)
#define HCTSIZ_PKTCNT(n) ((n)<<19)
#define HCTSIZ_XFRSIZ_MASK (0x7FFFF<<0)
#define HCTSIZ_XFRSIZ(n) ((n)<<0)
DCFG register bit definitions
#define DCFG_PFIVL_MASK (3U<<11)
#define DCFG_PFIVL(n) ((n)<<11)
#define DCFG_DAD_MASK (0x7FU<<4)
#define DCFG_DAD(n) ((n)<<4)
#define DCFG_NZLSOHSK (1U<<2)
#define DCFG_DSPD_MASK (3U<<0)
#define DCFG_DSPD_HS (0U<<0)
#define DCFG_DSPD_HS_FS (1U<<0)
#define DCFG_DSPD_FS11 (3U<<0)
DCTL register bit definitions
#define DCTL_POPRGDNE (1U<<11)
#define DCTL_CGONAK (1U<<10)
#define DCTL_SGONAK (1U<<9)
#define DCTL_CGINAK (1U<<8)
#define DCTL_SGINAK (1U<<7)
#define DCTL_TCTL_MASK (7U<<4)
#define DCTL_TCTL(n) ((n)<<4
#define DCTL_GONSTS (1U<<3)
#define DCTL_GINSTS (1U<<2)
#define DCTL_SDIS (1U<<1)
#define DCTL_RWUSIG (1U<<0)
DSTS register bit definitions
#define DSTS_FNSOF_MASK (0x3FFU<<8)
#define DSTS_FNSOF(n) ((n)<<8)
#define DSTS_FNSOF_ODD (1U<<8)
#define DSTS_EERR (1U<<3)
#define DSTS_ENUMSPD_MASK (3U<<1)
#define DSTS_ENUMSPD_FS_48 (3U<<1)
#define DSTS_ENUMSPD_HS_480 (0U<<1)
#define DSTS_SUSPSTS (1U<<0)
DIEPMSK register bit definitions
#define DIEPMSK_TXFEM (1U<<6)
#define DIEPMSK_INEPNEM (1U<<6)
#define DIEPMSK_ITTXFEMSK (1U<<4)
#define DIEPMSK_TOCM (1U<<3)
#define DIEPMSK_EPDM (1U<<1)
#define DIEPMSK_XFRCM (1U<<0)
DOEPMSK register bit definitions
#define DOEPMSK_OTEPDM (1U<<4)
#define DOEPMSK_STUPM (1U<<3)
#define DOEPMSK_EPDM (1U<<1)
#define DOEPMSK_XFRCM (1U<<0)
DAINT register bit definitions
#define DAINT_OEPINT_MASK (0xFFFFU<<16)
#define DAINT_OEPINT(n) ((n)<<16)
#define DAINT_IEPINT_MASK (0xFFFFU<<0)
#define DAINT_IEPINT(n) ((n)<<0)
DAINTMSK register bit definitions
#define DAINTMSK_OEPM_MASK (0xFFFFU<<16)
#define DAINTMSK_OEPM(n) (1U<<(16+(n)))
#define DAINTMSK_IEPM_MASK (0xFFFFU<<0)
#define DAINTMSK_IEPM(n) (1U<<(n))
DVBUSDIS register bit definitions
#define DVBUSDIS_VBUSDT_MASK (0xFFFFU<<0)
#define DVBUSDIS_VBUSDT(n) ((n)<<0)
DVBUSPULSE register bit definitions
#define DVBUSPULSE_DVBUSP_MASK (0xFFFU<<0)
#define DVBUSPULSE_DVBUSP(n) ((n)<<0)
DIEPEMPMSK register bit definitions
#define DIEPEMPMSK_INEPTXFEM(n) (1U<<(n))
DIEPCTL register bit definitions
#define DIEPCTL_EPENA (1U<<31)
#define DIEPCTL_EPDIS (1U<<30)
#define DIEPCTL_SD1PID (1U<<29)
#define DIEPCTL_SODDFRM (1U<<29)
#define DIEPCTL_SD0PID (1U<<28)
#define DIEPCTL_SEVNFRM (1U<<28)
#define DIEPCTL_SNAK (1U<<27)
#define DIEPCTL_CNAK (1U<<26)
#define DIEPCTL_TXFNUM_MASK (15U<<22)
#define DIEPCTL_TXFNUM(n) ((n)<<22)
#define DIEPCTL_STALL (1U<<21)
#define DIEPCTL_SNPM (1U<<20)
#define DIEPCTL_EPTYP_MASK (3<<18)
#define DIEPCTL_EPTYP_CTRL (0U<<18)
#define DIEPCTL_EPTYP_ISO (1U<<18)
#define DIEPCTL_EPTYP_BULK (2U<<18)
#define DIEPCTL_EPTYP_INTR (3U<<18)
#define DIEPCTL_NAKSTS (1U<<17)
#define DIEPCTL_EONUM (1U<<16)
#define DIEPCTL_DPID (1U<<16)
#define DIEPCTL_USBAEP (1U<<15)
#define DIEPCTL_MPSIZ_MASK (0x3FFU<<0)
#define DIEPCTL_MPSIZ(n) ((n)<<0)
DIEPINT register bit definitions
#define DIEPINT_TXFE (1U<<7)
#define DIEPINT_INEPNE (1U<<6)
#define DIEPINT_ITTXFE (1U<<4)
#define DIEPINT_TOC (1U<<3)
#define DIEPINT_EPDISD (1U<<1)
#define DIEPINT_XFRC (1U<<0)
DIEPTSIZ register bit definitions
#define DIEPTSIZ_MCNT_MASK (3U<<29)
#define DIEPTSIZ_MCNT(n) ((n)<<29)
#define DIEPTSIZ_PKTCNT_MASK (0x3FF<<19)
#define DIEPTSIZ_PKTCNT(n) ((n)<<19)
#define DIEPTSIZ_XFRSIZ_MASK (0x7FFFFU<<0)
#define DIEPTSIZ_XFRSIZ(n) ((n)<<0)
DTXFSTS register bit definitions.
#define DTXFSTS_INEPTFSAV_MASK (0xFFFF<<0)
DOEPCTL register bit definitions.
#define DOEPCTL_EPENA (1U<<31)
#define DOEPCTL_EPDIS (1U<<30)
#define DOEPCTL_SD1PID (1U<<29)
#define DOEPCTL_SODDFRM (1U<<29)
#define DOEPCTL_SD0PID (1U<<28)
#define DOEPCTL_SEVNFRM (1U<<28)
#define DOEPCTL_SNAK (1U<<27)
#define DOEPCTL_CNAK (1U<<26)
#define DOEPCTL_STALL (1U<<21)
#define DOEPCTL_SNPM (1U<<20)
#define DOEPCTL_EPTYP_MASK (3U<<18)
#define DOEPCTL_EPTYP_CTRL (0U<<18)
#define DOEPCTL_EPTYP_ISO (1U<<18)
#define DOEPCTL_EPTYP_BULK (2U<<18)
#define DOEPCTL_EPTYP_INTR (3U<<18)
#define DOEPCTL_NAKSTS (1U<<17)
#define DOEPCTL_EONUM (1U<<16)
#define DOEPCTL_DPID (1U<<16)
#define DOEPCTL_USBAEP (1U<<15)
#define DOEPCTL_MPSIZ_MASK (0x3FFU<<0)
#define DOEPCTL_MPSIZ(n) ((n)<<0)
DOEPINT register bit definitions
#define DOEPINT_SETUP_RCVD (1U<<15)
#define DOEPINT_B2BSTUP (1U<<6)
#define DOEPINT_OTEPDIS (1U<<4)
#define DOEPINT_STUP (1U<<3)
#define DOEPINT_EPDISD (1U<<1)
#define DOEPINT_XFRC (1U<<0)
DOEPTSIZ register bit definitions
#define DOEPTSIZ_RXDPID_MASK (3U<<29)
#define DOEPTSIZ_RXDPID(n) ((n)<<29)
#define DOEPTSIZ_STUPCNT_MASK (3U<<29)
#define DOEPTSIZ_STUPCNT(n) ((n)<<29)
#define DOEPTSIZ_PKTCNT_MASK (0x3FFU<<19)
#define DOEPTSIZ_PKTCNT(n) ((n)<<19)
#define DOEPTSIZ_XFRSIZ_MASK (0x7FFFFU<<0)
#define DOEPTSIZ_XFRSIZ(n) ((n)<<0)
PCGCCTL register bit definitions
#define PCGCCTL_PHYSUSP (1U<<4)
#define PCGCCTL_GATEHCLK (1U<<1)
#define PCGCCTL_STPPCLK (1U<<0)
Register aliases
#define RXCOUNT1 TXCOUNT0
#define TXCOUNT1 RXCOUNT0
#define RXADDR1 TXADDR0
#define TXADDR1 RXADDR0
Helper macros for USB descriptors
#define USB_DESC_INDEX(i) ((uint8_t)(i))
Helper macro for index values into descriptor strings.
#define USB_DESC_BYTE(b) ((uint8_t)(b))
Helper macro for byte values into descriptor strings.
#define USB_DESC_WORD(w)
Helper macro for word values into descriptor strings.
#define USB_DESC_BCD(bcd)
Helper macro for BCD values into descriptor strings.
#define USB_DESC_DEVICE_SIZE 18U
#define USB_DESC_DEVICE(bcdUSB, bDeviceClass, bDeviceSubClass, bDeviceProtocol, bMaxPacketSize, idVendor, idProduct, bcdDevice, iManufacturer, iProduct, iSerialNumber, bNumConfigurations)
Device Descriptor helper macro.
#define USB_DESC_CONFIGURATION_SIZE 9U
Configuration Descriptor size.
#define USB_DESC_CONFIGURATION(wTotalLength, bNumInterfaces, bConfigurationValue, iConfiguration, bmAttributes, bMaxPower)
Configuration Descriptor helper macro.
#define USB_DESC_INTERFACE_SIZE 9U
Interface Descriptor size.
#define USB_DESC_INTERFACE(bInterfaceNumber, bAlternateSetting, bNumEndpoints, bInterfaceClass, bInterfaceSubClass, bInterfaceProtocol, iInterface)
Interface Descriptor helper macro.
#define USB_DESC_INTERFACE_ASSOCIATION_SIZE 8U
Interface Association Descriptor size.
#define USB_DESC_INTERFACE_ASSOCIATION(bFirstInterface, bInterfaceCount, bFunctionClass, bFunctionSubClass, bFunctionProcotol, iInterface)
Interface Association Descriptor helper macro.
#define USB_DESC_ENDPOINT_SIZE 7U
Endpoint Descriptor size.
#define USB_DESC_ENDPOINT(bEndpointAddress, bmAttributes, wMaxPacketSize, bInterval)
Endpoint Descriptor helper macro.
Endpoint types and settings
#define USB_EP_MODE_TYPE 0x0003U
#define USB_EP_MODE_TYPE_CTRL 0x0000U
#define USB_EP_MODE_TYPE_ISOC 0x0001U
#define USB_EP_MODE_TYPE_BULK 0x0002U
#define USB_EP_MODE_TYPE_INTR 0x0003U
Macro Functions
#define usbGetDriverStateI(usbp) ((usbp)->state)
Returns the driver state.
#define usbConnectBus(usbp) usb_lld_connect_bus(usbp)
Connects the USB device.
#define usbDisconnectBus(usbp) usb_lld_disconnect_bus(usbp)
Disconnect the USB device.
#define usbGetFrameNumberX(usbp) usb_lld_get_frame_number(usbp)
Returns the current frame number.
#define usbGetTransmitStatusI(usbp, ep) (((usbp)->transmitting & (uint16_t)((unsigned)1U << (unsigned)(ep))) != 0U)
Returns the status of an IN endpoint.
#define usbGetReceiveStatusI(usbp, ep) (((usbp)->receiving & (uint16_t)((unsigned)1U << (unsigned)(ep))) != 0U)
Returns the status of an OUT endpoint.
#define usbGetReceiveTransactionSizeX(usbp, ep) usb_lld_get_transaction_size(usbp, ep)
Returns the exact size of a receive transaction.
#define usbSetupTransfer(usbp, buf, n, endcb)
Request transfer setup.
#define usbReadSetup(usbp, ep, buf) usb_lld_read_setup(usbp, ep, buf)
Reads a setup packet from the dedicated packet buffer.
Low level driver helper macros
#define _usb_isr_invoke_event_cb(usbp, evt)
Common ISR code, usb event callback.
#define _usb_isr_invoke_sof_cb(usbp)
Common ISR code, SOF callback.
#define _usb_isr_invoke_setup_cb(usbp, ep)
Common ISR code, setup packet callback.
#define _usb_isr_invoke_in_cb(usbp, ep)
Common ISR code, IN endpoint callback.
#define _usb_isr_invoke_out_cb(usbp, ep)
Common ISR code, OUT endpoint event.
Typedefs
typedef uint32_t stm32_usb_pma_t
Width of USB packet memory accesses.
typedef struct USBDriver USBDriver
Type of a structure representing an USB driver.
typedef uint8_t usbep_t
Type of an endpoint identifier.
typedef void(* usbcallback_t) (USBDriver *usbp)
Type of an USB generic notification callback.
typedef void(* usbepcallback_t) (USBDriver *usbp, usbep_t ep)
Type of an USB endpoint callback.
typedef void(* usbeventcb_t) (USBDriver *usbp, usbevent_t event)
Type of an USB event notification callback.
typedef bool(* usbreqhandler_t) (USBDriver *usbp)
Type of a requests handler callback.
typedef const USBDescriptor *(* usbgetdescriptor_t) (USBDriver *usbp, uint8_t dtype, uint8_t dindex, uint16_t lang)
Type of an USB descriptor-retrieving callback.
Data Structures
struct stm32_otg_params_t
Peripheral-specific parameters block.
struct USBInEndpointState
Type of an IN endpoint state structure.
struct USBOutEndpointState
Type of an OUT endpoint state structure.
struct USBEndpointConfig
Type of an USB endpoint configuration structure.
struct USBConfig
Type of an USB driver configuration structure.
struct USBDriver
Structure representing an USB driver.
struct stm32_otg_host_chn_t
Host channel registers group.
struct stm32_otg_in_ep_t
Device input endpoint registers group.
struct stm32_otg_out_ep_t
Device output endpoint registers group.
struct stm32_otg_t
USB registers memory map.
struct stm32_usb_t
USB registers block.
struct stm32_usb_descriptor_t
USB descriptor registers block.
struct USBDescriptor
Type of an USB descriptor.
Functions
static void otg_ram_reset (USBDriver *usbp)
Resets the FIFO RAM memory allocator.
static uint32_t otg_ram_alloc (USBDriver *usbp, size_t size)
Allocates a block from the FIFO RAM memory.
static void otg_fifo_write_from_buffer (volatile uint32_t *fifop, const uint8_t *buf, size_t n)
Writes to a TX FIFO.
static void otg_fifo_read_to_buffer (volatile uint32_t *fifop, uint8_t *buf, size_t n, size_t max)
Reads a packet from the RXFIFO.
static void otg_rxfifo_handler (USBDriver *usbp)
Incoming packets handler.
static bool otg_txfifo_handler (USBDriver *usbp, usbep_t ep)
Outgoing packets handler.
static void otg_epin_handler (USBDriver *usbp, usbep_t ep)
Generic endpoint IN handler.
static void otg_epout_handler (USBDriver *usbp, usbep_t ep)
Generic endpoint OUT handler.
static void otg_isoc_in_failed_handler (USBDriver *usbp)
Isochronous IN transfer failed handler.
static void otg_isoc_out_failed_handler (USBDriver *usbp)
Isochronous OUT transfer failed handler.
static void usb_lld_serve_interrupt (USBDriver *usbp)
OTG shared ISR.
OSAL_IRQ_HANDLER (STM32_OTG1_HANDLER)
OTG1 interrupt handler.
OSAL_IRQ_HANDLER (STM32_OTG2_HANDLER)
OTG2 interrupt handler.
void usb_lld_init (void)
Low level USB driver initialization.
void usb_lld_start (USBDriver *usbp)
Configures and activates the USB peripheral.
void usb_lld_stop (USBDriver *usbp)
Deactivates the USB peripheral.
void usb_lld_reset (USBDriver *usbp)
USB low level reset routine.
void usb_lld_set_address (USBDriver *usbp)
Sets the USB address.
void usb_lld_init_endpoint (USBDriver *usbp, usbep_t ep)
Enables an endpoint.
void usb_lld_disable_endpoints (USBDriver *usbp)
Disables all the active endpoints except the endpoint zero.
usbepstatus_t usb_lld_get_status_out (USBDriver *usbp, usbep_t ep)
Returns the status of an OUT endpoint.
usbepstatus_t usb_lld_get_status_in (USBDriver *usbp, usbep_t ep)
Returns the status of an IN endpoint.
void usb_lld_read_setup (USBDriver *usbp, usbep_t ep, uint8_t *buf)
Reads a setup packet from the dedicated packet buffer.
void usb_lld_start_out (USBDriver *usbp, usbep_t ep)
Starts a receive operation on an OUT endpoint.
void usb_lld_start_in (USBDriver *usbp, usbep_t ep)
Starts a transmit operation on an IN endpoint.
void usb_lld_stall_out (USBDriver *usbp, usbep_t ep)
Brings an OUT endpoint in the stalled state.
void usb_lld_stall_in (USBDriver *usbp, usbep_t ep)
Brings an IN endpoint in the stalled state.
void usb_lld_clear_out (USBDriver *usbp, usbep_t ep)
Brings an OUT endpoint in the active state.
void usb_lld_clear_in (USBDriver *usbp, usbep_t ep)
Brings an IN endpoint in the active state.
static void usb_pm_reset (USBDriver *usbp)
Resets the packet memory allocator.
static uint32_t usb_pm_alloc (USBDriver *usbp, size_t size)
Resets the packet memory allocator.
static size_t usb_packet_read_to_buffer (usbep_t ep, uint8_t *buf)
Reads from a dedicated packet buffer.
static void usb_packet_write_from_buffer (usbep_t ep, const uint8_t *buf, size_t n)
Writes to a dedicated packet buffer.
static void usb_serve_endpoints (USBDriver *usbp, uint32_t ep)
Common ISR code, serves the EP-related interrupts.
OSAL_IRQ_HANDLER (STM32_USB1_LP_HANDLER)
USB low priority interrupt handler.
static void set_address (USBDriver *usbp)
SET ADDRESS transaction callback.
static bool default_handler (USBDriver *usbp)
Standard requests handler.
void usbInit (void)
USB Driver initialization.
void usbObjectInit (USBDriver *usbp)
Initializes the standard part of a USBDriver structure.
void usbStart (USBDriver *usbp, const USBConfig *config)
Configures and activates the USB peripheral.
void usbStop (USBDriver *usbp)
Deactivates the USB peripheral.
void usbInitEndpointI (USBDriver *usbp, usbep_t ep, const USBEndpointConfig *epcp)
Enables an endpoint.
void usbDisableEndpointsI (USBDriver *usbp)
Disables all the active endpoints.
void usbStartReceiveI (USBDriver *usbp, usbep_t ep, uint8_t *buf, size_t n)
Starts a receive transaction on an OUT endpoint.
void usbStartTransmitI (USBDriver *usbp, usbep_t ep, const uint8_t *buf, size_t n)
Starts a transmit transaction on an IN endpoint.
msg_t usbReceive (USBDriver *usbp, usbep_t ep, uint8_t *buf, size_t n)
Performs a receive transaction on an OUT endpoint.
msg_t usbTransmit (USBDriver *usbp, usbep_t ep, const uint8_t *buf, size_t n)
Performs a transmit transaction on an IN endpoint.
bool usbStallReceiveI (USBDriver *usbp, usbep_t ep)
Stalls an OUT endpoint.
bool usbStallTransmitI (USBDriver *usbp, usbep_t ep)
Stalls an IN endpoint.
void usbWakeupHost (USBDriver *usbp)
Host wake-up procedure.
void _usb_reset (USBDriver *usbp)
USB reset routine.
void _usb_suspend (USBDriver *usbp)
USB suspend routine.
void _usb_wakeup (USBDriver *usbp)
USB wake-up routine.
void _usb_ep0setup (USBDriver *usbp, usbep_t ep)
Default EP0 SETUP callback.
void _usb_ep0in (USBDriver *usbp, usbep_t ep)
Default EP0 IN callback.
void _usb_ep0out (USBDriver *usbp, usbep_t ep)
Default EP0 OUT callback.
Enumerations
Variables
USBDriver USBD1
OTG_FS driver identifier.
USBDriver USBD2
OTG_HS driver identifier.
union {
USBInEndpointState in
IN EP0 state.
USBOutEndpointState out
OUT EP0 state.
} ep0_state
EP0 state.
static uint8_t ep0setup_buffer [8]
Buffer for the EP0 setup packets.
static const USBEndpointConfig ep0config
EP0 initialization structure.
USBDriver USBD1
OTG_FS driver identifier.
USBDriver USBD2
OTG_HS driver identifier.
union {
USBInEndpointState in
IN EP0 state.
USBOutEndpointState out
OUT EP0 state.
} ep0_state
EP0 state.
static uint8_t ep0setup_buffer [8]
Buffer for the EP0 setup packets.
static const USBEndpointConfig ep0config
EP0 initialization structure.
USBDriver USBD1
USB1 driver identifier.
union {
USBInEndpointState in
IN EP0 state.
USBOutEndpointState out
OUT EP0 state.
} ep0_state
EP0 state.
static uint8_t ep0setup_buffer [8]
Buffer for the EP0 setup packets.
static const USBEndpointConfig ep0config
EP0 initialization structure.
Macro Definition Documentation
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
Definition at line 39 of file OTGv1/hal_usb_lld.h.
#define USB_SET_ADDRESS_MODE USB_EARLY_SET_ADDRESS
The address can be changed immediately upon packet reception.
Definition at line 44 of file OTGv1/hal_usb_lld.h.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
Definition at line 49 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_USE_OTG1 FALSE
OTG1 driver enable switch.
If set to TRUE the support for OTG_FS is included.
Note
The default is FALSE
Definition at line 61 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_USE_OTG2 FALSE
OTG2 driver enable switch.
If set to TRUE the support for OTG_HS is included.
Note
The default is FALSE.
Definition at line 70 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_OTG1_IRQ_PRIORITY 14
OTG1 interrupt priority level setting.
Definition at line 77 of file OTGv1/hal_usb_lld.h.
Referenced by usb_lld_start().
#define STM32_USB_OTG2_IRQ_PRIORITY 14
OTG2 interrupt priority level setting.
Definition at line 84 of file OTGv1/hal_usb_lld.h.
Referenced by usb_lld_start().
#define STM32_USB_OTG1_RX_FIFO_SIZE 512
OTG1 RX shared FIFO size.
Note
Must be a multiple of 4.
Definition at line 92 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_OTG2_RX_FIFO_SIZE 1024
OTG2 RX shared FIFO size.
Note
Must be a multiple of 4.
Definition at line 100 of file OTGv1/hal_usb_lld.h.
#define STM32_USE_USB_OTG2_HS TRUE
Enables HS mode on OTG2 else FS mode.
Note
The default is TRUE.
Has effect only if BOARD_OTG2_USES_ULPI is defined.
Definition at line 109 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_OTG_THREAD_PRIO LOWPRIO
Dedicated data pump threads priority.
Definition at line 116 of file OTGv1/hal_usb_lld.h.
Referenced by usb_lld_start().
#define STM32_USB_OTG_THREAD_STACK_SIZE 128
Dedicated data pump threads stack size.
Definition at line 123 of file OTGv1/hal_usb_lld.h.
#define STM32_USB_OTGFIFO_FILL_BASEPRI 0
Exception priority level during TXFIFOs operations.
Note
Because an undocumented silicon behavior the operation of copying a packet into a TXFIFO must not be interrupted by any other operation on the OTG peripheral. This parameter represents the priority mask during copy operations. The default value only allows to call USB functions from callbacks invoked from USB ISR handlers. If you need to invoke USB functions from other handlers then raise this priority mast to the same level of the handler you need to use.
The value zero means disabled, when disabled calling USB functions is only safe from thread level or from USB callbacks.
Definition at line 142 of file OTGv1/hal_usb_lld.h.
Referenced by otg_txfifo_handler().
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
Definition at line 149 of file OTGv1/hal_usb_lld.h.
#define USB_MAX_ENDPOINTS STM32_OTG2_ENDPOINTS
Maximum endpoint address.
Definition at line 200 of file OTGv1/hal_usb_lld.h.
Referenced by _usb_reset(), _usb_suspend(), usbDisableEndpointsI(), usbObjectInit(), usbStart(), usbStartReceiveI(), usbStartTransmitI(), and usbStop().
#define usb_lld_get_transaction_size (usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
The received size can be different from the size specified in usbStartReceiveI() because the last packet could have a size different from the expected one.
Precondition
The OUT endpoint must have been configured in transaction mode in order to use this function.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
Received data size.
Function Class:
Not an API, this function is for internal use only.
Definition at line 551 of file OTGv1/hal_usb_lld.h.
#define usb_lld_connect_bus (usbp) ((usbp)->otg->GCCFG |= GCCFG_VBUSBSEN)
Connects the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 560 of file OTGv1/hal_usb_lld.h.
#define usb_lld_disconnect_bus (usbp) ((usbp)->otg->GCCFG &= ~GCCFG_VBUSBSEN)
Disconnect the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 571 of file OTGv1/hal_usb_lld.h.
#define usb_lld_wakeup_host (usbp)
Value:
do{                                                                       \
    (usbp)->otg->DCTL |= DCTL_RWUSIG;                                       \
    osalThreadSleepMilliseconds(USB_HOST_WAKEUP_DURATION);                  \
    (usbp)->otg->DCTL &= ~DCTL_RWUSIG;                                      \
  } while (false)
Start of host wake-up procedure.
Function Class:
Not an API, this function is for internal use only.
Definition at line 581 of file OTGv1/hal_usb_lld.h.
Referenced by usbWakeupHost().
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
Definition at line 39 of file hal_usb_lld_alt.h.
#define USB_SET_ADDRESS_MODE USB_EARLY_SET_ADDRESS
The address can be changed immediately upon packet reception.
Definition at line 44 of file hal_usb_lld_alt.h.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
Definition at line 49 of file hal_usb_lld_alt.h.
#define STM32_USB_USE_OTG1 FALSE
OTG1 driver enable switch.
If set to TRUE the support for OTG_FS is included.
Note
The default is FALSE
Definition at line 61 of file hal_usb_lld_alt.h.
#define STM32_USB_USE_OTG2 FALSE
OTG2 driver enable switch.
If set to TRUE the support for OTG_HS is included.
Note
The default is FALSE.
Definition at line 70 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG1_IRQ_PRIORITY 14
OTG1 interrupt priority level setting.
Definition at line 77 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG2_IRQ_PRIORITY 14
OTG2 interrupt priority level setting.
Definition at line 84 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG1_RX_FIFO_SIZE 512
OTG1 RX shared FIFO size.
Note
Must be a multiple of 4.
Definition at line 92 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG2_RX_FIFO_SIZE 1024
OTG2 RX shared FIFO size.
Note
Must be a multiple of 4.
Definition at line 100 of file hal_usb_lld_alt.h.
#define STM32_USE_USB_OTG2_HS TRUE
Enables HS mode on OTG2 else FS mode.
Note
The default is TRUE.
Has effect only if BOARD_OTG2_USES_ULPI is defined.
Definition at line 109 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG_THREAD_PRIO LOWPRIO
Dedicated data pump threads priority.
Definition at line 116 of file hal_usb_lld_alt.h.
#define STM32_USB_OTG_THREAD_STACK_SIZE 128
Dedicated data pump threads stack size.
Definition at line 123 of file hal_usb_lld_alt.h.
#define STM32_USB_OTGFIFO_FILL_BASEPRI 0
Exception priority level during TXFIFOs operations.
Note
Because an undocumented silicon behavior the operation of copying a packet into a TXFIFO must not be interrupted by any other operation on the OTG peripheral. This parameter represents the priority mask during copy operations. The default value only allows to call USB functions from callbacks invoked from USB ISR handlers. If you need to invoke USB functions from other handlers then raise this priority mast to the same level of the handler you need to use.
The value zero means disabled, when disabled calling USB functions is only safe from thread level or from USB callbacks.
Definition at line 142 of file hal_usb_lld_alt.h.
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
Definition at line 149 of file hal_usb_lld_alt.h.
#define USB_MAX_ENDPOINTS STM32_OTG2_ENDPOINTS
Maximum endpoint address.
Definition at line 200 of file hal_usb_lld_alt.h.
#define usb_lld_get_transaction_size (usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
The received size can be different from the size specified in usbStartReceiveI() because the last packet could have a size different from the expected one.
Precondition
The OUT endpoint must have been configured in transaction mode in order to use this function.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
Received data size.
Function Class:
Not an API, this function is for internal use only.
Definition at line 551 of file hal_usb_lld_alt.h.
#define usb_lld_connect_bus (usbp) ((usbp)->otg->GCCFG |= GCCFG_VBUSBSEN)
Connects the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 560 of file hal_usb_lld_alt.h.
#define usb_lld_disconnect_bus (usbp) ((usbp)->otg->GCCFG &= ~GCCFG_VBUSBSEN)
Disconnect the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 571 of file hal_usb_lld_alt.h.
#define usb_lld_wakeup_host (usbp)
Value:
do{                                                                       \
    (usbp)->otg->DCTL |= DCTL_RWUSIG;                                       \
    osalThreadSleepMilliseconds(USB_HOST_WAKEUP_DURATION);                  \
    (usbp)->otg->DCTL &= ~DCTL_RWUSIG;                                      \
  } while (false)
Start of host wake-up procedure.
Function Class:
Not an API, this function is for internal use only.
Definition at line 581 of file hal_usb_lld_alt.h.
#define STM32_OTG1_FIFO_MEM_SIZE 320
OTG_FS FIFO memory size in words.
Definition at line 31 of file stm32_otg.h.
#define STM32_OTG2_FIFO_MEM_SIZE 1024
OTG_HS FIFO memory size in words.
Definition at line 36 of file stm32_otg.h.
#define GOTGCTL_BSVLD (1U<<19)
B-Session Valid.
Definition at line 176 of file stm32_otg.h.
#define GOTGCTL_ASVLD (1U<<18)
A-Session Valid.
Definition at line 177 of file stm32_otg.h.
#define GOTGCTL_DBCT (1U<<17)
Long/Short debounce time.
Definition at line 178 of file stm32_otg.h.
#define GOTGCTL_CIDSTS (1U<<16)
Connector ID status.
Definition at line 179 of file stm32_otg.h.
#define GOTGCTL_DHNPEN (1U<<11)
Device HNP enabled.
Definition at line 181 of file stm32_otg.h.
#define GOTGCTL_HSHNPEN (1U<<10)
Host Set HNP enable.
Definition at line 182 of file stm32_otg.h.
#define GOTGCTL_HNPRQ (1U<<9)
HNP request.
Definition at line 183 of file stm32_otg.h.
#define GOTGCTL_HNGSCS (1U<<8)
Host negotiation success.
Definition at line 184 of file stm32_otg.h.
#define GOTGCTL_SRQ (1U<<1)
Session request.
Definition at line 191 of file stm32_otg.h.
#define GOTGCTL_SRQSCS (1U<<0)
Session request success.
Definition at line 192 of file stm32_otg.h.
#define GOTGINT_DBCDNE (1U<<19)
Debounce done.
Definition at line 199 of file stm32_otg.h.
#define GOTGINT_ADTOCHG (1U<<18)
A-Device timeout change.
Definition at line 200 of file stm32_otg.h.
#define GOTGINT_HNGDET (1U<<17)
Host negotiation detected.
Definition at line 201 of file stm32_otg.h.
#define GOTGINT_HNSSCHG (1U<<9)
Host negotiation success status change.
Definition at line 202 of file stm32_otg.h.
#define GOTGINT_SRSSCHG (1U<<8)
Session request success status change.
Definition at line 205 of file stm32_otg.h.
#define GOTGINT_SEDET (1U<<2)
Session end detected.
Definition at line 208 of file stm32_otg.h.
#define GAHBCFG_PTXFELVL (1U<<8)
Periodic TxFIFO empty level.
Definition at line 215 of file stm32_otg.h.
#define GAHBCFG_TXFELVL (1U<<7)
Non-periodic TxFIFO empty level.
Definition at line 218 of file stm32_otg.h.
#define GAHBCFG_DMAEN (1U<<5)
DMA enable (HS only).
Definition at line 221 of file stm32_otg.h.
#define GAHBCFG_HBSTLEN_MASK (15U<<1)
Burst length/type mask (HS only).
Definition at line 222 of file stm32_otg.h.
#define GAHBCFG_HBSTLEN (n) ((n)<<1)
Burst length/type (HS only).
Definition at line 225 of file stm32_otg.h.
#define GAHBCFG_GINTMSK (1U<<0)
Global interrupt mask.
Definition at line 229 of file stm32_otg.h.
Referenced by usb_lld_clear_in(), and usb_lld_start().
#define GUSBCFG_CTXPKT (1U<<31)
Corrupt Tx packet.
Definition at line 236 of file stm32_otg.h.
#define GUSBCFG_FDMOD (1U<<30)
Force Device Mode.
Definition at line 237 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GUSBCFG_FHMOD (1U<<29)
Force Host Mode.
Definition at line 238 of file stm32_otg.h.
#define GUSBCFG_TRDT_MASK (15U<<10)
USB Turnaround time field mask.
Definition at line 239 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GUSBCFG_TRDT (n) ((n)<<10)
USB Turnaround time field value.
Definition at line 242 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt(), and usb_lld_start().
#define GUSBCFG_HNPCAP (1U<<9)
HNP-Capable.
Definition at line 246 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GUSBCFG_SRPCAP (1U<<8)
SRP-Capable.
Definition at line 247 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GUSBCFG_PHYSEL (1U<<6)
USB 2.0 High-Speed PHY or USB 1.1 Full-Speed serial transceiver Select.
Definition at line 248 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GUSBCFG_TOCAL_MASK (7U<<0)
HS/FS timeout calibration field mask.
Definition at line 253 of file stm32_otg.h.
#define GUSBCFG_TOCAL (n) ((n)<<0)
HS/FS timeout calibration field value.
Definition at line 256 of file stm32_otg.h.
#define GRSTCTL_AHBIDL (1U<<31)
AHB Master Idle.
Definition at line 266 of file stm32_otg.h.
#define GRSTCTL_TXFNUM_MASK (31U<<6)
TxFIFO number field mask.
Definition at line 267 of file stm32_otg.h.
#define GRSTCTL_TXFNUM (n) ((n)<<6)
TxFIFO number field value.
Definition at line 268 of file stm32_otg.h.
#define GRSTCTL_TXFFLSH (1U<<5)
TxFIFO flush.
Definition at line 269 of file stm32_otg.h.
#define GRSTCTL_RXFFLSH (1U<<4)
RxFIFO flush.
Definition at line 270 of file stm32_otg.h.
#define GRSTCTL_FCRST (1U<<2)
Host frame counter reset.
Definition at line 271 of file stm32_otg.h.
#define GRSTCTL_HSRST (1U<<1)
HClk soft reset.
Definition at line 272 of file stm32_otg.h.
#define GRSTCTL_CSRST (1U<<0)
Core soft reset.
Definition at line 273 of file stm32_otg.h.
#define GINTSTS_WKUPINT (1U<<31)
Resume/Remote wakeup detected interrupt.
Definition at line 280 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_SRQINT (1U<<30)
Session request/New session detected interrupt.
Definition at line 283 of file stm32_otg.h.
#define GINTSTS_DISCINT (1U<<29)
Disconnect detected interrupt.
Definition at line 286 of file stm32_otg.h.
#define GINTSTS_CIDSCHG (1U<<28)
Connector ID status change.
Definition at line 289 of file stm32_otg.h.
#define GINTSTS_PTXFE (1U<<26)
Periodic TxFIFO empty.
Definition at line 290 of file stm32_otg.h.
#define GINTSTS_HCINT (1U<<25)
Host channels interrupt.
Definition at line 291 of file stm32_otg.h.
#define GINTSTS_HPRTINT (1U<<24)
Host port interrupt.
Definition at line 292 of file stm32_otg.h.
#define GINTSTS_IPXFR (1U<<21)
Incomplete periodic transfer.
Definition at line 293 of file stm32_otg.h.
#define GINTSTS_IISOOXFR (1U<<21)
Incomplete isochronous OUT transfer.
Definition at line 296 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_IISOIXFR (1U<<20)
Incomplete isochronous IN transfer.
Definition at line 299 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_OEPINT (1U<<19)
OUT endpoints interrupt.
Definition at line 302 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_IEPINT (1U<<18)
IN endpoints interrupt.
Definition at line 303 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_EOPF (1U<<15)
End of periodic frame interrupt.
Definition at line 304 of file stm32_otg.h.
#define GINTSTS_ISOODRP (1U<<14)
Isochronous OUT packet dropped interrupt.
Definition at line 307 of file stm32_otg.h.
#define GINTSTS_ENUMDNE (1U<<13)
Enumeration done.
Definition at line 310 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_USBRST (1U<<12)
USB reset.
Definition at line 311 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_USBSUSP (1U<<11)
USB suspend.
Definition at line 312 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_ESUSP (1U<<10)
Early suspend.
Definition at line 313 of file stm32_otg.h.
#define GINTSTS_GONAKEFF (1U<<7)
Global OUT NAK effective.
Definition at line 314 of file stm32_otg.h.
#define GINTSTS_GINAKEFF (1U<<6)
Global IN non-periodic NAK effective.
Definition at line 315 of file stm32_otg.h.
#define GINTSTS_NPTXFE (1U<<5)
Non-periodic TxFIFO empty.
Definition at line 318 of file stm32_otg.h.
#define GINTSTS_RXFLVL (1U<<4)
RxFIFO non-empty.
Definition at line 319 of file stm32_otg.h.
Referenced by usb_lld_clear_in(), and usb_lld_serve_interrupt().
#define GINTSTS_SOF (1U<<3)
Start of frame.
Definition at line 320 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define GINTSTS_OTGINT (1U<<2)
OTG interrupt.
Definition at line 321 of file stm32_otg.h.
#define GINTSTS_MMIS (1U<<1)
Mode Mismatch interrupt.
Definition at line 322 of file stm32_otg.h.
#define GINTSTS_CMOD (1U<<0)
Current mode of operation.
Definition at line 323 of file stm32_otg.h.
#define GINTMSK_WKUM (1U<<31)
Resume/remote wakeup detected interrupt mask.
Definition at line 330 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_SRQM (1U<<30)
Session request/New session detected interrupt mask.
Definition at line 333 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_DISCM (1U<<29)
Disconnect detected interrupt mask.
Definition at line 336 of file stm32_otg.h.
#define GINTMSK_CIDSCHGM (1U<<28)
Connector ID status change mask.
Definition at line 339 of file stm32_otg.h.
#define GINTMSK_PTXFEM (1U<<26)
Periodic TxFIFO empty mask.
Definition at line 342 of file stm32_otg.h.
#define GINTMSK_HCM (1U<<25)
Host channels interrupt mask.
Definition at line 343 of file stm32_otg.h.
#define GINTMSK_HPRTM (1U<<24)
Host port interrupt mask.
Definition at line 346 of file stm32_otg.h.
#define GINTMSK_IPXFRM (1U<<21)
Incomplete periodic transfer mask.
Definition at line 347 of file stm32_otg.h.
#define GINTMSK_IISOOXFRM (1U<<21)
Incomplete isochronous OUT transfer mask.
Definition at line 350 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_IISOIXFRM (1U<<20)
Incomplete isochronous IN transfer mask.
Definition at line 353 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_OEPM (1U<<19)
OUT endpoints interrupt mask.
Definition at line 356 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define GINTMSK_IEPM (1U<<18)
IN endpoints interrupt mask.
Definition at line 359 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define GINTMSK_EOPFM (1U<<15)
End of periodic frame interrupt mask.
Definition at line 362 of file stm32_otg.h.
#define GINTMSK_ISOODRPM (1U<<14)
Isochronous OUT packet dropped interrupt mask.
Definition at line 365 of file stm32_otg.h.
#define GINTMSK_ENUMDNEM (1U<<13)
Enumeration done mask.
Definition at line 368 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_USBRSTM (1U<<12)
USB reset mask.
Definition at line 369 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_USBSUSPM (1U<<11)
USB suspend mask.
Definition at line 370 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_ESUSPM (1U<<10)
Early suspend mask.
Definition at line 371 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_GONAKEFFM (1U<<7)
Global OUT NAK effective mask.
Definition at line 372 of file stm32_otg.h.
#define GINTMSK_GINAKEFFM (1U<<6)
Global non-periodic IN NAK effective mask.
Definition at line 375 of file stm32_otg.h.
#define GINTMSK_NPTXFEM (1U<<5)
Non-periodic TxFIFO empty mask.
Definition at line 378 of file stm32_otg.h.
#define GINTMSK_RXFLVLM (1U<<4)
Receive FIFO non-empty mask.
Definition at line 381 of file stm32_otg.h.
Referenced by usb_lld_clear_in(), usb_lld_reset(), and usb_lld_serve_interrupt().
#define GINTMSK_SOFM (1U<<3)
Start of (micro)frame mask.
Definition at line 384 of file stm32_otg.h.
Referenced by usb_lld_start().
#define GINTMSK_OTGM (1U<<2)
OTG interrupt mask.
Definition at line 385 of file stm32_otg.h.
#define GINTMSK_MMISM (1U<<1)
Mode Mismatch interrupt mask.
Definition at line 386 of file stm32_otg.h.
#define GRXSTSR_PKTSTS_MASK (15U<<17)
Packet status mask.
Definition at line 395 of file stm32_otg.h.
#define GRXSTSR_PKTSTS (n) ((n)<<17)
Packet status value.
Definition at line 396 of file stm32_otg.h.
#define GRXSTSR_DPID_MASK (3U<<15)
Data PID mask.
Definition at line 402 of file stm32_otg.h.
#define GRXSTSR_DPID (n) ((n)<<15)
Data PID value.
Definition at line 403 of file stm32_otg.h.
#define GRXSTSR_BCNT_MASK (0x7FF<<4)
Byte count mask.
Definition at line 404 of file stm32_otg.h.
#define GRXSTSR_BCNT (n) ((n)<<4)
Byte count value.
Definition at line 405 of file stm32_otg.h.
#define GRXSTSR_CHNUM_MASK (15U<<0)
Channel number mask.
Definition at line 406 of file stm32_otg.h.
#define GRXSTSR_CHNUM (n) ((n)<<0)
Channel number value.
Definition at line 407 of file stm32_otg.h.
#define GRXSTSR_EPNUM_MASK (15U<<0)
Endpoint number mask.
Definition at line 408 of file stm32_otg.h.
#define GRXSTSR_EPNUM (n) ((n)<<0)
Endpoint number value.
Definition at line 409 of file stm32_otg.h.
#define GRXSTSP_PKTSTS_MASK (15<<17)
Packet status mask.
Definition at line 416 of file stm32_otg.h.
Referenced by otg_rxfifo_handler().
#define GRXSTSP_PKTSTS (n) ((n)<<17)
Packet status value.
Definition at line 417 of file stm32_otg.h.
#define GRXSTSP_DPID_MASK (3U<<15)
Data PID mask.
Definition at line 423 of file stm32_otg.h.
#define GRXSTSP_DPID (n) ((n)<<15)
Data PID value.
Definition at line 424 of file stm32_otg.h.
#define GRXSTSP_BCNT_MASK (0x7FF<<4)
Byte count mask.
Definition at line 425 of file stm32_otg.h.
Referenced by otg_rxfifo_handler().
#define GRXSTSP_BCNT_OFF 4
Byte count offset.
Definition at line 426 of file stm32_otg.h.
Referenced by otg_rxfifo_handler().
#define GRXSTSP_BCNT (n) ((n)<<4)
Byte count value.
Definition at line 427 of file stm32_otg.h.
#define GRXSTSP_CHNUM_MASK (15U<<0)
Channel number mask.
Definition at line 428 of file stm32_otg.h.
#define GRXSTSP_CHNUM (n) ((n)<<0)
Channel number value.
Definition at line 429 of file stm32_otg.h.
#define GRXSTSP_EPNUM_MASK (15U<<0)
Endpoint number mask.
Definition at line 430 of file stm32_otg.h.
Referenced by otg_rxfifo_handler().
#define GRXSTSP_EPNUM_OFF 0
Endpoint number offset.
Definition at line 431 of file stm32_otg.h.
Referenced by otg_rxfifo_handler().
#define GRXSTSP_EPNUM (n) ((n)<<0)
Endpoint number value.
Definition at line 432 of file stm32_otg.h.
#define GRXFSIZ_RXFD_MASK (0xFFFF<<0)
RxFIFO depth mask.
Definition at line 439 of file stm32_otg.h.
#define GRXFSIZ_RXFD (n) ((n)<<0)
RxFIFO depth value.
Definition at line 440 of file stm32_otg.h.
#define DIEPTXF_INEPTXFD_MASK (0xFFFFU<<16)
IN endpoint TxFIFO depth mask.
Definition at line 447 of file stm32_otg.h.
#define DIEPTXF_INEPTXFD (n) ((n)<<16)
IN endpoint TxFIFO depth value.
Definition at line 450 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPTXF_INEPTXSA_MASK (0xFFFF<<0)
IN endpoint FIFOx transmit RAM start address mask.
Definition at line 454 of file stm32_otg.h.
#define DIEPTXF_INEPTXSA (n) ((n)<<0)
IN endpoint FIFOx transmit RAM start address value.
Definition at line 457 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define GCCFG_NOVBUSSENS (1U<<21)
VBUS sensing disable.
Definition at line 468 of file stm32_otg.h.
#define GCCFG_SOFOUTEN (1U<<20)
SOF output enable.
Definition at line 469 of file stm32_otg.h.
#define GCCFG_VBUSBSEN (1U<<19)
Enable the VBUS sensing "B" device.
Definition at line 470 of file stm32_otg.h.
#define GCCFG_VBUSASEN (1U<<18)
Enable the VBUS sensing "A" device.
Definition at line 473 of file stm32_otg.h.
#define GCCFG_VBDEN (1U<<21)
VBUS sensing enable.
Definition at line 478 of file stm32_otg.h.
#define GCCFG_PWRDWN (1U<<16)
Power down.
Definition at line 479 of file stm32_otg.h.
#define HPTXFSIZ_PTXFD_MASK (0xFFFFU<<16)
Host periodic TxFIFO depth mask.
Definition at line 486 of file stm32_otg.h.
#define HPTXFSIZ_PTXFD (n) ((n)<<16)
Host periodic TxFIFO depth value.
Definition at line 489 of file stm32_otg.h.
#define HPTXFSIZ_PTXSA_MASK (0xFFFFU<<0)
Host periodic TxFIFO Start address mask.
Definition at line 493 of file stm32_otg.h.
#define HPTXFSIZ_PTXSA (n) ((n)<<0)
Host periodic TxFIFO start address value.
Definition at line 496 of file stm32_otg.h.
#define HCFG_FSLSS (1U<<2)
FS- and LS-only support.
Definition at line 506 of file stm32_otg.h.
#define HCFG_FSLSPCS_MASK (3U<<0)
FS/LS PHY clock select mask.
Definition at line 507 of file stm32_otg.h.
#define HCFG_FSLSPCS_48 (1U<<0)
PHY clock is running at 48 MHz.
Definition at line 510 of file stm32_otg.h.
#define HCFG_FSLSPCS_6 (2U<<0)
PHY clock is running at 6 MHz.
Definition at line 513 of file stm32_otg.h.
#define HFIR_FRIVL_MASK (0xFFFFU<<0)
Frame interval mask.
Definition at line 522 of file stm32_otg.h.
#define HFIR_FRIVL (n) ((n)<<0)
Frame interval value.
Definition at line 523 of file stm32_otg.h.
#define HFNUM_FTREM_MASK (0xFFFFU<<16)
Frame time Remaining mask.
Definition at line 530 of file stm32_otg.h.
#define HFNUM_FTREM (n) ((n)<<16)
Frame time Remaining value.
Definition at line 531 of file stm32_otg.h.
#define HFNUM_FRNUM_MASK (0xFFFFU<<0)
Frame number mask.
Definition at line 532 of file stm32_otg.h.
#define HFNUM_FRNUM (n) ((n)<<0)
Frame number value.
Definition at line 533 of file stm32_otg.h.
#define HPTXSTS_PTXQTOP_MASK (0xFFU<<24)
Top of the periodic transmit request queue mask.
Definition at line 540 of file stm32_otg.h.
#define HPTXSTS_PTXQTOP (n) ((n)<<24)
Top of the periodic transmit request queue value.
Definition at line 545 of file stm32_otg.h.
#define HPTXSTS_PTXQSAV_MASK (0xFF<<16)
Periodic transmit request queue Space Available mask.
Definition at line 552 of file stm32_otg.h.
#define HPTXSTS_PTXQSAV (n) ((n)<<16)
Periodic transmit request queue Space Available value.
Definition at line 557 of file stm32_otg.h.
#define HPTXSTS_PTXFSAVL_MASK (0xFFFF<<0)
Periodic transmit Data FIFO Space Available mask.
Definition at line 564 of file stm32_otg.h.
#define HPTXSTS_PTXFSAVL (n) ((n)<<0)
Periodic transmit Data FIFO Space Available value.
Definition at line 569 of file stm32_otg.h.
#define HAINT_HAINT_MASK (0xFFFFU<<0)
Channel interrupts mask.
Definition at line 582 of file stm32_otg.h.
#define HAINT_HAINT (n) ((n)<<0)
Channel interrupts value.
Definition at line 583 of file stm32_otg.h.
#define HAINTMSK_HAINTM_MASK (0xFFFFU<<0)
Channel interrupt mask mask.
Definition at line 590 of file stm32_otg.h.
#define HAINTMSK_HAINTM (n) ((n)<<0)
Channel interrupt mask value.
Definition at line 593 of file stm32_otg.h.
#define HPRT_PSPD_MASK (3U<<17)
Port speed mask.
Definition at line 603 of file stm32_otg.h.
#define HPRT_PSPD_FS (1U<<17)
Full speed value.
Definition at line 604 of file stm32_otg.h.
#define HPRT_PSPD_LS (2U<<17)
Low speed value.
Definition at line 605 of file stm32_otg.h.
#define HPRT_PTCTL_MASK (15<<13)
Port Test control mask.
Definition at line 606 of file stm32_otg.h.
#define HPRT_PTCTL (n) ((n)<<13)
Port Test control value.
Definition at line 607 of file stm32_otg.h.
#define HPRT_PPWR (1U<<12)
Port power.
Definition at line 608 of file stm32_otg.h.
#define HPRT_PLSTS_MASK (3U<<11)
Port Line status mask.
Definition at line 609 of file stm32_otg.h.
#define HPRT_PLSTS_DM (1U<<11)
Logic level of D-.
Definition at line 610 of file stm32_otg.h.
#define HPRT_PLSTS_DP (1U<<10)
Logic level of D+.
Definition at line 611 of file stm32_otg.h.
#define HPRT_PRST (1U<<8)
Port reset.
Definition at line 612 of file stm32_otg.h.
#define HPRT_PSUSP (1U<<7)
Port suspend.
Definition at line 613 of file stm32_otg.h.
#define HPRT_PRES (1U<<6)
Port Resume.
Definition at line 614 of file stm32_otg.h.
#define HPRT_POCCHNG (1U<<5)
Port overcurrent change.
Definition at line 615 of file stm32_otg.h.
#define HPRT_POCA (1U<<4)
Port overcurrent active.
Definition at line 616 of file stm32_otg.h.
#define HPRT_PENCHNG (1U<<3)
Port enable/disable change.
Definition at line 617 of file stm32_otg.h.
#define HPRT_PENA (1U<<2)
Port enable.
Definition at line 618 of file stm32_otg.h.
#define HPRT_PCDET (1U<<1)
Port Connect detected.
Definition at line 619 of file stm32_otg.h.
#define HPRT_PCSTS (1U<<0)
Port connect status.
Definition at line 620 of file stm32_otg.h.
#define HCCHAR_CHENA (1U<<31)
Channel enable.
Definition at line 627 of file stm32_otg.h.
#define HCCHAR_CHDIS (1U<<30)
Channel Disable.
Definition at line 628 of file stm32_otg.h.
#define HCCHAR_ODDFRM (1U<<29)
Odd frame.
Definition at line 629 of file stm32_otg.h.
#define HCCHAR_DAD_MASK (0x7FU<<22)
Device Address mask.
Definition at line 630 of file stm32_otg.h.
#define HCCHAR_DAD (n) ((n)<<22)
Device Address value.
Definition at line 631 of file stm32_otg.h.
#define HCCHAR_MCNT_MASK (3U<<20)
Multicount mask.
Definition at line 632 of file stm32_otg.h.
#define HCCHAR_MCNT (n) ((n)<<20)
Multicount value.
Definition at line 633 of file stm32_otg.h.
#define HCCHAR_EPTYP_MASK (3U<<18)
Endpoint type mask.
Definition at line 634 of file stm32_otg.h.
#define HCCHAR_EPTYP (n) ((n)<<18)
Endpoint type value.
Definition at line 635 of file stm32_otg.h.
#define HCCHAR_EPTYP_CTL (0U<<18)
Control endpoint value.
Definition at line 636 of file stm32_otg.h.
#define HCCHAR_EPTYP_ISO (1U<<18)
Isochronous endpoint value.
Definition at line 637 of file stm32_otg.h.
#define HCCHAR_EPTYP_BULK (2U<<18)
Bulk endpoint value.
Definition at line 638 of file stm32_otg.h.
#define HCCHAR_EPTYP_INTR (3U<<18)
Interrupt endpoint value.
Definition at line 639 of file stm32_otg.h.
#define HCCHAR_LSDEV (1U<<17)
Low-Speed device.
Definition at line 640 of file stm32_otg.h.
#define HCCHAR_EPDIR (1U<<15)
Endpoint direction.
Definition at line 641 of file stm32_otg.h.
#define HCCHAR_EPNUM_MASK (15U<<11)
Endpoint number mask.
Definition at line 642 of file stm32_otg.h.
#define HCCHAR_EPNUM (n) ((n)<<11)
Endpoint number value.
Definition at line 643 of file stm32_otg.h.
#define HCCHAR_MPS_MASK (0x7FFU<<0)
Maximum packet size mask.
Definition at line 644 of file stm32_otg.h.
#define HCCHAR_MPS (n) ((n)<<0)
Maximum packet size value.
Definition at line 645 of file stm32_otg.h.
#define HCINT_DTERR (1U<<10)
Data toggle error.
Definition at line 652 of file stm32_otg.h.
#define HCINT_FRMOR (1U<<9)
Frame overrun.
Definition at line 653 of file stm32_otg.h.
#define HCINT_BBERR (1U<<8)
Babble error.
Definition at line 654 of file stm32_otg.h.
#define HCINT_TRERR (1U<<7)
Transaction Error.
Definition at line 655 of file stm32_otg.h.
#define HCINT_ACK (1U<<5)
ACK response received/transmitted interrupt.
Definition at line 656 of file stm32_otg.h.
#define HCINT_NAK (1U<<4)
NAK response received interrupt.
Definition at line 661 of file stm32_otg.h.
#define HCINT_STALL (1U<<3)
STALL response received interrupt.
Definition at line 664 of file stm32_otg.h.
#define HCINT_AHBERR (1U<<2)
AHB error interrupt.
Definition at line 667 of file stm32_otg.h.
#define HCINT_CHH (1U<<1)
Channel halted.
Definition at line 668 of file stm32_otg.h.
#define HCINT_XFRC (1U<<0)
Transfer completed.
Definition at line 669 of file stm32_otg.h.
#define HCINTMSK_DTERRM (1U<<10)
Data toggle error mask.
Definition at line 676 of file stm32_otg.h.
#define HCINTMSK_FRMORM (1U<<9)
Frame overrun mask.
Definition at line 677 of file stm32_otg.h.
#define HCINTMSK_BBERRM (1U<<8)
Babble error mask.
Definition at line 678 of file stm32_otg.h.
#define HCINTMSK_TRERRM (1U<<7)
Transaction error mask.
Definition at line 679 of file stm32_otg.h.
#define HCINTMSK_NYET (1U<<6)
NYET response received interrupt mask.
Definition at line 680 of file stm32_otg.h.
#define HCINTMSK_ACKM (1U<<5)
ACK Response received/transmitted interrupt mask.
Definition at line 683 of file stm32_otg.h.
#define HCINTMSK_NAKM (1U<<4)
NAK response received interrupt mask.
Definition at line 688 of file stm32_otg.h.
#define HCINTMSK_STALLM (1U<<3)
STALL response received interrupt mask.
Definition at line 691 of file stm32_otg.h.
#define HCINTMSK_AHBERRM (1U<<2)
AHB error interrupt mask.
Definition at line 694 of file stm32_otg.h.
#define HCINTMSK_CHHM (1U<<1)
Channel halted mask.
Definition at line 695 of file stm32_otg.h.
#define HCINTMSK_XFRCM (1U<<0)
Transfer completed mask.
Definition at line 696 of file stm32_otg.h.
#define HCTSIZ_DPID_MASK (3U<<29)
PID mask.
Definition at line 703 of file stm32_otg.h.
#define HCTSIZ_DPID_DATA0 (0U<<29)
DATA0.
Definition at line 704 of file stm32_otg.h.
#define HCTSIZ_DPID_DATA2 (1U<<29)
DATA2.
Definition at line 705 of file stm32_otg.h.
#define HCTSIZ_DPID_DATA1 (2U<<29)
DATA1.
Definition at line 706 of file stm32_otg.h.
#define HCTSIZ_DPID_MDATA (3U<<29)
MDATA.
Definition at line 707 of file stm32_otg.h.
#define HCTSIZ_DPID_SETUP (3U<<29)
SETUP.
Definition at line 708 of file stm32_otg.h.
#define HCTSIZ_PKTCNT_MASK (0x3FFU<<19)
Packet count mask.
Definition at line 709 of file stm32_otg.h.
#define HCTSIZ_PKTCNT (n) ((n)<<19)
Packet count value.
Definition at line 710 of file stm32_otg.h.
#define HCTSIZ_XFRSIZ_MASK (0x7FFFF<<0)
Transfer size mask.
Definition at line 711 of file stm32_otg.h.
#define HCTSIZ_XFRSIZ (n) ((n)<<0)
Transfer size value.
Definition at line 712 of file stm32_otg.h.
#define DCFG_PFIVL_MASK (3U<<11)
Periodic frame interval mask.
Definition at line 719 of file stm32_otg.h.
#define DCFG_PFIVL (n) ((n)<<11)
Periodic frame interval value.
Definition at line 722 of file stm32_otg.h.
#define DCFG_DAD_MASK (0x7FU<<4)
Device address mask.
Definition at line 726 of file stm32_otg.h.
Referenced by usb_lld_reset(), and usb_lld_set_address().
#define DCFG_DAD (n) ((n)<<4)
Device address value.
Definition at line 727 of file stm32_otg.h.
Referenced by usb_lld_reset(), and usb_lld_set_address().
#define DCFG_NZLSOHSK (1U<<2)
Non-Zero-Length status OUT handshake.
Definition at line 728 of file stm32_otg.h.
#define DCFG_DSPD_MASK (3U<<0)
Device speed mask.
Definition at line 731 of file stm32_otg.h.
#define DCFG_DSPD_HS (0U<<0)
High speed (USB 2.0).
Definition at line 732 of file stm32_otg.h.
Referenced by usb_lld_start().
#define DCFG_DSPD_HS_FS (1U<<0)
High speed (USB 2.0) in FS mode.
Definition at line 733 of file stm32_otg.h.
Referenced by usb_lld_start().
#define DCFG_DSPD_FS11 (3U<<0)
Full speed (USB 1.1 transceiver clock is 48 MHz).
Definition at line 736 of file stm32_otg.h.
Referenced by usb_lld_start().
#define DCTL_POPRGDNE (1U<<11)
Power-on programming done.
Definition at line 747 of file stm32_otg.h.
#define DCTL_CGONAK (1U<<10)
Clear global OUT NAK.
Definition at line 748 of file stm32_otg.h.
#define DCTL_SGONAK (1U<<9)
Set global OUT NAK.
Definition at line 749 of file stm32_otg.h.
#define DCTL_CGINAK (1U<<8)
Clear global non-periodic IN NAK.
Definition at line 750 of file stm32_otg.h.
#define DCTL_SGINAK (1U<<7)
Set global non-periodic IN NAK.
Definition at line 753 of file stm32_otg.h.
#define DCTL_TCTL_MASK (7U<<4)
Test control mask.
Definition at line 756 of file stm32_otg.h.
#define DCTL_TCTL (n) ((n)<<4
Test control value.
Definition at line 757 of file stm32_otg.h.
#define DCTL_GONSTS (1U<<3)
Global OUT NAK status.
Definition at line 758 of file stm32_otg.h.
#define DCTL_GINSTS (1U<<2)
Global non-periodic IN NAK status.
Definition at line 759 of file stm32_otg.h.
#define DCTL_SDIS (1U<<1)
Soft disconnect.
Definition at line 762 of file stm32_otg.h.
#define DCTL_RWUSIG (1U<<0)
Remote wakeup signaling.
Definition at line 763 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define DSTS_FNSOF_MASK (0x3FFU<<8)
Frame number of the received SOF mask.
Definition at line 770 of file stm32_otg.h.
#define DSTS_FNSOF (n) ((n)<<8)
Frame number of the received SOF value.
Definition at line 773 of file stm32_otg.h.
#define DSTS_FNSOF_ODD (1U<<8)
Frame parity of the received SOF value.
Definition at line 777 of file stm32_otg.h.
Referenced by usb_lld_start_in(), and usb_lld_start_out().
#define DSTS_EERR (1U<<3)
Erratic error.
Definition at line 780 of file stm32_otg.h.
#define DSTS_ENUMSPD_MASK (3U<<1)
Enumerated speed mask.
Definition at line 781 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define DSTS_ENUMSPD_FS_48 (3U<<1)
Full speed (PHY clock is running at 48 MHz).
Definition at line 782 of file stm32_otg.h.
#define DSTS_ENUMSPD_HS_480 (0U<<1)
High speed.
Definition at line 785 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define DSTS_SUSPSTS (1U<<0)
Suspend status.
Definition at line 786 of file stm32_otg.h.
#define DIEPMSK_TXFEM (1U<<6)
Transmit FIFO empty mask.
Definition at line 793 of file stm32_otg.h.
#define DIEPMSK_INEPNEM (1U<<6)
IN endpoint NAK effective mask.
Definition at line 794 of file stm32_otg.h.
#define DIEPMSK_ITTXFEMSK (1U<<4)
IN token received when TxFIFO empty mask.
Definition at line 797 of file stm32_otg.h.
#define DIEPMSK_TOCM (1U<<3)
Timeout condition mask.
Definition at line 800 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define DIEPMSK_EPDM (1U<<1)
Endpoint disabled interrupt mask.
Definition at line 801 of file stm32_otg.h.
#define DIEPMSK_XFRCM (1U<<0)
Transfer completed interrupt mask.
Definition at line 804 of file stm32_otg.h.
Referenced by otg_epin_handler(), and usb_lld_reset().
#define DOEPMSK_OTEPDM (1U<<4)
OUT token received when endpoint disabled mask.
Definition at line 813 of file stm32_otg.h.
#define DOEPMSK_STUPM (1U<<3)
SETUP phase done mask.
Definition at line 816 of file stm32_otg.h.
Referenced by otg_epout_handler(), and usb_lld_reset().
#define DOEPMSK_EPDM (1U<<1)
Endpoint disabled interrupt mask.
Definition at line 817 of file stm32_otg.h.
#define DOEPMSK_XFRCM (1U<<0)
Transfer completed interrupt mask.
Definition at line 820 of file stm32_otg.h.
Referenced by otg_epout_handler(), and usb_lld_reset().
#define DAINT_OEPINT_MASK (0xFFFFU<<16)
OUT endpoint interrupt bits mask.
Definition at line 829 of file stm32_otg.h.
#define DAINT_OEPINT (n) ((n)<<16)
OUT endpoint interrupt bits value.
Definition at line 832 of file stm32_otg.h.
#define DAINT_IEPINT_MASK (0xFFFFU<<0)
IN endpoint interrupt bits mask.
Definition at line 836 of file stm32_otg.h.
#define DAINT_IEPINT (n) ((n)<<0)
IN endpoint interrupt bits value.
Definition at line 839 of file stm32_otg.h.
#define DAINTMSK_OEPM_MASK (0xFFFFU<<16)
OUT EP interrupt mask bits mask.
Definition at line 849 of file stm32_otg.h.
#define DAINTMSK_OEPM (n) (1U<<(16+(n)))
OUT EP interrupt mask bits value.
Definition at line 852 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DAINTMSK_IEPM_MASK (0xFFFFU<<0)
IN EP interrupt mask bits mask.
Definition at line 856 of file stm32_otg.h.
#define DAINTMSK_IEPM (n) (1U<<(n))
IN EP interrupt mask bits value.
Definition at line 859 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DVBUSDIS_VBUSDT_MASK (0xFFFFU<<0)
Device VBUS discharge time mask.
Definition at line 869 of file stm32_otg.h.
#define DVBUSDIS_VBUSDT (n) ((n)<<0)
Device VBUS discharge time value.
Definition at line 872 of file stm32_otg.h.
#define DVBUSPULSE_DVBUSP_MASK (0xFFFU<<0)
Device VBUSpulsing time mask.
Definition at line 882 of file stm32_otg.h.
#define DVBUSPULSE_DVBUSP (n) ((n)<<0)
Device VBUS pulsing time value.
Definition at line 885 of file stm32_otg.h.
#define DIEPEMPMSK_INEPTXFEM (n) (1U<<(n))
IN EP Tx FIFO empty interrupt mask bit.
Definition at line 895 of file stm32_otg.h.
Referenced by otg_epin_handler(), otg_txfifo_handler(), and usb_lld_start_in().
#define DIEPCTL_EPENA (1U<<31)
Endpoint enable.
Definition at line 905 of file stm32_otg.h.
Referenced by otg_isoc_in_failed_handler(), and usb_lld_start_in().
#define DIEPCTL_EPDIS (1U<<30)
Endpoint disable.
Definition at line 906 of file stm32_otg.h.
Referenced by otg_isoc_in_failed_handler().
#define DIEPCTL_SD1PID (1U<<29)
Set DATA1 PID.
Definition at line 907 of file stm32_otg.h.
#define DIEPCTL_SODDFRM (1U<<29)
Set odd frame.
Definition at line 908 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DIEPCTL_SD0PID (1U<<28)
Set DATA0 PID.
Definition at line 909 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPCTL_SEVNFRM (1U<<28)
Set even frame.
Definition at line 910 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DIEPCTL_SNAK (1U<<27)
Set NAK.
Definition at line 911 of file stm32_otg.h.
Referenced by otg_isoc_in_failed_handler(), and usb_lld_reset().
#define DIEPCTL_CNAK (1U<<26)
Clear NAK.
Definition at line 912 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DIEPCTL_TXFNUM_MASK (15U<<22)
TxFIFO number mask.
Definition at line 913 of file stm32_otg.h.
#define DIEPCTL_TXFNUM (n) ((n)<<22)
TxFIFO number value.
Definition at line 914 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPCTL_STALL (1U<<21)
STALL handshake.
Definition at line 915 of file stm32_otg.h.
Referenced by usb_lld_clear_in(), usb_lld_get_status_in(), and usb_lld_stall_in().
#define DIEPCTL_SNPM (1U<<20)
Snoop mode.
Definition at line 916 of file stm32_otg.h.
#define DIEPCTL_EPTYP_MASK (3<<18)
Endpoint type mask.
Definition at line 917 of file stm32_otg.h.
Referenced by otg_isoc_in_failed_handler().
#define DIEPCTL_EPTYP_CTRL (0U<<18)
Control.
Definition at line 918 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPCTL_EPTYP_ISO (1U<<18)
Isochronous.
Definition at line 919 of file stm32_otg.h.
Referenced by otg_isoc_in_failed_handler(), and usb_lld_init_endpoint().
#define DIEPCTL_EPTYP_BULK (2U<<18)
Bulk.
Definition at line 920 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint().
#define DIEPCTL_EPTYP_INTR (3U<<18)
Interrupt.
Definition at line 921 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint().
#define DIEPCTL_NAKSTS (1U<<17)
NAK status.
Definition at line 922 of file stm32_otg.h.
#define DIEPCTL_EONUM (1U<<16)
Even/odd frame.
Definition at line 923 of file stm32_otg.h.
#define DIEPCTL_DPID (1U<<16)
Endpoint data PID.
Definition at line 924 of file stm32_otg.h.
#define DIEPCTL_USBAEP (1U<<15)
USB active endpoint.
Definition at line 925 of file stm32_otg.h.
Referenced by usb_lld_get_status_in(), usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPCTL_MPSIZ_MASK (0x3FFU<<0)
Maximum Packet size mask.
Definition at line 926 of file stm32_otg.h.
#define DIEPCTL_MPSIZ (n) ((n)<<0)
Maximum Packet size value.
Definition at line 927 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DIEPINT_TXFE (1U<<7)
Transmit FIFO empty.
Definition at line 934 of file stm32_otg.h.
Referenced by otg_epin_handler().
#define DIEPINT_INEPNE (1U<<6)
IN endpoint NAK effective.
Definition at line 935 of file stm32_otg.h.
#define DIEPINT_ITTXFE (1U<<4)
IN Token received when TxFIFO is empty.
Definition at line 936 of file stm32_otg.h.
#define DIEPINT_TOC (1U<<3)
Timeout condition.
Definition at line 939 of file stm32_otg.h.
Referenced by otg_epin_handler().
#define DIEPINT_EPDISD (1U<<1)
Endpoint disabled interrupt.
Definition at line 940 of file stm32_otg.h.
#define DIEPINT_XFRC (1U<<0)
Transfer completed.
Definition at line 943 of file stm32_otg.h.
Referenced by otg_epin_handler().
#define DIEPTSIZ_MCNT_MASK (3U<<29)
Multi count mask.
Definition at line 950 of file stm32_otg.h.
#define DIEPTSIZ_MCNT (n) ((n)<<29)
Multi count value.
Definition at line 951 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DIEPTSIZ_PKTCNT_MASK (0x3FF<<19)
Packet count mask.
Definition at line 952 of file stm32_otg.h.
#define DIEPTSIZ_PKTCNT (n) ((n)<<19)
Packet count value.
Definition at line 953 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DIEPTSIZ_XFRSIZ_MASK (0x7FFFFU<<0)
Transfer size mask.
Definition at line 954 of file stm32_otg.h.
#define DIEPTSIZ_XFRSIZ (n) ((n)<<0)
Transfer size value.
Definition at line 955 of file stm32_otg.h.
Referenced by usb_lld_start_in().
#define DTXFSTS_INEPTFSAV_MASK (0xFFFF<<0)
IN endpoint TxFIFO space available.
Definition at line 962 of file stm32_otg.h.
Referenced by otg_txfifo_handler().
#define DOEPCTL_EPENA (1U<<31)
Endpoint enable.
Definition at line 971 of file stm32_otg.h.
Referenced by otg_isoc_out_failed_handler(), and usb_lld_start_out().
#define DOEPCTL_EPDIS (1U<<30)
Endpoint disable.
Definition at line 972 of file stm32_otg.h.
#define DOEPCTL_SD1PID (1U<<29)
Set DATA1 PID.
Definition at line 973 of file stm32_otg.h.
#define DOEPCTL_SODDFRM (1U<<29)
Set odd frame.
Definition at line 974 of file stm32_otg.h.
Referenced by usb_lld_start_out().
#define DOEPCTL_SD0PID (1U<<28)
Set DATA0 PID.
Definition at line 975 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define DOEPCTL_SEVNFRM (1U<<28)
Set even frame.
Definition at line 976 of file stm32_otg.h.
Referenced by usb_lld_start_out().
#define DOEPCTL_SNAK (1U<<27)
Set NAK.
Definition at line 977 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define DOEPCTL_CNAK (1U<<26)
Clear NAK.
Definition at line 978 of file stm32_otg.h.
Referenced by usb_lld_start_out().
#define DOEPCTL_STALL (1U<<21)
STALL handshake.
Definition at line 979 of file stm32_otg.h.
Referenced by usb_lld_clear_out(), usb_lld_get_status_out(), and usb_lld_stall_out().
#define DOEPCTL_SNPM (1U<<20)
Snoop mode.
Definition at line 980 of file stm32_otg.h.
#define DOEPCTL_EPTYP_MASK (3U<<18)
Endpoint type mask.
Definition at line 981 of file stm32_otg.h.
Referenced by otg_isoc_out_failed_handler().
#define DOEPCTL_EPTYP_CTRL (0U<<18)
Control.
Definition at line 982 of file stm32_otg.h.
Referenced by usb_lld_reset().
#define DOEPCTL_EPTYP_ISO (1U<<18)
Isochronous.
Definition at line 983 of file stm32_otg.h.
Referenced by otg_isoc_out_failed_handler().
#define DOEPCTL_EPTYP_BULK (2U<<18)
Bulk.
Definition at line 984 of file stm32_otg.h.
#define DOEPCTL_EPTYP_INTR (3U<<18)
Interrupt.
Definition at line 985 of file stm32_otg.h.
#define DOEPCTL_NAKSTS (1U<<17)
NAK status.
Definition at line 986 of file stm32_otg.h.
#define DOEPCTL_EONUM (1U<<16)
Even/odd frame.
Definition at line 987 of file stm32_otg.h.
#define DOEPCTL_DPID (1U<<16)
Endpoint data PID.
Definition at line 988 of file stm32_otg.h.
#define DOEPCTL_USBAEP (1U<<15)
USB active endpoint.
Definition at line 989 of file stm32_otg.h.
Referenced by usb_lld_get_status_out(), usb_lld_init_endpoint(), and usb_lld_reset().
#define DOEPCTL_MPSIZ_MASK (0x3FFU<<0)
Maximum Packet size mask.
Definition at line 990 of file stm32_otg.h.
#define DOEPCTL_MPSIZ (n) ((n)<<0)
Maximum Packet size value.
Definition at line 991 of file stm32_otg.h.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
#define DOEPINT_SETUP_RCVD (1U<<15)
SETUP packet received.
Definition at line 998 of file stm32_otg.h.
#define DOEPINT_B2BSTUP (1U<<6)
Back-to-back SETUP packets received.
Definition at line 999 of file stm32_otg.h.
#define DOEPINT_OTEPDIS (1U<<4)
OUT token received when endpoint disabled.
Definition at line 1002 of file stm32_otg.h.
#define DOEPINT_STUP (1U<<3)
SETUP phase done.
Definition at line 1005 of file stm32_otg.h.
Referenced by otg_epout_handler().
#define DOEPINT_EPDISD (1U<<1)
Endpoint disabled interrupt.
Definition at line 1006 of file stm32_otg.h.
#define DOEPINT_XFRC (1U<<0)
Transfer completed interrupt.
Definition at line 1009 of file stm32_otg.h.
Referenced by otg_epout_handler().
#define DOEPTSIZ_RXDPID_MASK (3U<<29)
Received data PID mask.
Definition at line 1018 of file stm32_otg.h.
#define DOEPTSIZ_RXDPID (n) ((n)<<29)
Received data PID value.
Definition at line 1019 of file stm32_otg.h.
#define DOEPTSIZ_STUPCNT_MASK (3U<<29)
SETUP packet count mask.
Definition at line 1020 of file stm32_otg.h.
#define DOEPTSIZ_STUPCNT (n) ((n)<<29)
SETUP packet count value.
Definition at line 1021 of file stm32_otg.h.
Referenced by usb_lld_reset(), and usb_lld_start_out().
#define DOEPTSIZ_PKTCNT_MASK (0x3FFU<<19)
Packet count mask.
Definition at line 1022 of file stm32_otg.h.
#define DOEPTSIZ_PKTCNT (n) ((n)<<19)
Packet count value.
Definition at line 1023 of file stm32_otg.h.
Referenced by usb_lld_start_out().
#define DOEPTSIZ_XFRSIZ_MASK (0x7FFFFU<<0)
Transfer size mask.
Definition at line 1024 of file stm32_otg.h.
#define DOEPTSIZ_XFRSIZ (n) ((n)<<0)
Transfer size value.
Definition at line 1025 of file stm32_otg.h.
Referenced by usb_lld_start_out().
#define PCGCCTL_PHYSUSP (1U<<4)
PHY Suspended.
Definition at line 1032 of file stm32_otg.h.
#define PCGCCTL_GATEHCLK (1U<<1)
Gate HCLK.
Definition at line 1033 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define PCGCCTL_STPPCLK (1U<<0)
Stop PCLK.
Definition at line 1034 of file stm32_otg.h.
Referenced by usb_lld_serve_interrupt().
#define OTG_FS_ADDR 0x50000000
OTG_FS registers block memory address.
Definition at line 1040 of file stm32_otg.h.
#define OTG_HS_ADDR 0x40040000
OTG_HS registers block memory address.
Definition at line 1045 of file stm32_otg.h.
#define OTG_FS ((stm32_otg_t *)OTG_FS_ADDR)
Accesses to the OTG_FS registers block.
Definition at line 1050 of file stm32_otg.h.
Referenced by usb_lld_init().
#define OTG_HS ((stm32_otg_t *)OTG_HS_ADDR)
Accesses to the OTG_HS registers block.
Definition at line 1055 of file stm32_otg.h.
Referenced by usb_lld_init().
#define USB_MAX_ENDPOINTS USB_ENDOPOINTS_NUMBER
Maximum endpoint address.
Definition at line 39 of file USBv1/hal_usb_lld.h.
#define USB_EP0_STATUS_STAGE USB_EP0_STATUS_STAGE_SW
Status stage handling method.
Definition at line 44 of file USBv1/hal_usb_lld.h.
#define USB_SET_ADDRESS_MODE USB_LATE_SET_ADDRESS
This device requires the address change after the status packet.
Definition at line 49 of file USBv1/hal_usb_lld.h.
#define USB_SET_ADDRESS_ACK_HANDLING USB_SET_ADDRESS_ACK_SW
Method for set address acknowledge.
Definition at line 54 of file USBv1/hal_usb_lld.h.
#define STM32_USB_USE_USB1 FALSE
USB1 driver enable switch.
If set to TRUE the support for USB1 is included.
Note
The default is TRUE.
Definition at line 66 of file USBv1/hal_usb_lld.h.
#define STM32_USB_LOW_POWER_ON_SUSPEND FALSE
Enables the USB device low power mode on suspend.
Definition at line 73 of file USBv1/hal_usb_lld.h.
#define STM32_USB_USB1_HP_IRQ_PRIORITY 13
USB1 interrupt priority level setting.
Definition at line 81 of file USBv1/hal_usb_lld.h.
Referenced by OSAL_IRQ_HANDLER().
#define STM32_USB_USB1_LP_IRQ_PRIORITY 14
USB1 interrupt priority level setting.
Definition at line 88 of file USBv1/hal_usb_lld.h.
Referenced by OSAL_IRQ_HANDLER().
#define STM32_USB_USE_ISOCHRONOUS FALSE
Enables isochronous support.
Note
Isochronous support requires special handling and this makes the code size increase significantly.
Definition at line 97 of file USBv1/hal_usb_lld.h.
#define STM32_USB_USE_FAST_COPY FALSE
Use faster copy for packets.
Note
Makes the driver larger.
Definition at line 105 of file USBv1/hal_usb_lld.h.
Referenced by usb_packet_read_to_buffer().
#define USB_HOST_WAKEUP_DURATION 2
Host wake-up procedure duration.
Definition at line 112 of file USBv1/hal_usb_lld.h.
#define usb_lld_get_frame_number (usbp) (STM32_USB->FNR & FNR_FN_MASK)
Returns the current frame number.
Parameters
[in] usbp pointer to the USBDriver object
Returns
The current frame number.
Function Class:
Not an API, this function is for internal use only.
Definition at line 413 of file USBv1/hal_usb_lld.h.
#define usb_lld_get_transaction_size (usbp, ep) ((usbp)->epc[ep]->out_state->rxcnt)
Returns the exact size of a receive transaction.
The received size can be different from the size specified in usbStartReceiveI() because the last packet could have a size different from the expected one.
Precondition
The OUT endpoint must have been configured in transaction mode in order to use this function.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
Received data size.
Function Class:
Not an API, this function is for internal use only.
Definition at line 429 of file USBv1/hal_usb_lld.h.
#define usb_lld_connect_bus (usbp) (STM32_USB->BCDR |= USB_BCDR_DPPU)
Connects the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 439 of file USBv1/hal_usb_lld.h.
#define usb_lld_disconnect_bus (usbp) (STM32_USB->BCDR &= ~USB_BCDR_DPPU)
Disconnect the USB device.
Function Class:
Not an API, this function is for internal use only.
Definition at line 448 of file USBv1/hal_usb_lld.h.
#define usb_lld_wakeup_host (usbp)
Value:
do{                                                                       \
    STM32_USB->CNTR |= USB_CNTR_RESUME;                                     \
    osalThreadSleepMilliseconds(USB_HOST_WAKEUP_DURATION);                  \
    STM32_USB->CNTR &= ~USB_CNTR_RESUME;                                    \
  } while (false)
Start of host wake-up procedure.
Function Class:
Not an API, this function is for internal use only.
Definition at line 467 of file USBv1/hal_usb_lld.h.
#define USB_ENDOPOINTS_NUMBER 7
Number of the available endpoints.
This value does not include the endpoint 0 which is always present.
Definition at line 34 of file stm32_usb.h.
Referenced by OSAL_IRQ_HANDLER().
#define STM32_USB_BASE USB_BASE
USB registers block numeric address.
Definition at line 125 of file stm32_usb.h.
#define STM32_USBRAM_BASE USB_PMAADDR
USB RAM numeric address.
Definition at line 134 of file stm32_usb.h.
#define STM32_USB ((stm32_usb_t *)STM32_USB_BASE)
Pointer to the USB registers block.
Definition at line 142 of file stm32_usb.h.
Referenced by OSAL_IRQ_HANDLER(), usb_packet_read_to_buffer(), usb_packet_write_from_buffer(), and usb_serve_endpoints().
#define STM32_USBRAM ((stm32_usb_pma_t *)STM32_USBRAM_BASE)
Pointer to the USB RAM.
Definition at line 147 of file stm32_usb.h.
#define EPR_TOGGLE_MASK
Value:
(EPR_STAT_TX_MASK | EPR_DTOG_TX |           \
                                 EPR_STAT_RX_MASK | EPR_DTOG_RX |           \
                                 EPR_SETUP)
Mask of all the toggling bits in the EPR register.
Definition at line 152 of file stm32_usb.h.
#define USB_GET_DESCRIPTOR (ep)
Value:
((stm32_usb_descriptor_t *)((uint32_t)STM32_USBRAM_BASE +                 \
                              (uint32_t)STM32_USB->BTABLE +                 \
                              (uint32_t)(ep) *                              \
                              sizeof(stm32_usb_descriptor_t)))
Returns an endpoint descriptor pointer.
Definition at line 250 of file stm32_usb.h.
Referenced by OSAL_IRQ_HANDLER(), usb_packet_read_to_buffer(), and usb_packet_write_from_buffer().
#define USB_ADDR2PTR (addr)
Value:
((stm32_usb_pma_t *)((addr) *                                             \
                       (sizeof(stm32_usb_pma_t) / 2) +                      \
                       STM32_USBRAM_BASE))
Converts from a PMA address to a physical address.
Definition at line 259 of file stm32_usb.h.
Referenced by OSAL_IRQ_HANDLER(), usb_packet_read_to_buffer(), and usb_packet_write_from_buffer().
#define USB_DESC_INDEX (i) ((uint8_t)(i))
Helper macro for index values into descriptor strings.
Definition at line 93 of file hal_usb.h.
#define USB_DESC_BYTE (b) ((uint8_t)(b))
Helper macro for byte values into descriptor strings.
Definition at line 98 of file hal_usb.h.
#define USB_DESC_WORD (w)
Value:
(uint8_t)((w) & 255U),                                                    \
  (uint8_t)(((w) >> 8) & 255U)
Helper macro for word values into descriptor strings.
Definition at line 103 of file hal_usb.h.
#define USB_DESC_BCD (bcd)
Value:
(uint8_t)((bcd) & 255U),                                                  \
  (uint8_t)(((bcd) >> 8) & 255)
Helper macro for BCD values into descriptor strings.
Definition at line 110 of file hal_usb.h.
#define USB_DESC_DEVICE (bcdUSB, bDeviceClass, bDeviceSubClass, bDeviceProtocol, bMaxPacketSize, idVendor, idProduct, bcdDevice, iManufacturer, iProduct, iSerialNumber, bNumConfigurations)
Value:
USB_DESC_BYTE(USB_DESC_DEVICE_SIZE),                                      \
  USB_DESC_BYTE(USB_DESCRIPTOR_DEVICE),                                     \
  USB_DESC_BCD(bcdUSB),                                                     \
  USB_DESC_BYTE(bDeviceClass),                                              \
  USB_DESC_BYTE(bDeviceSubClass),                                           \
  USB_DESC_BYTE(bDeviceProtocol),                                           \
  USB_DESC_BYTE(bMaxPacketSize),                                            \
  USB_DESC_WORD(idVendor),                                                  \
  USB_DESC_WORD(idProduct),                                                 \
  USB_DESC_BCD(bcdDevice),                                                  \
  USB_DESC_INDEX(iManufacturer),                                            \
  USB_DESC_INDEX(iProduct),                                                 \
  USB_DESC_INDEX(iSerialNumber),                                            \
  USB_DESC_BYTE(bNumConfigurations)
Device Descriptor helper macro.
Definition at line 122 of file hal_usb.h.
#define USB_DESC_CONFIGURATION_SIZE 9U
Configuration Descriptor size.
Definition at line 144 of file hal_usb.h.
#define USB_DESC_CONFIGURATION (wTotalLength, bNumInterfaces, bConfigurationValue, iConfiguration, bmAttributes, bMaxPower)
Value:
USB_DESC_BYTE(USB_DESC_CONFIGURATION_SIZE),                               \
  USB_DESC_BYTE(USB_DESCRIPTOR_CONFIGURATION),                              \
  USB_DESC_WORD(wTotalLength),                                              \
  USB_DESC_BYTE(bNumInterfaces),                                            \
  USB_DESC_BYTE(bConfigurationValue),                                       \
  USB_DESC_INDEX(iConfiguration),                                           \
  USB_DESC_BYTE(bmAttributes),                                              \
  USB_DESC_BYTE(bMaxPower)
Configuration Descriptor helper macro.
Definition at line 149 of file hal_usb.h.
#define USB_DESC_INTERFACE_SIZE 9U
Interface Descriptor size.
Definition at line 164 of file hal_usb.h.
#define USB_DESC_INTERFACE (bInterfaceNumber, bAlternateSetting, bNumEndpoints, bInterfaceClass, bInterfaceSubClass, bInterfaceProtocol, iInterface)
Value:
USB_DESC_BYTE(USB_DESC_INTERFACE_SIZE),                                   \
  USB_DESC_BYTE(USB_DESCRIPTOR_INTERFACE),                                  \
  USB_DESC_BYTE(bInterfaceNumber),                                          \
  USB_DESC_BYTE(bAlternateSetting),                                         \
  USB_DESC_BYTE(bNumEndpoints),                                             \
  USB_DESC_BYTE(bInterfaceClass),                                           \
  USB_DESC_BYTE(bInterfaceSubClass),                                        \
  USB_DESC_BYTE(bInterfaceProtocol),                                        \
  USB_DESC_INDEX(iInterface)
Interface Descriptor helper macro.
Definition at line 169 of file hal_usb.h.
#define USB_DESC_INTERFACE_ASSOCIATION_SIZE 8U
Interface Association Descriptor size.
Definition at line 186 of file hal_usb.h.
#define USB_DESC_INTERFACE_ASSOCIATION (bFirstInterface, bInterfaceCount, bFunctionClass, bFunctionSubClass, bFunctionProcotol, iInterface)
Value:
USB_DESC_BYTE(USB_DESC_INTERFACE_ASSOCIATION_SIZE),                       \
  USB_DESC_BYTE(USB_DESCRIPTOR_INTERFACE_ASSOCIATION),                      \
  USB_DESC_BYTE(bFirstInterface),                                           \
  USB_DESC_BYTE(bInterfaceCount),                                           \
  USB_DESC_BYTE(bFunctionClass),                                            \
  USB_DESC_BYTE(bFunctionSubClass),                                         \
  USB_DESC_BYTE(bFunctionProcotol),                                         \
  USB_DESC_INDEX(iInterface)
Interface Association Descriptor helper macro.
Definition at line 191 of file hal_usb.h.
#define USB_DESC_ENDPOINT_SIZE 7U
Endpoint Descriptor size.
Definition at line 207 of file hal_usb.h.
#define USB_DESC_ENDPOINT (bEndpointAddress, bmAttributes, wMaxPacketSize, bInterval)
Value:
USB_DESC_BYTE(USB_DESC_ENDPOINT_SIZE),                                    \
  USB_DESC_BYTE(USB_DESCRIPTOR_ENDPOINT),                                   \
  USB_DESC_BYTE(bEndpointAddress),                                          \
  USB_DESC_BYTE(bmAttributes),                                              \
  USB_DESC_WORD(wMaxPacketSize),                                            \
  USB_DESC_BYTE(bInterval)
Endpoint Descriptor helper macro.
Definition at line 212 of file hal_usb.h.
#define USB_EP_MODE_TYPE 0x0003U
Endpoint type mask.
Definition at line 226 of file hal_usb.h.
Referenced by OSAL_IRQ_HANDLER(), usb_lld_init_endpoint(), usb_lld_start_in(), and usb_lld_start_out().
#define USB_EP_MODE_TYPE_CTRL 0x0000U
Control endpoint.
Definition at line 227 of file hal_usb.h.
Referenced by usb_lld_init_endpoint().
#define USB_EP_MODE_TYPE_ISOC 0x0001U
Isochronous endpoint.
Definition at line 228 of file hal_usb.h.
Referenced by OSAL_IRQ_HANDLER(), usb_lld_init_endpoint(), usb_lld_start_in(), and usb_lld_start_out().
#define USB_EP_MODE_TYPE_BULK 0x0002U
Bulk endpoint.
Definition at line 229 of file hal_usb.h.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_init_endpoint().
#define USB_EP_MODE_TYPE_INTR 0x0003U
Interrupt endpoint.
Definition at line 230 of file hal_usb.h.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_init_endpoint().
#define USB_USE_WAIT FALSE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 245 of file hal_usb.h.
#define usbGetDriverStateI (usbp) ((usbp)->state)
Returns the driver state.
Parameters
[in] usbp pointer to the USBDriver object
Returns
The driver state.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 391 of file hal_usb.h.
Referenced by obnotify(), sduSOFHookI(), usbReceive(), and usbTransmit().
#define usbConnectBus (usbp) usb_lld_connect_bus(usbp)
Connects the USB device.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 400 of file hal_usb.h.
#define usbDisconnectBus (usbp) usb_lld_disconnect_bus(usbp)
Disconnect the USB device.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 409 of file hal_usb.h.
#define usbGetFrameNumberX (usbp) usb_lld_get_frame_number(usbp)
Returns the current frame number.
Parameters
[in] usbp pointer to the USBDriver object
Returns
The current frame number.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 419 of file hal_usb.h.
#define usbGetTransmitStatusI (usbp, ep) (((usbp)->transmitting & (uint16_t)((unsigned)1U << (unsigned)(ep))) != 0U)
Returns the status of an IN endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The operation status.
Return values
false Endpoint ready.
true Endpoint transmitting.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 432 of file hal_usb.h.
Referenced by obnotify(), sduSOFHookI(), usbStallTransmitI(), and usbStartTransmitI().
#define usbGetReceiveStatusI (usbp, ep) (((usbp)->receiving & (uint16_t)((unsigned)1U << (unsigned)(ep))) != 0U)
Returns the status of an OUT endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The operation status.
Return values
false Endpoint ready.
true Endpoint receiving.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 446 of file hal_usb.h.
Referenced by usbStallReceiveI(), and usbStartReceiveI().
#define usbGetReceiveTransactionSizeX (usbp, ep) usb_lld_get_transaction_size(usbp, ep)
Returns the exact size of a receive transaction.
The received size can be different from the size specified in usbStartReceiveI() because the last packet could have a size different from the expected one.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
Received data size.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 461 of file hal_usb.h.
Referenced by _usb_ep0out(), and sduDataReceived().
#define usbSetupTransfer (usbp, buf, n, endcb)
Value:
{                             \
  (usbp)->ep0next  = (buf);                                                 \
  (usbp)->ep0n     = (n);                                                   \
  (usbp)->ep0endcb = (endcb);                                               \
}
Request transfer setup.
This macro is used by the request handling callbacks in order to prepare a transaction over the endpoint zero.
Parameters
[in] usbp pointer to the USBDriver object
[in] buf pointer to a buffer for the transaction data
[in] n number of bytes to be transferred
[in] endcb callback to be invoked after the transfer or NULL
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 476 of file hal_usb.h.
Referenced by default_handler(), and sduRequestsHook().
#define usbReadSetup (usbp, ep, buf) usb_lld_read_setup(usbp, ep, buf)
Reads a setup packet from the dedicated packet buffer.
This function must be invoked in the context of the setup_cb callback in order to read the received setup packet.
Precondition
In order to use this function the endpoint must have been initialized as a control endpoint.
Note
This function can be invoked both in thread and IRQ context.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[out] buf buffer where to copy the packet data
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 496 of file hal_usb.h.
Referenced by _usb_ep0setup().
#define _usb_isr_invoke_event_cb (usbp, evt)
Value:
{                               \
  if (((usbp)->config->event_cb) != NULL) {                                 \
    (usbp)->config->event_cb(usbp, evt);                                    \
  }                                                                         \
}
Common ISR code, usb event callback.
Parameters
[in] usbp pointer to the USBDriver object
[in] evt USB event code
Function Class:
Not an API, this function is for internal use only.
Definition at line 511 of file hal_usb.h.
Referenced by _usb_ep0in(), _usb_ep0out(), _usb_ep0setup(), _usb_reset(), _usb_suspend(), _usb_wakeup(), default_handler(), and set_address().
#define _usb_isr_invoke_sof_cb (usbp)
Value:
{                                      \
  if (((usbp)->config->sof_cb) != NULL) {                                   \
    (usbp)->config->sof_cb(usbp);                                           \
  }                                                                         \
}
Common ISR code, SOF callback.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 524 of file hal_usb.h.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_serve_interrupt().
#define _usb_isr_invoke_setup_cb (usbp, ep)
Value:
{                                \
  (usbp)->epc[ep]->setup_cb(usbp, ep);                                      \
}
Common ISR code, setup packet callback.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 538 of file hal_usb.h.
Referenced by otg_epout_handler(), and usb_serve_endpoints().
#define _usb_isr_invoke_in_cb (usbp, ep)
Value:
{                                   \
  (usbp)->transmitting &= ~(1 << (ep));                                     \
  if ((usbp)->epc[ep]->in_cb != NULL) {                                     \
    (usbp)->epc[ep]->in_cb(usbp, ep);                                       \
  }                                                                         \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(usbp)->epc[ep]->in_state->thread, MSG_OK);            \
  osalSysUnlockFromISR();                                                   \
}
Common ISR code, IN endpoint callback.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 551 of file hal_usb.h.
Referenced by otg_epin_handler(), otg_isoc_in_failed_handler(), and usb_serve_endpoints().
#define _usb_isr_invoke_out_cb (usbp, ep)
Value:
{                                  \
  (usbp)->receiving &= ~(1 << (ep));                                        \
  if ((usbp)->epc[ep]->out_cb != NULL) {                                    \
    (usbp)->epc[ep]->out_cb(usbp, ep);                                      \
  }                                                                         \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(usbp)->epc[ep]->out_state->thread,                    \
                    usbGetReceiveTransactionSizeX(usbp, ep));               \
  osalSysUnlockFromISR();                                                   \
}
Common ISR code, OUT endpoint event.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 578 of file hal_usb.h.
Referenced by otg_epout_handler(), otg_isoc_out_failed_handler(), and usb_serve_endpoints().
Typedef Documentation
typedef uint32_t stm32_usb_pma_t
Width of USB packet memory accesses.
Definition at line 42 of file stm32_usb.h.
typedef struct USBDriver USBDriver
Type of a structure representing an USB driver.
Definition at line 259 of file hal_usb.h.
typedef uint8_t usbep_t
Type of an endpoint identifier.
Definition at line 264 of file hal_usb.h.
typedef void(* usbcallback_t) (USBDriver *usbp)
Type of an USB generic notification callback.
Parameters
[in] usbp pointer to the USBDriver object triggering the callback
Definition at line 333 of file hal_usb.h.
typedef void(* usbepcallback_t) (USBDriver *usbp, usbep_t ep)
Type of an USB endpoint callback.
Parameters
[in] usbp pointer to the USBDriver object triggering the callback
[in] ep endpoint number
Definition at line 342 of file hal_usb.h.
typedef void(* usbeventcb_t) (USBDriver *usbp, usbevent_t event)
Type of an USB event notification callback.
Parameters
[in] usbp pointer to the USBDriver object triggering the callback
[in] event event type
Definition at line 351 of file hal_usb.h.
typedef bool(* usbreqhandler_t) (USBDriver *usbp)
Type of a requests handler callback.
The request is encoded in the usb_setup buffer.
Parameters
[in] usbp pointer to the USBDriver object triggering the callback
Returns
The request handling exit code.
Return values
false Request not recognized by the handler.
true Request handled.
Definition at line 363 of file hal_usb.h.
typedef const USBDescriptor*(* usbgetdescriptor_t) (USBDriver *usbp, uint8_t dtype, uint8_t dindex, uint16_t lang)
Type of an USB descriptor-retrieving callback.
Definition at line 368 of file hal_usb.h.
Enumeration Type Documentation
enum usbstate_t
Type of a driver state machine possible states.
Enumerator
USB_UNINIT
Not initialized.
USB_STOP
Stopped.
USB_READY
Ready, after bus reset.
USB_SELECTED
Address assigned.
USB_ACTIVE
Active, configuration selected.
USB_SUSPENDED
Suspended, low power mode.
Definition at line 269 of file hal_usb.h.
enum usbepstatus_t
Type of an endpoint status.
Enumerator
EP_STATUS_DISABLED
Endpoint not active.
EP_STATUS_STALLED
Endpoint opened but stalled.
EP_STATUS_ACTIVE
Active endpoint.
Definition at line 281 of file hal_usb.h.
enum usbep0state_t
Type of an endpoint zero state machine states.
Enumerator
USB_EP0_STP_WAITING
Waiting for SETUP data.
USB_EP0_IN_TX
Transmitting.
USB_EP0_IN_WAITING_TX0
Waiting transmit 0.
USB_EP0_IN_SENDING_STS
Sending status.
USB_EP0_OUT_WAITING_STS
Waiting status.
USB_EP0_OUT_RX
Receiving.
USB_EP0_ERROR
Error, EP0 stalled.
Definition at line 290 of file hal_usb.h.
enum usbevent_t
Type of an enumeration of the possible USB events.
Enumerator
USB_EVENT_RESET
Driver has been reset by host.
USB_EVENT_ADDRESS
Address assigned.
USB_EVENT_CONFIGURED
Configuration selected.
USB_EVENT_UNCONFIGURED
Configuration removed.
USB_EVENT_SUSPEND
Entering suspend mode.
USB_EVENT_WAKEUP
Leaving suspend mode.
USB_EVENT_STALLED
Endpoint 0 error, stalled.
Definition at line 303 of file hal_usb.h.
Function Documentation
static void otg_ram_reset (USBDriver * usbp) static
Resets the FIFO RAM memory allocator.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 194 of file OTGv1/hal_usb_lld.c.
References USBDriver::otgparams, and USBDriver::pmnext.
Referenced by usb_lld_disable_endpoints(), and usb_lld_reset().
static uint32_t otg_ram_alloc (USBDriver * usbp, size_t size) static
Allocates a block from the FIFO RAM memory.
Parameters
[in] usbp pointer to the USBDriver object
[in] size size of the packet buffer to allocate in words
Function Class:
Not an API, this function is for internal use only.
Definition at line 207 of file OTGv1/hal_usb_lld.c.
References osalDbgAssert, USBDriver::otgparams, and USBDriver::pmnext.
Referenced by usb_lld_init_endpoint(), and usb_lld_reset().
static void otg_fifo_write_from_buffer (volatile uint32_t * fifop, const uint8_t * buf, size_t n) static
Writes to a TX FIFO.
Parameters
[in] fifop pointer to the FIFO register
[in] buf buffer where to copy the endpoint data
[in] n maximum number of bytes to copy
Function Class:
Not an API, this function is for internal use only.
Definition at line 226 of file OTGv1/hal_usb_lld.c.
References osalDbgAssert.
Referenced by otg_txfifo_handler().
static void otg_fifo_read_to_buffer (volatile uint32_t * fifop, uint8_t * buf, size_t n, size_t max) static
Reads a packet from the RXFIFO.
Parameters
[in] fifop pointer to the FIFO register
[out] buf buffer where to copy the endpoint data
[in] n number of bytes to pull from the FIFO
[in] max number of bytes to copy into the buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 252 of file OTGv1/hal_usb_lld.c.
Referenced by otg_rxfifo_handler().
static void otg_rxfifo_handler (USBDriver * usbp) static
Incoming packets handler.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 278 of file OTGv1/hal_usb_lld.c.
References USBDriver::epc, stm32_otg_t::GRXSTSP, GRXSTSP_BCNT_MASK, GRXSTSP_BCNT_OFF, GRXSTSP_EPNUM_MASK, GRXSTSP_EPNUM_OFF, GRXSTSP_PKTSTS_MASK, USBDriver::otg, otg_fifo_read_to_buffer(), USBEndpointConfig::out_state, USBOutEndpointState::rxbuf, USBOutEndpointState::rxcnt, USBOutEndpointState::rxsize, and USBEndpointConfig::setup_buf.
Referenced by usb_lld_clear_in(), and usb_lld_serve_interrupt().
static bool otg_txfifo_handler (USBDriver * usbp, usbep_t ep) static
Outgoing packets handler.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 321 of file OTGv1/hal_usb_lld.c.
References stm32_otg_t::DIEPEMPMSK, DIEPEMPMSK_INEPTXFEM, stm32_otg_in_ep_t::DTXFSTS, DTXFSTS_INEPTFSAV_MASK, USBDriver::epc, stm32_otg_t::ie, USBEndpointConfig::in_maxsize, USBEndpointConfig::in_state, USBDriver::otg, otg_fifo_write_from_buffer(), STM32_USB_OTGFIFO_FILL_BASEPRI, USBInEndpointState::txbuf, USBInEndpointState::txcnt, and USBInEndpointState::txsize.
Referenced by otg_epin_handler(), otg_isoc_in_failed_handler(), and usb_lld_clear_in().
static void otg_epin_handler (USBDriver * usbp, usbep_t ep) static
Generic endpoint IN handler.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 367 of file OTGv1/hal_usb_lld.c.
References _usb_isr_invoke_in_cb, stm32_otg_t::DIEPEMPMSK, DIEPEMPMSK_INEPTXFEM, stm32_otg_in_ep_t::DIEPINT, DIEPINT_TOC, DIEPINT_TXFE, DIEPINT_XFRC, stm32_otg_t::DIEPMSK, DIEPMSK_XFRCM, USBDriver::epc, stm32_otg_t::ie, USBEndpointConfig::in_state, osalSysLockFromISR(), osalSysUnlockFromISR(), osalThreadResumeI(), USBDriver::otg, otg_txfifo_handler(), USBInEndpointState::totsize, USBInEndpointState::txcnt, USBInEndpointState::txsize, and usb_lld_start_in().
Referenced by usb_lld_serve_interrupt().
static void otg_epout_handler (USBDriver * usbp, usbep_t ep) static
Generic endpoint OUT handler.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 419 of file OTGv1/hal_usb_lld.c.
References _usb_isr_invoke_out_cb, _usb_isr_invoke_setup_cb, stm32_otg_out_ep_t::DOEPINT, DOEPINT_STUP, DOEPINT_XFRC, stm32_otg_t::DOEPMSK, DOEPMSK_STUPM, DOEPMSK_XFRCM, USBDriver::ep0state, USBDriver::epc, stm32_otg_t::oe, osalSysLockFromISR(), osalSysUnlockFromISR(), USBDriver::otg, USBEndpointConfig::out_maxsize, USBEndpointConfig::out_state, USBOutEndpointState::rxcnt, USBOutEndpointState::rxsize, USBOutEndpointState::totsize, and usb_lld_start_out().
Referenced by usb_lld_serve_interrupt().
static void otg_isoc_in_failed_handler (USBDriver * usbp) static
Isochronous IN transfer failed handler.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 476 of file OTGv1/hal_usb_lld.c.
References _usb_isr_invoke_in_cb, stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_EPDIS, DIEPCTL_EPENA, DIEPCTL_EPTYP_ISO, DIEPCTL_EPTYP_MASK, DIEPCTL_SNAK, stm32_otg_t::DIEPEMPMSK, stm32_otg_t::ie, osalSysLockFromISR(), osalSysUnlockFromISR(), osalThreadResumeI(), USBDriver::otg, otg_txfifo_handler(), and USBDriver::otgparams.
Referenced by usb_lld_serve_interrupt().
static void otg_isoc_out_failed_handler (USBDriver * usbp) static
Isochronous OUT transfer failed handler.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 517 of file OTGv1/hal_usb_lld.c.
References _usb_isr_invoke_out_cb, stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_EPENA, DOEPCTL_EPTYP_ISO, DOEPCTL_EPTYP_MASK, stm32_otg_t::oe, USBDriver::otg, and USBDriver::otgparams.
Referenced by usb_lld_serve_interrupt().
static void usb_lld_serve_interrupt (USBDriver * usbp) static
OTG shared ISR.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 543 of file OTGv1/hal_usb_lld.c.
References _usb_isr_invoke_sof_cb, _usb_reset(), _usb_suspend(), _usb_wakeup(), stm32_otg_t::DAINT, stm32_otg_t::DCTL, DCTL_RWUSIG, stm32_otg_t::DSTS, DSTS_ENUMSPD_HS_480, DSTS_ENUMSPD_MASK, stm32_otg_t::GINTMSK, GINTMSK_RXFLVLM, stm32_otg_t::GINTSTS, GINTSTS_ENUMDNE, GINTSTS_IEPINT, GINTSTS_IISOIXFR, GINTSTS_IISOOXFR, GINTSTS_OEPINT, GINTSTS_RXFLVL, GINTSTS_SOF, GINTSTS_USBRST, GINTSTS_USBSUSP, GINTSTS_WKUPINT, stm32_otg_t::GUSBCFG, GUSBCFG_TRDT, GUSBCFG_TRDT_MASK, osalSysLockFromISR(), osalSysUnlockFromISR(), osalThreadResumeI(), USBDriver::otg, otg_epin_handler(), otg_epout_handler(), otg_isoc_in_failed_handler(), otg_isoc_out_failed_handler(), otg_rxfifo_handler(), stm32_otg_t::PCGCCTL, PCGCCTL_GATEHCLK, and PCGCCTL_STPPCLK.
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_OTG1_HANDLER)
OTG1 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 709 of file OTGv1/hal_usb_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and usb_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_OTG2_HANDLER)
OTG2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 725 of file OTGv1/hal_usb_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and usb_lld_serve_interrupt().
void usb_lld_init (void)
Low level USB driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 744 of file OTGv1/hal_usb_lld.c.
References USBDriver::otg, OTG_FS, OTG_HS, USBDriver::otgparams, and usbObjectInit().
Referenced by OSAL_IRQ_HANDLER(), and usbInit().
void usb_lld_start (USBDriver * usbp)
Configures and activates the USB peripheral.
Note
Starting the OTG cell can be a slow operation carried out with interrupts disabled, perform it before starting time-critical operations.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 808 of file OTGv1/hal_usb_lld.c.
References USBDriver::config, stm32_otg_t::DAINTMSK, stm32_otg_t::DCFG, DCFG_DSPD_FS11, DCFG_DSPD_HS, DCFG_DSPD_HS_FS, stm32_otg_t::DIEPMSK, stm32_otg_t::DOEPMSK, stm32_otg_t::GAHBCFG, GAHBCFG_GINTMSK, stm32_otg_t::GCCFG, stm32_otg_t::GINTMSK, GINTMSK_ENUMDNEM, GINTMSK_ESUSPM, GINTMSK_IISOIXFRM, GINTMSK_IISOOXFRM, GINTMSK_SOFM, GINTMSK_SRQM, GINTMSK_USBRSTM, GINTMSK_USBSUSPM, GINTMSK_WKUM, stm32_otg_t::GINTSTS, stm32_otg_t::GOTGCTL, stm32_otg_t::GUSBCFG, GUSBCFG_FDMOD, GUSBCFG_HNPCAP, GUSBCFG_PHYSEL, GUSBCFG_SRPCAP, GUSBCFG_TRDT, USBDriver::otg, stm32_otg_t::PCGCCTL, rccEnableOTG_FS, rccResetOTG_FS, USBConfig::sof_cb, USBDriver::state, STM32_USB_OTG1_IRQ_PRIORITY, STM32_USB_OTG2_IRQ_PRIORITY, STM32_USB_OTG_THREAD_PRIO, and USB_STOP.
Referenced by OSAL_IRQ_HANDLER(), and usbStart().
void usb_lld_stop (USBDriver * usbp)
Deactivates the USB peripheral.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 962 of file OTGv1/hal_usb_lld.c.
References stm32_otg_t::DAINTMSK, stm32_otg_t::GAHBCFG, stm32_otg_t::GCCFG, USBDriver::otg, rccDisableOTG_FS, USBDriver::state, and USB_STOP.
Referenced by OSAL_IRQ_HANDLER(), and usbStop().
void usb_lld_reset (USBDriver * usbp)
USB low level reset routine.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 1005 of file OTGv1/hal_usb_lld.c.
References stm32_otg_t::DAINTMSK, DAINTMSK_IEPM, DAINTMSK_OEPM, stm32_otg_t::DCFG, DCFG_DAD, DCFG_DAD_MASK, stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_EPTYP_CTRL, DIEPCTL_MPSIZ, DIEPCTL_SD0PID, DIEPCTL_SNAK, DIEPCTL_TXFNUM, DIEPCTL_USBAEP, stm32_otg_t::DIEPEMPMSK, stm32_otg_in_ep_t::DIEPINT, stm32_otg_t::DIEPMSK, DIEPMSK_TOCM, DIEPMSK_XFRCM, stm32_otg_in_ep_t::DIEPTSIZ, stm32_otg_t::DIEPTXF0, DIEPTXF_INEPTXFD, DIEPTXF_INEPTXSA, stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_EPTYP_CTRL, DOEPCTL_MPSIZ, DOEPCTL_SD0PID, DOEPCTL_SNAK, DOEPCTL_USBAEP, stm32_otg_out_ep_t::DOEPINT, stm32_otg_t::DOEPMSK, DOEPMSK_STUPM, DOEPMSK_XFRCM, stm32_otg_out_ep_t::DOEPTSIZ, DOEPTSIZ_STUPCNT, ep0config, USBDriver::epc, stm32_otg_t::GINTMSK, GINTMSK_IEPM, GINTMSK_OEPM, GINTMSK_RXFLVLM, stm32_otg_t::GRXFSIZ, stm32_otg_t::ie, USBEndpointConfig::in_maxsize, stm32_otg_t::oe, USBDriver::otg, otg_ram_alloc(), otg_ram_reset(), USBDriver::otgparams, and USBEndpointConfig::out_maxsize.
Referenced by _usb_reset(), and OSAL_IRQ_HANDLER().
void usb_lld_set_address (USBDriver * usbp)
Sets the USB address.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 1059 of file OTGv1/hal_usb_lld.c.
References USBDriver::address, stm32_otg_t::DCFG, DCFG_DAD, DCFG_DAD_MASK, and USBDriver::otg.
Referenced by OSAL_IRQ_HANDLER(), and set_address().
void usb_lld_init_endpoint (USBDriver * usbp, usbep_t ep)
Enables an endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1073 of file OTGv1/hal_usb_lld.c.
References stm32_otg_t::DAINTMSK, DAINTMSK_IEPM, DAINTMSK_OEPM, stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_EPTYP_BULK, DIEPCTL_EPTYP_CTRL, DIEPCTL_EPTYP_INTR, DIEPCTL_EPTYP_ISO, DIEPCTL_MPSIZ, DIEPCTL_SD0PID, DIEPCTL_TXFNUM, DIEPCTL_USBAEP, stm32_otg_in_ep_t::DIEPTSIZ, stm32_otg_t::DIEPTXF, DIEPTXF_INEPTXFD, DIEPTXF_INEPTXSA, stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_MPSIZ, DOEPCTL_USBAEP, stm32_otg_out_ep_t::DOEPTSIZ, USBEndpointConfig::ep_mode, USBDriver::epc, stm32_otg_t::ie, USBEndpointConfig::in_maxsize, USBEndpointConfig::in_multiplier, USBEndpointConfig::in_state, stm32_otg_t::oe, USBDriver::otg, otg_ram_alloc(), USBEndpointConfig::out_maxsize, USBEndpointConfig::out_state, USB_EP_MODE_TYPE, USB_EP_MODE_TYPE_BULK, USB_EP_MODE_TYPE_CTRL, USB_EP_MODE_TYPE_INTR, and USB_EP_MODE_TYPE_ISOC.
Referenced by OSAL_IRQ_HANDLER(), and usbInitEndpointI().
void usb_lld_disable_endpoints (USBDriver * usbp)
Disables all the active endpoints except the endpoint zero.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 1137 of file OTGv1/hal_usb_lld.c.
References otg_ram_reset().
Referenced by OSAL_IRQ_HANDLER(), and usbDisableEndpointsI().
usbepstatus_t usb_lld_get_status_out (USBDriver * usbp, usbep_t ep)
Returns the status of an OUT endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The endpoint status.
Return values
EP_STATUS_DISABLED The endpoint is not active.
EP_STATUS_STALLED The endpoint is stalled.
EP_STATUS_ACTIVE The endpoint is active.
Function Class:
Not an API, this function is for internal use only.
Definition at line 1158 of file OTGv1/hal_usb_lld.c.
References stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_STALL, DOEPCTL_USBAEP, EP_STATUS_ACTIVE, EP_STATUS_DISABLED, EP_STATUS_STALLED, stm32_otg_t::oe, and USBDriver::otg.
Referenced by default_handler(), and OSAL_IRQ_HANDLER().
usbepstatus_t usb_lld_get_status_in (USBDriver * usbp, usbep_t ep)
Returns the status of an IN endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The endpoint status.
Return values
EP_STATUS_DISABLED The endpoint is not active.
EP_STATUS_STALLED The endpoint is stalled.
EP_STATUS_ACTIVE The endpoint is active.
Function Class:
Not an API, this function is for internal use only.
Definition at line 1183 of file OTGv1/hal_usb_lld.c.
References stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_STALL, DIEPCTL_USBAEP, EP_STATUS_ACTIVE, EP_STATUS_DISABLED, EP_STATUS_STALLED, stm32_otg_t::ie, and USBDriver::otg.
Referenced by default_handler(), and OSAL_IRQ_HANDLER().
void usb_lld_read_setup (USBDriver * usbp, usbep_t ep, uint8_t * buf)
Reads a setup packet from the dedicated packet buffer.
This function must be invoked in the context of the setup_cb callback in order to read the received setup packet.
Precondition
In order to use this function the endpoint must have been initialized as a control endpoint.
Postcondition
The endpoint is ready to accept another packet.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[out] buf buffer where to copy the packet data
Function Class:
Not an API, this function is for internal use only.
Definition at line 1210 of file OTGv1/hal_usb_lld.c.
References USBDriver::epc, and USBEndpointConfig::setup_buf.
Referenced by OSAL_IRQ_HANDLER().
void usb_lld_start_out (USBDriver * usbp, usbep_t ep)
Starts a receive operation on an OUT endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1223 of file OTGv1/hal_usb_lld.c.
References stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_CNAK, DOEPCTL_EPENA, DOEPCTL_SEVNFRM, DOEPCTL_SODDFRM, stm32_otg_out_ep_t::DOEPTSIZ, DOEPTSIZ_PKTCNT, DOEPTSIZ_STUPCNT, DOEPTSIZ_XFRSIZ, stm32_otg_t::DSTS, DSTS_FNSOF_ODD, USBEndpointConfig::ep_mode, USBDriver::epc, stm32_otg_t::oe, USBDriver::otg, USBEndpointConfig::out_maxsize, USBEndpointConfig::out_state, USBOutEndpointState::rxsize, USBOutEndpointState::totsize, USB_EP_MODE_TYPE, and USB_EP_MODE_TYPE_ISOC.
Referenced by OSAL_IRQ_HANDLER(), otg_epout_handler(), and usbStartReceiveI().
void usb_lld_start_in (USBDriver * usbp, usbep_t ep)
Starts a transmit operation on an IN endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1266 of file OTGv1/hal_usb_lld.c.
References stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_CNAK, DIEPCTL_EPENA, DIEPCTL_SEVNFRM, DIEPCTL_SODDFRM, stm32_otg_t::DIEPEMPMSK, DIEPEMPMSK_INEPTXFEM, stm32_otg_in_ep_t::DIEPTSIZ, DIEPTSIZ_MCNT, DIEPTSIZ_PKTCNT, DIEPTSIZ_XFRSIZ, stm32_otg_t::DSTS, DSTS_FNSOF_ODD, USBEndpointConfig::ep_mode, USBDriver::epc, stm32_otg_t::ie, USBEndpointConfig::in_maxsize, USBEndpointConfig::in_state, USBDriver::otg, USBInEndpointState::totsize, USBInEndpointState::txsize, USB_EP_MODE_TYPE, and USB_EP_MODE_TYPE_ISOC.
Referenced by OSAL_IRQ_HANDLER(), otg_epin_handler(), and usbStartTransmitI().
void usb_lld_stall_out (USBDriver * usbp, usbep_t ep)
Brings an OUT endpoint in the stalled state.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1309 of file OTGv1/hal_usb_lld.c.
References stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_STALL, stm32_otg_t::oe, and USBDriver::otg.
Referenced by _usb_ep0in(), _usb_ep0out(), _usb_ep0setup(), default_handler(), OSAL_IRQ_HANDLER(), and usbStallReceiveI().
void usb_lld_stall_in (USBDriver * usbp, usbep_t ep)
Brings an IN endpoint in the stalled state.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1322 of file OTGv1/hal_usb_lld.c.
References stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_STALL, stm32_otg_t::ie, and USBDriver::otg.
Referenced by _usb_ep0in(), _usb_ep0out(), _usb_ep0setup(), default_handler(), OSAL_IRQ_HANDLER(), and usbStallTransmitI().
void usb_lld_clear_out (USBDriver * usbp, usbep_t ep)
Brings an OUT endpoint in the active state.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1335 of file OTGv1/hal_usb_lld.c.
References stm32_otg_out_ep_t::DOEPCTL, DOEPCTL_STALL, stm32_otg_t::oe, and USBDriver::otg.
Referenced by default_handler(), and OSAL_IRQ_HANDLER().
void usb_lld_clear_in (USBDriver * usbp, usbep_t ep)
Brings an IN endpoint in the active state.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 1348 of file OTGv1/hal_usb_lld.c.
References stm32_otg_in_ep_t::DIEPCTL, DIEPCTL_STALL, stm32_otg_t::DIEPEMPMSK, stm32_otg_t::GAHBCFG, GAHBCFG_GINTMSK, stm32_otg_t::GINTMSK, GINTMSK_RXFLVLM, stm32_otg_t::GINTSTS, GINTSTS_RXFLVL, stm32_otg_t::ie, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), USBDriver::otg, otg_rxfifo_handler(), otg_txfifo_handler(), USBDriver::otgparams, USBDriver::state, and USB_STOP.
Referenced by default_handler(), and OSAL_IRQ_HANDLER().
static void usb_pm_reset (USBDriver * usbp) static
Resets the packet memory allocator.
Parameters
[in] usbp pointer to the USBDriver object
Definition at line 98 of file USBv1/hal_usb_lld.c.
References USBDriver::pmnext.
Referenced by OSAL_IRQ_HANDLER().
static uint32_t usb_pm_alloc (USBDriver * usbp, size_t size) static
Resets the packet memory allocator.
Parameters
[in] usbp pointer to the USBDriver object
[in] size size of the packet buffer to allocate
Returns
The packet buffer address.
Definition at line 112 of file USBv1/hal_usb_lld.c.
References osalDbgAssert, and USBDriver::pmnext.
Referenced by OSAL_IRQ_HANDLER().
static size_t usb_packet_read_to_buffer (usbep_t ep, uint8_t * buf) static
Reads from a dedicated packet buffer.
Parameters
[in] ep endpoint number
[out] buf buffer where to copy the packet data
Returns
The size of the receivee packet.
Function Class:
Not an API, this function is for internal use only.
Definition at line 130 of file USBv1/hal_usb_lld.c.
References stm32_usb_descriptor_t::RXADDR0, stm32_usb_descriptor_t::RXCOUNT0, STM32_USB, STM32_USB_USE_FAST_COPY, USB_ADDR2PTR, and USB_GET_DESCRIPTOR.
Referenced by usb_serve_endpoints().
static void usb_packet_write_from_buffer (usbep_t ep, const uint8_t * buf, size_t n) static
Writes to a dedicated packet buffer.
Parameters
[in] ep endpoint number
[in] buf buffer where to fetch the packet data
[in] n maximum number of bytes to copy. This value must not exceed the maximum packet size for this endpoint.
Function Class:
Not an API, this function is for internal use only.
Definition at line 213 of file USBv1/hal_usb_lld.c.
References STM32_USB, stm32_usb_descriptor_t::TXADDR0, stm32_usb_descriptor_t::TXCOUNT0, USB_ADDR2PTR, and USB_GET_DESCRIPTOR.
Referenced by OSAL_IRQ_HANDLER(), and usb_serve_endpoints().
static void usb_serve_endpoints (USBDriver * usbp, uint32_t ep) static
Common ISR code, serves the EP-related interrupts.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Function Class:
Not an API, this function is for internal use only.
Definition at line 290 of file USBv1/hal_usb_lld.c.
References _usb_isr_invoke_in_cb, _usb_isr_invoke_out_cb, _usb_isr_invoke_setup_cb, USBDriver::epc, USBEndpointConfig::in_maxsize, USBEndpointConfig::in_state, OSAL_IRQ_EPILOGUE, OSAL_IRQ_HANDLER(), OSAL_IRQ_PROLOGUE, USBEndpointConfig::out_state, USBOutEndpointState::rxbuf, USBOutEndpointState::rxcnt, USBOutEndpointState::rxpkts, USBOutEndpointState::rxsize, STM32_USB, USBInEndpointState::txbuf, USBInEndpointState::txcnt, USBInEndpointState::txlast, USBInEndpointState::txsize, usb_packet_read_to_buffer(), usb_packet_write_from_buffer(), and USBD1.
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_USB1_LP_HANDLER)
USB low priority interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 392 of file USBv1/hal_usb_lld.c.
References _usb_isr_invoke_sof_cb, _usb_reset(), _usb_suspend(), _usb_wakeup(), USBDriver::address, USBDriver::config, ep0config, USBEndpointConfig::ep_mode, EP_STATUS_ACTIVE, EP_STATUS_DISABLED, EP_STATUS_STALLED, USBDriver::epc, USBEndpointConfig::in_maxsize, USBEndpointConfig::in_state, OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, osalDbgAssert, USBEndpointConfig::out_maxsize, USBEndpointConfig::out_state, rccDisableUSB, rccEnableUSB, stm32_usb_descriptor_t::RXADDR0, stm32_usb_descriptor_t::RXCOUNT0, USBOutEndpointState::rxpkts, USBOutEndpointState::rxsize, USBConfig::sof_cb, USBDriver::state, STM32_USB, STM32_USB_USB1_HP_IRQ_PRIORITY, STM32_USB_USB1_LP_IRQ_PRIORITY, stm32_usb_descriptor_t::TXADDR0, USBInEndpointState::txbuf, stm32_usb_descriptor_t::TXCOUNT0, USBInEndpointState::txlast, USBInEndpointState::txsize, USB_ADDR2PTR, USB_ENDOPOINTS_NUMBER, USB_EP_MODE_TYPE, USB_EP_MODE_TYPE_BULK, USB_EP_MODE_TYPE_INTR, USB_EP_MODE_TYPE_ISOC, USB_GET_DESCRIPTOR, usb_lld_clear_in(), usb_lld_clear_out(), usb_lld_disable_endpoints(), usb_lld_get_status_in(), usb_lld_get_status_out(), usb_lld_init(), usb_lld_init_endpoint(), usb_lld_read_setup(), usb_lld_reset(), usb_lld_set_address(), usb_lld_stall_in(), usb_lld_stall_out(), usb_lld_start(), usb_lld_start_in(), usb_lld_start_out(), usb_lld_stop(), usb_packet_write_from_buffer(), usb_pm_alloc(), usb_pm_reset(), usb_serve_endpoints(), USB_STOP, USBD1, and usbObjectInit().
Referenced by usb_serve_endpoints().
static void set_address (USBDriver * usbp) static
SET ADDRESS transaction callback.
Parameters
[in] usbp pointer to the USBDriver object
Definition at line 64 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::address, USBDriver::setup, USBDriver::state, USB_EVENT_ADDRESS, usb_lld_set_address(), and USB_SELECTED.
Referenced by default_handler().
static bool default_handler (USBDriver * usbp) static
Standard requests handler.
This is the standard requests default handler, most standard requests are handled here, the user can override the standard handling using the requests_hook_cb hook in the USBConfig structure.
Parameters
[in] usbp pointer to the USBDriver object
Returns
The request handling exit code.
Return values
false Request not recognized by the handler or error.
true Request handled.
Definition at line 84 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::config, USBDriver::configuration, EP_STATUS_ACTIVE, EP_STATUS_DISABLED, EP_STATUS_STALLED, USBConfig::get_descriptor_cb, osalSysLockFromISR(), osalSysUnlockFromISR(), set_address(), USBDriver::setup, USBDriver::state, USBDriver::status, USBDescriptor::ud_size, USBDescriptor::ud_string, USB_ACTIVE, USB_EVENT_CONFIGURED, USB_EVENT_UNCONFIGURED, usb_lld_clear_in(), usb_lld_clear_out(), usb_lld_get_status_in(), usb_lld_get_status_out(), usb_lld_stall_in(), usb_lld_stall_out(), USB_SELECTED, usbDisableEndpointsI(), and usbSetupTransfer.
Referenced by _usb_ep0setup().
void usbInit (void)
USB Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 267 of file hal_usb.c.
References usb_lld_init().
Referenced by halInit().
void usbObjectInit (USBDriver * usbp)
Initializes the standard part of a USBDriver structure.
Parameters
[out] usbp pointer to the USBDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 279 of file hal_usb.c.
References USBDriver::config, USBDriver::in_params, USBDriver::out_params, USBDriver::receiving, USBDriver::state, USBDriver::transmitting, USB_MAX_ENDPOINTS, and USB_STOP.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_init().
void usbStart (USBDriver * usbp, const USBConfig * config)
Configures and activates the USB peripheral.
Parameters
[in] usbp pointer to the USBDriver object
[in] config pointer to the USBConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 300 of file hal_usb.c.
References USBDriver::config, USBDriver::epc, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), USBDriver::state, usb_lld_start(), USB_MAX_ENDPOINTS, USB_READY, and USB_STOP.
void usbStop (USBDriver * usbp)
Deactivates the USB peripheral.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 324 of file hal_usb.c.
References USBDriver::config, USBDriver::epc, USBEndpointConfig::in_state, osalDbgAssert, osalDbgCheck, osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), osalThreadResumeI(), USBEndpointConfig::out_state, USBDriver::state, USBInEndpointState::thread, USBOutEndpointState::thread, USB_ACTIVE, usb_lld_stop(), USB_MAX_ENDPOINTS, USB_READY, USB_SELECTED, USB_STOP, and USB_SUSPENDED.
void usbInitEndpointI (USBDriver * usbp, usbep_t ep, const USBEndpointConfig * epcp)
Enables an endpoint.
This function enables an endpoint, both IN and/or OUT directions depending on the configuration structure.
Note
This function must be invoked in response of a SET_CONFIGURATION or SET_INTERFACE message.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[in] epcp the endpoint configuration
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 372 of file hal_usb.c.
References USBDriver::epc, USBEndpointConfig::in_state, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, USBEndpointConfig::out_state, USBDriver::state, USB_ACTIVE, and usb_lld_init_endpoint().
void usbDisableEndpointsI (USBDriver * usbp)
Disables all the active endpoints.
This function disables all the active endpoints except the endpoint zero.
Note
This function must be invoked in response of a SET_CONFIGURATION message with configuration number zero.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 407 of file hal_usb.c.
References USBDriver::epc, USBEndpointConfig::in_state, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, osalThreadResumeI(), USBEndpointConfig::out_state, USBDriver::receiving, USBDriver::state, USBInEndpointState::thread, USBOutEndpointState::thread, USBDriver::transmitting, USB_ACTIVE, usb_lld_disable_endpoints(), and USB_MAX_ENDPOINTS.
Referenced by default_handler().
void usbStartReceiveI (USBDriver * usbp, usbep_t ep, uint8_t * buf, size_t n)
Starts a receive transaction on an OUT endpoint.
Note
This function is meant to be called from ISR context outside critical zones because there is a potentially slow operation inside.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[out] buf buffer where to copy the received data
[in] n transaction size. It is recommended a multiple of the packet size because the excess is discarded.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 450 of file hal_usb.c.
References USBDriver::epc, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, USBEndpointConfig::out_state, USBDriver::receiving, USBOutEndpointState::rxbuf, USBOutEndpointState::rxcnt, USBOutEndpointState::rxsize, USBOutEndpointState::thread, usb_lld_start_out(), USB_MAX_ENDPOINTS, and usbGetReceiveStatusI.
Referenced by _usb_ep0in(), _usb_ep0setup(), and usbReceive().
void usbStartTransmitI (USBDriver * usbp, usbep_t ep, const uint8_t * buf, size_t n)
Starts a transmit transaction on an IN endpoint.
Note
This function is meant to be called from ISR context outside critical zones because there is a potentially slow operation inside.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[in] buf buffer where to fetch the data to be transmitted
[in] n transaction size
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 489 of file hal_usb.c.
References USBDriver::epc, USBEndpointConfig::in_state, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, USBInEndpointState::thread, USBDriver::transmitting, USBInEndpointState::txbuf, USBInEndpointState::txcnt, USBInEndpointState::txsize, usb_lld_start_in(), USB_MAX_ENDPOINTS, and usbGetTransmitStatusI.
Referenced by _usb_ep0in(), _usb_ep0out(), _usb_ep0setup(), obnotify(), sduDataTransmitted(), sduSOFHookI(), and usbTransmit().
msg_t usbReceive (USBDriver * usbp, usbep_t ep, uint8_t * buf, size_t n)
Performs a receive transaction on an OUT endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[out] buf buffer where to copy the received data
[in] n transaction size. It is recommended a multiple of the packet size because the excess is discarded.
Returns
The received effective data size, it can be less than the amount specified.
Return values
MSG_RESET driver not in USB_ACTIVE state or the operation has been aborted by an USB reset or a transition to the USB_SUSPENDED state.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 533 of file hal_usb.c.
References USBDriver::epc, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), USBEndpointConfig::out_state, USBOutEndpointState::thread, USB_ACTIVE, usbGetDriverStateI, and usbStartReceiveI().
msg_t usbTransmit (USBDriver * usbp, usbep_t ep, const uint8_t * buf, size_t n)
Performs a transmit transaction on an IN endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
[in] buf buffer where to fetch the data to be transmitted
[in] n transaction size
Returns
The operation status.
Return values
MSG_OK operation performed successfully.
MSG_RESET driver not in USB_ACTIVE state or the operation has been aborted by an USB reset or a transition to the USB_SUSPENDED state.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 566 of file hal_usb.c.
References USBDriver::epc, USBEndpointConfig::in_state, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), USBInEndpointState::thread, USB_ACTIVE, usbGetDriverStateI, and usbStartTransmitI().
bool usbStallReceiveI (USBDriver * usbp, usbep_t ep)
Stalls an OUT endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The operation status.
Return values
false Endpoint stalled.
true Endpoint busy, not stalled.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 596 of file hal_usb.c.
References osalDbgCheck, osalDbgCheckClassI, usb_lld_stall_out(), and usbGetReceiveStatusI.
bool usbStallTransmitI (USBDriver * usbp, usbep_t ep)
Stalls an IN endpoint.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number
Returns
The operation status.
Return values
false Endpoint stalled.
true Endpoint busy, not stalled.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 621 of file hal_usb.c.
References osalDbgCheck, osalDbgCheckClassI, usb_lld_stall_in(), and usbGetTransmitStatusI.
void usbWakeupHost (USBDriver * usbp)
Host wake-up procedure.
Note
It is silently ignored if the USB device is not in the USB_SUSPENDED state.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 643 of file hal_usb.c.
References USBDriver::state, usb_lld_wakeup_host, and USB_SUSPENDED.
void _usb_reset (USBDriver * usbp)
USB reset routine.
This function must be invoked when an USB bus reset condition is detected.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 660 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::address, USBDriver::configuration, USBDriver::ep0state, USBDriver::epc, USBEndpointConfig::in_state, osalSysLockFromISR(), osalSysUnlockFromISR(), osalThreadResumeI(), USBEndpointConfig::out_state, USBDriver::receiving, USBDriver::state, USBDriver::status, USBInEndpointState::thread, USBOutEndpointState::thread, USBDriver::transmitting, USB_EP0_STP_WAITING, USB_EVENT_RESET, usb_lld_reset(), USB_MAX_ENDPOINTS, and USB_READY.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_serve_interrupt().
void _usb_suspend (USBDriver * usbp)
USB suspend routine.
This function must be invoked when an USB bus suspend condition is detected.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 710 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::epc, USBEndpointConfig::in_state, osalSysLockFromISR(), osalSysUnlockFromISR(), osalThreadResumeI(), USBEndpointConfig::out_state, USBDriver::saved_state, USBDriver::state, USBInEndpointState::thread, USBOutEndpointState::thread, USB_EVENT_SUSPEND, USB_MAX_ENDPOINTS, and USB_SUSPENDED.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_serve_interrupt().
void _usb_wakeup (USBDriver * usbp)
USB wake-up routine.
This function must be invoked when an USB bus wake-up condition is detected.
Parameters
[in] usbp pointer to the USBDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 750 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::saved_state, USBDriver::state, and USB_EVENT_WAKEUP.
Referenced by OSAL_IRQ_HANDLER(), and usb_lld_serve_interrupt().
void _usb_ep0setup (USBDriver * usbp, usbep_t ep)
Default EP0 SETUP callback.
This function is used by the low level driver as default handler for EP0 SETUP events.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number, always zero
Function Class:
Not an API, this function is for internal use only.
Definition at line 769 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::config, default_handler(), USBDriver::ep0n, USBDriver::ep0next, USBDriver::ep0state, osalSysLockFromISR(), osalSysUnlockFromISR(), USBConfig::requests_hook_cb, USBDriver::setup, USB_EP0_ERROR, USB_EP0_IN_SENDING_STS, USB_EP0_IN_TX, USB_EP0_OUT_RX, USB_EP0_OUT_WAITING_STS, USB_EP0_STP_WAITING, USB_EVENT_STALLED, usb_lld_stall_in(), usb_lld_stall_out(), usbReadSetup, usbStartReceiveI(), and usbStartTransmitI().
void _usb_ep0in (USBDriver * usbp, usbep_t ep)
Default EP0 IN callback.
This function is used by the low level driver as default handler for EP0 IN events.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number, always zero
Function Class:
Not an API, this function is for internal use only.
Definition at line 877 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::ep0endcb, USBDriver::ep0n, USBDriver::ep0state, USBDriver::epc, USBEndpointConfig::in_maxsize, osalDbgAssert, osalSysLockFromISR(), osalSysUnlockFromISR(), USBDriver::setup, USB_EP0_ERROR, USB_EP0_IN_SENDING_STS, USB_EP0_IN_TX, USB_EP0_IN_WAITING_TX0, USB_EP0_OUT_RX, USB_EP0_OUT_WAITING_STS, USB_EP0_STP_WAITING, USB_EVENT_STALLED, usb_lld_stall_in(), usb_lld_stall_out(), usbStartReceiveI(), and usbStartTransmitI().
void _usb_ep0out (USBDriver * usbp, usbep_t ep)
Default EP0 OUT callback.
This function is used by the low level driver as default handler for EP0 OUT events.
Parameters
[in] usbp pointer to the USBDriver object
[in] ep endpoint number, always zero
Function Class:
Not an API, this function is for internal use only.
Definition at line 944 of file hal_usb.c.
References _usb_isr_invoke_event_cb, USBDriver::ep0endcb, USBDriver::ep0state, osalDbgAssert, osalSysLockFromISR(), osalSysUnlockFromISR(), USB_EP0_ERROR, USB_EP0_IN_SENDING_STS, USB_EP0_IN_TX, USB_EP0_IN_WAITING_TX0, USB_EP0_OUT_RX, USB_EP0_OUT_WAITING_STS, USB_EP0_STP_WAITING, USB_EVENT_STALLED, usb_lld_stall_in(), usb_lld_stall_out(), usbGetReceiveTransactionSizeX, and usbStartTransmitI().
Variable Documentation
USBDriver USBD1
OTG_FS driver identifier.
Definition at line 65 of file OTGv1/hal_usb_lld.c.
USBDriver USBD2
OTG_HS driver identifier.
Definition at line 70 of file OTGv1/hal_usb_lld.c.
union { ... } ep0_state
EP0 state.
Note
It is an union because IN and OUT endpoints are never used at the same time for EP0.
USBInEndpointState { ... } in
IN EP0 state.
Definition at line 86 of file OTGv1/hal_usb_lld.c.
USBOutEndpointState { ... } out
OUT EP0 state.
Definition at line 90 of file OTGv1/hal_usb_lld.c.
uint8_t ep0setup_buffer[8] static
Buffer for the EP0 setup packets.
Definition at line 96 of file OTGv1/hal_usb_lld.c.
const USBEndpointConfig ep0config static
Initial value:
= {
  USB_EP_MODE_TYPE_CTRL,
  _usb_ep0setup,
  _usb_ep0in,
  _usb_ep0out,
  0x40,
  0x40,
  &ep0_state.in,
  &ep0_state.out,
  1,
  ep0setup_buffer
}
EP0 initialization structure.
Definition at line 101 of file OTGv1/hal_usb_lld.c.
Referenced by usb_lld_reset().
USBDriver USBD1
OTG_FS driver identifier.
Definition at line 65 of file hal_usb_lld_alt.c.
USBDriver USBD2
OTG_HS driver identifier.
Definition at line 70 of file hal_usb_lld_alt.c.
union { ... } ep0_state
EP0 state.
Note
It is an union because IN and OUT endpoints are never used at the same time for EP0.
USBInEndpointState { ... } in
IN EP0 state.
Definition at line 86 of file hal_usb_lld_alt.c.
USBOutEndpointState { ... } out
OUT EP0 state.
Definition at line 90 of file hal_usb_lld_alt.c.
uint8_t ep0setup_buffer[8] static
Buffer for the EP0 setup packets.
Definition at line 96 of file hal_usb_lld_alt.c.
const USBEndpointConfig ep0config static
Initial value:
= {
  USB_EP_MODE_TYPE_CTRL,
  _usb_ep0setup,
  _usb_ep0in,
  _usb_ep0out,
  0x40,
  0x40,
  &ep0_state.in,
  &ep0_state.out,
  1,
  ep0setup_buffer
}
EP0 initialization structure.
Definition at line 101 of file hal_usb_lld_alt.c.
USBDriver USBD1
USB1 driver identifier.
Definition at line 45 of file USBv1/hal_usb_lld.c.
Referenced by OSAL_IRQ_HANDLER(), and usb_serve_endpoints().
union { ... } ep0_state
EP0 state.
Note
It is an union because IN and OUT endpoints are never used at the same time for EP0.
USBInEndpointState { ... } in
IN EP0 state.
Definition at line 61 of file USBv1/hal_usb_lld.c.
USBOutEndpointState { ... } out
OUT EP0 state.
Definition at line 65 of file USBv1/hal_usb_lld.c.
uint8_t ep0setup_buffer[8] static
Buffer for the EP0 setup packets.
Definition at line 71 of file USBv1/hal_usb_lld.c.
const USBEndpointConfig ep0config static
Initial value:
= {
  USB_EP_MODE_TYPE_CTRL,
  _usb_ep0setup,
  _usb_ep0in,
  _usb_ep0out,
  0x40,
  0x40,
  &ep0_state.in,
  &ep0_state.out,
  1,
  ep0setup_buffer
}
EP0 initialization structure.
Definition at line 76 of file USBv1/hal_usb_lld.c.
Referenced by OSAL_IRQ_HANDLER().