ChibiOS/HAL: SPI Driver
SPI Driver
HAL » Normal Drivers
Generic SPI Driver.
Detailed Description
Generic SPI Driver.
This module implements a generic SPI (Serial Peripheral Interface) driver allowing bidirectional and monodirectional transfers, complex atomic transactions are supported as well.
Precondition
In order to use the SPI driver the HAL_USE_SPI option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
The driver is not thread safe for performance reasons, if you need to access the SPI bus from multiple threads then use the spiAcquireBus() and spiReleaseBus() APIs in order to gain exclusive access.
Macros
#define SPI_SUPPORTS_CIRCULAR TRUE
Circular mode support flag.
Configuration options
#define STM32_SPI_USE_SPI1 FALSE
SPI1 driver enable switch.
#define STM32_SPI_USE_SPI2 FALSE
SPI2 driver enable switch.
#define STM32_SPI_USE_SPI3 FALSE
SPI3 driver enable switch.
#define STM32_SPI_USE_SPI4 FALSE
SPI4 driver enable switch.
#define STM32_SPI_USE_SPI5 FALSE
SPI5 driver enable switch.
#define STM32_SPI_USE_SPI6 FALSE
SPI6 driver enable switch.
#define STM32_SPI_SPI1_IRQ_PRIORITY 10
SPI1 interrupt priority level setting.
#define STM32_SPI_SPI2_IRQ_PRIORITY 10
SPI2 interrupt priority level setting.
#define STM32_SPI_SPI3_IRQ_PRIORITY 10
SPI3 interrupt priority level setting.
#define STM32_SPI_SPI4_IRQ_PRIORITY 10
SPI4 interrupt priority level setting.
#define STM32_SPI_SPI5_IRQ_PRIORITY 10
SPI5 interrupt priority level setting.
#define STM32_SPI_SPI6_IRQ_PRIORITY 10
SPI6 interrupt priority level setting.
#define STM32_SPI_SPI1_DMA_PRIORITY 1
SPI1 DMA priority (0..3|lowest..highest).
#define STM32_SPI_SPI2_DMA_PRIORITY 1
SPI2 DMA priority (0..3|lowest..highest).
#define STM32_SPI_SPI3_DMA_PRIORITY 1
SPI3 DMA priority (0..3|lowest..highest).
#define STM32_SPI_SPI4_DMA_PRIORITY 1
SPI4 DMA priority (0..3|lowest..highest).
#define STM32_SPI_SPI5_DMA_PRIORITY 1
SPI5 DMA priority (0..3|lowest..highest).
#define STM32_SPI_SPI6_DMA_PRIORITY 1
SPI6 DMA priority (0..3|lowest..highest).
#define STM32_SPI_DMA_ERROR_HOOK(spip) osalSysHalt("DMA failure")
SPI DMA error hook.
Chip Select modes
#define SPI_SELECT_MODE_NONE
#define SPI_SELECT_MODE_PAD 1 /** @brief Legacy mode. */
#define SPI_SELECT_MODE_PORT 2 /** @brief Fastest mode. */
#define SPI_SELECT_MODE_LINE 3 /** @brief Packed mode. */
#define SPI_SELECT_MODE_LLD 4 /** @brief LLD-defined mode.*/
SPI configuration options
#define SPI_USE_WAIT TRUE
Enables synchronous APIs.
#define SPI_USE_CIRCULAR FALSE
Enables circular transfers APIs.
#define SPI_USE_MUTUAL_EXCLUSION TRUE
Enables the spiAcquireBus() and spiReleaseBus() APIs.
#define SPI_SELECT_MODE SPI_SELECT_MODE_PAD
Enables the use of the .
Macro Functions
#define spiSelectI(spip)
Asserts the slave select signal and prepares for transfers.
#define spiUnselectI(spip)
Deasserts the slave select signal.
#define spiStartIgnoreI(spip, n)
Ignores data on the SPI bus.
#define spiStartExchangeI(spip, n, txbuf, rxbuf)
Exchanges data on the SPI bus.
#define spiStartSendI(spip, n, txbuf)
Sends data over the SPI bus.
#define spiStartReceiveI(spip, n, rxbuf)
Receives data from the SPI bus.
#define spiPolledExchange(spip, frame) spi_lld_polled_exchange(spip, frame)
Exchanges one frame using a polled wait.
Low level driver helper macros
#define _spi_wakeup_isr(spip)
Wakes up the waiting thread.
#define _spi_isr_code(spip)
Common ISR code.
#define _spi_isr_code_half1(spip)
Common ISR code in circular mode.
#define _spi_isr_code_half2(spip)
Common ISR code in circular mode.
Typedefs
typedef struct SPIDriver SPIDriver
Type of a structure representing an SPI driver.
typedef void(* spicallback_t) (SPIDriver *spip)
SPI notification callback type.
Data Structures
struct SPIConfig
Driver configuration structure.
struct SPIDriver
Structure representing an SPI driver.
Functions
static void spi_lld_serve_rx_interrupt (SPIDriver *spip, uint32_t flags)
Shared end-of-rx service routine.
static void spi_lld_serve_tx_interrupt (SPIDriver *spip, uint32_t flags)
Shared end-of-tx service routine.
void spi_lld_init (void)
Low level SPI driver initialization.
void spi_lld_start (SPIDriver *spip)
Configures and activates the SPI peripheral.
void spi_lld_stop (SPIDriver *spip)
Deactivates the SPI peripheral.
void spi_lld_select (SPIDriver *spip)
Asserts the slave select signal and prepares for transfers.
void spi_lld_unselect (SPIDriver *spip)
Deasserts the slave select signal.
void spi_lld_ignore (SPIDriver *spip, size_t n)
Ignores data on the SPI bus.
void spi_lld_exchange (SPIDriver *spip, size_t n, const void *txbuf, void *rxbuf)
Exchanges data on the SPI bus.
void spi_lld_send (SPIDriver *spip, size_t n, const void *txbuf)
Sends data over the SPI bus.
void spi_lld_receive (SPIDriver *spip, size_t n, void *rxbuf)
Receives data from the SPI bus.
void spi_lld_abort (SPIDriver *spip)
Aborts the ongoing SPI operation, if any.
uint16_t spi_lld_polled_exchange (SPIDriver *spip, uint16_t frame)
Exchanges one frame using a polled wait.
void spiInit (void)
SPI Driver initialization.
void spiObjectInit (SPIDriver *spip)
Initializes the standard part of a SPIDriver structure.
void spiStart (SPIDriver *spip, const SPIConfig *config)
Configures and activates the SPI peripheral.
void spiStop (SPIDriver *spip)
Deactivates the SPI peripheral.
void spiSelect (SPIDriver *spip)
Asserts the slave select signal and prepares for transfers.
void spiUnselect (SPIDriver *spip)
Deasserts the slave select signal.
void spiStartIgnore (SPIDriver *spip, size_t n)
Ignores data on the SPI bus.
void spiStartExchange (SPIDriver *spip, size_t n, const void *txbuf, void *rxbuf)
Exchanges data on the SPI bus.
void spiStartSend (SPIDriver *spip, size_t n, const void *txbuf)
Sends data over the SPI bus.
void spiStartReceive (SPIDriver *spip, size_t n, void *rxbuf)
Receives data from the SPI bus.
void spiAbortI (SPIDriver *spip)
Aborts the ongoing SPI operation.
void spiAbort (SPIDriver *spip)
Aborts the ongoing SPI operation, if any.
void spiIgnore (SPIDriver *spip, size_t n)
Ignores data on the SPI bus.
void spiExchange (SPIDriver *spip, size_t n, const void *txbuf, void *rxbuf)
Exchanges data on the SPI bus.
void spiSend (SPIDriver *spip, size_t n, const void *txbuf)
Sends data over the SPI bus.
void spiReceive (SPIDriver *spip, size_t n, void *rxbuf)
Receives data from the SPI bus.
void spiAcquireBus (SPIDriver *spip)
Gains exclusive access to the SPI bus.
void spiReleaseBus (SPIDriver *spip)
Releases exclusive access to the SPI bus.
Enumerations
Variables
SPIDriver SPID1
SPI1 driver identifier.
SPIDriver SPID2
SPI2 driver identifier.
SPIDriver SPID3
SPI3 driver identifier.
SPIDriver SPID4
SPI4 driver identifier.
SPIDriver SPID5
SPI5 driver identifier.
SPIDriver SPID6
SPI6 driver identifier.
Macro Definition Documentation
#define SPI_SUPPORTS_CIRCULAR TRUE
Circular mode support flag.
Definition at line 37 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI1 FALSE
SPI1 driver enable switch.
If set to TRUE the support for SPI1 is included.
Note
The default is FALSE.
Definition at line 53 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI2 FALSE
SPI2 driver enable switch.
If set to TRUE the support for SPI2 is included.
Note
The default is FALSE.
Definition at line 62 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI3 FALSE
SPI3 driver enable switch.
If set to TRUE the support for SPI3 is included.
Note
The default is FALSE.
Definition at line 71 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI4 FALSE
SPI4 driver enable switch.
If set to TRUE the support for SPI4 is included.
Note
The default is FALSE.
Definition at line 80 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI5 FALSE
SPI5 driver enable switch.
If set to TRUE the support for SPI5 is included.
Note
The default is FALSE.
Definition at line 89 of file hal_spi_lld.h.
#define STM32_SPI_USE_SPI6 FALSE
SPI6 driver enable switch.
If set to TRUE the support for SPI6 is included.
Note
The default is FALSE.
Definition at line 98 of file hal_spi_lld.h.
#define STM32_SPI_SPI1_IRQ_PRIORITY 10
SPI1 interrupt priority level setting.
Definition at line 105 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI2_IRQ_PRIORITY 10
SPI2 interrupt priority level setting.
Definition at line 112 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI3_IRQ_PRIORITY 10
SPI3 interrupt priority level setting.
Definition at line 119 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI4_IRQ_PRIORITY 10
SPI4 interrupt priority level setting.
Definition at line 126 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI5_IRQ_PRIORITY 10
SPI5 interrupt priority level setting.
Definition at line 133 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI6_IRQ_PRIORITY 10
SPI6 interrupt priority level setting.
Definition at line 140 of file hal_spi_lld.h.
Referenced by spi_lld_start().
#define STM32_SPI_SPI1_DMA_PRIORITY 1
SPI1 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 150 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_SPI2_DMA_PRIORITY 1
SPI2 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 160 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_SPI3_DMA_PRIORITY 1
SPI3 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 170 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_SPI4_DMA_PRIORITY 1
SPI4 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 180 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_SPI5_DMA_PRIORITY 1
SPI5 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 190 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_SPI6_DMA_PRIORITY 1
SPI6 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 200 of file hal_spi_lld.h.
Referenced by spi_lld_init().
#define STM32_SPI_DMA_ERROR_HOOK (spip) osalSysHalt("DMA failure")
SPI DMA error hook.
Definition at line 207 of file hal_spi_lld.h.
Referenced by spi_lld_serve_rx_interrupt(), and spi_lld_serve_tx_interrupt().
#define SPI_USE_WAIT TRUE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 60 of file hal_spi.h.
#define SPI_USE_CIRCULAR FALSE
Enables circular transfers APIs.
Note
Disabling this option saves both code and data space.
Definition at line 68 of file hal_spi.h.
#define SPI_USE_MUTUAL_EXCLUSION TRUE
Enables the spiAcquireBus() and spiReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 76 of file hal_spi.h.
#define SPI_SELECT_MODE SPI_SELECT_MODE_PAD
Enables the use of the .
Note
Disabling this option saves both code and data space.
Definition at line 84 of file hal_spi.h.
#define spiSelectI (spip)
Value:
do {                                                                        \
  spi_lld_select(spip);                                                     \
} while (false)
Asserts the slave select signal and prepares for transfers.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 139 of file hal_spi.h.
Referenced by spiSelect().
#define spiUnselectI (spip)
Value:
do {                                                                        \
  spi_lld_unselect(spip);                                                   \
} while (false)
Deasserts the slave select signal.
The previously selected peripheral is unselected.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 152 of file hal_spi.h.
Referenced by spiUnselect().
#define spiStartIgnoreI (spip, n)
Value:
{                                          \
  (spip)->state = SPI_ACTIVE;                                               \
  spi_lld_ignore(spip, n);                                                  \
}
Ignores data on the SPI bus.
This asynchronous function starts the transmission of a series of idle words on the SPI bus and ignores the received data.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be ignored
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 209 of file hal_spi.h.
Referenced by spiIgnore(), and spiStartIgnore().
#define spiStartExchangeI (spip, n, txbuf, rxbuf)
Value:
{                          \
  (spip)->state = SPI_ACTIVE;                                               \
  spi_lld_exchange(spip, n, txbuf, rxbuf);                                  \
}
Exchanges data on the SPI bus.
This asynchronous function starts a simultaneous transmit/receive operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be exchanged
[in] txbuf the pointer to the transmit buffer
[out] rxbuf the pointer to the receive buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 231 of file hal_spi.h.
Referenced by spiExchange(), and spiStartExchange().
#define spiStartSendI (spip, n, txbuf)
Value:
{                                     \
  (spip)->state = SPI_ACTIVE;                                               \
  spi_lld_send(spip, n, txbuf);                                             \
}
Sends data over the SPI bus.
This asynchronous function starts a transmit operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to send
[in] txbuf the pointer to the transmit buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 251 of file hal_spi.h.
Referenced by spiSend(), and spiStartSend().
#define spiStartReceiveI (spip, n, rxbuf)
Value:
{                                  \
  (spip)->state = SPI_ACTIVE;                                               \
  spi_lld_receive(spip, n, rxbuf);                                          \
}
Receives data from the SPI bus.
This asynchronous function starts a receive operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to receive
[out] rxbuf the pointer to the receive buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 271 of file hal_spi.h.
Referenced by spiReceive(), and spiStartReceive().
#define spiPolledExchange (spip, frame) spi_lld_polled_exchange(spip, frame)
Exchanges one frame using a polled wait.
This synchronous function exchanges one frame using a polled synchronization method. This function is useful when exchanging small amount of data on high speed channels, usually in this situation is much more efficient just wait for completion using polling than suspending the thread waiting for an interrupt.
Note
This API is implemented as a macro in order to minimize latency.
Parameters
[in] spip pointer to the SPIDriver object
[in] frame the data frame to send over the SPI bus
Returns
The received data frame from the SPI bus.
Definition at line 289 of file hal_spi.h.
#define _spi_wakeup_isr (spip)
Value:
{                                             \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(spip)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 304 of file hal_spi.h.
#define _spi_isr_code (spip)
Value:
{                                               \
  if ((spip)->config->end_cb) {                                             \
    (spip)->state = SPI_COMPLETE;                                           \
    (spip)->config->end_cb(spip);                                           \
    if ((spip)->state == SPI_COMPLETE)                                      \
      (spip)->state = SPI_READY;                                            \
  }                                                                         \
  else                                                                      \
    (spip)->state = SPI_READY;                                              \
  _spi_wakeup_isr(spip);                                                    \
}
Common ISR code.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 327 of file hal_spi.h.
Referenced by spi_lld_serve_rx_interrupt().
#define _spi_isr_code_half1 (spip)
Value:
{                                         \
  if ((spip)->config->end_cb) {                                             \
    (spip)->config->end_cb(spip);                                           \
  }                                                                         \
}
Common ISR code in circular mode.
This code handles the portable part of the ISR code:
Callback invocation.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 351 of file hal_spi.h.
Referenced by spi_lld_serve_rx_interrupt().
#define _spi_isr_code_half2 (spip)
Value:
{                                         \
  if ((spip)->config->end_cb) {                                             \
    (spip)->state = SPI_COMPLETE;                                           \
    (spip)->config->end_cb(spip);                                           \
    if ((spip)->state == SPI_COMPLETE)                                      \
      (spip)->state = SPI_ACTIVE;                                           \
  }                                                                         \
}
Common ISR code in circular mode.
This code handles the portable part of the ISR code:
Callback invocation.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 370 of file hal_spi.h.
Referenced by spi_lld_serve_rx_interrupt().
Typedef Documentation
typedef struct SPIDriver SPIDriver
Type of a structure representing an SPI driver.
Definition at line 415 of file hal_spi_lld.h.
typedef void(* spicallback_t) (SPIDriver *spip)
SPI notification callback type.
Parameters
[in] spip pointer to the SPIDriver object triggering the callback
Definition at line 423 of file hal_spi_lld.h.
Enumeration Type Documentation
enum spistate_t
Driver state machine possible states.
Enumerator
SPI_UNINIT
Not initialized.
SPI_STOP
Stopped.
SPI_READY
Ready.
SPI_ACTIVE
Exchanging data.
SPI_COMPLETE
Asynchronous operation complete.
Definition at line 107 of file hal_spi.h.
Function Documentation
static void spi_lld_serve_rx_interrupt (SPIDriver * spip, uint32_t flags) static
Shared end-of-rx service routine.
Parameters
[in] spip pointer to the SPIDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 132 of file hal_spi_lld.c.
References _spi_isr_code, _spi_isr_code_half1, _spi_isr_code_half2, SPIConfig::circular, SPIDriver::config, SPIDriver::dmarx, dmaStreamDisable, SPIDriver::dmatx, and STM32_SPI_DMA_ERROR_HOOK.
Referenced by spi_lld_start().
static void spi_lld_serve_tx_interrupt (SPIDriver * spip, uint32_t flags) static
Shared end-of-tx service routine.
Parameters
[in] spip pointer to the SPIDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 170 of file hal_spi_lld.c.
References STM32_SPI_DMA_ERROR_HOOK.
Referenced by spi_lld_start().
void spi_lld_init (void)
Low level SPI driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 197 of file hal_spi_lld.c.
References SPIDriver::dmarx, SPIDriver::dmatx, SPIDriver::rxdmamode, SPIDriver::spi, spiObjectInit(), STM32_DMA_CR_DMEIE, STM32_DMA_STREAM, STM32_SPI_SPI1_DMA_PRIORITY, STM32_SPI_SPI2_DMA_PRIORITY, STM32_SPI_SPI3_DMA_PRIORITY, STM32_SPI_SPI4_DMA_PRIORITY, STM32_SPI_SPI5_DMA_PRIORITY, STM32_SPI_SPI6_DMA_PRIORITY, and SPIDriver::txdmamode.
Referenced by spiInit().
void spi_lld_start (SPIDriver * spip)
Configures and activates the SPI peripheral.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 315 of file hal_spi_lld.c.
References SPIConfig::circular, SPIDriver::config, SPIConfig::cr1, SPIConfig::cr2, SPIDriver::dmarx, dmaStreamAllocate(), dmaStreamSetPeripheral, SPIDriver::dmatx, osalDbgAssert, rccEnableSPI1, rccEnableSPI2, rccEnableSPI3, SPIDriver::rxdmamode, SPIDriver::spi, spi_lld_serve_rx_interrupt(), spi_lld_serve_tx_interrupt(), SPI_STOP, SPIDriver::state, STM32_SPI_SPI1_IRQ_PRIORITY, STM32_SPI_SPI2_IRQ_PRIORITY, STM32_SPI_SPI3_IRQ_PRIORITY, STM32_SPI_SPI4_IRQ_PRIORITY, STM32_SPI_SPI5_IRQ_PRIORITY, STM32_SPI_SPI6_IRQ_PRIORITY, and SPIDriver::txdmamode.
Referenced by spiStart().
void spi_lld_stop (SPIDriver * spip)
Deactivates the SPI peripheral.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 462 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamRelease(), SPIDriver::dmatx, rccDisableSPI1, rccDisableSPI2, rccDisableSPI3, SPIDriver::spi, SPI_READY, and SPIDriver::state.
Referenced by spiStop().
void spi_lld_select (SPIDriver * spip)
Asserts the slave select signal and prepares for transfers.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 509 of file hal_spi_lld.c.
void spi_lld_unselect (SPIDriver * spip)
Deasserts the slave select signal.
The previously selected peripheral is unselected.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 522 of file hal_spi_lld.c.
void spi_lld_ignore (SPIDriver * spip, size_t n)
Ignores data on the SPI bus.
This asynchronous function starts the transmission of a series of idle words on the SPI bus and ignores the received data.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be ignored
Function Class:
Not an API, this function is for internal use only.
Definition at line 539 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, SPIDriver::dmatx, osalDbgAssert, SPIDriver::rxdmamode, and SPIDriver::txdmamode.
void spi_lld_exchange (SPIDriver * spip, size_t n, const void * txbuf, void * rxbuf)
Exchanges data on the SPI bus.
This asynchronous function starts a simultaneous transmit/receive operation.
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be exchanged
[in] txbuf the pointer to the transmit buffer
[out] rxbuf the pointer to the receive buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 570 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, SPIDriver::dmatx, osalDbgAssert, SPIDriver::rxdmamode, and SPIDriver::txdmamode.
void spi_lld_send (SPIDriver * spip, size_t n, const void * txbuf)
Sends data over the SPI bus.
This asynchronous function starts a transmit operation.
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 600 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, SPIDriver::dmatx, osalDbgAssert, SPIDriver::rxdmamode, and SPIDriver::txdmamode.
void spi_lld_receive (SPIDriver * spip, size_t n, void * rxbuf)
Receives data from the SPI bus.
This asynchronous function starts a receive operation.
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to receive
[out] rxbuf the pointer to the receive buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 629 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, SPIDriver::dmatx, osalDbgAssert, SPIDriver::rxdmamode, and SPIDriver::txdmamode.
void spi_lld_abort (SPIDriver * spip)
Aborts the ongoing SPI operation, if any.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 653 of file hal_spi_lld.c.
References SPIDriver::dmarx, dmaStreamDisable, and SPIDriver::dmatx.
Referenced by spiAbortI().
uint16_t spi_lld_polled_exchange (SPIDriver * spip, uint16_t frame)
Exchanges one frame using a polled wait.
This synchronous function exchanges one frame using a polled synchronization method. This function is useful when exchanging small amount of data on high speed channels, usually in this situation is much more efficient just wait for completion using polling than suspending the thread waiting for an interrupt.
Parameters
[in] spip pointer to the SPIDriver object
[in] frame the data frame to send over the SPI bus
Returns
The received data frame from the SPI bus.
Definition at line 673 of file hal_spi_lld.c.
References SPIDriver::spi.
void spiInit (void)
SPI Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_spi.c.
References spi_lld_init().
Referenced by halInit().
void spiObjectInit (SPIDriver * spip)
Initializes the standard part of a SPIDriver structure.
Parameters
[out] spip pointer to the SPIDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_spi.c.
References SPIDriver::config, SPIDriver::mutex, osalMutexObjectInit(), SPI_STOP, SPIDriver::state, and SPIDriver::thread.
Referenced by spi_lld_init().
void spiStart (SPIDriver * spip, const SPIConfig * config)
Configures and activates the SPI peripheral.
Parameters
[in] spip pointer to the SPIDriver object
[in] config pointer to the SPIConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 91 of file hal_spi.c.
References SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), spi_lld_start(), SPI_READY, SPI_STOP, and SPIDriver::state.
Referenced by mmcConnect(), mmcDisconnect(), mmcStartSequentialRead(), mmcStartSequentialWrite(), and mmcSync().
void spiStop (SPIDriver * spip)
Deactivates the SPI peripheral.
Note
Deactivating the peripheral also enforces a release of the slave select line.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 113 of file hal_spi.c.
References SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), spi_lld_stop(), SPI_READY, SPI_STOP, and SPIDriver::state.
Referenced by mmcConnect(), mmcDisconnect(), mmcErase(), mmcSequentialRead(), mmcSequentialWrite(), mmcStartSequentialRead(), mmcStartSequentialWrite(), and mmcStop().
void spiSelect (SPIDriver * spip)
Asserts the slave select signal and prepares for transfers.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 136 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiSelectI, and SPIDriver::state.
Referenced by mmcStartSequentialRead(), mmcStartSequentialWrite(), read_CxD(), send_command_R1(), send_command_R3(), and sync().
void spiUnselect (SPIDriver * spip)
Deasserts the slave select signal.
The previously selected peripheral is unselected.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 154 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiUnselectI, and SPIDriver::state.
Referenced by mmcSequentialRead(), mmcSequentialWrite(), mmcStopSequentialRead(), mmcStopSequentialWrite(), read_CxD(), send_command_R1(), send_command_R3(), and sync().
void spiStartIgnore (SPIDriver * spip, size_t n)
Ignores data on the SPI bus.
This asynchronous function starts the transmission of a series of idle words on the SPI bus and ignores the received data.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be ignored
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 177 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiStartIgnoreI, and SPIDriver::state.
void spiStartExchange (SPIDriver * spip, size_t n, const void * txbuf, void * rxbuf)
Exchanges data on the SPI bus.
This asynchronous function starts a simultaneous transmit/receive operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be exchanged
[in] txbuf the pointer to the transmit buffer
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 204 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiStartExchangeI, and SPIDriver::state.
void spiStartSend (SPIDriver * spip, size_t n, const void * txbuf)
Sends data over the SPI bus.
This asynchronous function starts a transmit operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 231 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiStartSendI, and SPIDriver::state.
void spiStartReceive (SPIDriver * spip, size_t n, void * rxbuf)
Receives data from the SPI bus.
This asynchronous function starts a receive operation.
Precondition
A slave must have been selected using spiSelect() or spiSelectI().
Postcondition
At the end of the operation the configured callback is invoked.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to receive
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 256 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), SPI_READY, spiStartReceiveI, and SPIDriver::state.
void spiAbortI (SPIDriver * spip)
Aborts the ongoing SPI operation.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 274 of file hal_spi.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, osalThreadResumeI(), SPI_ACTIVE, SPI_COMPLETE, spi_lld_abort(), SPI_READY, SPIDriver::state, and SPIDriver::thread.
Referenced by spiAbort().
void spiAbort (SPIDriver * spip)
Aborts the ongoing SPI operation, if any.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 296 of file hal_spi.c.
References osalDbgAssert, osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), SPI_ACTIVE, SPI_READY, spiAbortI(), and SPIDriver::state.
void spiIgnore (SPIDriver * spip, size_t n)
Ignores data on the SPI bus.
This synchronous function performs the transmission of a series of idle words on the SPI bus and ignores the received data.
Precondition
In order to use this function the option SPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be ignored
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 324 of file hal_spi.c.
References SPIConfig::circular, SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), SPI_READY, spiStartIgnoreI, SPIDriver::state, and SPIDriver::thread.
Referenced by mmcConnect(), mmcSequentialRead(), mmcSequentialWrite(), and read_CxD().
void spiExchange (SPIDriver * spip, size_t n, const void * txbuf, void * rxbuf)
Exchanges data on the SPI bus.
This synchronous function performs a simultaneous transmit/receive operation.
Precondition
In order to use this function the option SPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to be exchanged
[in] txbuf the pointer to the transmit buffer
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 356 of file hal_spi.c.
References SPIConfig::circular, SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), SPI_READY, spiStartExchangeI, SPIDriver::state, and SPIDriver::thread.
void spiSend (SPIDriver * spip, size_t n, const void * txbuf)
Sends data over the SPI bus.
This synchronous function performs a transmit operation.
Precondition
In order to use this function the option SPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 388 of file hal_spi.c.
References SPIConfig::circular, SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), SPI_READY, spiStartSendI, SPIDriver::state, and SPIDriver::thread.
Referenced by mmcSequentialWrite(), mmcStopSequentialRead(), mmcStopSequentialWrite(), and send_hdr().
void spiReceive (SPIDriver * spip, size_t n, void * rxbuf)
Receives data from the SPI bus.
This synchronous function performs a receive operation.
Precondition
In order to use this function the option SPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] spip pointer to the SPIDriver object
[in] n number of words to receive
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 418 of file hal_spi.c.
References SPIConfig::circular, SPIDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), SPI_READY, spiStartReceiveI, SPIDriver::state, and SPIDriver::thread.
Referenced by mmcSequentialRead(), mmcSequentialWrite(), read_CxD(), recvr1(), recvr3(), sync(), and wait().
void spiAcquireBus (SPIDriver * spip)
Gains exclusive access to the SPI bus.
This function tries to gain ownership to the SPI bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option SPI_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 445 of file hal_spi.c.
References SPIDriver::mutex, osalDbgCheck, and osalMutexLock().
void spiReleaseBus (SPIDriver * spip)
Releases exclusive access to the SPI bus.
Precondition
In order to use this function the option SPI_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] spip pointer to the SPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 461 of file hal_spi.c.
References SPIDriver::mutex, osalDbgCheck, and osalMutexUnlock().
Variable Documentation
SPIDriver SPID1
SPI1 driver identifier.
Definition at line 87 of file hal_spi_lld.c.
SPIDriver SPID2
SPI2 driver identifier.
Definition at line 92 of file hal_spi_lld.c.
SPIDriver SPID3
SPI3 driver identifier.
Definition at line 97 of file hal_spi_lld.c.
SPIDriver SPID4
SPI4 driver identifier.
Definition at line 102 of file hal_spi_lld.c.
SPIDriver SPID5
SPI5 driver identifier.
Definition at line 107 of file hal_spi_lld.c.
SPIDriver SPID6
SPI6 driver identifier.
Definition at line 112 of file hal_spi_lld.c.