ChibiOS/HAL: GPT Driver
GPT Driver
HAL » Normal Drivers
Generic GPT Driver.
Detailed Description
Generic GPT Driver.
This module implements a generic GPT (General Purpose Timer) driver. The timer can be programmed in order to trigger callbacks after a specified time period or continuously with a specified interval.
Precondition
In order to use the GPT driver the HAL_USE_GPT option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
GPT Operations.
This driver abstracts a generic timer composed of:
A clock prescaler.
A main up counter.
A comparator register that resets the main counter to zero when the limit is reached. A callback is invoked when this happens.
The timer can operate in three different modes:
Continuous Mode, a periodic callback is invoked until the driver is explicitly stopped.
One Shot Mode, a callback is invoked after the programmed period and then the timer automatically stops.
Delay Mode, the timer is used for inserting a brief delay into the execution flow, no callback is invoked in this mode.
Macros
#define gpt_lld_change_interval(gptp, interval) ((gptp)->tim->ARR = (uint32_t)(interval))
Changes the interval of GPT peripheral.
#define gpt_lld_get_interval(gptp) ((gptcnt_t)(gptp)->tim->ARR)
Returns the interval of GPT peripheral.
#define gpt_lld_get_counter(gptp) ((gptcnt_t)(gptp)->tim->CNT)
Returns the counter value of GPT peripheral.
#define gptChangeIntervalI(gptp, interval)
Changes the interval of GPT peripheral.
#define gptGetIntervalX(gptp) gpt_lld_get_interval(gptp)
Returns the interval of GPT peripheral.
#define gptGetCounterX(gptp) gpt_lld_get_counter(gptp)
Returns the counter value of GPT peripheral.
Configuration options
#define STM32_GPT_USE_TIM1 FALSE
GPTD1 driver enable switch.
#define STM32_GPT_USE_TIM2 FALSE
GPTD2 driver enable switch.
#define STM32_GPT_USE_TIM3 FALSE
GPTD3 driver enable switch.
#define STM32_GPT_USE_TIM4 FALSE
GPTD4 driver enable switch.
#define STM32_GPT_USE_TIM5 FALSE
GPTD5 driver enable switch.
#define STM32_GPT_USE_TIM6 FALSE
GPTD6 driver enable switch.
#define STM32_GPT_USE_TIM7 FALSE
GPTD7 driver enable switch.
#define STM32_GPT_USE_TIM8 FALSE
GPTD8 driver enable switch.
#define STM32_GPT_USE_TIM9 FALSE
GPTD9 driver enable switch.
#define STM32_GPT_USE_TIM11 FALSE
GPTD11 driver enable switch.
#define STM32_GPT_USE_TIM12 FALSE
GPTD12 driver enable switch.
#define STM32_GPT_USE_TIM14 FALSE
GPTD14 driver enable switch.
#define STM32_GPT_TIM1_IRQ_PRIORITY 7
GPTD1 interrupt priority level setting.
#define STM32_GPT_TIM2_IRQ_PRIORITY 7
GPTD2 interrupt priority level setting.
#define STM32_GPT_TIM3_IRQ_PRIORITY 7
GPTD3 interrupt priority level setting.
#define STM32_GPT_TIM4_IRQ_PRIORITY 7
GPTD4 interrupt priority level setting.
#define STM32_GPT_TIM5_IRQ_PRIORITY 7
GPTD5 interrupt priority level setting.
#define STM32_GPT_TIM6_IRQ_PRIORITY 7
GPTD6 interrupt priority level setting.
#define STM32_GPT_TIM7_IRQ_PRIORITY 7
GPTD7 interrupt priority level setting.
#define STM32_GPT_TIM8_IRQ_PRIORITY 7
GPTD8 interrupt priority level setting.
#define STM32_GPT_TIM9_IRQ_PRIORITY 7
GPTD9 interrupt priority level setting.
#define STM32_GPT_TIM11_IRQ_PRIORITY 7
GPTD11 interrupt priority level setting.
#define STM32_GPT_TIM12_IRQ_PRIORITY 7
GPTD12 interrupt priority level setting.
#define STM32_GPT_TIM14_IRQ_PRIORITY 7
GPTD14 interrupt priority level setting.
Typedefs
typedef uint32_t gptfreq_t
GPT frequency type.
typedef uint32_t gptcnt_t
GPT counter type.
typedef struct GPTDriver GPTDriver
Type of a structure representing a GPT driver.
typedef void(* gptcallback_t) (GPTDriver *gptp)
GPT notification callback type.
Data Structures
struct GPTConfig
Driver configuration structure.
struct GPTDriver
Structure representing a GPT driver.
Functions
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM6_HANDLER)
TIM6 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM7_HANDLER)
TIM7 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM11_HANDLER)
TIM11 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM12_HANDLER)
TIM12 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM14_HANDLER)
TIM14 interrupt handler.
void gpt_lld_init (void)
Low level GPT driver initialization.
void gpt_lld_start (GPTDriver *gptp)
Configures and activates the GPT peripheral.
void gpt_lld_stop (GPTDriver *gptp)
Deactivates the GPT peripheral.
void gpt_lld_start_timer (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in continuous mode.
void gpt_lld_stop_timer (GPTDriver *gptp)
Stops the timer.
void gpt_lld_polled_delay (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in one shot mode and waits for completion.
void gpt_lld_serve_interrupt (GPTDriver *gptp)
Shared IRQ handler.
void gptInit (void)
GPT Driver initialization.
void gptObjectInit (GPTDriver *gptp)
Initializes the standard part of a GPTDriver structure.
void gptStart (GPTDriver *gptp, const GPTConfig *config)
Configures and activates the GPT peripheral.
void gptStop (GPTDriver *gptp)
Deactivates the GPT peripheral.
void gptChangeInterval (GPTDriver *gptp, gptcnt_t interval)
Changes the interval of GPT peripheral.
void gptStartContinuous (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in continuous mode.
void gptStartContinuousI (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in continuous mode.
void gptStartOneShot (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in one shot mode.
void gptStartOneShotI (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in one shot mode.
void gptStopTimer (GPTDriver *gptp)
Stops the timer.
void gptStopTimerI (GPTDriver *gptp)
Stops the timer.
void gptPolledDelay (GPTDriver *gptp, gptcnt_t interval)
Starts the timer in one shot mode and waits for completion.
Enumerations
Variables
GPTDriver GPTD1
GPTD1 driver identifier.
GPTDriver GPTD2
GPTD2 driver identifier.
GPTDriver GPTD3
GPTD3 driver identifier.
GPTDriver GPTD4
GPTD4 driver identifier.
GPTDriver GPTD5
GPTD5 driver identifier.
GPTDriver GPTD6
GPTD6 driver identifier.
GPTDriver GPTD7
GPTD7 driver identifier.
GPTDriver GPTD8
GPTD8 driver identifier.
GPTDriver GPTD9
GPTD9 driver identifier.
GPTDriver GPTD11
GPTD11 driver identifier.
GPTDriver GPTD12
GPTD12 driver identifier.
GPTDriver GPTD14
GPTD14 driver identifier.
Macro Definition Documentation
#define STM32_GPT_USE_TIM1 FALSE
GPTD1 driver enable switch.
If set to TRUE the support for GPTD1 is included.
Note
The default is TRUE.
Definition at line 50 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM2 FALSE
GPTD2 driver enable switch.
If set to TRUE the support for GPTD2 is included.
Note
The default is TRUE.
Definition at line 59 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM3 FALSE
GPTD3 driver enable switch.
If set to TRUE the support for GPTD3 is included.
Note
The default is TRUE.
Definition at line 68 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM4 FALSE
GPTD4 driver enable switch.
If set to TRUE the support for GPTD4 is included.
Note
The default is TRUE.
Definition at line 77 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM5 FALSE
GPTD5 driver enable switch.
If set to TRUE the support for GPTD5 is included.
Note
The default is TRUE.
Definition at line 86 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM6 FALSE
GPTD6 driver enable switch.
If set to TRUE the support for GPTD6 is included.
Note
The default is TRUE.
Definition at line 95 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM7 FALSE
GPTD7 driver enable switch.
If set to TRUE the support for GPTD7 is included.
Note
The default is TRUE.
Definition at line 104 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM8 FALSE
GPTD8 driver enable switch.
If set to TRUE the support for GPTD8 is included.
Note
The default is TRUE.
Definition at line 113 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM9 FALSE
GPTD9 driver enable switch.
If set to TRUE the support for GPTD9 is included.
Note
The default is TRUE.
Definition at line 122 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM11 FALSE
GPTD11 driver enable switch.
If set to TRUE the support for GPTD11 is included.
Note
The default is TRUE.
Definition at line 131 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM12 FALSE
GPTD12 driver enable switch.
If set to TRUE the support for GPTD12 is included.
Note
The default is TRUE.
Definition at line 140 of file hal_gpt_lld.h.
#define STM32_GPT_USE_TIM14 FALSE
GPTD14 driver enable switch.
If set to TRUE the support for GPTD14 is included.
Note
The default is TRUE.
Definition at line 149 of file hal_gpt_lld.h.
#define STM32_GPT_TIM1_IRQ_PRIORITY 7
GPTD1 interrupt priority level setting.
Definition at line 156 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM2_IRQ_PRIORITY 7
GPTD2 interrupt priority level setting.
Definition at line 163 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM3_IRQ_PRIORITY 7
GPTD3 interrupt priority level setting.
Definition at line 170 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM4_IRQ_PRIORITY 7
GPTD4 interrupt priority level setting.
Definition at line 177 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM5_IRQ_PRIORITY 7
GPTD5 interrupt priority level setting.
Definition at line 184 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM6_IRQ_PRIORITY 7
GPTD6 interrupt priority level setting.
Definition at line 191 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM7_IRQ_PRIORITY 7
GPTD7 interrupt priority level setting.
Definition at line 198 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM8_IRQ_PRIORITY 7
GPTD8 interrupt priority level setting.
Definition at line 205 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM9_IRQ_PRIORITY 7
GPTD9 interrupt priority level setting.
Definition at line 212 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM11_IRQ_PRIORITY 7
GPTD11 interrupt priority level setting.
Definition at line 219 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM12_IRQ_PRIORITY 7
GPTD12 interrupt priority level setting.
Definition at line 226 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define STM32_GPT_TIM14_IRQ_PRIORITY 7
GPTD14 interrupt priority level setting.
Definition at line 233 of file hal_gpt_lld.h.
Referenced by gpt_lld_start().
#define gpt_lld_change_interval (gptp, interval) ((gptp)->tim->ARR = (uint32_t)(interval))
Changes the interval of GPT peripheral.
This function changes the interval of a running GPT unit.
Precondition
The GPT unit must be running in continuous mode.
Postcondition
The GPT unit interval is changed to the new value.
Note
The function has effect at the next cycle start.
Parameters
[in] gptp pointer to a GPTDriver object
[in] interval new cycle time in timer ticks
Function Class:
Not an API, this function is for internal use only.
Definition at line 544 of file hal_gpt_lld.h.
#define gpt_lld_get_interval (gptp) ((gptcnt_t)(gptp)->tim->ARR)
Returns the interval of GPT peripheral.
Precondition
The GPT unit must be running in continuous mode.
Parameters
[in] gptp pointer to a GPTDriver object
Returns
The current interval.
Function Class:
Not an API, this function is for internal use only.
Definition at line 556 of file hal_gpt_lld.h.
#define gpt_lld_get_counter (gptp) ((gptcnt_t)(gptp)->tim->CNT)
Returns the counter value of GPT peripheral.
Precondition
The GPT unit must be running in continuous mode.
Note
The nature of the counter is not defined, it may count upward or downward, it could be continuously running or not.
Parameters
[in] gptp pointer to a GPTDriver object
Returns
The current counter value.
Function Class:
Not an API, this function is for internal use only.
Definition at line 569 of file hal_gpt_lld.h.
#define gptChangeIntervalI (gptp, interval)
Value:
{                                \
  gpt_lld_change_interval(gptp, interval);                                  \
}
Changes the interval of GPT peripheral.
This function changes the interval of a running GPT unit.
Precondition
The GPT unit must be running in continuous mode.
Postcondition
The GPT unit interval is changed to the new value.
Parameters
[in] gptp pointer to a GPTDriver object
[in] interval new cycle time in timer ticks
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 86 of file hal_gpt.h.
Referenced by gptChangeInterval().
#define gptGetIntervalX (gptp) gpt_lld_get_interval(gptp)
Returns the interval of GPT peripheral.
Precondition
The GPT unit must be running in continuous mode.
Parameters
[in] gptp pointer to a GPTDriver object
Returns
The current interval.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 99 of file hal_gpt.h.
#define gptGetCounterX (gptp) gpt_lld_get_counter(gptp)
Returns the counter value of GPT peripheral.
Precondition
The GPT unit must be running in continuous mode.
Note
The nature of the counter is not defined, it may count upward or downward, it could be continuously running or not.
Parameters
[in] gptp pointer to a GPTDriver object
Returns
The current counter value.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 112 of file hal_gpt.h.
Typedef Documentation
typedef uint32_t gptfreq_t
GPT frequency type.
Definition at line 463 of file hal_gpt_lld.h.
typedef uint32_t gptcnt_t
GPT counter type.
Definition at line 468 of file hal_gpt_lld.h.
typedef struct GPTDriver GPTDriver
Type of a structure representing a GPT driver.
Definition at line 60 of file hal_gpt.h.
typedef void(* gptcallback_t) (GPTDriver *gptp)
GPT notification callback type.
Parameters
[in] gptp pointer to a GPTDriver object
Definition at line 67 of file hal_gpt.h.
Enumeration Type Documentation
enum gptstate_t
Driver state machine possible states.
Enumerator
GPT_UNINIT
Not initialized.
GPT_STOP
Stopped.
GPT_READY
Ready.
GPT_CONTINUOUS
Active in continuous mode.
GPT_ONESHOT
Active in one shot mode.
Definition at line 49 of file hal_gpt.h.
Function Documentation
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 155 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 176 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 197 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 218 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 239 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM6_HANDLER)
TIM6 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 260 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM7_HANDLER)
TIM7 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 281 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 302 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 323 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM11_HANDLER)
TIM11 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 344 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM12_HANDLER)
TIM12 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 365 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM14_HANDLER)
TIM14 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 386 of file hal_gpt_lld.c.
References gpt_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
void gpt_lld_init (void)
Low level GPT driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 406 of file hal_gpt_lld.c.
References gptObjectInit(), and GPTDriver::tim.
Referenced by gptInit().
void gpt_lld_start (GPTDriver * gptp)
Configures and activates the GPT peripheral.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 488 of file hal_gpt_lld.c.
References GPTDriver::clock, GPTDriver::config, GPTConfig::cr2, GPTConfig::dier, GPTConfig::frequency, GPT_STOP, osalDbgAssert, rccEnableTIM1, rccEnableTIM11, rccEnableTIM12, rccEnableTIM14, rccEnableTIM2, rccEnableTIM3, rccEnableTIM4, rccEnableTIM5, rccEnableTIM6, rccEnableTIM7, rccEnableTIM8, rccEnableTIM9, rccResetTIM1, rccResetTIM11, rccResetTIM12, rccResetTIM14, rccResetTIM2, rccResetTIM3, rccResetTIM4, rccResetTIM5, rccResetTIM6, rccResetTIM7, rccResetTIM8, rccResetTIM9, GPTDriver::state, STM32_GPT_TIM11_IRQ_PRIORITY, STM32_GPT_TIM12_IRQ_PRIORITY, STM32_GPT_TIM14_IRQ_PRIORITY, STM32_GPT_TIM1_IRQ_PRIORITY, STM32_GPT_TIM2_IRQ_PRIORITY, STM32_GPT_TIM3_IRQ_PRIORITY, STM32_GPT_TIM4_IRQ_PRIORITY, STM32_GPT_TIM5_IRQ_PRIORITY, STM32_GPT_TIM6_IRQ_PRIORITY, STM32_GPT_TIM7_IRQ_PRIORITY, STM32_GPT_TIM8_IRQ_PRIORITY, STM32_GPT_TIM9_IRQ_PRIORITY, STM32_TIMCLK1, STM32_TIMCLK2, and GPTDriver::tim.
Referenced by gptStart().
void gpt_lld_stop (GPTDriver * gptp)
Deactivates the GPT peripheral.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 695 of file hal_gpt_lld.c.
References GPT_READY, rccDisableTIM1, rccDisableTIM11, rccDisableTIM12, rccDisableTIM14, rccDisableTIM2, rccDisableTIM3, rccDisableTIM4, rccDisableTIM5, rccDisableTIM6, rccDisableTIM7, rccDisableTIM8, rccDisableTIM9, GPTDriver::state, and GPTDriver::tim.
Referenced by gptStop().
void gpt_lld_start_timer (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in continuous mode.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval period in ticks
Function Class:
Not an API, this function is for internal use only.
Definition at line 820 of file hal_gpt_lld.c.
References GPTConfig::callback, GPTDriver::config, and GPTDriver::tim.
Referenced by gptStartContinuousI(), and gptStartOneShotI().
void gpt_lld_stop_timer (GPTDriver * gptp)
Stops the timer.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 842 of file hal_gpt_lld.c.
References GPTDriver::tim.
Referenced by gpt_lld_serve_interrupt(), and gptStopTimerI().
void gpt_lld_polled_delay (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in one shot mode and waits for completion.
This function specifically polls the timer waiting for completion in order to not have extra delays caused by interrupt servicing, this function is only recommended for short delays.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval time interval in ticks
Function Class:
Not an API, this function is for internal use only.
Definition at line 862 of file hal_gpt_lld.c.
References GPTDriver::tim.
Referenced by gptPolledDelay().
void gpt_lld_serve_interrupt (GPTDriver * gptp)
Shared IRQ handler.
Parameters
[in] gptp pointer to a GPTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 880 of file hal_gpt_lld.c.
References GPTConfig::callback, GPTDriver::config, gpt_lld_stop_timer(), GPT_ONESHOT, GPT_READY, GPTDriver::state, and GPTDriver::tim.
Referenced by OSAL_IRQ_HANDLER().
void gptInit (void)
GPT Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_gpt.c.
References gpt_lld_init().
Referenced by halInit().
void gptObjectInit (GPTDriver * gptp)
Initializes the standard part of a GPTDriver structure.
Parameters
[out] gptp pointer to the GPTDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_gpt.c.
References GPTDriver::config, GPT_STOP, and GPTDriver::state.
Referenced by gpt_lld_init().
void gptStart (GPTDriver * gptp, const GPTConfig * config)
Configures and activates the GPT peripheral.
Parameters
[in] gptp pointer to the GPTDriver object
[in] config pointer to the GPTConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 82 of file hal_gpt.c.
References GPTDriver::config, gpt_lld_start(), GPT_READY, GPT_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and GPTDriver::state.
void gptStop (GPTDriver * gptp)
Deactivates the GPT peripheral.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 102 of file hal_gpt.c.
References GPTDriver::config, gpt_lld_stop(), GPT_READY, GPT_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and GPTDriver::state.
void gptChangeInterval (GPTDriver * gptp, gptcnt_t interval)
Changes the interval of GPT peripheral.
This function changes the interval of a running GPT unit.
Precondition
The GPT unit must be running in continuous mode.
Postcondition
The GPT unit interval is changed to the new value.
Parameters
[in] gptp pointer to a GPTDriver object
[in] interval new cycle time in timer ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 129 of file hal_gpt.c.
References GPT_CONTINUOUS, gptChangeIntervalI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and GPTDriver::state.
void gptStartContinuous (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in continuous mode.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval period in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 148 of file hal_gpt.c.
References gptStartContinuousI(), osalSysLock(), and osalSysUnlock().
void gptStartContinuousI (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in continuous mode.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval period in ticks
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 163 of file hal_gpt.c.
References GPT_CONTINUOUS, gpt_lld_start_timer(), GPT_READY, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and GPTDriver::state.
Referenced by gptStartContinuous().
void gptStartOneShot (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in one shot mode.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval time interval in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 182 of file hal_gpt.c.
References gptStartOneShotI(), osalSysLock(), and osalSysUnlock().
void gptStartOneShotI (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in one shot mode.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval time interval in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 197 of file hal_gpt.c.
References GPTConfig::callback, GPTDriver::config, gpt_lld_start_timer(), GPT_ONESHOT, GPT_READY, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and GPTDriver::state.
Referenced by gptStartOneShot().
void gptStopTimer (GPTDriver * gptp)
Stops the timer.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 216 of file hal_gpt.c.
References gptStopTimerI(), osalSysLock(), and osalSysUnlock().
void gptStopTimerI (GPTDriver * gptp)
Stops the timer.
Parameters
[in] gptp pointer to the GPTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 230 of file hal_gpt.c.
References GPT_CONTINUOUS, gpt_lld_stop_timer(), GPT_ONESHOT, GPT_READY, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and GPTDriver::state.
Referenced by gptStopTimer().
void gptPolledDelay (GPTDriver * gptp, gptcnt_t interval)
Starts the timer in one shot mode and waits for completion.
This function specifically polls the timer waiting for completion in order to not have extra delays caused by interrupt servicing, this function is only recommended for short delays.
Note
The configured callback is not invoked when using this function.
Parameters
[in] gptp pointer to the GPTDriver object
[in] interval time interval in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 254 of file hal_gpt.c.
References gpt_lld_polled_delay(), GPT_ONESHOT, GPT_READY, osalDbgAssert, and GPTDriver::state.
Variable Documentation
GPTDriver GPTD1
GPTD1 driver identifier.
Note
The driver GPTD1 allocates the complex timer TIM1 when enabled.
Definition at line 42 of file hal_gpt_lld.c.
GPTDriver GPTD2
GPTD2 driver identifier.
Note
The driver GPTD2 allocates the timer TIM2 when enabled.
Definition at line 50 of file hal_gpt_lld.c.
GPTDriver GPTD3
GPTD3 driver identifier.
Note
The driver GPTD3 allocates the timer TIM3 when enabled.
Definition at line 58 of file hal_gpt_lld.c.
GPTDriver GPTD4
GPTD4 driver identifier.
Note
The driver GPTD4 allocates the timer TIM4 when enabled.
Definition at line 66 of file hal_gpt_lld.c.
GPTDriver GPTD5
GPTD5 driver identifier.
Note
The driver GPTD5 allocates the timer TIM5 when enabled.
Definition at line 74 of file hal_gpt_lld.c.
GPTDriver GPTD6
GPTD6 driver identifier.
Note
The driver GPTD6 allocates the timer TIM6 when enabled.
Definition at line 82 of file hal_gpt_lld.c.
GPTDriver GPTD7
GPTD7 driver identifier.
Note
The driver GPTD7 allocates the timer TIM7 when enabled.
Definition at line 90 of file hal_gpt_lld.c.
GPTDriver GPTD8
GPTD8 driver identifier.
Note
The driver GPTD8 allocates the timer TIM8 when enabled.
Definition at line 98 of file hal_gpt_lld.c.
GPTDriver GPTD9
GPTD9 driver identifier.
Note
The driver GPTD9 allocates the timer TIM9 when enabled.
Definition at line 106 of file hal_gpt_lld.c.
GPTDriver GPTD11
GPTD11 driver identifier.
Note
The driver GPTD11 allocates the timer TIM11 when enabled.
Definition at line 114 of file hal_gpt_lld.c.
GPTDriver GPTD12
GPTD12 driver identifier.
Note
The driver GPTD12 allocates the timer TIM12 when enabled.
Definition at line 122 of file hal_gpt_lld.c.
GPTDriver GPTD14
GPTD14 driver identifier.
Note
The driver GPTD14 allocates the timer TIM14 when enabled.
Definition at line 130 of file hal_gpt_lld.c.