ChibiOS/HAL: HAL Driver
HAL Driver
HAL » Normal Drivers
Hardware Abstraction Layer.
Detailed Description
Hardware Abstraction Layer.
The HAL (Hardware Abstraction Layer) driver performs the system initialization and includes the platform support code shared by the other drivers. This driver does contain any API function except for a general initialization function halInit() that must be invoked before any HAL service can be used, usually the HAL initialization should be performed immediately before the kernel initialization.
Some HAL driver implementations also offer a custom early clock setup function that can be invoked before the C runtime initialization in order to accelerate the startup time.
Modules
STM32F100 HAL Support
STM32F103 HAL Support
STM32F105/F107 HAL Support
Macros
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
#define CH_HAL_STABLE 1
Stable release flag.
Platform identification
#define PLATFORM_NAME "STM32F1xx"
#define STM32F1XX
Sub-family identifier.
Internal clock sources
#define STM32_HSICLK 8000000
#define STM32_LSICLK 40000
PWR_CR register bits definitions
#define STM32_PLS_MASK (7 << 5)
#define STM32_PLS_LEV0 (0 << 5)
#define STM32_PLS_LEV1 (1 << 5)
#define STM32_PLS_LEV2 (2 << 5)
#define STM32_PLS_LEV3 (3 << 5)
#define STM32_PLS_LEV4 (4 << 5)
#define STM32_PLS_LEV5 (5 << 5)
#define STM32_PLS_LEV6 (6 << 5)
#define STM32_PLS_LEV7 (7 << 5)
Configuration options
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
#define STM32_LSI_ENABLED FALSE
Enables or disables the LSI clock source.
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
STM32F100 MD capabilities
#define STM32_TIM15_IS_32BITS FALSE
#define STM32_TIM15_CHANNELS 2
#define STM32_TIM16_IS_32BITS FALSE
#define STM32_TIM16_CHANNELS 1
#define STM32_TIM17_IS_32BITS FALSE
#define STM32_TIM17_CHANNELS 1
STM32F103 HD capabilities
#define STM32_DMA2_CH45_HANDLER Vector12C
#define STM32_DMA2_CH45_NUMBER 59
#define DMA2_CH4_CMASK 0x00000C00U
#define DMA2_CH5_CMASK 0x00000C00U
STM32F103 XL capabilities
#define STM32_USB_ACCESS_SCHEME_2x16 FALSE
#define STM32_USB_ACCESS_SCHEME_2x16 FALSE
#define STM32_USB_ACCESS_SCHEME_2x16 FALSE
#define STM32_USB_PMA_SIZE 512
#define STM32_USB_PMA_SIZE 512
#define STM32_USB_PMA_SIZE 512
#define STM32_USB_HAS_BCDR FALSE
#define STM32_USB_HAS_BCDR FALSE
#define STM32_USB_HAS_BCDR FALSE
#define STM32_SDC_SDIO_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_SDC_SDIO_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_TIM8_IS_32BITS FALSE
#define STM32_TIM8_IS_32BITS FALSE
#define STM32_TIM8_CHANNELS 4
#define STM32_TIM8_CHANNELS 4
#define STM32_FSMC_IS_FMC FALSE
#define STM32_FSMC_IS_FMC FALSE
#define STM32_FSMC_HANDLER Vector100
#define STM32_FSMC_HANDLER Vector100
#define STM32_FSMC_NUMBER 48
#define STM32_FSMC_NUMBER 48
#define STM32_TIM9_IS_32BITS FALSE
#define STM32_TIM9_CHANNELS 2
#define STM32_TIM10_IS_32BITS FALSE
#define STM32_TIM10_CHANNELS 1
#define STM32_TIM11_IS_32BITS FALSE
#define STM32_TIM11_CHANNELS 1
#define STM32_TIM12_IS_32BITS FALSE
#define STM32_TIM12_CHANNELS 2
#define STM32_TIM13_IS_32BITS FALSE
#define STM32_TIM13_CHANNELS 1
#define STM32_TIM14_IS_32BITS FALSE
#define STM32_TIM14_CHANNELS 1
STM32F105/F107 CL capabilities
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC1 TRUE
#define STM32_HAS_ADC2 FALSE
#define STM32_HAS_ADC2 TRUE
#define STM32_HAS_ADC2 TRUE
#define STM32_HAS_ADC2 TRUE
#define STM32_HAS_ADC2 TRUE
#define STM32_HAS_ADC2 TRUE
#define STM32_HAS_ADC3 FALSE
#define STM32_HAS_ADC3 FALSE
#define STM32_HAS_ADC3 FALSE
#define STM32_HAS_ADC3 TRUE
#define STM32_HAS_ADC3 TRUE
#define STM32_HAS_ADC3 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_CAN1 FALSE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN2 TRUE
#define STM32_HAS_CAN3 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_CAN_MAX_FILTERS 0
#define STM32_CAN_MAX_FILTERS 14
#define STM32_CAN_MAX_FILTERS 14
#define STM32_CAN_MAX_FILTERS 14
#define STM32_CAN_MAX_FILTERS 14
#define STM32_CAN_MAX_FILTERS 28
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_HAS_DAC1_CH1 FALSE
#define STM32_HAS_DAC1_CH1 FALSE
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_DAC_DAC1_CH1_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_DAC_DAC1_CH1_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_DAC_DAC1_CH1_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_DAC_DAC1_CH1_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_HAS_DAC1_CH2 FALSE
#define STM32_HAS_DAC1_CH2 FALSE
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_DAC_DAC1_CH2_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_DAC_DAC1_CH2_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_DAC_DAC1_CH2_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_DAC_DAC1_CH2_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA2_NUM_CHANNELS 0
#define STM32_DMA2_NUM_CHANNELS 0
#define STM32_DMA2_NUM_CHANNELS 0
#define STM32_DMA2_NUM_CHANNELS 5
#define STM32_DMA2_NUM_CHANNELS 5
#define STM32_DMA2_NUM_CHANNELS 5
#define STM32_HAS_ETH FALSE
#define STM32_HAS_ETH FALSE
#define STM32_HAS_ETH FALSE
#define STM32_HAS_ETH FALSE
#define STM32_HAS_ETH FALSE
#define STM32_HAS_ETH TRUE
#define STM32_EXTI_NUM_LINES 19
#define STM32_EXTI_NUM_LINES 19
#define STM32_EXTI_NUM_LINES 19
#define STM32_EXTI_NUM_LINES 19
#define STM32_EXTI_NUM_LINES 19
#define STM32_EXTI_NUM_LINES 20
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOE FALSE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOF FALSE
#define STM32_HAS_GPIOF FALSE
#define STM32_HAS_GPIOF FALSE
#define STM32_HAS_GPIOF TRUE
#define STM32_HAS_GPIOF TRUE
#define STM32_HAS_GPIOF FALSE
#define STM32_HAS_GPIOG FALSE
#define STM32_HAS_GPIOG FALSE
#define STM32_HAS_GPIOG FALSE
#define STM32_HAS_GPIOG TRUE
#define STM32_HAS_GPIOG TRUE
#define STM32_HAS_GPIOG FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_HAS_I2C1 TRUE
#define STM32_HAS_I2C1 TRUE
#define STM32_HAS_I2C1 TRUE
#define STM32_HAS_I2C1 TRUE
#define STM32_HAS_I2C1 TRUE
#define STM32_HAS_I2C1 TRUE
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_HAS_I2C2 TRUE
#define STM32_HAS_I2C2 FALSE
#define STM32_HAS_I2C2 TRUE
#define STM32_HAS_I2C2 TRUE
#define STM32_HAS_I2C2 TRUE
#define STM32_HAS_I2C2 TRUE
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_RTC TRUE
#define STM32_HAS_RTC TRUE
#define STM32_HAS_RTC TRUE
#define STM32_HAS_RTC TRUE
#define STM32_HAS_RTC TRUE
#define STM32_HAS_RTC TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_RTC_IS_CALENDAR FALSE
#define STM32_HAS_SDIO FALSE
#define STM32_HAS_SDIO FALSE
#define STM32_HAS_SDIO FALSE
#define STM32_HAS_SDIO TRUE
#define STM32_HAS_SDIO TRUE
#define STM32_HAS_SDIO FALSE
#define STM32_HAS_SPI1 TRUE
#define STM32_HAS_SPI1 TRUE
#define STM32_HAS_SPI1 TRUE
#define STM32_HAS_SPI1 TRUE
#define STM32_HAS_SPI1 TRUE
#define STM32_HAS_SPI1 TRUE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_HAS_SPI2 TRUE
#define STM32_HAS_SPI2 FALSE
#define STM32_HAS_SPI2 TRUE
#define STM32_HAS_SPI2 TRUE
#define STM32_HAS_SPI2 TRUE
#define STM32_HAS_SPI2 TRUE
#define STM32_SPI2_SUPPORTS_I2S FALSE
#define STM32_SPI2_SUPPORTS_I2S FALSE
#define STM32_SPI2_SUPPORTS_I2S TRUE
#define STM32_SPI2_SUPPORTS_I2S TRUE
#define STM32_SPI2_SUPPORTS_I2S TRUE
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_HAS_SPI3 FALSE
#define STM32_HAS_SPI3 FALSE
#define STM32_HAS_SPI3 FALSE
#define STM32_HAS_SPI3 TRUE
#define STM32_HAS_SPI3 TRUE
#define STM32_HAS_SPI3 TRUE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_HAS_TIM1 TRUE
#define STM32_HAS_TIM1 TRUE
#define STM32_HAS_TIM1 TRUE
#define STM32_HAS_TIM1 TRUE
#define STM32_HAS_TIM1 TRUE
#define STM32_HAS_TIM1 TRUE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_CHANNELS 4
#define STM32_TIM1_CHANNELS 4
#define STM32_TIM1_CHANNELS 4
#define STM32_TIM1_CHANNELS 4
#define STM32_TIM1_CHANNELS 4
#define STM32_TIM1_CHANNELS 4
#define STM32_HAS_TIM2 TRUE
#define STM32_HAS_TIM2 TRUE
#define STM32_HAS_TIM2 TRUE
#define STM32_HAS_TIM2 TRUE
#define STM32_HAS_TIM2 TRUE
#define STM32_HAS_TIM2 TRUE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_IS_32BITS FALSE
#define STM32_TIM2_CHANNELS 4
#define STM32_TIM2_CHANNELS 4
#define STM32_TIM2_CHANNELS 4
#define STM32_TIM2_CHANNELS 4
#define STM32_TIM2_CHANNELS 4
#define STM32_TIM2_CHANNELS 4
#define STM32_HAS_TIM3 TRUE
#define STM32_HAS_TIM3 TRUE
#define STM32_HAS_TIM3 TRUE
#define STM32_HAS_TIM3 TRUE
#define STM32_HAS_TIM3 TRUE
#define STM32_HAS_TIM3 TRUE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_CHANNELS 4
#define STM32_TIM3_CHANNELS 4
#define STM32_TIM3_CHANNELS 4
#define STM32_TIM3_CHANNELS 4
#define STM32_TIM3_CHANNELS 4
#define STM32_TIM3_CHANNELS 4
#define STM32_HAS_TIM4 TRUE
#define STM32_HAS_TIM4 FALSE
#define STM32_HAS_TIM4 TRUE
#define STM32_HAS_TIM4 TRUE
#define STM32_HAS_TIM4 TRUE
#define STM32_HAS_TIM4 TRUE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_CHANNELS 4
#define STM32_TIM4_CHANNELS 4
#define STM32_TIM4_CHANNELS 4
#define STM32_TIM4_CHANNELS 4
#define STM32_TIM4_CHANNELS 4
#define STM32_HAS_TIM6 TRUE
#define STM32_HAS_TIM6 FALSE
#define STM32_HAS_TIM6 FALSE
#define STM32_HAS_TIM6 TRUE
#define STM32_HAS_TIM6 TRUE
#define STM32_HAS_TIM6 TRUE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_CHANNELS 0
#define STM32_TIM6_CHANNELS 0
#define STM32_TIM6_CHANNELS 0
#define STM32_TIM6_CHANNELS 0
#define STM32_HAS_TIM7 TRUE
#define STM32_HAS_TIM7 FALSE
#define STM32_HAS_TIM7 FALSE
#define STM32_HAS_TIM7 TRUE
#define STM32_HAS_TIM7 TRUE
#define STM32_HAS_TIM7 TRUE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_CHANNELS 0
#define STM32_TIM7_CHANNELS 0
#define STM32_TIM7_CHANNELS 0
#define STM32_TIM7_CHANNELS 0
#define STM32_HAS_TIM15 TRUE
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM16 TRUE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM17 TRUE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM5 FALSE
#define STM32_HAS_TIM5 FALSE
#define STM32_HAS_TIM5 FALSE
#define STM32_HAS_TIM5 TRUE
#define STM32_HAS_TIM5 TRUE
#define STM32_HAS_TIM5 TRUE
#define STM32_HAS_TIM8 FALSE
#define STM32_HAS_TIM8 FALSE
#define STM32_HAS_TIM8 FALSE
#define STM32_HAS_TIM8 TRUE
#define STM32_HAS_TIM8 TRUE
#define STM32_HAS_TIM8 FALSE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM9 TRUE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM10 TRUE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM11 TRUE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM12 TRUE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM13 TRUE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM14 TRUE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_USART1 TRUE
#define STM32_HAS_USART1 TRUE
#define STM32_HAS_USART1 TRUE
#define STM32_HAS_USART1 TRUE
#define STM32_HAS_USART1 TRUE
#define STM32_HAS_USART1 TRUE
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_HAS_USART2 TRUE
#define STM32_HAS_USART2 TRUE
#define STM32_HAS_USART2 TRUE
#define STM32_HAS_USART2 TRUE
#define STM32_HAS_USART2 TRUE
#define STM32_HAS_USART2 TRUE
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_HAS_USART3 TRUE
#define STM32_HAS_USART3 FALSE
#define STM32_HAS_USART3 TRUE
#define STM32_HAS_USART3 TRUE
#define STM32_HAS_USART3 TRUE
#define STM32_HAS_USART3 TRUE
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_HAS_UART4 FALSE
#define STM32_HAS_UART4 FALSE
#define STM32_HAS_UART4 FALSE
#define STM32_HAS_UART4 TRUE
#define STM32_HAS_UART4 TRUE
#define STM32_HAS_UART4 TRUE
#define STM32_HAS_UART5 FALSE
#define STM32_HAS_UART5 FALSE
#define STM32_HAS_UART5 FALSE
#define STM32_HAS_UART5 FALSE
#define STM32_HAS_UART5 FALSE
#define STM32_HAS_UART5 TRUE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_USB FALSE
#define STM32_HAS_USB FALSE
#define STM32_HAS_USB TRUE
#define STM32_HAS_USB TRUE
#define STM32_HAS_USB TRUE
#define STM32_HAS_USB FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG1 TRUE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_IWDG TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_FSMC FALSE
#define STM32_HAS_FSMC FALSE
#define STM32_HAS_FSMC FALSE
#define STM32_HAS_FSMC TRUE
#define STM32_HAS_FSMC TRUE
#define STM32_HAS_FSMC FALSE
#define STM32_HAS_CRC TRUE
#define STM32_HAS_CRC TRUE
#define STM32_HAS_CRC TRUE
#define STM32_HAS_CRC TRUE
#define STM32_HAS_CRC TRUE
#define STM32_HAS_CRC TRUE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_CRC_PROGRAMMABLE FALSE
#define STM32_DMA2_CH1_HANDLER Vector120
#define STM32_DMA2_CH1_HANDLER Vector120
#define STM32_DMA2_CH1_HANDLER Vector120
#define STM32_DMA2_CH2_HANDLER Vector124
#define STM32_DMA2_CH2_HANDLER Vector124
#define STM32_DMA2_CH2_HANDLER Vector124
#define STM32_DMA2_CH3_HANDLER Vector128
#define STM32_DMA2_CH3_HANDLER Vector128
#define STM32_DMA2_CH3_HANDLER Vector128
#define STM32_DMA2_CH1_NUMBER 56
#define STM32_DMA2_CH1_NUMBER 56
#define STM32_DMA2_CH1_NUMBER 56
#define STM32_DMA2_CH2_NUMBER 57
#define STM32_DMA2_CH2_NUMBER 57
#define STM32_DMA2_CH2_NUMBER 57
#define STM32_DMA2_CH3_NUMBER 58
#define STM32_DMA2_CH3_NUMBER 58
#define STM32_DMA2_CH3_NUMBER 58
#define STM32_DMA2_CH4_NUMBER STM32_DMA2_CH45_NUMBER
#define STM32_DMA2_CH4_NUMBER 59
#define STM32_DMA2_CH4_NUMBER 59
#define STM32_DMA2_CH5_NUMBER STM32_DMA2_CH45_NUMBER
#define STM32_DMA2_CH5_NUMBER 60
#define STM32_DMA2_CH5_NUMBER 60
#define STM32_SPI2_I2S_FULLDUPLEX FALSE
#define STM32_SPI2_I2S_FULLDUPLEX FALSE
#define STM32_SPI2_I2S_FULLDUPLEX FALSE
#define STM32_SPI3_SUPPORTS_I2S TRUE
#define STM32_SPI3_SUPPORTS_I2S TRUE
#define STM32_SPI3_SUPPORTS_I2S TRUE
#define STM32_SPI3_I2S_FULLDUPLEX FALSE
#define STM32_SPI3_I2S_FULLDUPLEX FALSE
#define STM32_SPI3_I2S_FULLDUPLEX FALSE
#define STM32_SPI_SPI3_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
#define STM32_SPI_SPI3_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
#define STM32_SPI_SPI3_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
#define STM32_SPI_SPI3_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_SPI_SPI3_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_SPI_SPI3_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_TIM5_IS_32BITS FALSE
#define STM32_TIM5_IS_32BITS FALSE
#define STM32_TIM5_IS_32BITS FALSE
#define STM32_TIM5_CHANNELS 4
#define STM32_TIM5_CHANNELS 4
#define STM32_TIM5_CHANNELS 4
#define STM32_UART_UART4_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_UART_UART4_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_UART_UART4_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_UART_UART4_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 5)
#define STM32_UART_UART4_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 5)
#define STM32_UART_UART4_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 5)
#define STM32_DMA2_CH4_HANDLER Vector12C
#define STM32_DMA2_CH4_HANDLER Vector12C
#define STM32_DMA2_CH5_HANDLER Vector130
#define STM32_DMA2_CH5_HANDLER Vector130
#define STM32_ETH_HANDLER Vector134
#define STM32_ETH_NUMBER 61
#define STM32_OTG_STEPPING 1
#define STM32_OTG1_ENDPOINTS 3
ChibiOS/HAL version identification
#define HAL_VERSION "6.0.0"
HAL version string.
#define CH_HAL_MAJOR 6
HAL version major number.
#define CH_HAL_MINOR 0
HAL version minor number.
#define CH_HAL_PATCH 0
HAL version patch number.
Return codes
#define HAL_SUCCESS false
#define HAL_FAILED true
Functions
static void hal_lld_backup_domain_init (void)
Initializes the backup domain.
OSAL_IRQ_HANDLER (STM32_DMA2_CH45_HANDLER)
DMA2 streams 4 and 5 shared ISR.
void hal_lld_init (void)
Low level HAL driver initialization.
void stm32_clock_init (void)
STM32 clocks and PLL initialization.
void halInit (void)
HAL initialization.
Variables
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Macro Definition Documentation
#define STM32F1XX
Sub-family identifier.
Definition at line 88 of file hal_lld.h.
#define STM32_HSICLK 8000000
High speed internal clock.
Definition at line 96 of file hal_lld.h.
#define STM32_LSICLK 40000
Low speed internal clock.
Definition at line 97 of file hal_lld.h.
#define STM32_PLS_MASK (7 << 5)
PLS bits mask.
Definition at line 104 of file hal_lld.h.
Referenced by hal_lld_init().
#define STM32_PLS_LEV0 (0 << 5)
PVD level 0.
Definition at line 105 of file hal_lld.h.
#define STM32_PLS_LEV1 (1 << 5)
PVD level 1.
Definition at line 106 of file hal_lld.h.
#define STM32_PLS_LEV2 (2 << 5)
PVD level 2.
Definition at line 107 of file hal_lld.h.
#define STM32_PLS_LEV3 (3 << 5)
PVD level 3.
Definition at line 108 of file hal_lld.h.
#define STM32_PLS_LEV4 (4 << 5)
PVD level 4.
Definition at line 109 of file hal_lld.h.
#define STM32_PLS_LEV5 (5 << 5)
PVD level 5.
Definition at line 110 of file hal_lld.h.
#define STM32_PLS_LEV6 (6 << 5)
PVD level 6.
Definition at line 111 of file hal_lld.h.
#define STM32_PLS_LEV7 (7 << 5)
PVD level 7.
Definition at line 112 of file hal_lld.h.
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
Definition at line 131 of file hal_lld.h.
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
Definition at line 138 of file hal_lld.h.
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
Definition at line 145 of file hal_lld.h.
Referenced by hal_lld_init().
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
Definition at line 152 of file hal_lld.h.
#define STM32_LSI_ENABLED FALSE
Enables or disables the LSI clock source.
Definition at line 159 of file hal_lld.h.
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
Definition at line 166 of file hal_lld.h.
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
Definition at line 173 of file hal_lld.h.
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
Definition at line 175 of file hal.h.
#define CH_HAL_STABLE 1
Stable release flag.
Definition at line 180 of file hal.h.
#define HAL_VERSION "6.0.0"
HAL version string.
Definition at line 189 of file hal.h.
#define CH_HAL_MAJOR 6
HAL version major number.
Definition at line 194 of file hal.h.
#define CH_HAL_MINOR 0
HAL version minor number.
Definition at line 199 of file hal.h.
#define CH_HAL_PATCH 0
HAL version patch number.
Definition at line 204 of file hal.h.
Function Documentation
static void hal_lld_backup_domain_init (void) static
Initializes the backup domain.
Note
WARNING! Changing clock source impossible without resetting of the whole BKP domain.
Definition at line 54 of file hal_lld.c.
References rtc_lld_set_prescaler(), STM32_RTCSEL, and STM32_RTCSEL_MASK.
Referenced by hal_lld_init().
OSAL_IRQ_HANDLER (STM32_DMA2_CH45_HANDLER)
DMA2 streams 4 and 5 shared ISR.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 108 of file hal_lld.c.
References dmaServeInterrupt, OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
void hal_lld_init (void)
Low level HAL driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 132 of file hal_lld.c.
References dmaInit(), hal_lld_backup_domain_init(), irqInit(), rccEnableBKPInterface, rccEnablePWRInterface, rccResetAPB1, rccResetAPB2, STM32_PLS, and STM32_PLS_MASK.
Referenced by halInit().
void stm32_clock_init (void)
STM32 clocks and PLL initialization.
Note
All the involved constants come from the file board.h.
This function should be invoked just after the system reset.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 173 of file hal_lld.c.
References STM32_ADCPRE, STM32_FLASHBITS, STM32_HPRE, STM32_MCOSEL, STM32_OTGFSPRE, STM32_PLL2MUL, STM32_PLL3MUL, STM32_PLLMUL, STM32_PLLSRC, STM32_PLLXTPRE, STM32_PPRE1, STM32_PPRE2, STM32_PREDIV1, STM32_PREDIV1SRC, STM32_PREDIV2, STM32_SW, and STM32_USBPRE.
void halInit (void)
HAL initialization.
This function invokes the low level initialization code then initializes all the drivers enabled in the HAL. Finally the board-specific initialization is performed by invoking boardInit() (usually defined in board.c).
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal.c.
References adcInit(), canInit(), cryInit(), dacInit(), extInit(), gptInit(), hal_lld_init(), i2cInit(), i2sInit(), icuInit(), macInit(), mmcInit(), osalInit(), palInit, pwmInit(), qspiInit(), rtcInit(), sdcInit(), sdInit(), sduInit(), spiInit(), stInit(), uartInit(), usbInit(), and wdgInit().
Variable Documentation
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Note
It is declared in system_stm32f10x.h.
Definition at line 39 of file hal_lld.c.