ChibiOS/HAL: MMC/SD Block Device
MMC/SD Block Device
HAL » Inner Code
Detailed Description
This module implements a common ancestor for all device drivers accessing MMC or SD cards. This interface inherits the state machine and the interface from the Abstract I/O Block Device module.
Macros
#define MMCSD_BLOCK_SIZE 512U
Fixed block size for MMC/SD block devices.
#define MMCSD_R1_ERROR_MASK 0xFDFFE008U
Mask of error bits in R1 responses.
#define MMCSD_CMD8_PATTERN 0x000001AAU
Fixed pattern for CMD8.
#define _mmcsd_block_device_methods _base_block_device_methods
MMCSDBlockDevice specific methods.
#define _mmcsd_block_device_data
MMCSDBlockDevice specific data.
SD/MMC status conditions
#define MMCSD_STS_IDLE 0U
#define MMCSD_STS_READY 1U
#define MMCSD_STS_IDENT 2U
#define MMCSD_STS_STBY 3U
#define MMCSD_STS_TRAN 4U
#define MMCSD_STS_DATA 5U
#define MMCSD_STS_RCV 6U
#define MMCSD_STS_PRG 7U
#define MMCSD_STS_DIS 8U
SD/MMC commands
#define MMCSD_CMD_GO_IDLE_STATE 0U
#define MMCSD_CMD_INIT 1U
#define MMCSD_CMD_ALL_SEND_CID 2U
#define MMCSD_CMD_SEND_RELATIVE_ADDR 3U
#define MMCSD_CMD_SET_BUS_WIDTH 6U
#define MMCSD_CMD_SWITCH MMCSD_CMD_SET_BUS_WIDTH
#define MMCSD_CMD_SEL_DESEL_CARD 7U
#define MMCSD_CMD_SEND_IF_COND 8U
#define MMCSD_CMD_SEND_EXT_CSD MMCSD_CMD_SEND_IF_COND
#define MMCSD_CMD_SEND_CSD 9U
#define MMCSD_CMD_SEND_CID 10U
#define MMCSD_CMD_STOP_TRANSMISSION 12U
#define MMCSD_CMD_SEND_STATUS 13U
#define MMCSD_CMD_SET_BLOCKLEN 16U
#define MMCSD_CMD_READ_SINGLE_BLOCK 17U
#define MMCSD_CMD_READ_MULTIPLE_BLOCK 18U
#define MMCSD_CMD_SET_BLOCK_COUNT 23U
#define MMCSD_CMD_WRITE_BLOCK 24U
#define MMCSD_CMD_WRITE_MULTIPLE_BLOCK 25U
#define MMCSD_CMD_ERASE_RW_BLK_START 32U
#define MMCSD_CMD_ERASE_RW_BLK_END 33U
#define MMCSD_CMD_ERASE 38U
#define MMCSD_CMD_APP_OP_COND 41U
#define MMCSD_CMD_LOCK_UNLOCK 42U
#define MMCSD_CMD_APP_CMD 55U
#define MMCSD_CMD_READ_OCR 58U
CSD record offsets
#define MMCSD_CSD_MMC_CSD_STRUCTURE_SLICE 127U,126U
Slice position of values in CSD register.
#define MMCSD_CSD_MMC_SPEC_VERS_SLICE 125U,122U
#define MMCSD_CSD_MMC_TAAC_SLICE 119U,112U
#define MMCSD_CSD_MMC_NSAC_SLICE 111U,104U
#define MMCSD_CSD_MMC_TRAN_SPEED_SLICE 103U,96U
#define MMCSD_CSD_MMC_CCC_SLICE 95U,84U
#define MMCSD_CSD_MMC_READ_BL_LEN_SLICE 83U,80U
#define MMCSD_CSD_MMC_READ_BL_PARTIAL_SLICE 79U,79U
#define MMCSD_CSD_MMC_WRITE_BLK_MISALIGN_SLICE 78U,78U
#define MMCSD_CSD_MMC_READ_BLK_MISALIGN_SLICE 77U,77U
#define MMCSD_CSD_MMC_DSR_IMP_SLICE 76U,76U
#define MMCSD_CSD_MMC_C_SIZE_SLICE 73U,62U
#define MMCSD_CSD_MMC_VDD_R_CURR_MIN_SLICE 61U,59U
#define MMCSD_CSD_MMC_VDD_R_CURR_MAX_SLICE 58U,56U
#define MMCSD_CSD_MMC_VDD_W_CURR_MIN_SLICE 55U,53U
#define MMCSD_CSD_MMC_VDD_W_CURR_MAX_SLICE 52U,50U
#define MMCSD_CSD_MMC_C_SIZE_MULT_SLICE 49U,47U
#define MMCSD_CSD_MMC_ERASE_GRP_SIZE_SLICE 46U,42U
#define MMCSD_CSD_MMC_ERASE_GRP_MULT_SLICE 41U,37U
#define MMCSD_CSD_MMC_WP_GRP_SIZE_SLICE 36U,32U
#define MMCSD_CSD_MMC_WP_GRP_ENABLE_SLICE 31U,31U
#define MMCSD_CSD_MMC_DEFAULT_ECC_SLICE 30U,29U
#define MMCSD_CSD_MMC_R2W_FACTOR_SLICE 28U,26U
#define MMCSD_CSD_MMC_WRITE_BL_LEN_SLICE 25U,22U
#define MMCSD_CSD_MMC_WRITE_BL_PARTIAL_SLICE 21U,21U
#define MMCSD_CSD_MMC_CONTENT_PROT_APP_SLICE 16U,16U
#define MMCSD_CSD_MMC_FILE_FORMAT_GRP_SLICE 15U,15U
#define MMCSD_CSD_MMC_COPY_SLICE 14U,14U
#define MMCSD_CSD_MMC_PERM_WRITE_PROTECT_SLICE 13U,13U
#define MMCSD_CSD_MMC_TMP_WRITE_PROTECT_SLICE 12U,12U
#define MMCSD_CSD_MMC_FILE_FORMAT_SLICE 11U,10U
#define MMCSD_CSD_MMC_ECC_SLICE 9U,8U
#define MMCSD_CSD_MMC_CRC_SLICE 7U,1U
#define MMCSD_CSD_20_CRC_SLICE 7U,1U
#define MMCSD_CSD_20_FILE_FORMAT_SLICE 11U,10U
#define MMCSD_CSD_20_TMP_WRITE_PROTECT_SLICE 12U,12U
#define MMCSD_CSD_20_PERM_WRITE_PROTECT_SLICE 13U,13U
#define MMCSD_CSD_20_COPY_SLICE 14U,14U
#define MMCSD_CSD_20_FILE_FORMAT_GRP_SLICE 15U,15U
#define MMCSD_CSD_20_WRITE_BL_PARTIAL_SLICE 21U,21U
#define MMCSD_CSD_20_WRITE_BL_LEN_SLICE 25U,12U
#define MMCSD_CSD_20_R2W_FACTOR_SLICE 28U,26U
#define MMCSD_CSD_20_WP_GRP_ENABLE_SLICE 31U,31U
#define MMCSD_CSD_20_WP_GRP_SIZE_SLICE 38U,32U
#define MMCSD_CSD_20_ERASE_SECTOR_SIZE_SLICE 45U,39U
#define MMCSD_CSD_20_ERASE_BLK_EN_SLICE 46U,46U
#define MMCSD_CSD_20_C_SIZE_SLICE 69U,48U
#define MMCSD_CSD_20_DSR_IMP_SLICE 76U,76U
#define MMCSD_CSD_20_READ_BLK_MISALIGN_SLICE 77U,77U
#define MMCSD_CSD_20_WRITE_BLK_MISALIGN_SLICE 78U,78U
#define MMCSD_CSD_20_READ_BL_PARTIAL_SLICE 79U,79U
#define MMCSD_CSD_20_READ_BL_LEN_SLICE 83U,80U
#define MMCSD_CSD_20_CCC_SLICE 95U,84U
#define MMCSD_CSD_20_TRANS_SPEED_SLICE 103U,96U
#define MMCSD_CSD_20_NSAC_SLICE 111U,104U
#define MMCSD_CSD_20_TAAC_SLICE 119U,112U
#define MMCSD_CSD_20_CSD_STRUCTURE_SLICE 127U,126U
#define MMCSD_CSD_10_CRC_SLICE MMCSD_CSD_20_CRC_SLICE
#define MMCSD_CSD_10_FILE_FORMAT_SLICE MMCSD_CSD_20_FILE_FORMAT_SLICE
#define MMCSD_CSD_10_TMP_WRITE_PROTECT_SLICE MMCSD_CSD_20_TMP_WRITE_PROTECT_SLICE
#define MMCSD_CSD_10_PERM_WRITE_PROTECT_SLICE MMCSD_CSD_20_PERM_WRITE_PROTECT_SLICE
#define MMCSD_CSD_10_COPY_SLICE MMCSD_CSD_20_COPY_SLICE
#define MMCSD_CSD_10_FILE_FORMAT_GRP_SLICE MMCSD_CSD_20_FILE_FORMAT_GRP_SLICE
#define MMCSD_CSD_10_WRITE_BL_PARTIAL_SLICE MMCSD_CSD_20_WRITE_BL_PARTIAL_SLICE
#define MMCSD_CSD_10_WRITE_BL_LEN_SLICE MMCSD_CSD_20_WRITE_BL_LEN_SLICE
#define MMCSD_CSD_10_R2W_FACTOR_SLICE MMCSD_CSD_20_R2W_FACTOR_SLICE
#define MMCSD_CSD_10_WP_GRP_ENABLE_SLICE MMCSD_CSD_20_WP_GRP_ENABLE_SLICE
#define MMCSD_CSD_10_WP_GRP_SIZE_SLICE MMCSD_CSD_20_WP_GRP_SIZE_SLICE
#define MMCSD_CSD_10_ERASE_SECTOR_SIZE_SLICE MMCSD_CSD_20_ERASE_SECTOR_SIZE_SLICE
#define MMCSD_CSD_10_ERASE_BLK_EN_SLICE MMCSD_CSD_20_ERASE_BLK_EN_SLICE
#define MMCSD_CSD_10_C_SIZE_MULT_SLICE 49U,47U
#define MMCSD_CSD_10_VDD_W_CURR_MAX_SLICE 52U,50U
#define MMCSD_CSD_10_VDD_W_CURR_MIN_SLICE 55U,53U
#define MMCSD_CSD_10_VDD_R_CURR_MAX_SLICE 58U,56U
#define MMCSD_CSD_10_VDD_R_CURR_MIX_SLICE 61U,59U
#define MMCSD_CSD_10_C_SIZE_SLICE 73U,62U
#define MMCSD_CSD_10_DSR_IMP_SLICE MMCSD_CSD_20_DSR_IMP_SLICE
#define MMCSD_CSD_10_READ_BLK_MISALIGN_SLICE MMCSD_CSD_20_READ_BLK_MISALIGN_SLICE
#define MMCSD_CSD_10_WRITE_BLK_MISALIGN_SLICE MMCSD_CSD_20_WRITE_BLK_MISALIGN_SLICE
#define MMCSD_CSD_10_READ_BL_PARTIAL_SLICE MMCSD_CSD_20_READ_BL_PARTIAL_SLICE
#define MMCSD_CSD_10_READ_BL_LEN_SLICE 83U,80U
#define MMCSD_CSD_10_CCC_SLICE MMCSD_CSD_20_CCC_SLICE
#define MMCSD_CSD_10_TRANS_SPEED_SLICE MMCSD_CSD_20_TRANS_SPEED_SLICE
#define MMCSD_CSD_10_NSAC_SLICE MMCSD_CSD_20_NSAC_SLICE
#define MMCSD_CSD_10_TAAC_SLICE MMCSD_CSD_20_TAAC_SLICE
#define MMCSD_CSD_10_CSD_STRUCTURE_SLICE MMCSD_CSD_20_CSD_STRUCTURE_SLICE
CID record offsets
#define MMCSD_CID_SDC_CRC_SLICE 7U,1U
Slice position of values in CID register.
#define MMCSD_CID_SDC_MDT_M_SLICE 11U,8U
#define MMCSD_CID_SDC_MDT_Y_SLICE 19U,12U
#define MMCSD_CID_SDC_PSN_SLICE 55U,24U
#define MMCSD_CID_SDC_PRV_M_SLICE 59U,56U
#define MMCSD_CID_SDC_PRV_N_SLICE 63U,60U
#define MMCSD_CID_SDC_PNM0_SLICE 71U,64U
#define MMCSD_CID_SDC_PNM1_SLICE 79U,72U
#define MMCSD_CID_SDC_PNM2_SLICE 87U,80U
#define MMCSD_CID_SDC_PNM3_SLICE 95U,88U
#define MMCSD_CID_SDC_PNM4_SLICE 103U,96U
#define MMCSD_CID_SDC_OID_SLICE 119U,104U
#define MMCSD_CID_SDC_MID_SLICE 127U,120U
#define MMCSD_CID_MMC_CRC_SLICE 7U,1U
#define MMCSD_CID_MMC_MDT_Y_SLICE 11U,8U
#define MMCSD_CID_MMC_MDT_M_SLICE 15U,12U
#define MMCSD_CID_MMC_PSN_SLICE 47U,16U
#define MMCSD_CID_MMC_PRV_M_SLICE 51U,48U
#define MMCSD_CID_MMC_PRV_N_SLICE 55U,52U
#define MMCSD_CID_MMC_PNM0_SLICE 63U,56U
#define MMCSD_CID_MMC_PNM1_SLICE 71U,64U
#define MMCSD_CID_MMC_PNM2_SLICE 79U,72U
#define MMCSD_CID_MMC_PNM3_SLICE 87U,80U
#define MMCSD_CID_MMC_PNM4_SLICE 95U,88U
#define MMCSD_CID_MMC_PNM5_SLICE 103U,96U
#define MMCSD_CID_MMC_OID_SLICE 119U,104U
#define MMCSD_CID_MMC_MID_SLICE 127U,120U
R1 response utilities
#define MMCSD_R1_ERROR(r1) (((r1) & MMCSD_R1_ERROR_MASK) != 0U)
Evaluates to true if the R1 response contains error flags.
#define MMCSD_R1_STS(r1) (((r1) >> 9U) & 15U)
Returns the status field of an R1 response.
#define MMCSD_R1_IS_CARD_LOCKED(r1) ((((r1) >> 21U) & 1U) != 0U)
Evaluates to true if the R1 response indicates a locked card.
Macro Functions
#define mmcsdGetCardCapacity(ip) ((ip)->capacity)
Returns the card capacity in blocks.
Data Structures
struct MMCSDBlockDeviceVMT
MMCSDBlockDevice virtual methods table.
struct MMCSDBlockDevice
MCC/SD block device class.
struct unpacked_sdc_cid_t
Unpacked CID register from SDC.
struct unpacked_mmc_cid_t
Unpacked CID register from MMC.
struct unpacked_sdc_csd_10_t
Unpacked CSD v1.0 register from SDC.
struct unpacked_sdc_csd_20_t
Unpacked CSD v2.0 register from SDC.
struct unpacked_mmc_csd_t
Unpacked CSD register from MMC.
Functions
uint32_t _mmcsd_get_slice (const uint32_t *data, uint32_t end, uint32_t start)
Gets a bit field from a words array.
uint32_t _mmcsd_get_capacity (const uint32_t *csd)
Extract card capacity from a CSD.
uint32_t _mmcsd_get_capacity_ext (const uint8_t *ext_csd)
Extract MMC card capacity from EXT_CSD.
void _mmcsd_unpack_sdc_cid (const MMCSDBlockDevice *sdcp, unpacked_sdc_cid_t *cidsdc)
Unpacks SDC CID array in structure.
void _mmcsd_unpack_mmc_cid (const MMCSDBlockDevice *sdcp, unpacked_mmc_cid_t *cidmmc)
Unpacks MMC CID array in structure.
void _mmcsd_unpack_csd_mmc (const MMCSDBlockDevice *sdcp, unpacked_mmc_csd_t *csdmmc)
Unpacks MMC CSD array in structure.
void _mmcsd_unpack_csd_v10 (const MMCSDBlockDevice *sdcp, unpacked_sdc_csd_10_t *csd10)
Unpacks SDC CSD v1.0 array in structure.
void _mmcsd_unpack_csd_v20 (const MMCSDBlockDevice *sdcp, unpacked_sdc_csd_20_t *csd20)
Unpacks SDC CSD v2.0 array in structure.
Macro Definition Documentation
#define MMCSD_BLOCK_SIZE 512U
Fixed block size for MMC/SD block devices.
Definition at line 39 of file hal_mmcsd.h.
Referenced by mmcConnect(), mmcErase(), mmcGetInfo(), mmcSequentialRead(), mmcSequentialWrite(), mmcStartSequentialRead(), mmcStartSequentialWrite(), sdcConnect(), sdcErase(), and sdcGetInfo().
#define MMCSD_R1_ERROR_MASK 0xFDFFE008U
Mask of error bits in R1 responses.
Definition at line 44 of file hal_mmcsd.h.
#define MMCSD_CMD8_PATTERN 0x000001AAU
Fixed pattern for CMD8.
Definition at line 49 of file hal_mmcsd.h.
Referenced by mmcConnect(), and mode_detect().
#define MMCSD_CSD_MMC_CSD_STRUCTURE_SLICE 127U,126U
Slice position of values in CSD register.
Definition at line 105 of file hal_mmcsd.h.
Referenced by _mmcsd_unpack_csd_mmc(), and sdcConnect().
#define MMCSD_CID_SDC_CRC_SLICE 7U,1U
Slice position of values in CID register.
Definition at line 204 of file hal_mmcsd.h.
Referenced by _mmcsd_unpack_sdc_cid().
#define _mmcsd_block_device_methods _base_block_device_methods
MMCSDBlockDevice specific methods.
Definition at line 250 of file hal_mmcsd.h.
#define _mmcsd_block_device_data
Value:
_base_block_device_data                                                   \
  /* Card CID.*/                                                            \
  uint32_t              cid[4];                                             \
  /* Card CSD.*/                                                            \
  uint32_t              csd[4];                                             \
  /* Total number of blocks in card.*/                                      \
  uint32_t              capacity;
MMCSDBlockDevice specific data.
Note
It is empty because MMCSDBlockDevice is only an interface without implementation.
Definition at line 258 of file hal_mmcsd.h.
#define MMCSD_R1_ERROR (r1) (((r1) & MMCSD_R1_ERROR_MASK) != 0U)
Evaluates to true if the R1 response contains error flags.
Parameters
[in] r1 the r1 response
Definition at line 435 of file hal_mmcsd.h.
Referenced by _sdc_wait_for_transfer_state(), mmc_detect_bus_clk(), mmc_set_bus_width(), mode_detect(), sdc_init(), sdc_set_bus_width(), sdcConnect(), and sdcErase().
#define MMCSD_R1_STS (r1) (((r1) >> 9U) & 15U)
Returns the status field of an R1 response.
Parameters
[in] r1 the r1 response
Definition at line 442 of file hal_mmcsd.h.
Referenced by _sdc_wait_for_transfer_state().
#define MMCSD_R1_IS_CARD_LOCKED (r1) ((((r1) >> 21U) & 1U) != 0U)
Evaluates to true if the R1 response indicates a locked card.
Parameters
[in] r1 the r1 response
Definition at line 449 of file hal_mmcsd.h.
#define mmcsdGetCardCapacity (ip) ((ip)->capacity)
Returns the card capacity in blocks.
Parameters
[in] ip pointer to a MMCSDBlockDevice or derived class
Returns
The card capacity.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 465 of file hal_mmcsd.h.
Function Documentation
uint32_t _mmcsd_get_slice (const uint32_t * data, uint32_t end, uint32_t start)
Gets a bit field from a words array.
Note
The bit zero is the LSb of the first word.
Parameters
[in] data pointer to the words array
[in] end bit offset of the last bit of the field, inclusive
[in] start bit offset of the first bit of the field, inclusive
Returns
The bits field value, left aligned.
Function Class:
Not an API, this function is for internal use only.
Definition at line 61 of file hal_mmcsd.c.
References osalDbgCheck.
Referenced by _mmcsd_get_capacity(), _mmcsd_unpack_csd_mmc(), _mmcsd_unpack_csd_v10(), _mmcsd_unpack_csd_v20(), _mmcsd_unpack_mmc_cid(), _mmcsd_unpack_sdc_cid(), sdc_detect_bus_clk(), and sdcConnect().
uint32_t _mmcsd_get_capacity (const uint32_t * csd)
Extract card capacity from a CSD.
The capacity is returned as number of available blocks.
Parameters
[in] csd the CSD record
Returns
The card capacity.
Return values
0 CSD format error
Function Class:
Not an API, this function is for internal use only.
Definition at line 93 of file hal_mmcsd.c.
References _mmcsd_get_slice(), and osalDbgCheck.
Referenced by mmcConnect(), and sdcConnect().
uint32_t _mmcsd_get_capacity_ext (const uint8_t * ext_csd)
Extract MMC card capacity from EXT_CSD.
The capacity is returned as number of available blocks.
Parameters
[in] ext_csd the extended CSD record
Returns
The card capacity.
Function Class:
Not an API, this function is for internal use only.
Definition at line 125 of file hal_mmcsd.c.
References osalDbgCheck.
Referenced by sdcConnect().
void _mmcsd_unpack_sdc_cid (const MMCSDBlockDevice * sdcp, unpacked_sdc_cid_t * cidsdc)
Unpacks SDC CID array in structure.
Parameters
[in] sdcp pointer to the MMCSDBlockDevice object
[out] cidsdc pointer to the unpacked_sdc_cid_t object
Function Class:
Not an API, this function is for internal use only.
Definition at line 143 of file hal_mmcsd.c.
References _mmcsd_get_slice(), MMCSD_CID_SDC_CRC_SLICE, and osalDbgCheck.
void _mmcsd_unpack_mmc_cid (const MMCSDBlockDevice * sdcp, unpacked_mmc_cid_t * cidmmc)
Unpacks MMC CID array in structure.
Parameters
[in] sdcp pointer to the MMCSDBlockDevice object
[out] cidmmc pointer to the unpacked_mmc_cid_t object
Function Class:
Not an API, this function is for internal use only.
Definition at line 174 of file hal_mmcsd.c.
References _mmcsd_get_slice(), and osalDbgCheck.
void _mmcsd_unpack_csd_mmc (const MMCSDBlockDevice * sdcp, unpacked_mmc_csd_t * csdmmc)
Unpacks MMC CSD array in structure.
Parameters
[in] sdcp pointer to the MMCSDBlockDevice object
[out] csdmmc pointer to the unpacked_mmc_csd_t object
Function Class:
Not an API, this function is for internal use only.
Definition at line 206 of file hal_mmcsd.c.
References _mmcsd_get_slice(), MMCSD_CSD_MMC_CSD_STRUCTURE_SLICE, and osalDbgCheck.
void _mmcsd_unpack_csd_v10 (const MMCSDBlockDevice * sdcp, unpacked_sdc_csd_10_t * csd10)
Unpacks SDC CSD v1.0 array in structure.
Parameters
[in] sdcp pointer to the MMCSDBlockDevice object
[out] csd10 pointer to the unpacked_sdc_csd_10_t object
Function Class:
Not an API, this function is for internal use only.
Definition at line 254 of file hal_mmcsd.c.
References _mmcsd_get_slice(), and osalDbgCheck.
void _mmcsd_unpack_csd_v20 (const MMCSDBlockDevice * sdcp, unpacked_sdc_csd_20_t * csd20)
Unpacks SDC CSD v2.0 array in structure.
Parameters
[in] sdcp pointer to the MMCSDBlockDevice object
[out] csd20 pointer to the unpacked_sdc_csd_20_t object
Function Class:
Not an API, this function is for internal use only.
Definition at line 296 of file hal_mmcsd.c.
References _mmcsd_get_slice(), and osalDbgCheck.