ChibiOS/HAL: CRYPTO
CRYPTO
Detailed Description
Macros
#define HAL_CRY_MAX_KEY_SIZE 32
Maximum size of a key for all supported algorithms.
#define HAL_CRY_USE_FALLBACK FALSE
Enables the SW fall-back of the cryptographic driver.
#define HAL_CRY_USE_FALLBACK TRUE
Enables the SW fall-back of the cryptographic driver.
#define HAL_CRY_ENFORCE_FALLBACK FALSE
Makes the driver forcibly use the fall-back implementations.
Typedefs
typedef size_t bitsize_t
Size, in bits, of a crypto field or message.
Functions
void cryInit (void)
Cryptographic Driver initialization.
void cryObjectInit (CRYDriver *cryp)
Initializes the standard part of a CRYDriver structure.
void cryStart (CRYDriver *cryp, const CRYConfig *config)
Configures and activates the cryptographic peripheral.
void cryStop (CRYDriver *cryp)
Deactivates the cryptographic peripheral.
cryerror_t cryLoadTransientKey (CRYDriver *cryp, cryalgorithm_t algorithm, size_t size, const uint8_t *keyp)
Initializes the transient key for a specific algorithm.
cryerror_t cryEncryptAES (CRYDriver *cryp, crykey_t key_id, const uint8_t *in, uint8_t *out)
Encryption of a single block using AES.
cryerror_t cryDecryptAES (CRYDriver *cryp, crykey_t key_id, const uint8_t *in, uint8_t *out)
Decryption of a single block using AES.
cryerror_t cryEncryptAES_ECB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out)
Encryption operation using AES-ECB.
cryerror_t cryDecryptAES_ECB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out)
Decryption operation using AES-ECB.
cryerror_t cryEncryptAES_CBC (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Encryption operation using AES-CBC.
cryerror_t cryDecryptAES_CBC (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Decryption operation using AES-CBC.
cryerror_t cryEncryptAES_CFB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Encryption operation using AES-CFB.
cryerror_t cryDecryptAES_CFB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Decryption operation using AES-CFB.
cryerror_t cryEncryptAES_CTR (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Encryption operation using AES-CTR.
cryerror_t cryDecryptAES_CTR (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Decryption operation using AES-CTR.
cryerror_t cryEncryptAES_GCM (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv, size_t aadsize, const uint8_t *aad, uint8_t *authtag)
Encryption operation using AES-GCM.
cryerror_t cryDecryptAES_GCM (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv, size_t aadsize, const uint8_t *aad, uint8_t *authtag)
Decryption operation using AES-GCM.
cryerror_t cryEncryptDES (CRYDriver *cryp, crykey_t key_id, const uint8_t *in, uint8_t *out)
Encryption of a single block using (T)DES.
cryerror_t cryDecryptDES (CRYDriver *cryp, crykey_t key_id, const uint8_t *in, uint8_t *out)
Decryption of a single block using (T)DES.
cryerror_t cryEncryptDES_ECB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out)
Encryption operation using (T)DES-ECB.
cryerror_t cryDecryptDES_ECB (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out)
Decryption operation using (T)DES-ECB.
cryerror_t cryEncryptDES_CBC (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Encryption operation using (T)DES-CBC.
cryerror_t cryDecryptDES_CBC (CRYDriver *cryp, crykey_t key_id, size_t size, const uint8_t *in, uint8_t *out, const uint8_t *iv)
Decryption operation using (T)DES-CBC.
cryerror_t crySHA1 (CRYDriver *cryp, size_t size, const uint8_t *in, uint8_t *out)
Hash using SHA1.
cryerror_t crySHA256 (CRYDriver *cryp, size_t size, const uint8_t *in, uint8_t *out)
Hash using SHA256.
cryerror_t crySHA512 (CRYDriver *cryp, size_t size, const uint8_t *in, uint8_t *out)
Hash using SHA512.
cryerror_t cryTRNG (CRYDriver *cryp, uint8_t *out)
True random numbers generator.
Enumerations
Macro Definition Documentation
#define HAL_CRY_MAX_KEY_SIZE 32
Maximum size of a key for all supported algorithms.
Definition at line 37 of file hal_crypto.h.
Referenced by cryLoadTransientKey().
#define HAL_CRY_USE_FALLBACK FALSE
Enables the SW fall-back of the cryptographic driver.
When enabled, this option, activates a fall-back software implementation for algorithms not supported by the underlying hardware.
Note
Fall-back implementations may not be present for all algorithms.
Definition at line 67 of file hal_crypto.h.
#define HAL_CRY_USE_FALLBACK TRUE
Enables the SW fall-back of the cryptographic driver.
When enabled, this option, activates a fall-back software implementation for algorithms not supported by the underlying hardware.
Note
Fall-back implementations may not be present for all algorithms.
Definition at line 67 of file hal_crypto.h.
#define HAL_CRY_ENFORCE_FALLBACK FALSE
Makes the driver forcibly use the fall-back implementations.
Definition at line 58 of file hal_crypto.h.
Typedef Documentation
typedef size_t bitsize_t
Size, in bits, of a crypto field or message.
Note
It is assumed, for simplicity, that this type is equivalent to a size_t.
Definition at line 79 of file hal_crypto.h.
Enumeration Type Documentation
enum crystate_t
Driver state machine possible states.
Enumerator
CRY_UNINIT
Not initialized.
CRY_STOP
Stopped.
CRY_READY
Ready.
Definition at line 84 of file hal_crypto.h.
enum cryerror_t
Driver error codes.
Enumerator
CRY_NOERROR
No error.
CRY_ERR_INV_ALGO
Invalid cypher/mode.
CRY_ERR_INV_KEY_SIZE
Invalid key size.
CRY_ERR_INV_KEY_TYPE
Invalid key type.
CRY_ERR_INV_KEY_ID
Invalid key type.
Definition at line 93 of file hal_crypto.h.
enum cryalgorithm_t
Type of an algorithm identifier.
Note
It is only used to determine the key required for operations.
Enumerator
cry_algo_aes
AES 128, 192, 256 bits.
cry_algo_des
DES 56, TDES 112, 168 bits.
Definition at line 105 of file hal_crypto.h.
Function Documentation
void cryInit (void)
Cryptographic Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_crypto.c.
Referenced by halInit().
void cryObjectInit (CRYDriver * cryp)
Initializes the standard part of a CRYDriver structure.
Parameters
[out] cryp pointer to the CRYDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 70 of file hal_crypto.c.
References CRY_STOP.
void cryStart (CRYDriver * cryp, const CRYConfig * config)
Configures and activates the cryptographic peripheral.
Parameters
[in] cryp pointer to the CRYDriver object
[in] config pointer to the CRYConfig object. Depending on the implementation the value can be NULL.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 88 of file hal_crypto.c.
References CRY_READY, CRY_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), and osalSysUnlock().
void cryStop (CRYDriver * cryp)
Deactivates the cryptographic peripheral.
Parameters
[in] cryp pointer to the CRYDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 110 of file hal_crypto.c.
References CRY_READY, CRY_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), and osalSysUnlock().
cryerror_t cryLoadTransientKey (CRYDriver * cryp, cryalgorithm_t algorithm, size_t size, const uint8_t * keyp)
Initializes the transient key for a specific algorithm.
Note
It is the underlying implementation to decide which combinations of algorithm and key size are allowable.
Parameters
[in] cryp pointer to the CRYDriver object
[in] algorithm the algorithm identifier
[in] size key size in bytes
[in] keyp pointer to the key data
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the specified algorithm is unknown or unsupported.
CRY_ERR_INV_KEY_SIZE if the specified key size is invalid for the specified algorithm.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 146 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_NOERROR, HAL_CRY_MAX_KEY_SIZE, and osalDbgCheck.
cryerror_t cryEncryptAES (CRYDriver * cryp, crykey_t key_id, const uint8_t * in, uint8_t * out)
Encryption of a single block using AES.
Note
The implementation of this function must guarantee that it can be called from any context.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 199 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES (CRYDriver * cryp, crykey_t key_id, const uint8_t * in, uint8_t * out)
Decryption of a single block using AES.
Note
The implementation of this function must guarantee that it can be called from any context.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 243 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptAES_ECB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out)
Encryption operation using AES-ECB.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 290 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES_ECB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out)
Decryption operation using AES-ECB.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 340 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptAES_CBC (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Encryption operation using AES-CBC.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
[in] iv 128 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 391 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES_CBC (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Decryption operation using AES-CBC.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
[in] iv 128 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 444 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptAES_CFB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Encryption operation using AES-CFB.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
[in] iv 128 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 497 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES_CFB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Decryption operation using AES-CFB.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
[in] iv 128 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 550 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptAES_CTR (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Encryption operation using AES-CTR.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
[in] iv 128 bits input vector + counter, it contains a 96 bits IV and a 32 bits counter
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 604 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES_CTR (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Decryption operation using AES-CTR.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 16
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
[in] iv 128 bits input vector + counter, it contains a 96 bits IV and a 32 bits counter
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 659 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptAES_GCM (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv, size_t aadsize, const uint8_t * aad, uint8_t * authtag)
Encryption operation using AES-GCM.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of the text buffers, this number must be a multiple of 16
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
[in] iv 128 bits input vector + counter, it contains a 96 bits IV and a 32 bits counter
[in] aadsize size of the authentication data, this number must be a multiple of 16
[in] aad buffer containing the authentication data
[in] authtag 128 bits buffer for the generated authentication tag
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 718 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptAES_GCM (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv, size_t aadsize, const uint8_t * aad, uint8_t * authtag)
Decryption operation using AES-GCM.
Note
The function operates on data buffers whose length is a multiple of an AES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of the text buffers, this number must be a multiple of 16
[in] in buffer for the output cyphertext
[out] out buffer containing the input plaintext
[in] iv 128 bits input vector + counter, it contains a 96 bits IV and a 32 bits counter
[in] aadsize size of the authentication data, this number must be a multiple of 16
[in] aad buffer containing the authentication data
[in] authtag 128 bits buffer for the generated authentication tag
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 786 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptDES (CRYDriver * cryp, crykey_t key_id, const uint8_t * in, uint8_t * out)
Encryption of a single block using (T)DES.
Note
The implementation of this function must guarantee that it can be called from any context.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 845 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptDES (CRYDriver * cryp, crykey_t key_id, const uint8_t * in, uint8_t * out)
Decryption of a single block using (T)DES.
Note
The implementation of this function must guarantee that it can be called from any context.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 890 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptDES_ECB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out)
Encryption operation using (T)DES-ECB.
Note
The function operates on data buffers whose length is a multiple of an DES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 8
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 937 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptDES_ECB (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out)
Decryption operation using (T)DES-ECB.
Note
The function operates on data buffers whose length is a multiple of an DES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 8
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 987 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryEncryptDES_CBC (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Encryption operation using (T)DES-CBC.
Note
The function operates on data buffers whose length is a multiple of an DES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 8
[in] in buffer containing the input plaintext
[out] out buffer for the output cyphertext
[in] iv 64 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1038 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryDecryptDES_CBC (CRYDriver * cryp, crykey_t key_id, size_t size, const uint8_t * in, uint8_t * out, const uint8_t * iv)
Decryption operation using (T)DES-CBC.
Note
The function operates on data buffers whose length is a multiple of an DES block, this means that padding must be done by the caller.
Parameters
[in] cryp pointer to the CRYDriver object
[in] key_id the key to be used for the operation, zero is the transient key, other values are keys stored in an unspecified way
[in] size size of both buffers, this number must be a multiple of 8
[in] in buffer containing the input cyphertext
[out] out buffer for the output plaintext
[in] iv 64 bits input vector
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
CRY_ERR_INV_KEY_TYPE the selected key is invalid for this operation.
CRY_ERR_INV_KEY_ID if the specified key identifier is invalid or refers to an empty key slot.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1091 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t crySHA1 (CRYDriver * cryp, size_t size, const uint8_t * in, uint8_t * out)
Hash using SHA1.
Note
Use of this algorithm is not recommended because proven weak.
Parameters
[in] cryp pointer to the CRYDriver object
[in] size size of input buffer
[in] in buffer containing the input text
[out] out 160 bits output buffer
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1134 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t crySHA256 (CRYDriver * cryp, size_t size, const uint8_t * in, uint8_t * out)
Hash using SHA256.
Parameters
[in] cryp pointer to the CRYDriver object
[in] size size of input buffer
[in] in buffer containing the input text
[out] out 256 bits output buffer
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1169 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t crySHA512 (CRYDriver * cryp, size_t size, const uint8_t * in, uint8_t * out)
Hash using SHA512.
Parameters
[in] cryp pointer to the CRYDriver object
[in] size size of input buffer
[in] in buffer containing the input text
[out] out 512 bits output buffer
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1204 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.
cryerror_t cryTRNG (CRYDriver * cryp, uint8_t * out)
True random numbers generator.
Parameters
[in] cryp pointer to the CRYDriver object
[out] out 128 bits output buffer
Returns
The operation status.
Return values
CRY_NOERROR if the operation succeeded.
CRY_ERR_INV_ALGO if the operation is unsupported on this device instance.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1237 of file hal_crypto.c.
References CRY_ERR_INV_ALGO, CRY_READY, osalDbgAssert, and osalDbgCheck.