ChibiOS/HAL: Serial Driver
Serial Driver
HAL » Normal Drivers
Generic Serial Driver.
Detailed Description
Generic Serial Driver.
This module implements a generic full duplex serial driver. The driver implements a SerialDriver interface and uses I/O Queues for communication between the upper and the lower driver. Event flags are used to notify the application about incoming data, outgoing data and other I/O events.
The module also contains functions that make the implementation of the interrupt service routines much easier.
Precondition
In order to use the SERIAL driver the HAL_USE_SERIAL option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
Macros
#define _serial_driver_data
SerialDriver specific data.
#define USART_CR2_STOP1_BITS (0 << 12)
CR2 1 stop bit value.
#define USART_CR2_STOP0P5_BITS (1 << 12)
CR2 0.5 stop bit value.
#define USART_CR2_STOP2_BITS (2 << 12)
CR2 2 stop bit value.
#define USART_CR2_STOP1P5_BITS (3 << 12)
CR2 1.5 stop bit value.
#define _serial_driver_methods _base_asynchronous_channel_methods
SerialDriver specific methods.
Configuration options
#define STM32_SERIAL_USE_USART1 FALSE
USART1 driver enable switch.
#define STM32_SERIAL_USE_USART2 FALSE
USART2 driver enable switch.
#define STM32_SERIAL_USE_USART3 FALSE
USART3 driver enable switch.
#define STM32_SERIAL_USE_UART4 FALSE
UART4 driver enable switch.
#define STM32_SERIAL_USE_UART5 FALSE
UART5 driver enable switch.
#define STM32_SERIAL_USE_USART6 FALSE
USART6 driver enable switch.
#define STM32_SERIAL_USE_UART7 FALSE
UART7 driver enable switch.
#define STM32_SERIAL_USE_UART8 FALSE
UART8 driver enable switch.
#define STM32_SERIAL_USART1_PRIORITY 12
USART1 interrupt priority level setting.
#define STM32_SERIAL_USART2_PRIORITY 12
USART2 interrupt priority level setting.
#define STM32_SERIAL_USART3_PRIORITY 12
USART3 interrupt priority level setting.
#define STM32_SERIAL_UART4_PRIORITY 12
UART4 interrupt priority level setting.
#define STM32_SERIAL_UART5_PRIORITY 12
UART5 interrupt priority level setting.
#define STM32_SERIAL_USART6_PRIORITY 12
USART6 interrupt priority level setting.
#define STM32_SERIAL_UART7_PRIORITY 12
UART7 interrupt priority level setting.
#define STM32_SERIAL_UART8_PRIORITY 12
UART8 interrupt priority level setting.
Serial status flags
#define SD_PARITY_ERROR (eventflags_t)32
Parity.
#define SD_FRAMING_ERROR (eventflags_t)64
Framing.
#define SD_OVERRUN_ERROR (eventflags_t)128
Overflow.
#define SD_NOISE_ERROR (eventflags_t)256
Line noise.
#define SD_BREAK_DETECTED (eventflags_t)512
LIN Break.
#define SD_QUEUE_FULL_ERROR (eventflags_t)1024
Queue full.
Serial configuration options
#define SERIAL_DEFAULT_BITRATE 38400
Default bit rate.
#define SERIAL_BUFFERS_SIZE 16
Serial buffers size.
Macro Functions
#define sdPutI(sdp, b) oqPutI(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
#define sdPut(sdp, b) oqPut(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
#define sdPutTimeout(sdp, b, t) oqPutTimeout(&(sdp)->oqueue, b, t)
Direct write to a SerialDriver with timeout specification.
#define sdGetI(sdp) iqGetI(&(sdp)->iqueue)
Direct read from a SerialDriver.
#define sdGet(sdp) iqGet(&(sdp)->iqueue)
Direct read from a SerialDriver.
#define sdGetTimeout(sdp, t) iqGetTimeout(&(sdp)->iqueue, t)
Direct read from a SerialDriver with timeout specification.
#define sdWriteI(sdp, b, n) oqWriteI(&(sdp)->oqueue, b, n)
Direct blocking write to a SerialDriver.
#define sdWrite(sdp, b, n) oqWriteTimeout(&(sdp)->oqueue, b, n, TIME_INFINITE)
Direct blocking write to a SerialDriver.
#define sdWriteTimeout(sdp, b, n, t) oqWriteTimeout(&(sdp)->oqueue, b, n, t)
Direct blocking write to a SerialDriver with timeout specification.
#define sdAsynchronousWrite(sdp, b, n) oqWriteTimeout(&(sdp)->oqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking write to a SerialDriver.
#define sdReadI(sdp, b, n) iqReadI(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
#define sdRead(sdp, b, n) iqReadTimeout(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
#define sdReadTimeout(sdp, b, n, t) iqReadTimeout(&(sdp)->iqueue, b, n, t)
Direct blocking read from a SerialDriver with timeout specification.
#define sdAsynchronousRead(sdp, b, n) iqReadTimeout(&(sdp)->iqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking read from a SerialDriver.
Typedefs
typedef struct SerialDriver SerialDriver
Structure representing a serial driver.
Data Structures
struct SerialConfig
STM32 Serial Driver configuration structure.
struct SerialDriverVMT
SerialDriver virtual methods table.
struct SerialDriver
Full duplex serial driver class.
Functions
static void usart_init (SerialDriver *sdp, const SerialConfig *config)
USART initialization.
static void usart_deinit (USART_TypeDef *u)
USART de-initialization.
static void set_error (SerialDriver *sdp, uint16_t sr)
Error handling routine.
static void serve_interrupt (SerialDriver *sdp)
Common IRQ handler.
OSAL_IRQ_HANDLER (STM32_USART1_HANDLER)
USART1 interrupt handler.
OSAL_IRQ_HANDLER (STM32_USART2_HANDLER)
USART2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_USART3_HANDLER)
USART3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_UART4_HANDLER)
UART4 interrupt handler.
OSAL_IRQ_HANDLER (STM32_UART5_HANDLER)
UART5 interrupt handler.
OSAL_IRQ_HANDLER (STM32_USART6_HANDLER)
USART6 interrupt handler.
OSAL_IRQ_HANDLER (STM32_UART7_HANDLER)
UART7 interrupt handler.
OSAL_IRQ_HANDLER (STM32_UART8_HANDLER)
UART8 interrupt handler.
void sd_lld_init (void)
Low level serial driver initialization.
void sd_lld_start (SerialDriver *sdp, const SerialConfig *config)
Low level serial driver configuration and (re)start.
void sd_lld_stop (SerialDriver *sdp)
Low level serial driver stop.
void sdInit (void)
Serial Driver initialization.
void sdObjectInit (SerialDriver *sdp, qnotify_t inotify, qnotify_t onotify)
Initializes a generic full duplex driver object.
void sdStart (SerialDriver *sdp, const SerialConfig *config)
Configures and starts the driver.
void sdStop (SerialDriver *sdp)
Stops the driver.
void sdIncomingDataI (SerialDriver *sdp, uint8_t b)
Handles incoming data.
msg_t sdRequestDataI (SerialDriver *sdp)
Handles outgoing data.
bool sdPutWouldBlock (SerialDriver *sdp)
Direct output check on a SerialDriver.
bool sdGetWouldBlock (SerialDriver *sdp)
Direct input check on a SerialDriver.
msg_t sdControl (SerialDriver *sdp, unsigned int operation, void *arg)
Control operation on a serial port.
Enumerations
Variables
SerialDriver SD1
USART1 serial driver identifier.
SerialDriver SD2
USART2 serial driver identifier.
SerialDriver SD3
USART3 serial driver identifier.
SerialDriver SD4
UART4 serial driver identifier.
SerialDriver SD5
UART5 serial driver identifier.
SerialDriver SD6
USART6 serial driver identifier.
SerialDriver SD7
UART7 serial driver identifier.
SerialDriver SD8
UART8 serial driver identifier.
static const SerialConfig default_config
Driver default configuration.
Macro Definition Documentation
#define STM32_SERIAL_USE_USART1 FALSE
USART1 driver enable switch.
If set to TRUE the support for USART1 is included.
Note
The default is FALSE.
Definition at line 48 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_USART2 FALSE
USART2 driver enable switch.
If set to TRUE the support for USART2 is included.
Note
The default is FALSE.
Definition at line 57 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_USART3 FALSE
USART3 driver enable switch.
If set to TRUE the support for USART3 is included.
Note
The default is FALSE.
Definition at line 66 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_UART4 FALSE
UART4 driver enable switch.
If set to TRUE the support for UART4 is included.
Note
The default is FALSE.
Definition at line 75 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_UART5 FALSE
UART5 driver enable switch.
If set to TRUE the support for UART5 is included.
Note
The default is FALSE.
Definition at line 84 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_USART6 FALSE
USART6 driver enable switch.
If set to TRUE the support for USART6 is included.
Note
The default is FALSE.
Definition at line 93 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_UART7 FALSE
UART7 driver enable switch.
If set to TRUE the support for UART7 is included.
Note
The default is FALSE.
Definition at line 102 of file hal_serial_lld.h.
#define STM32_SERIAL_USE_UART8 FALSE
UART8 driver enable switch.
If set to TRUE the support for UART8 is included.
Note
The default is FALSE.
Definition at line 111 of file hal_serial_lld.h.
#define STM32_SERIAL_USART1_PRIORITY 12
USART1 interrupt priority level setting.
Definition at line 118 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_USART2_PRIORITY 12
USART2 interrupt priority level setting.
Definition at line 125 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_USART3_PRIORITY 12
USART3 interrupt priority level setting.
Definition at line 132 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_UART4_PRIORITY 12
UART4 interrupt priority level setting.
Definition at line 139 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_UART5_PRIORITY 12
UART5 interrupt priority level setting.
Definition at line 146 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_USART6_PRIORITY 12
USART6 interrupt priority level setting.
Definition at line 153 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_UART7_PRIORITY 12
UART7 interrupt priority level setting.
Definition at line 160 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define STM32_SERIAL_UART8_PRIORITY 12
UART8 interrupt priority level setting.
Definition at line 167 of file hal_serial_lld.h.
Referenced by sd_lld_start().
#define _serial_driver_data
Value:
_base_asynchronous_channel_data                                           \
  /* Driver state.*/                                                        \
  sdstate_t                 state;                                          \
  /* Input queue.*/                                                         \
  input_queue_t             iqueue;                                         \
  /* Output queue.*/                                                        \
  output_queue_t            oqueue;                                         \
  /* Input circular buffer.*/                                               \
  uint8_t                   ib[SERIAL_BUFFERS_SIZE];                        \
  /* Output circular buffer.*/                                              \
  uint8_t                   ob[SERIAL_BUFFERS_SIZE];                        \
  /* End of the mandatory fields.*/                                         \
  /* Pointer to the USART registers block.*/                                \
  USART_TypeDef             *usart;                                         \
  /* Mask to be applied on received frames.*/                               \
  uint8_t                   rxmask;
SerialDriver specific data.
Definition at line 289 of file hal_serial_lld.h.
#define USART_CR2_STOP1_BITS (0 << 12)
CR2 1 stop bit value.
Definition at line 314 of file hal_serial_lld.h.
#define USART_CR2_STOP0P5_BITS (1 << 12)
CR2 0.5 stop bit value.
Definition at line 315 of file hal_serial_lld.h.
#define USART_CR2_STOP2_BITS (2 << 12)
CR2 2 stop bit value.
Definition at line 316 of file hal_serial_lld.h.
#define USART_CR2_STOP1P5_BITS (3 << 12)
CR2 1.5 stop bit value.
Definition at line 317 of file hal_serial_lld.h.
#define SD_PARITY_ERROR (eventflags_t)32
Parity.
Definition at line 38 of file hal_serial.h.
Referenced by set_error().
#define SD_FRAMING_ERROR (eventflags_t)64
Framing.
Definition at line 39 of file hal_serial.h.
Referenced by set_error().
#define SD_OVERRUN_ERROR (eventflags_t)128
Overflow.
Definition at line 40 of file hal_serial.h.
Referenced by set_error().
#define SD_NOISE_ERROR (eventflags_t)256
Line noise.
Definition at line 41 of file hal_serial.h.
Referenced by set_error().
#define SD_BREAK_DETECTED (eventflags_t)512
LIN Break.
Definition at line 42 of file hal_serial.h.
Referenced by serve_interrupt().
#define SD_QUEUE_FULL_ERROR (eventflags_t)1024
Queue full.
Definition at line 43 of file hal_serial.h.
Referenced by sdIncomingDataI().
#define SERIAL_DEFAULT_BITRATE 38400
Default bit rate.
Configuration parameter, this is the baud rate selected for the default configuration.
Definition at line 60 of file hal_serial.h.
#define SERIAL_BUFFERS_SIZE 16
Serial buffers size.
Configuration parameter, you can change the depth of the queue buffers depending on the requirements of your application.
Note
The default is 16 bytes for both the transmission and receive buffers.
This is a global setting and it can be overridden by low level driver specific settings.
Definition at line 73 of file hal_serial.h.
Referenced by sdObjectInit().
#define _serial_driver_methods _base_asynchronous_channel_methods
SerialDriver specific methods.
Definition at line 104 of file hal_serial.h.
#define sdPutI (sdp, b) oqPutI(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
Note
This function bypasses the indirect access to the channel and writes directly on the output queue. This is faster but cannot be used to write to different channels implementations.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 145 of file hal_serial.h.
#define sdPut (sdp, b) oqPut(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
Note
This function bypasses the indirect access to the channel and writes directly on the output queue. This is faster but cannot be used to write to different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 155 of file hal_serial.h.
#define sdPutTimeout (sdp, b, t) oqPutTimeout(&(sdp)->oqueue, b, t)
Direct write to a SerialDriver with timeout specification.
Note
This function bypasses the indirect access to the channel and writes directly on the output queue. This is faster but cannot be used to write to different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 165 of file hal_serial.h.
#define sdGetI (sdp) iqGetI(&(sdp)->iqueue)
Direct read from a SerialDriver.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 175 of file hal_serial.h.
#define sdGet (sdp) iqGet(&(sdp)->iqueue)
Direct read from a SerialDriver.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 185 of file hal_serial.h.
#define sdGetTimeout (sdp, t) iqGetTimeout(&(sdp)->iqueue, t)
Direct read from a SerialDriver with timeout specification.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 195 of file hal_serial.h.
#define sdWriteI (sdp, b, n) oqWriteI(&(sdp)->oqueue, b, n)
Direct blocking write to a SerialDriver.
Note
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write from different channels implementations.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 205 of file hal_serial.h.
#define sdWrite (sdp, b, n) oqWriteTimeout(&(sdp)->oqueue, b, n, TIME_INFINITE)
Direct blocking write to a SerialDriver.
Note
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 215 of file hal_serial.h.
#define sdWriteTimeout (sdp, b, n, t) oqWriteTimeout(&(sdp)->oqueue, b, n, t)
Direct blocking write to a SerialDriver with timeout specification.
Note
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write to different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 226 of file hal_serial.h.
#define sdAsynchronousWrite (sdp, b, n) oqWriteTimeout(&(sdp)->oqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking write to a SerialDriver.
Note
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write to different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 237 of file hal_serial.h.
#define sdReadI (sdp, b, n) iqReadI(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 248 of file hal_serial.h.
#define sdRead (sdp, b, n) iqReadTimeout(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 258 of file hal_serial.h.
#define sdReadTimeout (sdp, b, n, t) iqReadTimeout(&(sdp)->iqueue, b, n, t)
Direct blocking read from a SerialDriver with timeout specification.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 269 of file hal_serial.h.
#define sdAsynchronousRead (sdp, b, n) iqReadTimeout(&(sdp)->iqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking read from a SerialDriver.
Note
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 279 of file hal_serial.h.
Typedef Documentation
typedef struct SerialDriver SerialDriver
Structure representing a serial driver.
Definition at line 97 of file hal_serial.h.
Enumeration Type Documentation
enum sdstate_t
Driver state machine possible states.
Enumerator
SD_UNINIT
Not initialized.
SD_STOP
Stopped.
SD_READY
Ready.
Definition at line 88 of file hal_serial.h.
Function Documentation
static void usart_init (SerialDriver * sdp, const SerialConfig * config) static
USART initialization.
This function must be invoked with interrupts disabled.
Parameters
[in] sdp pointer to a SerialDriver object
[in] config the architecture-dependent serial driver configuration
Definition at line 101 of file hal_serial_lld.c.
References SerialConfig::cr1, SerialConfig::cr2, SerialConfig::cr3, SerialConfig::speed, STM32_PCLK1, and STM32_PCLK2.
Referenced by sd_lld_start().
static void usart_deinit (USART_TypeDef * u) static
USART de-initialization.
This function must be invoked with interrupts disabled.
Parameters
[in] u pointer to an USART I/O block
Definition at line 140 of file hal_serial_lld.c.
Referenced by sd_lld_stop().
static void set_error (SerialDriver * sdp, uint16_t sr) static
Error handling routine.
Parameters
[in] sdp pointer to a SerialDriver object
[in] sr USART SR register value
Definition at line 153 of file hal_serial_lld.c.
References chnAddFlagsI, SD_FRAMING_ERROR, SD_NOISE_ERROR, SD_OVERRUN_ERROR, and SD_PARITY_ERROR.
Referenced by serve_interrupt().
static void serve_interrupt (SerialDriver * sdp) static
Common IRQ handler.
Parameters
[in] sdp communication channel associated to the USART
Definition at line 172 of file hal_serial_lld.c.
References CHN_OUTPUT_EMPTY, CHN_TRANSMISSION_END, chnAddFlagsI, oqGetI(), oqIsEmptyI, osalSysLockFromISR(), osalSysUnlockFromISR(), SD_BREAK_DETECTED, sdIncomingDataI(), and set_error().
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_USART1_HANDLER)
USART1 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 303 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_USART2_HANDLER)
USART2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 322 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_USART3_HANDLER)
USART3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 341 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_UART4_HANDLER)
UART4 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 360 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_UART5_HANDLER)
UART5 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 379 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_USART6_HANDLER)
USART6 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 398 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_UART7_HANDLER)
UART7 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 417 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
OSAL_IRQ_HANDLER (STM32_UART8_HANDLER)
UART8 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 436 of file hal_serial_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_interrupt().
void sd_lld_init (void)
Low level serial driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 455 of file hal_serial_lld.c.
References sdObjectInit().
Referenced by sdInit().
void sd_lld_start (SerialDriver * sdp, const SerialConfig * config)
Low level serial driver configuration and (re)start.
Parameters
[in] sdp pointer to a SerialDriver object
[in] config the architecture-dependent serial driver configuration. If this parameter is set to NULL then a default configuration is used.
Function Class:
Not an API, this function is for internal use only.
Definition at line 508 of file hal_serial_lld.c.
References default_config, rccEnableUART4, rccEnableUART5, rccEnableUSART1, rccEnableUSART2, rccEnableUSART3, SD_STOP, STM32_SERIAL_UART4_PRIORITY, STM32_SERIAL_UART5_PRIORITY, STM32_SERIAL_UART7_PRIORITY, STM32_SERIAL_UART8_PRIORITY, STM32_SERIAL_USART1_PRIORITY, STM32_SERIAL_USART2_PRIORITY, STM32_SERIAL_USART3_PRIORITY, STM32_SERIAL_USART6_PRIORITY, and usart_init().
Referenced by sdStart().
void sd_lld_stop (SerialDriver * sdp)
Low level serial driver stop.
De-initializes the USART, stops the associated clock, resets the interrupt vector.
Parameters
[in] sdp pointer to a SerialDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 575 of file hal_serial_lld.c.
References rccDisableUART4, rccDisableUART5, rccDisableUSART1, rccDisableUSART2, rccDisableUSART3, SD_READY, and usart_deinit().
Referenced by sdStop().
void sdInit (void)
Serial Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 134 of file hal_serial.c.
References sd_lld_init().
Referenced by halInit().
void sdObjectInit (SerialDriver * sdp, qnotify_t inotify, qnotify_t onotify)
Initializes a generic full duplex driver object.
The HW dependent part of the initialization has to be performed outside, usually in the hardware initialization code.
Parameters
[out] sdp pointer to a SerialDriver structure
[in] inotify pointer to a callback function that is invoked when some data is read from the Queue. The value can be NULL.
[in] onotify pointer to a callback function that is invoked when some data is written in the Queue. The value can be NULL.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 157 of file hal_serial.c.
References iqObjectInit(), oqObjectInit(), osalEventObjectInit(), SD_STOP, SERIAL_BUFFERS_SIZE, and SerialDriver::vmt.
Referenced by sd_lld_init().
void sdStart (SerialDriver * sdp, const SerialConfig * config)
Configures and starts the driver.
Parameters
[in] sdp pointer to a SerialDriver object
[in] config the architecture-dependent serial driver configuration. If this parameter is set to NULL then a default configuration is used.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 184 of file hal_serial.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), sd_lld_start(), SD_READY, and SD_STOP.
void sdStop (SerialDriver * sdp)
Stops the driver.
Any thread waiting on the driver's queues will be awakened with the message MSG_RESET.
Parameters
[in] sdp pointer to a SerialDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 205 of file hal_serial.c.
References iqResetI(), oqResetI(), osalDbgAssert, osalDbgCheck, osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), sd_lld_stop(), SD_READY, and SD_STOP.
void sdIncomingDataI (SerialDriver * sdp, uint8_t b)
Handles incoming data.
This function must be called from the input interrupt service routine in order to enqueue incoming data and generate the related events.
Note
The incoming data event is only generated when the input queue becomes non-empty.
In order to gain some performance it is suggested to not use this function directly but copy this code directly into the interrupt service routine.
Parameters
[in] sdp pointer to a SerialDriver structure
[in] b the byte to be written in the driver's Input Queue
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 239 of file hal_serial.c.
References CHN_INPUT_AVAILABLE, chnAddFlagsI, iqIsEmptyI, iqPutI(), osalDbgCheck, osalDbgCheckClassI, and SD_QUEUE_FULL_ERROR.
Referenced by serve_interrupt().
msg_t sdRequestDataI (SerialDriver * sdp)
Handles outgoing data.
Must be called from the output interrupt service routine in order to get the next byte to be transmitted.
Note
In order to gain some performance it is suggested to not use this function directly but copy this code directly into the interrupt service routine.
Parameters
[in] sdp pointer to a SerialDriver structure
Returns
The byte value read from the driver's output queue.
Return values
MSG_TIMEOUT if the queue is empty (the lower driver usually disables the interrupt source when this happens).
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 265 of file hal_serial.c.
References CHN_OUTPUT_EMPTY, chnAddFlagsI, oqGetI(), osalDbgCheck, and osalDbgCheckClassI.
bool sdPutWouldBlock (SerialDriver * sdp)
Direct output check on a SerialDriver.
Note
This function bypasses the indirect access to the channel and checks directly the output queue. This is faster but cannot be used to check different channels implementations.
Parameters
[in] sdp pointer to a SerialDriver structure
Returns
The queue status.
Return values
false if the next write operation would not block.
true if the next write operation would block.
Deprecated:
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 292 of file hal_serial.c.
References oqIsFullI, osalSysLock(), and osalSysUnlock().
bool sdGetWouldBlock (SerialDriver * sdp)
Direct input check on a SerialDriver.
Note
This function bypasses the indirect access to the channel and checks directly the input queue. This is faster but cannot be used to check different channels implementations.
Parameters
[in] sdp pointer to a SerialDriver structure
Returns
The queue status.
Return values
false if the next write operation would not block.
true if the next write operation would block.
Deprecated:
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 317 of file hal_serial.c.
References iqIsEmptyI, osalSysLock(), and osalSysUnlock().
msg_t sdControl (SerialDriver * sdp, unsigned int operation, void * arg)
Control operation on a serial port.
Parameters
[in] sdp pointer to a SerialDriver object
[in] operation control operation code
[in,out] arg operation argument
Returns
The control operation status.
Return values
MSG_OK in case of success.
MSG_TIMEOUT in case of operation timeout.
MSG_RESET in case of operation reset.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 341 of file hal_serial.c.
Variable Documentation
SerialDriver SD1
USART1 serial driver identifier.
Definition at line 39 of file hal_serial_lld.c.
SerialDriver SD2
USART2 serial driver identifier.
Definition at line 44 of file hal_serial_lld.c.
SerialDriver SD3
USART3 serial driver identifier.
Definition at line 49 of file hal_serial_lld.c.
SerialDriver SD4
UART4 serial driver identifier.
Definition at line 54 of file hal_serial_lld.c.
SerialDriver SD5
UART5 serial driver identifier.
Definition at line 59 of file hal_serial_lld.c.
SerialDriver SD6
USART6 serial driver identifier.
Definition at line 64 of file hal_serial_lld.c.
SerialDriver SD7
UART7 serial driver identifier.
Definition at line 69 of file hal_serial_lld.c.
SerialDriver SD8
UART8 serial driver identifier.
Definition at line 74 of file hal_serial_lld.c.
const SerialConfig default_config static
Initial value:
=
{
  SERIAL_DEFAULT_BITRATE,
  0,
  USART_CR2_STOP1_BITS,
  0
}
Driver default configuration.
Definition at line 82 of file hal_serial_lld.c.
Referenced by sd_lld_start().