ChibiOS/HAL: ST Driver
ST Driver
HAL » Normal Drivers
Generic System Tick Driver.
Detailed Description
Generic System Tick Driver.
This module implements a system tick timer in order to support the underlying operating system.
Configuration options
#define STM32_ST_IRQ_PRIORITY 8
SysTick timer IRQ priority.
#define STM32_ST_USE_TIMER 2
TIMx unit (by number) to be used for free running operations.
Macro Functions
#define stGetCounter() st_lld_get_counter()
Returns the time counter value.
#define stIsAlarmActive() st_lld_is_alarm_active()
Determines if the alarm is active.
Functions
OSAL_IRQ_HANDLER (SysTick_Handler)
System Timer vector.
OSAL_IRQ_HANDLER (ST_HANDLER)
TIM2 interrupt handler.
void st_lld_init (void)
Low level ST driver initialization.
static systime_t st_lld_get_counter (void)
Returns the time counter value.
static void st_lld_start_alarm (systime_t time)
Starts the alarm.
static void st_lld_stop_alarm (void)
Stops the alarm interrupt.
static void st_lld_set_alarm (systime_t time)
Sets the alarm time.
static systime_t st_lld_get_alarm (void)
Returns the current alarm time.
static bool st_lld_is_alarm_active (void)
Determines if the alarm is active.
void stInit (void)
ST Driver initialization.
void stStartAlarm (systime_t abstime)
Starts the alarm.
void stStopAlarm (void)
Stops the alarm interrupt.
void stSetAlarm (systime_t abstime)
Sets the alarm time.
systime_t stGetAlarm (void)
Returns the current alarm time.
Macro Definition Documentation
#define STM32_ST_IRQ_PRIORITY 8
SysTick timer IRQ priority.
Definition at line 50 of file hal_st_lld.h.
Referenced by st_lld_init().
#define STM32_ST_USE_TIMER 2
TIMx unit (by number) to be used for free running operations.
Note
You must select a 32 bits timer if a 32 bits systick_t type is required.
Timers 2, 3, 4 and 5 are supported.
Definition at line 60 of file hal_st_lld.h.
#define stGetCounter () st_lld_get_counter()
Returns the time counter value.
Note
This functionality is only available in free running mode, the behaviour in periodic mode is undefined.
Returns
The counter value.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 65 of file hal_st.h.
#define stIsAlarmActive () st_lld_is_alarm_active()
Determines if the alarm is active.
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 76 of file hal_st.h.
Referenced by stGetAlarm(), stSetAlarm(), and stStartAlarm().
Function Documentation
OSAL_IRQ_HANDLER (SysTick_Handler)
System Timer vector.
This interrupt is used for system tick in periodic mode.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 234 of file hal_st_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, osalOsTimerHandlerI(), osalSysLockFromISR(), and osalSysUnlockFromISR().
OSAL_IRQ_HANDLER (ST_HANDLER)
TIM2 interrupt handler.
This interrupt is used for system tick in free running mode.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 253 of file hal_st_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, osalOsTimerHandlerI(), osalSysLockFromISR(), and osalSysUnlockFromISR().
void st_lld_init (void)
Low level ST driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 281 of file hal_st_lld.c.
References OSAL_ST_FREQUENCY, and STM32_ST_IRQ_PRIORITY.
Referenced by stInit().
static systime_t st_lld_get_counter (void) inline static
Returns the time counter value.
Returns
The counter value.
Function Class:
Not an API, this function is for internal use only.
Definition at line 139 of file hal_st_lld.h.
static void st_lld_start_alarm (systime_t time) inline static
Starts the alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
Parameters
[in] time the time to be set for the first alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 153 of file hal_st_lld.h.
Referenced by stStartAlarm().
static void st_lld_stop_alarm (void) inline static
Stops the alarm interrupt.
Function Class:
Not an API, this function is for internal use only.
Definition at line 165 of file hal_st_lld.h.
Referenced by stStopAlarm().
static void st_lld_set_alarm (systime_t time) inline static
Sets the alarm time.
Parameters
[in] time the time to be set for the next alarm
Function Class:
Not an API, this function is for internal use only.
Definition at line 177 of file hal_st_lld.h.
Referenced by stSetAlarm().
static systime_t st_lld_get_alarm (void) inline static
Returns the current alarm time.
Returns
The currently set alarm time.
Function Class:
Not an API, this function is for internal use only.
Definition at line 189 of file hal_st_lld.h.
Referenced by stGetAlarm().
static bool st_lld_is_alarm_active (void) inline static
Determines if the alarm is active.
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:
Not an API, this function is for internal use only.
Definition at line 203 of file hal_st_lld.h.
void stInit (void)
ST Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 60 of file hal_st.c.
References st_lld_init().
Referenced by halInit().
void stStartAlarm (systime_t abstime)
Starts the alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] abstime the time to be set for the first alarm
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 76 of file hal_st.c.
References osalDbgAssert, st_lld_start_alarm(), and stIsAlarmActive.
void stStopAlarm (void)
Stops the alarm interrupt.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 90 of file hal_st.c.
References st_lld_stop_alarm().
void stSetAlarm (systime_t abstime)
Sets the alarm time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] abstime the time to be set for the next alarm
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 104 of file hal_st.c.
References osalDbgAssert, st_lld_set_alarm(), and stIsAlarmActive.
systime_t stGetAlarm (void)
Returns the current alarm time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Returns
The currently set alarm time.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 120 of file hal_st.c.
References osalDbgAssert, st_lld_get_alarm(), and stIsAlarmActive.