ChibiOS/HAL: I2C Driver
I2C Driver
HAL » Normal Drivers
Generic I2C Driver.
Detailed Description
Generic I2C Driver.
This module implements a generic I2C (Inter-Integrated Circuit) driver.
Precondition
In order to use the I2C driver the HAL_USE_I2C option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
The driver is not thread safe for performance reasons, if you need to access the I2C bus from multiple threads then use the i2cAcquireBus() and i2cReleaseBus() APIs in order to gain exclusive access.
Macros
#define I2C_CLK_FREQ ((STM32_PCLK1) / 1000000)
Peripheral clock frequency.
#define STM32_DMA_REQUIRED
error checks
#define i2c_lld_get_errors(i2cp) ((i2cp)->errors)
Get errors from I2C driver.
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
#define _i2c_wakeup_isr(i2cp)
Wakes up the waiting thread notifying no errors.
#define _i2c_wakeup_error_isr(i2cp)
Wakes up the waiting thread notifying errors.
#define i2cMasterTransmit(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
#define i2cMasterReceive(i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
Configuration options
#define STM32_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
#define STM32_I2C_USE_I2C2 FALSE
I2C2 driver enable switch.
#define STM32_I2C_USE_I2C3 FALSE
I2C3 driver enable switch.
#define STM32_I2C_BUSY_TIMEOUT 50
I2C timeout on busy condition in milliseconds.
#define STM32_I2C_I2C1_IRQ_PRIORITY 10
I2C1 interrupt priority level setting.
#define STM32_I2C_I2C2_IRQ_PRIORITY 10
I2C2 interrupt priority level setting.
#define STM32_I2C_I2C3_IRQ_PRIORITY 10
I2C3 interrupt priority level setting.
#define STM32_I2C_I2C1_DMA_PRIORITY 1
I2C1 DMA priority (0..3|lowest..highest).
#define STM32_I2C_I2C2_DMA_PRIORITY 1
I2C2 DMA priority (0..3|lowest..highest).
#define STM32_I2C_I2C3_DMA_PRIORITY 1
I2C3 DMA priority (0..3|lowest..highest).
#define STM32_I2C_DMA_ERROR_HOOK(i2cp) osalSysHalt("DMA failure")
I2C DMA error hook.
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 0)
DMA stream used for I2C1 RX operations.
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
DMA stream used for I2C1 TX operations.
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
DMA stream used for I2C2 RX operations.
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
DMA stream used for I2C2 TX operations.
#define STM32_I2C_I2C3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
DMA stream used for I2C3 RX operations.
#define STM32_I2C_I2C3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
DMA stream used for I2C3 TX operations.
I2C bus error conditions
#define I2C_NO_ERROR 0x00
No error.
#define I2C_BUS_ERROR 0x01
Bus Error.
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
#define I2C_OVERRUN 0x08
Overrun/Underrun.
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
#define I2C_TIMEOUT 0x20
Hardware timeout.
#define I2C_SMB_ALERT 0x40
SMBus Alert.
Typedefs
typedef uint16_t i2caddr_t
Type representing an I2C address.
typedef uint32_t i2cflags_t
Type of I2C driver condition flags.
typedef struct I2CDriver I2CDriver
Type of a structure representing an I2C driver.
Data Structures
struct I2CConfig
Type of I2C driver configuration structure.
struct I2CDriver
Structure representing an I2C driver.
Functions
static void i2c_lld_abort_operation (I2CDriver *i2cp)
Aborts an I2C transaction.
static void i2c_lld_set_clock (I2CDriver *i2cp)
Set clock speed.
static void i2c_lld_set_opmode (I2CDriver *i2cp)
Set operation mode of I2C hardware.
static void i2c_lld_serve_event_interrupt (I2CDriver *i2cp)
I2C shared ISR code.
static void i2c_lld_serve_rx_end_irq (I2CDriver *i2cp, uint32_t flags)
DMA RX end IRQ handler.
static void i2c_lld_serve_tx_end_irq (I2CDriver *i2cp, uint32_t flags)
DMA TX end IRQ handler.
static void i2c_lld_serve_error_interrupt (I2CDriver *i2cp, uint16_t sr)
I2C error handler.
OSAL_IRQ_HANDLER (STM32_I2C1_EVENT_HANDLER)
I2C1 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C1_ERROR_HANDLER)
I2C1 error interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C2_EVENT_HANDLER)
I2C2 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C2_ERROR_HANDLER)
I2C2 error interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C3_EVENT_HANDLER)
I2C3 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C3_ERROR_HANDLER)
I2C3 error interrupt handler.
void i2c_lld_init (void)
Low level I2C driver initialization.
void i2c_lld_start (I2CDriver *i2cp)
Configures and activates the I2C peripheral.
void i2c_lld_stop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
msg_t i2c_lld_master_receive_timeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
msg_t i2c_lld_master_transmit_timeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
void i2cInit (void)
I2C Driver initialization.
void i2cObjectInit (I2CDriver *i2cp)
Initializes the standard part of a I2CDriver structure.
void i2cStart (I2CDriver *i2cp, const I2CConfig *config)
Configures and activates the I2C peripheral.
void i2cStop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
i2cflags_t i2cGetErrors (I2CDriver *i2cp)
Returns the errors mask associated to the previous operation.
msg_t i2cMasterTransmitTimeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
msg_t i2cMasterReceiveTimeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
void i2cAcquireBus (I2CDriver *i2cp)
Gains exclusive access to the I2C bus.
void i2cReleaseBus (I2CDriver *i2cp)
Releases exclusive access to the I2C bus.
Enumerations
Variables
I2CDriver I2CD1
I2C1 driver identifier.
I2CDriver I2CD2
I2C2 driver identifier.
I2CDriver I2CD3
I2C3 driver identifier.
Macro Definition Documentation
#define I2C_CLK_FREQ ((STM32_PCLK1) / 1000000)
Peripheral clock frequency.
Definition at line 41 of file hal_i2c_lld.h.
Referenced by i2c_lld_set_clock().
#define STM32_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
If set to TRUE the support for I2C1 is included.
Note
The default is FALSE.
Definition at line 57 of file hal_i2c_lld.h.
#define STM32_I2C_USE_I2C2 FALSE
I2C2 driver enable switch.
If set to TRUE the support for I2C2 is included.
Note
The default is FALSE.
Definition at line 66 of file hal_i2c_lld.h.
#define STM32_I2C_USE_I2C3 FALSE
I2C3 driver enable switch.
If set to TRUE the support for I2C3 is included.
Note
The default is FALSE.
Definition at line 75 of file hal_i2c_lld.h.
#define STM32_I2C_BUSY_TIMEOUT 50
I2C timeout on busy condition in milliseconds.
Definition at line 82 of file hal_i2c_lld.h.
Referenced by i2c_lld_master_receive_timeout(), and i2c_lld_master_transmit_timeout().
#define STM32_I2C_I2C1_IRQ_PRIORITY 10
I2C1 interrupt priority level setting.
Definition at line 89 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_I2C2_IRQ_PRIORITY 10
I2C2 interrupt priority level setting.
Definition at line 96 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_I2C3_IRQ_PRIORITY 10
I2C3 interrupt priority level setting.
Definition at line 103 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_I2C1_DMA_PRIORITY 1
I2C1 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 113 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_I2C2_DMA_PRIORITY 1
I2C2 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 123 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_I2C3_DMA_PRIORITY 1
I2C3 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 133 of file hal_i2c_lld.h.
Referenced by i2c_lld_start().
#define STM32_I2C_DMA_ERROR_HOOK (i2cp) osalSysHalt("DMA failure")
I2C DMA error hook.
Note
The default action for DMA errors is a system halt because DMA error can only happen because programming errors.
Definition at line 142 of file hal_i2c_lld.h.
Referenced by i2c_lld_serve_rx_end_irq(), and i2c_lld_serve_tx_end_irq().
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 0)
DMA stream used for I2C1 RX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 152 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
DMA stream used for I2C1 TX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 160 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
DMA stream used for I2C2 RX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 168 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
DMA stream used for I2C2 TX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 176 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_I2C_I2C3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
DMA stream used for I2C3 RX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 184 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_I2C_I2C3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
DMA stream used for I2C3 TX operations.
Note
This option is only available on platforms with enhanced DMA.
Definition at line 192 of file hal_i2c_lld.h.
Referenced by i2c_lld_init().
#define STM32_DMA_REQUIRED
error checks
Definition at line 320 of file hal_i2c_lld.h.
#define i2c_lld_get_errors (i2cp) ((i2cp)->errors)
Get errors from I2C driver.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 472 of file hal_i2c_lld.h.
Referenced by i2cGetErrors().
#define I2C_NO_ERROR 0x00
No error.
Definition at line 43 of file hal_i2c.h.
Referenced by i2c_lld_master_receive_timeout(), i2c_lld_master_transmit_timeout(), i2c_lld_serve_error_interrupt(), i2cMasterReceiveTimeout(), and i2cMasterTransmitTimeout().
#define I2C_BUS_ERROR 0x01
Bus Error.
Definition at line 44 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
Definition at line 45 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
Definition at line 46 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_OVERRUN 0x08
Overrun/Underrun.
Definition at line 47 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
Definition at line 48 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_TIMEOUT 0x20
Hardware timeout.
Definition at line 51 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_SMB_ALERT 0x40
SMBus Alert.
Definition at line 52 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
Definition at line 63 of file hal_i2c.h.
#define _i2c_wakeup_isr (i2cp)
Value:
do {                                          \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
} while(0)
Wakes up the waiting thread notifying no errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 99 of file hal_i2c.h.
Referenced by i2c_lld_serve_event_interrupt(), and i2c_lld_serve_rx_end_irq().
#define _i2c_wakeup_error_isr (i2cp)
Value:
do {                                    \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_RESET);                            \
  osalSysUnlockFromISR();                                                   \
} while(0)
Wakes up the waiting thread notifying errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 112 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
#define i2cMasterTransmit (i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Value:
(i2cMasterTransmitTimeout(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes,     \
                            TIME_INFINITE))
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 122 of file hal_i2c.h.
#define i2cMasterReceive (i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 130 of file hal_i2c.h.
Typedef Documentation
typedef uint16_t i2caddr_t
Type representing an I2C address.
Definition at line 362 of file hal_i2c_lld.h.
typedef uint32_t i2cflags_t
Type of I2C driver condition flags.
Definition at line 367 of file hal_i2c_lld.h.
typedef struct I2CDriver I2CDriver
Type of a structure representing an I2C driver.
Definition at line 403 of file hal_i2c_lld.h.
Enumeration Type Documentation
enum i2copmode_t
Supported modes for the I2C bus.
Definition at line 372 of file hal_i2c_lld.h.
enum i2cdutycycle_t
Supported duty cycle modes for the I2C bus.
Definition at line 381 of file hal_i2c_lld.h.
enum i2cstate_t
Driver state machine possible states.
Enumerator
I2C_UNINIT
Not initialized.
I2C_STOP
Stopped.
I2C_READY
Ready.
I2C_ACTIVE_TX
Transmitting.
I2C_ACTIVE_RX
Receiving.
Definition at line 77 of file hal_i2c.h.
Function Documentation
static void i2c_lld_abort_operation (I2CDriver * i2cp) static
Aborts an I2C transaction.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 122 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamDisable, I2CDriver::dmatx, and I2CDriver::i2c.
Referenced by i2c_lld_stop().
static void i2c_lld_set_clock (I2CDriver * i2cp) static
Set clock speed.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 143 of file hal_i2c_lld.c.
References I2CConfig::clock_speed, I2CDriver::config, I2CConfig::duty_cycle, I2CDriver::i2c, I2C_CLK_FREQ, osalDbgAssert, osalDbgCheck, and STM32_PCLK1.
Referenced by i2c_lld_start().
static void i2c_lld_set_opmode (I2CDriver * i2cp) static
Set operation mode of I2C hardware.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 217 of file hal_i2c_lld.c.
References I2CDriver::config, I2CDriver::i2c, and I2CConfig::op_mode.
Referenced by i2c_lld_start().
static void i2c_lld_serve_event_interrupt (I2CDriver * i2cp) static
I2C shared ISR code.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 245 of file hal_i2c_lld.c.
References _i2c_wakeup_isr, I2CDriver::addr, I2CDriver::dmarx, dmaStreamEnable, dmaStreamGetTransactionSize, I2CDriver::dmatx, and I2CDriver::i2c.
Referenced by OSAL_IRQ_HANDLER().
static void i2c_lld_serve_rx_end_irq (I2CDriver * i2cp, uint32_t flags) static
DMA RX end IRQ handler.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] flags pre-shifted content of the ISR register
Function Class:
Not an API, this function is for internal use only.
Definition at line 305 of file hal_i2c_lld.c.
References _i2c_wakeup_isr, I2CDriver::dmarx, dmaStreamDisable, I2CDriver::i2c, and STM32_I2C_DMA_ERROR_HOOK.
Referenced by i2c_lld_start().
static void i2c_lld_serve_tx_end_irq (I2CDriver * i2cp, uint32_t flags) static
DMA TX end IRQ handler.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 332 of file hal_i2c_lld.c.
References dmaStreamDisable, I2CDriver::dmatx, I2CDriver::i2c, and STM32_I2C_DMA_ERROR_HOOK.
Referenced by i2c_lld_start().
static void i2c_lld_serve_error_interrupt (I2CDriver * i2cp, uint16_t sr) static
I2C error handler.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] sr content of the SR1 register to be decoded
Function Class:
Not an API, this function is for internal use only.
Definition at line 359 of file hal_i2c_lld.c.
References _i2c_wakeup_error_isr, I2CDriver::dmarx, dmaStreamDisable, I2CDriver::dmatx, I2CDriver::errors, I2CDriver::i2c, I2C_ACK_FAILURE, I2C_ARBITRATION_LOST, I2C_BUS_ERROR, I2C_NO_ERROR, I2C_OVERRUN, I2C_PEC_ERROR, I2C_SMB_ALERT, and I2C_TIMEOUT.
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_I2C1_EVENT_HANDLER)
I2C1 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 406 of file hal_i2c_lld.c.
References i2c_lld_serve_event_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_I2C1_ERROR_HANDLER)
I2C1 error interrupt handler.
Definition at line 418 of file hal_i2c_lld.c.
References I2CDriver::i2c, i2c_lld_serve_error_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_I2C2_EVENT_HANDLER)
I2C2 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 436 of file hal_i2c_lld.c.
References i2c_lld_serve_event_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_I2C2_ERROR_HANDLER)
I2C2 error interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 450 of file hal_i2c_lld.c.
References I2CDriver::i2c, i2c_lld_serve_error_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_I2C3_EVENT_HANDLER)
I2C3 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 468 of file hal_i2c_lld.c.
References i2c_lld_serve_event_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_I2C3_ERROR_HANDLER)
I2C3 error interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 482 of file hal_i2c_lld.c.
References I2CDriver::i2c, i2c_lld_serve_error_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
void i2c_lld_init (void)
Low level I2C driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 503 of file hal_i2c_lld.c.
References I2CDriver::dmarx, I2CDriver::dmatx, I2CDriver::i2c, i2cObjectInit(), STM32_DMA_STREAM, STM32_I2C_I2C1_RX_DMA_STREAM, STM32_I2C_I2C1_TX_DMA_STREAM, STM32_I2C_I2C2_RX_DMA_STREAM, STM32_I2C_I2C2_TX_DMA_STREAM, STM32_I2C_I2C3_RX_DMA_STREAM, STM32_I2C_I2C3_TX_DMA_STREAM, and I2CDriver::thread.
Referenced by i2cInit().
void i2c_lld_start (I2CDriver * i2cp)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 537 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamAllocate(), dmaStreamSetPeripheral, I2CDriver::dmatx, I2CDriver::i2c, i2c_lld_serve_rx_end_irq(), i2c_lld_serve_tx_end_irq(), i2c_lld_set_clock(), i2c_lld_set_opmode(), I2C_STOP, osalDbgAssert, rccEnableI2C1, rccEnableI2C2, rccResetI2C1, rccResetI2C2, I2CDriver::rxdmamode, I2CDriver::state, STM32_DMA_CR_DMEIE, STM32_I2C_I2C1_DMA_PRIORITY, STM32_I2C_I2C1_IRQ_PRIORITY, STM32_I2C_I2C2_DMA_PRIORITY, STM32_I2C_I2C2_IRQ_PRIORITY, STM32_I2C_I2C3_DMA_PRIORITY, STM32_I2C_I2C3_IRQ_PRIORITY, and I2CDriver::txdmamode.
Referenced by i2cStart().
void i2c_lld_stop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 655 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamRelease(), I2CDriver::dmatx, i2c_lld_abort_operation(), I2C_STOP, rccDisableI2C1, rccDisableI2C2, and I2CDriver::state.
Referenced by i2cStop().
msg_t i2c_lld_master_receive_timeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
Number of receiving bytes must be more than 1 on STM32F1x. This is hardware restriction.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:
Not an API, this function is for internal use only.
Definition at line 714 of file hal_i2c_lld.c.
References I2CDriver::addr, I2CDriver::dmarx, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, I2CDriver::errors, I2CDriver::i2c, I2C_NO_ERROR, OSAL_MS2I, osalDbgCheck, osalOsGetSystemTimeX(), osalSysLock(), osalSysUnlock(), osalThreadSuspendTimeoutS(), osalTimeAddX(), osalTimeIsInRangeX(), I2CDriver::rxdmamode, STM32_I2C_BUSY_TIMEOUT, and I2CDriver::thread.
Referenced by i2cMasterReceiveTimeout().
msg_t i2c_lld_master_transmit_timeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
Number of receiving bytes must be 0 or more than 1 on STM32F1x. This is hardware restriction.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[in] txbuf pointer to the transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:
Not an API, this function is for internal use only.
Definition at line 793 of file hal_i2c_lld.c.
References I2CDriver::addr, I2CDriver::dmarx, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, I2CDriver::dmatx, I2CDriver::errors, I2CDriver::i2c, I2C_NO_ERROR, OSAL_MS2I, osalDbgCheck, osalOsGetSystemTimeX(), osalSysLock(), osalSysUnlock(), osalThreadSuspendTimeoutS(), osalTimeAddX(), osalTimeIsInRangeX(), I2CDriver::rxdmamode, STM32_I2C_BUSY_TIMEOUT, I2CDriver::thread, and I2CDriver::txdmamode.
Referenced by i2cMasterTransmitTimeout().
void i2cInit (void)
I2C Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 59 of file hal_i2c.c.
References i2c_lld_init().
Referenced by halInit().
void i2cObjectInit (I2CDriver * i2cp)
Initializes the standard part of a I2CDriver structure.
Parameters
[out] i2cp pointer to the I2CDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 71 of file hal_i2c.c.
References I2CDriver::config, I2C_STOP, I2CDriver::mutex, osalMutexObjectInit(), and I2CDriver::state.
Referenced by i2c_lld_init().
void i2cStart (I2CDriver * i2cp, const I2CConfig * config)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] config pointer to the I2CConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 93 of file hal_i2c.c.
References I2CDriver::config, i2c_lld_start(), I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2CDriver::state.
void i2cStop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 113 of file hal_i2c.c.
References I2CDriver::config, i2c_lld_stop(), I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2CDriver::state.
i2cflags_t i2cGetErrors (I2CDriver * i2cp)
Returns the errors mask associated to the previous operation.
Parameters
[in] i2cp pointer to the I2CDriver object
Returns
The errors mask.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 137 of file hal_i2c.c.
References i2c_lld_get_errors, and osalDbgCheck.
msg_t i2cMasterTransmitTimeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
Function designed to realize "read-through-write" transfer paradigm. If you want transmit data without any further read, than set rxbytes field to 0.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[in] txbuf pointer to transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received, set it to 0 if you want transmit only
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 170 of file hal_i2c.c.
References I2CDriver::errors, I2C_ACTIVE_TX, i2c_lld_master_transmit_timeout(), I2C_NO_ERROR, I2C_READY, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2CDriver::state.
msg_t i2cMasterReceiveTimeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 221 of file hal_i2c.c.
References I2CDriver::errors, I2C_ACTIVE_RX, i2c_lld_master_receive_timeout(), I2C_NO_ERROR, I2C_READY, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2CDriver::state.
void i2cAcquireBus (I2CDriver * i2cp)
Gains exclusive access to the I2C bus.
This function tries to gain ownership to the I2C bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 261 of file hal_i2c.c.
References I2CDriver::mutex, osalDbgCheck, and osalMutexLock().
void i2cReleaseBus (I2CDriver * i2cp)
Releases exclusive access to the I2C bus.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 277 of file hal_i2c.c.
References I2CDriver::mutex, osalDbgCheck, and osalMutexUnlock().
Variable Documentation
I2CDriver I2CD1
I2C1 driver identifier.
Definition at line 94 of file hal_i2c_lld.c.
I2CDriver I2CD2
I2C2 driver identifier.
Definition at line 99 of file hal_i2c_lld.c.
I2CDriver I2CD3
I2C3 driver identifier.
Definition at line 104 of file hal_i2c_lld.c.