ChibiOS/HAL: PWM Driver
PWM Driver
HAL » Normal Drivers
Generic PWM Driver.
Detailed Description
Generic PWM Driver.
This module implements a generic PWM (Pulse Width Modulation) driver.
Precondition
In order to use the PWM driver the HAL_USE_PWM option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
PWM Operations.
This driver abstracts a generic PWM timer composed of:
A clock prescaler.
A main up counter.
A comparator register that resets the main counter to zero when the limit is reached. An optional callback can be generated when this happens.
An array of PWM_CHANNELS PWM channels, each channel has an output, a comparator and is able to invoke an optional callback when a comparator match with the main counter happens.
A PWM channel output can be in two different states:
IDLE, when the channel is disabled or after a match occurred.
ACTIVE, when the channel is enabled and a match didn't occur yet in the current PWM cycle.
Note that the two states can be associated to both logical zero or one in the PWMChannelConfig structure.
Macros
#define PWM_CHANNELS STM32_TIM_MAX_CHANNELS
Number of PWM channels per PWM driver.
#define pwm_lld_change_period(pwmp, period) ((pwmp)->tim->ARR = ((period) - 1))
Changes the period the PWM peripheral.
STM32-specific PWM complementary output mode macros
#define PWM_COMPLEMENTARY_OUTPUT_MASK 0xF0
Complementary output modes mask.
#define PWM_COMPLEMENTARY_OUTPUT_DISABLED 0x00
Complementary output not driven.
#define PWM_COMPLEMENTARY_OUTPUT_ACTIVE_HIGH 0x10
Complementary output, active is logic level one.
#define PWM_COMPLEMENTARY_OUTPUT_ACTIVE_LOW 0x20
Complementary output, active is logic level zero.
Configuration options
#define STM32_PWM_USE_ADVANCED FALSE
If advanced timer features switch.
#define STM32_PWM_USE_TIM1 FALSE
PWMD1 driver enable switch.
#define STM32_PWM_USE_TIM2 FALSE
PWMD2 driver enable switch.
#define STM32_PWM_USE_TIM3 FALSE
PWMD3 driver enable switch.
#define STM32_PWM_USE_TIM4 FALSE
PWMD4 driver enable switch.
#define STM32_PWM_USE_TIM5 FALSE
PWMD5 driver enable switch.
#define STM32_PWM_USE_TIM8 FALSE
PWMD8 driver enable switch.
#define STM32_PWM_USE_TIM9 FALSE
PWMD9 driver enable switch.
#define STM32_PWM_TIM1_IRQ_PRIORITY 7
PWMD1 interrupt priority level setting.
#define STM32_PWM_TIM2_IRQ_PRIORITY 7
PWMD2 interrupt priority level setting.
#define STM32_PWM_TIM3_IRQ_PRIORITY 7
PWMD3 interrupt priority level setting.
#define STM32_PWM_TIM4_IRQ_PRIORITY 7
PWMD4 interrupt priority level setting.
#define STM32_PWM_TIM5_IRQ_PRIORITY 7
PWMD5 interrupt priority level setting.
#define STM32_PWM_TIM8_IRQ_PRIORITY 7
PWMD8 interrupt priority level setting.
#define STM32_PWM_TIM9_IRQ_PRIORITY 7
PWMD9 interrupt priority level setting.
PWM output mode macros
#define PWM_OUTPUT_MASK 0x0FU
Standard output modes mask.
#define PWM_OUTPUT_DISABLED 0x00U
Output not driven, callback only.
#define PWM_OUTPUT_ACTIVE_HIGH 0x01U
Positive PWM logic, active is logic level one.
#define PWM_OUTPUT_ACTIVE_LOW 0x02U
Inverse PWM logic, active is logic level zero.
PWM duty cycle conversion
#define PWM_FRACTION_TO_WIDTH(pwmp, denominator, numerator)
Converts from fraction to pulse width.
#define PWM_DEGREES_TO_WIDTH(pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
#define PWM_PERCENTAGE_TO_WIDTH(pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Macro Functions
#define pwmChangePeriodI(pwmp, value)
Changes the period the PWM peripheral.
#define pwmEnableChannelI(pwmp, channel, width)
Enables a PWM channel.
#define pwmDisableChannelI(pwmp, channel)
Disables a PWM channel.
#define pwmIsChannelEnabledI(pwmp, channel) (((pwmp)->enabled & ((pwmchnmsk_t)1U << (pwmchnmsk_t)(channel))) != 0U)
Returns a PWM channel status.
#define pwmEnablePeriodicNotificationI(pwmp) pwm_lld_enable_periodic_notification(pwmp)
Enables the periodic activation edge notification.
#define pwmDisablePeriodicNotificationI(pwmp) pwm_lld_disable_periodic_notification(pwmp)
Disables the periodic activation edge notification.
#define pwmEnableChannelNotificationI(pwmp, channel) pwm_lld_enable_channel_notification(pwmp, channel)
Enables a channel de-activation edge notification.
#define pwmDisableChannelNotificationI(pwmp, channel) pwm_lld_disable_channel_notification(pwmp, channel)
Disables a channel de-activation edge notification.
Typedefs
typedef uint32_t pwmmode_t
Type of a PWM mode.
typedef uint8_t pwmchannel_t
Type of a PWM channel.
typedef uint32_t pwmchnmsk_t
Type of a channels mask.
typedef uint32_t pwmcnt_t
Type of a PWM counter.
typedef struct PWMDriver PWMDriver
Type of a structure representing a PWM driver.
typedef void(* pwmcallback_t) (PWMDriver *pwmp)
Type of a PWM notification callback.
Data Structures
struct PWMChannelConfig
Type of a PWM driver channel configuration structure.
struct PWMConfig
Type of a PWM driver configuration structure.
struct PWMDriver
Structure representing a PWM driver.
Functions
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM1 update interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM1_CC_HANDLER)
TIM1 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 update interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM8_CC_HANDLER)
TIM8 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
void pwm_lld_init (void)
Low level PWM driver initialization.
void pwm_lld_start (PWMDriver *pwmp)
Configures and activates the PWM peripheral.
void pwm_lld_stop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
void pwm_lld_enable_channel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwm_lld_disable_channel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel and its notification.
void pwm_lld_enable_periodic_notification (PWMDriver *pwmp)
Enables the periodic activation edge notification.
void pwm_lld_disable_periodic_notification (PWMDriver *pwmp)
Disables the periodic activation edge notification.
void pwm_lld_enable_channel_notification (PWMDriver *pwmp, pwmchannel_t channel)
Enables a channel de-activation edge notification.
void pwm_lld_disable_channel_notification (PWMDriver *pwmp, pwmchannel_t channel)
Disables a channel de-activation edge notification.
void pwm_lld_serve_interrupt (PWMDriver *pwmp)
Common TIM2...TIM5,TIM9 IRQ handler.
void pwmInit (void)
PWM Driver initialization.
void pwmObjectInit (PWMDriver *pwmp)
Initializes the standard part of a PWMDriver structure.
void pwmStart (PWMDriver *pwmp, const PWMConfig *config)
Configures and activates the PWM peripheral.
void pwmStop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
void pwmChangePeriod (PWMDriver *pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
void pwmEnableChannel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwmDisableChannel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel and its notification.
void pwmEnablePeriodicNotification (PWMDriver *pwmp)
Enables the periodic activation edge notification.
void pwmDisablePeriodicNotification (PWMDriver *pwmp)
Disables the periodic activation edge notification.
void pwmEnableChannelNotification (PWMDriver *pwmp, pwmchannel_t channel)
Enables a channel de-activation edge notification.
void pwmDisableChannelNotification (PWMDriver *pwmp, pwmchannel_t channel)
Disables a channel de-activation edge notification.
Enumerations
Variables
PWMDriver PWMD1
PWMD1 driver identifier.
PWMDriver PWMD2
PWMD2 driver identifier.
PWMDriver PWMD3
PWMD3 driver identifier.
PWMDriver PWMD4
PWMD4 driver identifier.
PWMDriver PWMD5
PWMD5 driver identifier.
PWMDriver PWMD8
PWMD8 driver identifier.
PWMDriver PWMD9
PWMD9 driver identifier.
Macro Definition Documentation
#define PWM_CHANNELS STM32_TIM_MAX_CHANNELS
Number of PWM channels per PWM driver.
Definition at line 39 of file hal_pwm_lld.h.
#define PWM_COMPLEMENTARY_OUTPUT_MASK 0xF0
Complementary output modes mask.
Note
This is an STM32-specific setting.
Definition at line 49 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define PWM_COMPLEMENTARY_OUTPUT_DISABLED 0x00
Complementary output not driven.
Note
This is an STM32-specific setting.
Definition at line 55 of file hal_pwm_lld.h.
#define PWM_COMPLEMENTARY_OUTPUT_ACTIVE_HIGH 0x10
Complementary output, active is logic level one.
Note
This is an STM32-specific setting.
This setting is only available if the configuration option STM32_PWM_USE_ADVANCED is set to TRUE and only for advanced timers TIM1 and TIM8.
Definition at line 64 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define PWM_COMPLEMENTARY_OUTPUT_ACTIVE_LOW 0x20
Complementary output, active is logic level zero.
Note
This is an STM32-specific setting.
This setting is only available if the configuration option STM32_PWM_USE_ADVANCED is set to TRUE and only for advanced timers TIM1 and TIM8.
Definition at line 73 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_USE_ADVANCED FALSE
If advanced timer features switch.
If set to TRUE the advanced features for TIM1 and TIM8 are enabled.
Note
The default is TRUE.
Definition at line 91 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM1 FALSE
PWMD1 driver enable switch.
If set to TRUE the support for PWMD1 is included.
Note
The default is TRUE.
Definition at line 100 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM2 FALSE
PWMD2 driver enable switch.
If set to TRUE the support for PWMD2 is included.
Note
The default is TRUE.
Definition at line 109 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM3 FALSE
PWMD3 driver enable switch.
If set to TRUE the support for PWMD3 is included.
Note
The default is TRUE.
Definition at line 118 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM4 FALSE
PWMD4 driver enable switch.
If set to TRUE the support for PWMD4 is included.
Note
The default is TRUE.
Definition at line 127 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM5 FALSE
PWMD5 driver enable switch.
If set to TRUE the support for PWMD5 is included.
Note
The default is TRUE.
Definition at line 136 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM8 FALSE
PWMD8 driver enable switch.
If set to TRUE the support for PWMD8 is included.
Note
The default is TRUE.
Definition at line 145 of file hal_pwm_lld.h.
#define STM32_PWM_USE_TIM9 FALSE
PWMD9 driver enable switch.
If set to TRUE the support for PWMD9 is included.
Note
The default is TRUE.
Definition at line 154 of file hal_pwm_lld.h.
#define STM32_PWM_TIM1_IRQ_PRIORITY 7
PWMD1 interrupt priority level setting.
Definition at line 161 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM2_IRQ_PRIORITY 7
PWMD2 interrupt priority level setting.
Definition at line 168 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM3_IRQ_PRIORITY 7
PWMD3 interrupt priority level setting.
Definition at line 175 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM4_IRQ_PRIORITY 7
PWMD4 interrupt priority level setting.
Definition at line 182 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM5_IRQ_PRIORITY 7
PWMD5 interrupt priority level setting.
Definition at line 189 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM8_IRQ_PRIORITY 7
PWMD8 interrupt priority level setting.
Definition at line 196 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define STM32_PWM_TIM9_IRQ_PRIORITY 7
PWMD9 interrupt priority level setting.
Definition at line 203 of file hal_pwm_lld.h.
Referenced by pwm_lld_start().
#define pwm_lld_change_period (pwmp, period) ((pwmp)->tim->ARR = ((period) - 1))
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
The function has effect at the next cycle start.
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] period new cycle time in ticks
Function Class:
Not an API, this function is for internal use only.
Definition at line 489 of file hal_pwm_lld.h.
#define PWM_OUTPUT_MASK 0x0FU
Standard output modes mask.
Definition at line 41 of file hal_pwm.h.
Referenced by pwm_lld_start().
#define PWM_OUTPUT_DISABLED 0x00U
Output not driven, callback only.
Definition at line 46 of file hal_pwm.h.
#define PWM_OUTPUT_ACTIVE_HIGH 0x01U
Positive PWM logic, active is logic level one.
Definition at line 51 of file hal_pwm.h.
Referenced by pwm_lld_start().
#define PWM_OUTPUT_ACTIVE_LOW 0x02U
Inverse PWM logic, active is logic level zero.
Definition at line 56 of file hal_pwm.h.
Referenced by pwm_lld_start().
#define PWM_FRACTION_TO_WIDTH (pwmp, denominator, numerator)
Value:
((pwmcnt_t)((((pwmcnt_t)(pwmp)->period) *                                 \
               (pwmcnt_t)(numerator)) / (pwmcnt_t)(denominator)))
Converts from fraction to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] denominator denominator of the fraction
[in] numerator numerator of the fraction
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 116 of file hal_pwm.h.
#define PWM_DEGREES_TO_WIDTH (pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify hundredths of degrees but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] degrees degrees as an integer between 0 and 36000
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 133 of file hal_pwm.h.
#define PWM_PERCENTAGE_TO_WIDTH (pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] percentage percentage as an integer between 0 and 10000
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 149 of file hal_pwm.h.
#define pwmChangePeriodI (pwmp, value)
Value:
{                                     \
  (pwmp)->period = (value);                                                 \
  pwm_lld_change_period(pwmp, value);                                       \
}
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] value new cycle time in ticks
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 172 of file hal_pwm.h.
Referenced by pwmChangePeriod().
#define pwmEnableChannelI (pwmp, channel, width)
Value:
do {                        \
  (pwmp)->enabled |= ((pwmchnmsk_t)1U << (pwmchnmsk_t)(channel));           \
  pwm_lld_enable_channel(pwmp, channel, width);                             \
} while (false)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
[in] width PWM pulse width as clock pulses number
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 191 of file hal_pwm.h.
Referenced by pwmEnableChannel().
#define pwmDisableChannelI (pwmp, channel)
Value:
do {                              \
  (pwmp)->enabled &= ~((pwmchnmsk_t)1U << (pwmchnmsk_t)(channel));          \
  pwm_lld_disable_channel(pwmp, channel);                                   \
} while (false)
Disables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 210 of file hal_pwm.h.
Referenced by pwmDisableChannel().
#define pwmIsChannelEnabledI (pwmp, channel) (((pwmp)->enabled & ((pwmchnmsk_t)1U << (pwmchnmsk_t)(channel))) != 0U)
Returns a PWM channel status.
Precondition
The PWM unit must have been activated using pwmStart().
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 224 of file hal_pwm.h.
#define pwmEnablePeriodicNotificationI (pwmp) pwm_lld_enable_periodic_notification(pwmp)
Enables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 236 of file hal_pwm.h.
Referenced by pwmEnablePeriodicNotification().
#define pwmDisablePeriodicNotificationI (pwmp) pwm_lld_disable_periodic_notification(pwmp)
Disables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 248 of file hal_pwm.h.
Referenced by pwmDisablePeriodicNotification().
#define pwmEnableChannelNotificationI (pwmp, channel) pwm_lld_enable_channel_notification(pwmp, channel)
Enables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 262 of file hal_pwm.h.
Referenced by pwmEnableChannelNotification().
#define pwmDisableChannelNotificationI (pwmp, channel) pwm_lld_disable_channel_notification(pwmp, channel)
Disables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 276 of file hal_pwm.h.
Referenced by pwmDisableChannelNotification().
Typedef Documentation
typedef uint32_t pwmmode_t
Type of a PWM mode.
Definition at line 350 of file hal_pwm_lld.h.
typedef uint8_t pwmchannel_t
Type of a PWM channel.
Definition at line 355 of file hal_pwm_lld.h.
typedef uint32_t pwmchnmsk_t
Type of a channels mask.
Definition at line 360 of file hal_pwm_lld.h.
typedef uint32_t pwmcnt_t
Type of a PWM counter.
Definition at line 365 of file hal_pwm_lld.h.
typedef struct PWMDriver PWMDriver
Type of a structure representing a PWM driver.
Definition at line 83 of file hal_pwm.h.
typedef void(* pwmcallback_t) (PWMDriver *pwmp)
Type of a PWM notification callback.
Parameters
[in] pwmp pointer to a PWMDriver object
Definition at line 90 of file hal_pwm.h.
Enumeration Type Documentation
enum pwmstate_t
Driver state machine possible states.
Enumerator
PWM_UNINIT
Not initialized.
PWM_STOP
Stopped.
PWM_READY
Ready.
Definition at line 74 of file hal_pwm.h.
Function Documentation
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM1 update interrupt handler.
Note
It is assumed that this interrupt is only activated if the callback pointer is not equal to NULL in order to not perform an extra check in a potentially critical interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 118 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM1_CC_HANDLER)
TIM1 compare interrupt handler.
Note
It is assumed that the various sources are only activated if the associated callback pointer is not equal to NULL in order to not perform an extra check in a potentially critical interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 138 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 159 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 180 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 201 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 222 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 update interrupt handler.
Note
It is assumed that this interrupt is only activated if the callback pointer is not equal to NULL in order to not perform an extra check in a potentially critical interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 246 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM8_CC_HANDLER)
TIM8 compare interrupt handler.
Note
It is assumed that the various sources are only activated if the associated callback pointer is not equal to NULL in order to not perform an extra check in a potentially critical interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 266 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 287 of file hal_pwm_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and pwm_lld_serve_interrupt().
void pwm_lld_init (void)
Low level PWM driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 307 of file hal_pwm_lld.c.
References PWMDriver::channels, pwmObjectInit(), and PWMDriver::tim.
Referenced by pwmInit().
void pwm_lld_start (PWMDriver * pwmp)
Configures and activates the PWM peripheral.
Note
Starting a driver that is already in the PWM_READY state disables all the active channels.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 368 of file hal_pwm_lld.c.
References PWMConfig::bdtr, PWMConfig::channels, PWMDriver::channels, PWMDriver::clock, PWMDriver::config, PWMConfig::cr2, PWMConfig::dier, PWMConfig::frequency, PWMChannelConfig::mode, osalDbgAssert, PWMDriver::period, PWM_COMPLEMENTARY_OUTPUT_ACTIVE_HIGH, PWM_COMPLEMENTARY_OUTPUT_ACTIVE_LOW, PWM_COMPLEMENTARY_OUTPUT_MASK, PWM_OUTPUT_ACTIVE_HIGH, PWM_OUTPUT_ACTIVE_LOW, PWM_OUTPUT_MASK, PWM_STOP, rccEnableTIM1, rccEnableTIM2, rccEnableTIM3, rccEnableTIM4, rccEnableTIM5, rccEnableTIM8, rccEnableTIM9, rccResetTIM1, rccResetTIM2, rccResetTIM3, rccResetTIM4, rccResetTIM5, rccResetTIM8, rccResetTIM9, PWMDriver::state, STM32_PWM_TIM1_IRQ_PRIORITY, STM32_PWM_TIM2_IRQ_PRIORITY, STM32_PWM_TIM3_IRQ_PRIORITY, STM32_PWM_TIM4_IRQ_PRIORITY, STM32_PWM_TIM5_IRQ_PRIORITY, STM32_PWM_TIM8_IRQ_PRIORITY, STM32_PWM_TIM9_IRQ_PRIORITY, STM32_TIMCLK1, STM32_TIMCLK2, and PWMDriver::tim.
Referenced by pwmStart().
void pwm_lld_stop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 626 of file hal_pwm_lld.c.
References PWM_READY, rccDisableTIM1, rccDisableTIM2, rccDisableTIM3, rccDisableTIM4, rccDisableTIM5, rccDisableTIM8, rccDisableTIM9, PWMDriver::state, and PWMDriver::tim.
Referenced by pwmStop().
void pwm_lld_enable_channel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
The function has effect at the next cycle start.
Channel notification is not enabled.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
[in] width PWM pulse width as clock pulses number
Function Class:
Not an API, this function is for internal use only.
Definition at line 717 of file hal_pwm_lld.c.
References PWMDriver::tim.
void pwm_lld_disable_channel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel and its notification.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
The function has effect at the next cycle start.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Not an API, this function is for internal use only.
Definition at line 744 of file hal_pwm_lld.c.
References PWMDriver::tim.
void pwm_lld_enable_periodic_notification (PWMDriver * pwmp)
Enables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 768 of file hal_pwm_lld.c.
References PWMDriver::tim.
void pwm_lld_disable_periodic_notification (PWMDriver * pwmp)
Disables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 788 of file hal_pwm_lld.c.
References PWMDriver::tim.
void pwm_lld_enable_channel_notification (PWMDriver * pwmp, pwmchannel_t channel)
Enables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Not an API, this function is for internal use only.
Definition at line 804 of file hal_pwm_lld.c.
References osalDbgAssert, and PWMDriver::tim.
void pwm_lld_disable_channel_notification (PWMDriver * pwmp, pwmchannel_t channel)
Disables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Not an API, this function is for internal use only.
Definition at line 832 of file hal_pwm_lld.c.
References PWMDriver::tim.
void pwm_lld_serve_interrupt (PWMDriver * pwmp)
Common TIM2...TIM5,TIM9 IRQ handler.
Note
It is assumed that the various sources are only activated if the associated callback pointer is not equal to NULL in order to not perform an extra check in a potentially critical interrupt handler.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 848 of file hal_pwm_lld.c.
References PWMChannelConfig::callback, PWMConfig::callback, PWMConfig::channels, PWMDriver::config, and PWMDriver::tim.
Referenced by OSAL_IRQ_HANDLER().
void pwmInit (void)
PWM Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_pwm.c.
References pwm_lld_init().
Referenced by halInit().
void pwmObjectInit (PWMDriver * pwmp)
Initializes the standard part of a PWMDriver structure.
Parameters
[out] pwmp pointer to a PWMDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_pwm.c.
References PWMDriver::channels, PWMDriver::config, PWMDriver::enabled, PWM_STOP, and PWMDriver::state.
Referenced by pwm_lld_init().
void pwmStart (PWMDriver * pwmp, const PWMConfig * config)
Configures and activates the PWM peripheral.
Note
Starting a driver that is already in the PWM_READY state disables all the active channels.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] config pointer to a PWMConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 89 of file hal_pwm.c.
References PWMDriver::config, PWMDriver::enabled, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWMConfig::period, PWMDriver::period, pwm_lld_start(), PWM_READY, PWM_STOP, and PWMDriver::state.
void pwmStop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 111 of file hal_pwm.c.
References PWMDriver::config, PWMDriver::enabled, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), pwm_lld_stop(), PWM_READY, PWM_STOP, and PWMDriver::state.
void pwmChangePeriod (PWMDriver * pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] period new cycle time in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 143 of file hal_pwm.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmChangePeriodI, and PWMDriver::state.
void pwmEnableChannel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
[in] width PWM pulse width as clock pulses number
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 167 of file hal_pwm.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmEnableChannelI, and PWMDriver::state.
void pwmDisableChannel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel and its notification.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 196 of file hal_pwm.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmDisableChannelI, and PWMDriver::state.
void pwmEnablePeriodicNotification (PWMDriver * pwmp)
Enables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 218 of file hal_pwm.c.
References PWMConfig::callback, PWMDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmEnablePeriodicNotificationI, and PWMDriver::state.
void pwmDisablePeriodicNotification (PWMDriver * pwmp)
Disables the periodic activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 241 of file hal_pwm.c.
References PWMConfig::callback, PWMDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmDisablePeriodicNotificationI, and PWMDriver::state.
void pwmEnableChannelNotification (PWMDriver * pwmp, pwmchannel_t channel)
Enables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 266 of file hal_pwm.c.
References PWMChannelConfig::callback, PWMConfig::channels, PWMDriver::config, PWMDriver::enabled, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmEnableChannelNotificationI, and PWMDriver::state.
void pwmDisableChannelNotification (PWMDriver * pwmp, pwmchannel_t channel)
Disables a channel de-activation edge notification.
Precondition
The PWM unit must have been activated using pwmStart().
The channel must have been activated using pwmEnableChannel().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...channels-1)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 294 of file hal_pwm.c.
References PWMChannelConfig::callback, PWMConfig::channels, PWMDriver::config, PWMDriver::enabled, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), PWM_READY, pwmDisableChannelNotificationI, and PWMDriver::state.
Variable Documentation
PWMDriver PWMD1
PWMD1 driver identifier.
Note
The driver PWMD1 allocates the complex timer TIM1 when enabled.
Definition at line 42 of file hal_pwm_lld.c.
PWMDriver PWMD2
PWMD2 driver identifier.
Note
The driver PWMD2 allocates the timer TIM2 when enabled.
Definition at line 50 of file hal_pwm_lld.c.
PWMDriver PWMD3
PWMD3 driver identifier.
Note
The driver PWMD3 allocates the timer TIM3 when enabled.
Definition at line 58 of file hal_pwm_lld.c.
PWMDriver PWMD4
PWMD4 driver identifier.
Note
The driver PWMD4 allocates the timer TIM4 when enabled.
Definition at line 66 of file hal_pwm_lld.c.
PWMDriver PWMD5
PWMD5 driver identifier.
Note
The driver PWMD5 allocates the timer TIM5 when enabled.
Definition at line 74 of file hal_pwm_lld.c.
PWMDriver PWMD8
PWMD8 driver identifier.
Note
The driver PWMD8 allocates the timer TIM8 when enabled.
Definition at line 82 of file hal_pwm_lld.c.
PWMDriver PWMD9
PWMD9 driver identifier.
Note
The driver PWMD9 allocates the timer TIM9 when enabled.
Definition at line 90 of file hal_pwm_lld.c.