ChibiOS/HAL: UART Driver
UART Driver
HAL » Normal Drivers
Generic UART Driver.
Detailed Description
Generic UART Driver.
This driver abstracts a generic UART (Universal Asynchronous Receiver Transmitter) peripheral, the API is designed to be:
Unbuffered and copy-less, transfers are always directly performed from/to the application-level buffers without extra copy operations.
Asynchronous, the API is always non blocking.
Callbacks capable, operations completion and other events are notified using callbacks.
Special hardware features like deep hardware buffers, DMA transfers are hidden to the user but fully supportable by the low level implementations.
This driver model is best used where communication events are meant to drive an higher level state machine, as example:
RS485 drivers.
Multipoint network drivers.
Serial protocol decoders.
If your application requires a synchronous buffered driver then the Serial Driver should be used instead.
Precondition
In order to use the UART driver the HAL_USE_UART option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
Transmitter sub State Machine
The follow diagram describes the transmitter state machine, this diagram is valid while the driver is in the UART_READY state. This state machine is automatically reset to the TX_IDLE state each time the driver enters the UART_READY state.
Receiver sub State Machine
The follow diagram describes the receiver state machine, this diagram is valid while the driver is in the UART_READY state. This state machine is automatically reset to the RX_IDLE state each time the driver enters the UART_READY state.
Configuration options
#define STM32_UART_USE_USART1 FALSE
UART driver on USART1 enable switch.
#define STM32_UART_USE_USART2 FALSE
UART driver on USART2 enable switch.
#define STM32_UART_USE_USART3 FALSE
UART driver on USART3 enable switch.
#define STM32_UART_USE_UART4 FALSE
UART driver on UART4 enable switch.
#define STM32_UART_USE_UART5 FALSE
UART driver on UART5 enable switch.
#define STM32_UART_USE_USART6 FALSE
UART driver on USART6 enable switch.
#define STM32_UART_USART1_IRQ_PRIORITY 12
USART1 interrupt priority level setting.
#define STM32_UART_USART2_IRQ_PRIORITY 12
USART2 interrupt priority level setting.
#define STM32_UART_USART3_IRQ_PRIORITY 12
USART3 interrupt priority level setting.
#define STM32_UART_UART4_IRQ_PRIORITY 12
UART4 interrupt priority level setting.
#define STM32_UART_UART5_IRQ_PRIORITY 12
UART5 interrupt priority level setting.
#define STM32_UART_USART6_IRQ_PRIORITY 12
USART6 interrupt priority level setting.
#define STM32_UART_USART1_DMA_PRIORITY 0
USART1 DMA priority (0..3|lowest..highest).
#define STM32_UART_USART2_DMA_PRIORITY 0
USART2 DMA priority (0..3|lowest..highest).
#define STM32_UART_USART3_DMA_PRIORITY 0
USART3 DMA priority (0..3|lowest..highest).
#define STM32_UART_UART4_DMA_PRIORITY 0
UART4 DMA priority (0..3|lowest..highest).
#define STM32_UART_UART5_DMA_PRIORITY 0
UART5 DMA priority (0..3|lowest..highest).
#define STM32_UART_USART6_DMA_PRIORITY 0
USART6 DMA priority (0..3|lowest..highest).
#define STM32_UART_DMA_ERROR_HOOK(uartp) osalSysHalt("DMA failure")
USART DMA error hook.
UART status flags
#define UART_NO_ERROR 0
No pending conditions.
#define UART_PARITY_ERROR 4
Parity error happened.
#define UART_FRAMING_ERROR 8
Framing error happened.
#define UART_OVERRUN_ERROR 16
Overflow happened.
#define UART_NOISE_ERROR 32
Noise on the line.
#define UART_BREAK_DETECTED 64
Break detected.
UART configuration options
#define UART_USE_WAIT FALSE
Enables synchronous APIs.
#define UART_USE_MUTUAL_EXCLUSION FALSE
Enables the uartAcquireBus() and uartReleaseBus() APIs.
Low level driver helper macros
#define _uart_wakeup_tx1_isr(uartp)
Wakes up the waiting thread in case of early TX complete.
#define _uart_wakeup_tx2_isr(uartp)
Wakes up the waiting thread in case of late TX complete.
#define _uart_wakeup_rx_complete_isr(uartp)
Wakes up the waiting thread in case of RX complete.
#define _uart_wakeup_rx_error_isr(uartp)
Wakes up the waiting thread in case of RX error.
#define _uart_wakeup_rx_timeout_isr(uartp)
Wakes up the waiting thread in case of RX timeout.
#define _uart_tx1_isr_code(uartp)
Common ISR code for early TX.
#define _uart_tx2_isr_code(uartp)
Common ISR code for late TX.
#define _uart_rx_complete_isr_code(uartp)
Common ISR code for RX complete.
#define _uart_rx_error_isr_code(uartp, errors)
Common ISR code for RX error.
#define _uart_rx_idle_code(uartp)
Common ISR code for RX on idle.
#define _uart_timeout_isr_code(uartp)
Timeout ISR code for receiver.
Typedefs
typedef uint32_t uartflags_t
UART driver condition flags type.
typedef struct UARTDriver UARTDriver
Structure representing an UART driver.
typedef void(* uartcb_t) (UARTDriver *uartp)
Generic UART notification callback type.
typedef void(* uartccb_t) (UARTDriver *uartp, uint16_t c)
Character received UART notification callback type.
typedef void(* uartecb_t) (UARTDriver *uartp, uartflags_t e)
Receive error UART notification callback type.
Data Structures
struct UARTConfig
Driver configuration structure.
struct UARTDriver
Structure representing an UART driver.
Functions
static uartflags_t translate_errors (uint16_t sr)
Status bits translation.
static void uart_enter_rx_idle_loop (UARTDriver *uartp)
Puts the receiver in the UART_RX_IDLE state.
static void usart_stop (UARTDriver *uartp)
USART de-initialization.
static void usart_start (UARTDriver *uartp)
USART initialization.
static void uart_lld_serve_rx_end_irq (UARTDriver *uartp, uint32_t flags)
RX DMA common service routine.
static void uart_lld_serve_tx_end_irq (UARTDriver *uartp, uint32_t flags)
TX DMA common service routine.
static void serve_usart_irq (UARTDriver *uartp)
USART common service routine.
OSAL_IRQ_HANDLER (STM32_USART1_HANDLER)
USART1 IRQ handler.
OSAL_IRQ_HANDLER (STM32_USART2_HANDLER)
USART2 IRQ handler.
OSAL_IRQ_HANDLER (STM32_USART3_HANDLER)
USART3 IRQ handler.
OSAL_IRQ_HANDLER (STM32_UART4_HANDLER)
UART4 IRQ handler.
OSAL_IRQ_HANDLER (STM32_UART5_HANDLER)
UART5 IRQ handler.
OSAL_IRQ_HANDLER (STM32_USART6_HANDLER)
USART6 IRQ handler.
void uart_lld_init (void)
Low level UART driver initialization.
void uart_lld_start (UARTDriver *uartp)
Configures and activates the UART peripheral.
void uart_lld_stop (UARTDriver *uartp)
Deactivates the UART peripheral.
void uart_lld_start_send (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
size_t uart_lld_stop_send (UARTDriver *uartp)
Stops any ongoing transmission.
void uart_lld_start_receive (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
size_t uart_lld_stop_receive (UARTDriver *uartp)
Stops any ongoing receive operation.
void uartInit (void)
UART Driver initialization.
void uartObjectInit (UARTDriver *uartp)
Initializes the standard part of a UARTDriver structure.
void uartStart (UARTDriver *uartp, const UARTConfig *config)
Configures and activates the UART peripheral.
void uartStop (UARTDriver *uartp)
Deactivates the UART peripheral.
void uartStartSend (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
void uartStartSendI (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
size_t uartStopSend (UARTDriver *uartp)
Stops any ongoing transmission.
size_t uartStopSendI (UARTDriver *uartp)
Stops any ongoing transmission.
void uartStartReceive (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
void uartStartReceiveI (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
size_t uartStopReceive (UARTDriver *uartp)
Stops any ongoing receive operation.
size_t uartStopReceiveI (UARTDriver *uartp)
Stops any ongoing receive operation.
msg_t uartSendTimeout (UARTDriver *uartp, size_t *np, const void *txbuf, sysinterval_t timeout)
Performs a transmission on the UART peripheral.
msg_t uartSendFullTimeout (UARTDriver *uartp, size_t *np, const void *txbuf, sysinterval_t timeout)
Performs a transmission on the UART peripheral.
msg_t uartReceiveTimeout (UARTDriver *uartp, size_t *np, void *rxbuf, sysinterval_t timeout)
Performs a receive operation on the UART peripheral.
void uartAcquireBus (UARTDriver *uartp)
Gains exclusive access to the UART bus.
void uartReleaseBus (UARTDriver *uartp)
Releases exclusive access to the UART bus.
Enumerations
Variables
UARTDriver UARTD1
USART1 UART driver identifier.
UARTDriver UARTD2
USART2 UART driver identifier.
UARTDriver UARTD3
USART3 UART driver identifier.
UARTDriver UARTD4
UART4 UART driver identifier.
UARTDriver UARTD5
UART5 UART driver identifier.
UARTDriver UARTD6
USART6 UART driver identifier.
Macro Definition Documentation
#define STM32_UART_USE_USART1 FALSE
UART driver on USART1 enable switch.
If set to TRUE the support for USART1 is included.
Note
The default is FALSE.
Definition at line 48 of file hal_uart_lld.h.
#define STM32_UART_USE_USART2 FALSE
UART driver on USART2 enable switch.
If set to TRUE the support for USART2 is included.
Note
The default is FALSE.
Definition at line 57 of file hal_uart_lld.h.
#define STM32_UART_USE_USART3 FALSE
UART driver on USART3 enable switch.
If set to TRUE the support for USART3 is included.
Note
The default is FALSE.
Definition at line 66 of file hal_uart_lld.h.
#define STM32_UART_USE_UART4 FALSE
UART driver on UART4 enable switch.
If set to TRUE the support for UART4 is included.
Note
The default is FALSE.
Definition at line 75 of file hal_uart_lld.h.
#define STM32_UART_USE_UART5 FALSE
UART driver on UART5 enable switch.
If set to TRUE the support for UART5 is included.
Note
The default is FALSE.
Definition at line 84 of file hal_uart_lld.h.
#define STM32_UART_USE_USART6 FALSE
UART driver on USART6 enable switch.
If set to TRUE the support for USART6 is included.
Note
The default is FALSE.
Definition at line 93 of file hal_uart_lld.h.
#define STM32_UART_USART1_IRQ_PRIORITY 12
USART1 interrupt priority level setting.
Definition at line 100 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART2_IRQ_PRIORITY 12
USART2 interrupt priority level setting.
Definition at line 107 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART3_IRQ_PRIORITY 12
USART3 interrupt priority level setting.
Definition at line 114 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_UART4_IRQ_PRIORITY 12
UART4 interrupt priority level setting.
Definition at line 121 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_UART5_IRQ_PRIORITY 12
UART5 interrupt priority level setting.
Definition at line 128 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART6_IRQ_PRIORITY 12
USART6 interrupt priority level setting.
Definition at line 135 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART1_DMA_PRIORITY 0
USART1 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 145 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART2_DMA_PRIORITY 0
USART2 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 155 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART3_DMA_PRIORITY 0
USART3 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 165 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_UART4_DMA_PRIORITY 0
UART4 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 175 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_UART5_DMA_PRIORITY 0
UART5 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 185 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_USART6_DMA_PRIORITY 0
USART6 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA channels but because of the channels ordering the RX channel has always priority over the TX channel.
Definition at line 195 of file hal_uart_lld.h.
Referenced by uart_lld_start().
#define STM32_UART_DMA_ERROR_HOOK (uartp) osalSysHalt("DMA failure")
USART DMA error hook.
Note
The default action for DMA errors is a system halt because DMA error can only happen because programming errors.
Definition at line 204 of file hal_uart_lld.h.
Referenced by uart_lld_serve_rx_end_irq(), and uart_lld_serve_tx_end_irq().
#define UART_NO_ERROR 0
No pending conditions.
Definition at line 38 of file hal_uart.h.
#define UART_PARITY_ERROR 4
Parity error happened.
Definition at line 39 of file hal_uart.h.
Referenced by translate_errors().
#define UART_FRAMING_ERROR 8
Framing error happened.
Definition at line 40 of file hal_uart.h.
Referenced by translate_errors().
#define UART_OVERRUN_ERROR 16
Overflow happened.
Definition at line 41 of file hal_uart.h.
Referenced by translate_errors().
#define UART_NOISE_ERROR 32
Noise on the line.
Definition at line 42 of file hal_uart.h.
Referenced by translate_errors().
#define UART_BREAK_DETECTED 64
Break detected.
Definition at line 43 of file hal_uart.h.
Referenced by translate_errors().
#define UART_USE_WAIT FALSE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 59 of file hal_uart.h.
#define UART_USE_MUTUAL_EXCLUSION FALSE
Enables the uartAcquireBus() and uartReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 67 of file hal_uart.h.
#define _uart_wakeup_tx1_isr (uartp)
Value:
{                                       \
  if ((uartp)->early == true) {                                             \
    osalSysLockFromISR();                                                   \
    osalThreadResumeI(&(uartp)->threadtx, MSG_OK);                          \
    osalSysUnlockFromISR();                                                 \
  }                                                                         \
}
Wakes up the waiting thread in case of early TX complete.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 124 of file hal_uart.h.
#define _uart_wakeup_tx2_isr (uartp)
Value:
{                                       \
  if ((uartp)->early == false) {                                            \
    osalSysLockFromISR();                                                   \
    osalThreadResumeI(&(uartp)->threadtx, MSG_OK);                          \
    osalSysUnlockFromISR();                                                 \
  }                                                                         \
}
Wakes up the waiting thread in case of late TX complete.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 143 of file hal_uart.h.
#define _uart_wakeup_rx_complete_isr (uartp)
Value:
{                               \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(uartp)->threadrx, MSG_OK);                            \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread in case of RX complete.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 162 of file hal_uart.h.
#define _uart_wakeup_rx_error_isr (uartp)
Value:
{                                  \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(uartp)->threadrx, MSG_RESET);                         \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread in case of RX error.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 179 of file hal_uart.h.
#define _uart_wakeup_rx_timeout_isr (uartp)
Value:
{                                \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(uartp)->threadrx, MSG_TIMEOUT);                       \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread in case of RX timeout.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 196 of file hal_uart.h.
#define _uart_tx1_isr_code (uartp)
Value:
{                                         \
  (uartp)->txstate = UART_TX_COMPLETE;                                      \
  if ((uartp)->config->txend1_cb != NULL) {                                 \
    (uartp)->config->txend1_cb(uartp);                                      \
  }                                                                         \
  if ((uartp)->txstate == UART_TX_COMPLETE) {                               \
    (uartp)->txstate = UART_TX_IDLE;                                        \
  }                                                                         \
  _uart_wakeup_tx1_isr(uartp);                                              \
}
Common ISR code for early TX.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 219 of file hal_uart.h.
Referenced by uart_lld_serve_tx_end_irq().
#define _uart_tx2_isr_code (uartp)
Value:
{                                         \
  if ((uartp)->config->txend2_cb != NULL) {                                 \
    (uartp)->config->txend2_cb(uartp);                                      \
  }                                                                         \
  _uart_wakeup_tx2_isr(uartp);                                              \
}
Common ISR code for late TX.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 244 of file hal_uart.h.
Referenced by serve_usart_irq().
#define _uart_rx_complete_isr_code (uartp)
Value:
{                                 \
  (uartp)->rxstate = UART_RX_COMPLETE;                                      \
  if ((uartp)->config->rxend_cb != NULL) {                                  \
    (uartp)->config->rxend_cb(uartp);                                       \
  }                                                                         \
  if ((uartp)->rxstate == UART_RX_COMPLETE) {                               \
    (uartp)->rxstate = UART_RX_IDLE;                                        \
    uart_enter_rx_idle_loop(uartp);                                         \
  }                                                                         \
  _uart_wakeup_rx_complete_isr(uartp);                                      \
}
Common ISR code for RX complete.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 265 of file hal_uart.h.
Referenced by uart_lld_serve_rx_end_irq().
#define _uart_rx_error_isr_code (uartp, errors)
Value:
{                            \
  if ((uartp)->config->rxerr_cb != NULL) {                                  \
    (uartp)->config->rxerr_cb(uartp, errors);                               \
  }                                                                         \
  _uart_wakeup_rx_error_isr(uartp);                                         \
}
Common ISR code for RX error.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
[in] errors mask of errors to be reported
Function Class:
Not an API, this function is for internal use only.
Definition at line 292 of file hal_uart.h.
Referenced by serve_usart_irq().
#define _uart_rx_idle_code (uartp)
Value:
{                                         \
  if ((uartp)->config->rxchar_cb != NULL)                                   \
    (uartp)->config->rxchar_cb(uartp, (uartp)->rxbuf);                      \
}
Common ISR code for RX on idle.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 313 of file hal_uart.h.
Referenced by uart_lld_serve_rx_end_irq().
#define _uart_timeout_isr_code (uartp)
Value:
{                                     \
  if ((uartp)->config->timeout_cb != NULL) {                                \
    (uartp)->config->timeout_cb(uartp);                                     \
  }                                                                         \
  _uart_wakeup_rx_timeout_isr(uartp);                                       \
}
Timeout ISR code for receiver.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 332 of file hal_uart.h.
Typedef Documentation
typedef uint32_t uartflags_t
UART driver condition flags type.
Definition at line 435 of file hal_uart_lld.h.
typedef struct UARTDriver UARTDriver
Structure representing an UART driver.
Definition at line 440 of file hal_uart_lld.h.
typedef void(* uartcb_t) (UARTDriver *uartp)
Generic UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 447 of file hal_uart_lld.h.
typedef void(* uartccb_t) (UARTDriver *uartp, uint16_t c)
Character received UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object
[in] c received character
Definition at line 455 of file hal_uart_lld.h.
typedef void(* uartecb_t) (UARTDriver *uartp, uartflags_t e)
Receive error UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object
[in] e receive error mask
Definition at line 463 of file hal_uart_lld.h.
Enumeration Type Documentation
enum uartstate_t
Driver state machine possible states.
Enumerator
UART_UNINIT
Not initialized.
UART_STOP
Stopped.
UART_READY
Ready.
Definition at line 82 of file hal_uart.h.
enum uarttxstate_t
Transmitter state machine states.
Enumerator
UART_TX_IDLE
Not transmitting.
UART_TX_ACTIVE
Transmitting.
UART_TX_COMPLETE
Buffer complete.
Definition at line 91 of file hal_uart.h.
enum uartrxstate_t
Receiver state machine states.
Enumerator
UART_RX_IDLE
Not receiving.
UART_RX_ACTIVE
Receiving.
UART_RX_COMPLETE
Buffer complete.
Definition at line 100 of file hal_uart.h.
Function Documentation
static uartflags_t translate_errors (uint16_t sr) static
Status bits translation.
Parameters
[in] sr USART SR register value
Returns
The error flags.
Definition at line 138 of file hal_uart_lld.c.
References UART_BREAK_DETECTED, UART_FRAMING_ERROR, UART_NOISE_ERROR, UART_OVERRUN_ERROR, and UART_PARITY_ERROR.
Referenced by serve_usart_irq().
static void uart_enter_rx_idle_loop (UARTDriver * uartp) static
Puts the receiver in the UART_RX_IDLE state.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 159 of file hal_uart_lld.c.
References UARTDriver::config, UARTDriver::dmamode, UARTDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, UARTDriver::rxbuf, and UARTConfig::rxchar_cb.
Referenced by uart_lld_stop_receive(), and usart_start().
static void usart_stop (UARTDriver * uartp) static
USART de-initialization.
This function must be invoked with interrupts disabled.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 180 of file hal_uart_lld.c.
References UARTDriver::dmarx, dmaStreamDisable, UARTDriver::dmatx, and UARTDriver::usart.
Referenced by uart_lld_stop(), and usart_start().
static void usart_start (UARTDriver * uartp) static
USART initialization.
This function must be invoked with interrupts disabled.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 198 of file hal_uart_lld.c.
References UARTDriver::config, UARTConfig::cr1, UARTConfig::cr2, UARTConfig::cr3, UARTConfig::speed, STM32_PCLK1, STM32_PCLK2, uart_enter_rx_idle_loop(), UARTDriver::usart, and usart_stop().
Referenced by uart_lld_start().
static void uart_lld_serve_rx_end_irq (UARTDriver * uartp, uint32_t flags) static
RX DMA common service routine.
Parameters
[in] uartp pointer to the UARTDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 241 of file hal_uart_lld.c.
References _uart_rx_complete_isr_code, _uart_rx_idle_code, UARTDriver::dmarx, dmaStreamDisable, UARTDriver::rxstate, STM32_UART_DMA_ERROR_HOOK, and UART_RX_IDLE.
Referenced by uart_lld_start().
static void uart_lld_serve_tx_end_irq (UARTDriver * uartp, uint32_t flags) static
TX DMA common service routine.
Parameters
[in] uartp pointer to the UARTDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 271 of file hal_uart_lld.c.
References _uart_tx1_isr_code, dmaStreamDisable, UARTDriver::dmatx, and STM32_UART_DMA_ERROR_HOOK.
Referenced by uart_lld_start().
static void serve_usart_irq (UARTDriver * uartp) static
USART common service routine.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 293 of file hal_uart_lld.c.
References _uart_rx_error_isr_code, _uart_tx2_isr_code, translate_errors(), and UARTDriver::usart.
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_USART1_HANDLER)
USART1 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 330 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
OSAL_IRQ_HANDLER (STM32_USART2_HANDLER)
USART2 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 349 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
OSAL_IRQ_HANDLER (STM32_USART3_HANDLER)
USART3 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 368 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
OSAL_IRQ_HANDLER (STM32_UART4_HANDLER)
UART4 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 387 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
OSAL_IRQ_HANDLER (STM32_UART5_HANDLER)
UART5 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 406 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
OSAL_IRQ_HANDLER (STM32_USART6_HANDLER)
USART6 IRQ handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 425 of file hal_uart_lld.c.
References OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, and serve_usart_irq().
void uart_lld_init (void)
Low level UART driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 444 of file hal_uart_lld.c.
References UARTDriver::dmamode, UARTDriver::dmarx, UARTDriver::dmatx, STM32_DMA_CR_DMEIE, STM32_DMA_STREAM, uartObjectInit(), and UARTDriver::usart.
Referenced by uartInit().
void uart_lld_start (UARTDriver * uartp)
Configures and activates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 501 of file hal_uart_lld.c.
References UARTDriver::config, UARTConfig::cr1, UARTConfig::cr2, UARTConfig::cr3, UARTDriver::dmamode, UARTDriver::dmarx, dmaStreamAllocate(), dmaStreamSetPeripheral, UARTDriver::dmatx, osalDbgAssert, rccEnableUART4, rccEnableUART5, rccEnableUSART1, rccEnableUSART2, rccEnableUSART3, UARTDriver::rxbuf, UARTDriver::rxstate, UARTDriver::state, STM32_UART_UART4_DMA_PRIORITY, STM32_UART_UART4_IRQ_PRIORITY, STM32_UART_UART5_DMA_PRIORITY, STM32_UART_UART5_IRQ_PRIORITY, STM32_UART_USART1_DMA_PRIORITY, STM32_UART_USART1_IRQ_PRIORITY, STM32_UART_USART2_DMA_PRIORITY, STM32_UART_USART2_IRQ_PRIORITY, STM32_UART_USART3_DMA_PRIORITY, STM32_UART_USART3_IRQ_PRIORITY, STM32_UART_USART6_DMA_PRIORITY, STM32_UART_USART6_IRQ_PRIORITY, UARTDriver::txstate, uart_lld_serve_rx_end_irq(), uart_lld_serve_tx_end_irq(), UART_RX_IDLE, UART_STOP, UART_TX_IDLE, UARTDriver::usart, and usart_start().
Referenced by uartStart().
void uart_lld_stop (UARTDriver * uartp)
Deactivates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 657 of file hal_uart_lld.c.
References UARTDriver::dmarx, dmaStreamRelease(), UARTDriver::dmatx, rccDisableUART4, rccDisableUART5, rccDisableUSART1, rccDisableUSART2, rccDisableUSART3, UARTDriver::state, UART_READY, and usart_stop().
Referenced by uartStop().
void uart_lld_start_send (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 725 of file hal_uart_lld.c.
References UARTDriver::config, UARTDriver::dmamode, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, UARTDriver::dmatx, UARTDriver::early, UARTConfig::txend2_cb, and UARTDriver::usart.
Referenced by uartSendFullTimeout(), uartSendTimeout(), uartStartSend(), and uartStartSendI().
size_t uart_lld_stop_send (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Function Class:
Not an API, this function is for internal use only.
Definition at line 760 of file hal_uart_lld.c.
References dmaStreamDisable, dmaStreamGetTransactionSize, and UARTDriver::dmatx.
Referenced by uartStopSend(), and uartStopSendI().
void uart_lld_start_receive (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[out] rxbuf the pointer to the receive buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 778 of file hal_uart_lld.c.
References UARTDriver::dmamode, UARTDriver::dmarx, dmaStreamDisable, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, and dmaStreamSetTransactionSize.
Referenced by uartReceiveTimeout(), uartStartReceive(), and uartStartReceiveI().
size_t uart_lld_stop_receive (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Function Class:
Not an API, this function is for internal use only.
Definition at line 804 of file hal_uart_lld.c.
References UARTDriver::dmarx, dmaStreamDisable, dmaStreamGetTransactionSize, and uart_enter_rx_idle_loop().
Referenced by uartStopReceive(), and uartStopReceiveI().
void uartInit (void)
UART Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_uart.c.
References uart_lld_init().
Referenced by halInit().
void uartObjectInit (UARTDriver * uartp)
Initializes the standard part of a UARTDriver structure.
Parameters
[out] uartp pointer to the UARTDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_uart.c.
References UARTDriver::config, UARTDriver::early, UARTDriver::mutex, osalMutexObjectInit(), UARTDriver::rxstate, UARTDriver::state, UARTDriver::threadrx, UARTDriver::threadtx, UARTDriver::txstate, UART_RX_IDLE, UART_STOP, and UART_TX_IDLE.
Referenced by uart_lld_init().
void uartStart (UARTDriver * uartp, const UARTConfig * config)
Configures and activates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
[in] config pointer to the UARTConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 97 of file hal_uart.c.
References UARTDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::state, uart_lld_start(), UART_READY, and UART_STOP.
void uartStop (UARTDriver * uartp)
Deactivates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 118 of file hal_uart.c.
References UARTDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::rxstate, UARTDriver::state, UARTDriver::txstate, uart_lld_stop(), UART_READY, UART_RX_IDLE, UART_STOP, and UART_TX_IDLE.
void uartStartSend (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::state, UARTDriver::txstate, uart_lld_start_send(), UART_READY, and UART_TX_ACTIVE.
void uartStartSendI (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 172 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, UARTDriver::state, UARTDriver::txstate, uart_lld_start_send(), UART_READY, and UART_TX_ACTIVE.
size_t uartStopSend (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Return values
0 There was no transmit operation in progress.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 195 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::state, UARTDriver::txstate, uart_lld_stop_send(), UART_READY, UART_TX_ACTIVE, and UART_TX_IDLE.
size_t uartStopSendI (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Return values
0 There was no transmit operation in progress.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 228 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, UARTDriver::state, UARTDriver::txstate, uart_lld_stop_send(), UART_READY, UART_TX_ACTIVE, and UART_TX_IDLE.
Referenced by uartSendFullTimeout(), and uartSendTimeout().
void uartStartReceive (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to receive
[in] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 253 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::rxstate, UARTDriver::state, uart_lld_start_receive(), UART_READY, and UART_RX_ACTIVE.
void uartStartReceiveI (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to receive
[out] rxbuf the pointer to the receive buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 278 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, UARTDriver::rxstate, UARTDriver::state, uart_lld_start_receive(), UART_READY, and UART_RX_ACTIVE.
size_t uartStopReceive (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Return values
0 There was no receive operation in progress.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 301 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), UARTDriver::rxstate, UARTDriver::state, uart_lld_stop_receive(), UART_READY, UART_RX_ACTIVE, and UART_RX_IDLE.
size_t uartStopReceiveI (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Return values
0 There was no receive operation in progress.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 334 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, UARTDriver::rxstate, UARTDriver::state, uart_lld_stop_receive(), UART_READY, UART_RX_ACTIVE, and UART_RX_IDLE.
Referenced by uartReceiveTimeout().
msg_t uartSendTimeout (UARTDriver * uartp, size_t * np, const void * txbuf, sysinterval_t timeout)
Performs a transmission on the UART peripheral.
Note
The function returns when the specified number of frames have been sent to the UART or on timeout.
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function implements a software timeout, it does not use any underlying HW timeout mechanism.
Parameters
[in] uartp pointer to the UARTDriver object
[in,out] np number of data frames to transmit, on exit the number of frames actually transmitted
[in] txbuf the pointer to the transmit buffer
[in] timeout operation timeout
Returns
The operation status.
Return values
MSG_OK if the operation completed successfully.
MSG_TIMEOUT if the operation timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 369 of file hal_uart.c.
References UARTDriver::early, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendTimeoutS(), UARTDriver::state, UARTDriver::threadtx, UARTDriver::txstate, uart_lld_start_send(), UART_READY, UART_TX_ACTIVE, and uartStopSendI().
msg_t uartSendFullTimeout (UARTDriver * uartp, size_t * np, const void * txbuf, sysinterval_t timeout)
Performs a transmission on the UART peripheral.
Note
The function returns when the specified number of frames have been physically transmitted or on timeout.
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function implements a software timeout, it does not use any underlying HW timeout mechanism.
Parameters
[in] uartp pointer to the UARTDriver object
[in,out] np number of data frames to transmit, on exit the number of frames actually transmitted
[in] txbuf the pointer to the transmit buffer
[in] timeout operation timeout
Returns
The operation status.
Return values
MSG_OK if the operation completed successfully.
MSG_TIMEOUT if the operation timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 414 of file hal_uart.c.
References UARTDriver::early, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendTimeoutS(), UARTDriver::state, UARTDriver::threadtx, UARTDriver::txstate, uart_lld_start_send(), UART_READY, UART_TX_ACTIVE, and uartStopSendI().
msg_t uartReceiveTimeout (UARTDriver * uartp, size_t * np, void * rxbuf, sysinterval_t timeout)
Performs a receive operation on the UART peripheral.
Note
The function returns when the specified number of frames have been received or on error/timeout.
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function implements a software timeout, it does not use any underlying HW timeout mechanism.
Parameters
[in] uartp pointer to the UARTDriver object
[in,out] np number of data frames to receive, on exit the number of frames actually received
[in] rxbuf the pointer to the receive buffer
[in] timeout operation timeout
Returns
The operation status.
Return values
MSG_OK if the operation completed successfully.
MSG_TIMEOUT if the operation timed out.
MSG_RESET in case of a receive error.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 461 of file hal_uart.c.
References osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadSuspendTimeoutS(), UARTDriver::rxstate, UARTDriver::state, UARTDriver::threadrx, uart_lld_start_receive(), UART_READY, UART_RX_ACTIVE, and uartStopReceiveI().
void uartAcquireBus (UARTDriver * uartp)
Gains exclusive access to the UART bus.
This function tries to gain ownership to the UART bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option UART_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 498 of file hal_uart.c.
References UARTDriver::mutex, osalDbgCheck, and osalMutexLock().
void uartReleaseBus (UARTDriver * uartp)
Releases exclusive access to the UART bus.
Precondition
In order to use this function the option UART_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 514 of file hal_uart.c.
References UARTDriver::mutex, osalDbgCheck, and osalMutexUnlock().
Variable Documentation
UARTDriver UARTD1
USART1 UART driver identifier.
Definition at line 95 of file hal_uart_lld.c.
UARTDriver UARTD2
USART2 UART driver identifier.
Definition at line 100 of file hal_uart_lld.c.
UARTDriver UARTD3
USART3 UART driver identifier.
Definition at line 105 of file hal_uart_lld.c.
UARTDriver UARTD4
UART4 UART driver identifier.
Definition at line 110 of file hal_uart_lld.c.
UARTDriver UARTD5
UART5 UART driver identifier.
Definition at line 115 of file hal_uart_lld.c.
UARTDriver UARTD6
USART6 UART driver identifier.
Definition at line 120 of file hal_uart_lld.c.