ChibiOS/HAL: RTC Driver
RTC Driver
HAL » Normal Drivers
Generic RTC Driver.
Detailed Description
Generic RTC Driver.
This module defines an abstract interface for a Real Time Clock Peripheral.
Precondition
In order to use the RTC driver the HAL_USE_RTC option must be enabled in halconf.h.
Macros
#define _rtc_driver_methods _file_stream_methods
FileStream specific methods.
#define RTC_BASE_YEAR 1980U
Base year of the calendar.
Implementation capabilities
#define RTC_SUPPORTS_CALLBACKS TRUE
This RTC implementation supports callbacks.
#define RTC_ALARMS 1
One alarm comparator available.
#define RTC_HAS_STORAGE FALSE
Presence of a local persistent storage.
Configuration options
#define STM32_RTC_IRQ_PRIORITY 15
Date/Time bit masks for FAT format
#define RTC_FAT_TIME_SECONDS_MASK 0x0000001FU
#define RTC_FAT_TIME_MINUTES_MASK 0x000007E0U
#define RTC_FAT_TIME_HOURS_MASK 0x0000F800U
#define RTC_FAT_DATE_DAYS_MASK 0x001F0000U
#define RTC_FAT_DATE_MONTHS_MASK 0x01E00000U
#define RTC_FAT_DATE_YEARS_MASK 0xFE000000U
Day of week encoding
#define RTC_DAY_CATURDAY 0U
#define RTC_DAY_MONDAY 1U
#define RTC_DAY_TUESDAY 2U
#define RTC_DAY_WEDNESDAY 3U
#define RTC_DAY_THURSDAY 4U
#define RTC_DAY_FRIDAY 5U
#define RTC_DAY_SATURDAY 6U
#define RTC_DAY_SUNDAY 7U
Typedefs
typedef struct RTCAlarm RTCAlarm
Type of a structure representing an RTC alarm time stamp.
typedef uint32_t rtcalarm_t
Type of an RTC alarm.
typedef void(* rtccb_t) (RTCDriver *rtcp, rtcevent_t event)
Type of a generic RTC callback.
typedef struct RTCDriver RTCDriver
Type of a structure representing an RTC driver.
Data Structures
struct RTCAlarm
Structure representing an RTC alarm time stamp.
struct RTCDriverVMT
RTCDriver virtual methods table.
struct RTCDriver
Structure representing an RTC driver.
struct RTCDateTime
Type of a structure representing an RTC date/time stamp.
Functions
static void rtc_apb1_sync (void)
Wait for synchronization of RTC registers with APB1 bus.
static void rtc_wait_write_completed (void)
Wait for for previous write operation complete.
static void rtc_acquire_access (void)
Acquires write access to RTC registers.
static void rtc_release_access (void)
Releases write access to RTC registers.
static time_t rtc_encode (const RTCDateTime *timespec)
Converts time from timespec to seconds counter.
static void rtc_decode (uint32_t tv_sec, uint32_t tv_msec, RTCDateTime *timespec)
Converts time from seconds/milliseconds to timespec.
OSAL_IRQ_HANDLER (STM32_RTC1_HANDLER)
RTC interrupt handler.
void rtc_lld_set_prescaler (void)
Load value of RTCCLK to prescaler registers.
void rtc_lld_init (void)
Initialize RTC.
void rtc_lld_set_time (RTCDriver *rtcp, const RTCDateTime *timespec)
Set current time.
void rtc_lld_get_time (RTCDriver *rtcp, RTCDateTime *timespec)
Get current time.
void rtc_lld_set_alarm (RTCDriver *rtcp, rtcalarm_t alarm_number, const RTCAlarm *alarmspec)
Set alarm time.
void rtc_lld_get_alarm (RTCDriver *rtcp, rtcalarm_t alarm_number, RTCAlarm *alarmspec)
Get current alarm.
void rtc_lld_set_callback (RTCDriver *rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
void rtcSTM32GetSecMsec (RTCDriver *rtcp, uint32_t *tv_sec, uint32_t *tv_msec)
Get seconds and (optionally) milliseconds from RTC.
void rtcSTM32SetSec (RTCDriver *rtcp, uint32_t tv_sec)
Set seconds in RTC.
void rtcInit (void)
RTC Driver initialization.
void rtcObjectInit (RTCDriver *rtcp)
Initializes a generic RTC driver object.
void rtcSetTime (RTCDriver *rtcp, const RTCDateTime *timespec)
Set current time.
void rtcGetTime (RTCDriver *rtcp, RTCDateTime *timespec)
Get current time.
void rtcSetAlarm (RTCDriver *rtcp, rtcalarm_t alarm, const RTCAlarm *alarmspec)
Set alarm time.
void rtcGetAlarm (RTCDriver *rtcp, rtcalarm_t alarm, RTCAlarm *alarmspec)
Get current alarm.
void rtcSetCallback (RTCDriver *rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
void rtcConvertDateTimeToStructTm (const RTCDateTime *timespec, struct tm *timp, uint32_t *tv_msec)
Convert RTCDateTime to broken-down time structure.
void rtcConvertStructTmToDateTime (const struct tm *timp, uint32_t tv_msec, RTCDateTime *timespec)
Convert broken-down time structure to RTCDateTime.
uint32_t rtcConvertDateTimeToFAT (const RTCDateTime *timespec)
Get current time in format suitable for usage in FAT file system.
Enumerations
Variables
RTCDriver RTCD1
RTC driver identifier.
Macro Definition Documentation
#define RTC_SUPPORTS_CALLBACKS TRUE
This RTC implementation supports callbacks.
Definition at line 44 of file hal_rtc_lld.h.
#define RTC_ALARMS 1
One alarm comparator available.
Definition at line 49 of file hal_rtc_lld.h.
Referenced by rtcGetAlarm(), and rtcSetAlarm().
#define RTC_HAS_STORAGE FALSE
Presence of a local persistent storage.
Definition at line 54 of file hal_rtc_lld.h.
#define _rtc_driver_methods _file_stream_methods
FileStream specific methods.
Definition at line 90 of file hal_rtc_lld.h.
#define RTC_BASE_YEAR 1980U
Base year of the calendar.
Definition at line 45 of file hal_rtc.h.
Typedef Documentation
typedef struct RTCAlarm RTCAlarm
Type of a structure representing an RTC alarm time stamp.
Definition at line 96 of file hal_rtc_lld.h.
typedef uint32_t rtcalarm_t
Type of an RTC alarm.
Meaningful on platforms with more than 1 alarm comparator.
Definition at line 102 of file hal_rtc_lld.h.
typedef void(* rtccb_t) (RTCDriver *rtcp, rtcevent_t event)
Type of a generic RTC callback.
Definition at line 116 of file hal_rtc_lld.h.
typedef struct RTCDriver RTCDriver
Type of a structure representing an RTC driver.
Definition at line 88 of file hal_rtc.h.
Enumeration Type Documentation
enum rtcevent_t
Type of an RTC event.
Enumerator
RTC_EVENT_ALARM
Triggered every second.
RTC_EVENT_OVERFLOW
Triggered on alarm.
Definition at line 107 of file hal_rtc_lld.h.
Function Documentation
static void rtc_apb1_sync (void) static
Wait for synchronization of RTC registers with APB1 bus.
This function must be invoked before trying to read RTC registers in the backup domain: DIV, CNT, ALR. CR registers can always be read.
Function Class:
Not an API, this function is for internal use only.
Definition at line 62 of file hal_rtc_lld.c.
Referenced by OSAL_IRQ_HANDLER(), rtc_lld_get_alarm(), rtc_lld_init(), and rtcSTM32GetSecMsec().
static void rtc_wait_write_completed (void) static
Wait for for previous write operation complete.
This function must be invoked before writing to any RTC registers
Function Class:
Not an API, this function is for internal use only.
Definition at line 74 of file hal_rtc_lld.c.
Referenced by rtc_acquire_access(), rtc_lld_init(), rtc_lld_set_callback(), and rtcSTM32GetSecMsec().
static void rtc_acquire_access (void) static
Acquires write access to RTC registers.
Before writing to the backup domain RTC registers the previous write operation must be completed. Use this function before writing to PRL, CNT, ALR registers.
Function Class:
Not an API, this function is for internal use only.
Definition at line 88 of file hal_rtc_lld.c.
References rtc_wait_write_completed().
Referenced by rtc_lld_set_alarm(), rtc_lld_set_prescaler(), and rtcSTM32SetSec().
static void rtc_release_access (void) static
Releases write access to RTC registers.
Function Class:
Not an API, this function is for internal use only.
Definition at line 99 of file hal_rtc_lld.c.
Referenced by rtc_lld_set_alarm(), rtc_lld_set_prescaler(), and rtcSTM32SetSec().
static time_t rtc_encode (const RTCDateTime * timespec) static
Converts time from timespec to seconds counter.
Parameters
[in] timespec pointer to a RTCDateTime structure
Returns
the TR register encoding.
Function Class:
Not an API, this function is for internal use only.
Definition at line 112 of file hal_rtc_lld.c.
References rtcConvertDateTimeToStructTm().
Referenced by rtc_lld_set_time().
static void rtc_decode (uint32_t tv_sec, uint32_t tv_msec, RTCDateTime * timespec) static
Converts time from seconds/milliseconds to timespec.
Parameters
[in] tv_sec seconds value
[in] tv_msec milliseconds value
[out] timespec pointer to a RTCDateTime structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 128 of file hal_rtc_lld.c.
References osalDbgAssert, and rtcConvertStructTmToDateTime().
Referenced by rtc_lld_get_time().
OSAL_IRQ_HANDLER (STM32_RTC1_HANDLER)
RTC interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 156 of file hal_rtc_lld.c.
References RTCDriver::callback, OSAL_IRQ_EPILOGUE, OSAL_IRQ_PROLOGUE, RTCDriver::rtc, rtc_apb1_sync(), RTC_EVENT_ALARM, and RTC_EVENT_OVERFLOW.
void rtc_lld_set_prescaler (void)
Load value of RTCCLK to prescaler registers.
Note
The pre-scaler must not be set on every reset as RTC clock counts are lost when it is set.
This function designed to be called from hal_lld_backup_domain_init(). Because there is only place where possible to detect BKP domain reset event reliably.
Function Class:
Not an API, this function is for internal use only.
Definition at line 195 of file hal_rtc_lld.c.
References osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), rtc_acquire_access(), rtc_release_access(), and STM32_RTCCLK.
Referenced by hal_lld_backup_domain_init().
void rtc_lld_init (void)
Initialize RTC.
Function Class:
Not an API, this function is for internal use only.
Definition at line 215 of file hal_rtc_lld.c.
References RTCDriver::callback, RTCDriver::rtc, rtc_apb1_sync(), rtc_wait_write_completed(), and rtcObjectInit().
Referenced by rtcInit().
void rtc_lld_set_time (RTCDriver * rtcp, const RTCDateTime * timespec)
Set current time.
Note
Fractional part will be silently ignored. There is no possibility to change it on STM32F1xx platform.
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[in] timespec pointer to a RTCDateTime structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 252 of file hal_rtc_lld.c.
References rtc_encode(), and rtcSTM32SetSec().
Referenced by rtcSetTime().
void rtc_lld_get_time (RTCDriver * rtcp, RTCDateTime * timespec)
Get current time.
Note
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[in] timespec pointer to a RTCDateTime structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 267 of file hal_rtc_lld.c.
References rtc_decode(), and rtcSTM32GetSecMsec().
Referenced by rtcGetTime().
void rtc_lld_set_alarm (RTCDriver * rtcp, rtcalarm_t alarm_number, const RTCAlarm * alarmspec)
Set alarm time.
Note
Default value after BKP domain reset is 0xFFFFFFFF
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[in] alarmspec pointer to a RTCAlarm structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 286 of file hal_rtc_lld.c.
References osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), RTCDriver::rtc, rtc_acquire_access(), rtc_release_access(), and RTCAlarm::tv_sec.
Referenced by rtcSetAlarm().
void rtc_lld_get_alarm (RTCDriver * rtcp, rtcalarm_t alarm_number, RTCAlarm * alarmspec)
Get current alarm.
Note
If an alarm has not been set then the returned alarm specification is not meaningful.
The function can be called from any context.
Default value after BKP domain reset is 0xFFFFFFFF.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[out] alarmspec pointer to a RTCAlarm structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 323 of file hal_rtc_lld.c.
References osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), RTCDriver::rtc, rtc_apb1_sync(), and RTCAlarm::tv_sec.
Referenced by rtcGetAlarm().
void rtc_lld_set_callback (RTCDriver * rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
This function enables or disables callbacks, use a NULL pointer in order to disable a callback.
Note
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[in] callback callback function pointer or NULL
Function Class:
Not an API, this function is for internal use only.
Definition at line 352 of file hal_rtc_lld.c.
References RTCDriver::callback, osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), RTCDriver::rtc, and rtc_wait_write_completed().
Referenced by rtcSetCallback().
void rtcSTM32GetSecMsec (RTCDriver * rtcp, uint32_t * tv_sec, uint32_t * tv_msec)
Get seconds and (optionally) milliseconds from RTC.
Note
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[out] tv_sec pointer to seconds value
[out] tv_msec pointer to milliseconds value, set it to NULL if not needed
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 390 of file hal_rtc_lld.c.
References osalDbgCheck, osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), RTCDriver::rtc, rtc_apb1_sync(), rtc_wait_write_completed(), and STM32_RTCCLK.
Referenced by rtc_lld_get_time().
void rtcSTM32SetSec (RTCDriver * rtcp, uint32_t tv_sec)
Set seconds in RTC.
Note
The function can be called from any context.
Parameters
[in] rtcp pointer to RTC driver structure
[in] tv_sec seconds value
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 427 of file hal_rtc_lld.c.
References osalDbgCheck, osalSysGetStatusAndLockX(), osalSysRestoreStatusX(), RTCDriver::rtc, rtc_acquire_access(), and rtc_release_access().
Referenced by rtc_lld_set_time().
void rtcInit (void)
RTC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 67 of file hal_rtc.c.
References rtc_lld_init().
Referenced by halInit().
void rtcObjectInit (RTCDriver * rtcp)
Initializes a generic RTC driver object.
The HW dependent part of the initialization has to be performed outside, usually in the hardware initialization code.
Parameters
[out] rtcp pointer to RTC driver structure
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 81 of file hal_rtc.c.
References RTCDriver::vmt.
Referenced by rtc_lld_init().
void rtcSetTime (RTCDriver * rtcp, const RTCDateTime * timespec)
Set current time.
Note
This function can be called from any context but limitations could be imposed by the low level implementation. It is guaranteed that the function can be called from thread context.
The function can be reentrant or not reentrant depending on the low level implementation.
Parameters
[in] rtcp pointer to RTC driver structure
[in] timespec pointer to a RTCDateTime structure
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 104 of file hal_rtc.c.
References osalDbgCheck, and rtc_lld_set_time().
void rtcGetTime (RTCDriver * rtcp, RTCDateTime * timespec)
Get current time.
Note
This function can be called from any context but limitations could be imposed by the low level implementation. It is guaranteed that the function can be called from thread context.
The function can be reentrant or not reentrant depending on the low level implementation.
Parameters
[in] rtcp pointer to RTC driver structure
[out] timespec pointer to a RTCDateTime structure
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 125 of file hal_rtc.c.
References osalDbgCheck, and rtc_lld_get_time().
void rtcSetAlarm (RTCDriver * rtcp, rtcalarm_t alarm, const RTCAlarm * alarmspec)
Set alarm time.
Note
This function can be called from any context but limitations could be imposed by the low level implementation. It is guaranteed that the function can be called from thread context.
The function can be reentrant or not reentrant depending on the low level implementation.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[in] alarmspec pointer to a RTCAlarm structure or NULL
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 148 of file hal_rtc.c.
References osalDbgCheck, RTC_ALARMS, and rtc_lld_set_alarm().
void rtcGetAlarm (RTCDriver * rtcp, rtcalarm_t alarm, RTCAlarm * alarmspec)
Get current alarm.
Note
If an alarm has not been set then the returned alarm specification is not meaningful.
This function can be called from any context but limitations could be imposed by the low level implementation. It is guaranteed that the function can be called from thread context.
The function can be reentrant or not reentrant depending on the low level implementation.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[out] alarmspec pointer to a RTCAlarm structure
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 174 of file hal_rtc.c.
References osalDbgCheck, RTC_ALARMS, and rtc_lld_get_alarm().
void rtcSetCallback (RTCDriver * rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
This function enables or disables the callback, use a NULL pointer in order to disable it.
Note
This function can be called from any context but limitations could be imposed by the low level implementation. It is guaranteed that the function can be called from thread context.
The function can be reentrant or not reentrant depending on the low level implementation.
Parameters
[in] rtcp pointer to RTC driver structure
[in] callback callback function pointer or NULL
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 203 of file hal_rtc.c.
References osalDbgCheck, and rtc_lld_set_callback().
void rtcConvertDateTimeToStructTm (const RTCDateTime * timespec, struct tm * timp, uint32_t * tv_msec)
Convert RTCDateTime to broken-down time structure.
Parameters
[in] timespec pointer to a RTCDateTime structure
[out] timp pointer to a broken-down time structure
[out] tv_msec pointer to milliseconds value or NULL
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 220 of file hal_rtc.c.
References RTCDateTime::day, RTCDateTime::dayofweek, RTCDateTime::dstflag, RTCDateTime::millisecond, RTCDateTime::month, and RTCDateTime::year.
Referenced by rtc_encode().
void rtcConvertStructTmToDateTime (const struct tm * timp, uint32_t tv_msec, RTCDateTime * timespec)
Convert broken-down time structure to RTCDateTime.
Parameters
[in] timp pointer to a broken-down time structure
[in] tv_msec milliseconds value
[out] timespec pointer to a RTCDateTime structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 251 of file hal_rtc.c.
References RTCDateTime::day, RTCDateTime::dayofweek, RTCDateTime::dstflag, RTCDateTime::millisecond, RTCDateTime::month, and RTCDateTime::year.
Referenced by rtc_decode().
uint32_t rtcConvertDateTimeToFAT (const RTCDateTime * timespec)
Get current time in format suitable for usage in FAT file system.
Note
The information about day of week and DST is lost in DOS format, the second field loses its least significant bit.
Parameters
[out] timespec pointer to a RTCDateTime structure
Returns
FAT date/time value.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 284 of file hal_rtc.c.
References RTCDateTime::day, RTCDateTime::dstflag, RTCDateTime::millisecond, RTCDateTime::month, and RTCDateTime::year.
Variable Documentation
RTCDriver RTCD1
RTC driver identifier.
Definition at line 44 of file hal_rtc_lld.c.