ChibiOS/HAL: ICU Driver
ICU Driver
HAL » Normal Drivers
Generic ICU Driver.
Detailed Description
Generic ICU Driver.
This module implements a generic ICU (Input Capture Unit) driver. The purpose of the driver is to measure period and duty cycle of an input digital signal (PWM input).
Precondition
In order to use the ICU driver the HAL_USE_ICU option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
ICU Operations.
This driver abstracts a generic Input Capture Unit composed of:
A clock prescaler.
A main up counter.
Two capture registers triggered by the rising and falling edges on the sampled input.
The ICU unit can be programmed to synchronize on the rising or falling edge of the sample input:
ICU_INPUT_ACTIVE_HIGH, a rising edge is the start signal.
ICU_INPUT_ACTIVE_LOW, a falling edge is the start signal.
Callbacks are optionally invoked when:
On the PWM de-activation edge.
On the PWM activation edge, measurements for the previous cycle are available from this callback and can be retrieved using icuGetPeriodX() and icuGetWidthX().
Macros
#define icu_lld_get_width(icup) (*((icup)->wccrp) + 1)
Returns the width of the latest pulse.
#define icu_lld_get_period(icup) (*((icup)->pccrp) + 1)
Returns the width of the latest cycle.
#define icu_lld_are_notifications_enabled(icup) (bool)(((icup)->tim->DIER & STM32_TIM_DIER_IRQ_MASK) != 0)
Check on notifications status.
Configuration options
#define STM32_ICU_USE_TIM1 FALSE
ICUD1 driver enable switch.
#define STM32_ICU_USE_TIM2 FALSE
ICUD2 driver enable switch.
#define STM32_ICU_USE_TIM3 FALSE
ICUD3 driver enable switch.
#define STM32_ICU_USE_TIM4 FALSE
ICUD4 driver enable switch.
#define STM32_ICU_USE_TIM5 FALSE
ICUD5 driver enable switch.
#define STM32_ICU_USE_TIM8 FALSE
ICUD8 driver enable switch.
#define STM32_ICU_USE_TIM9 FALSE
ICUD9 driver enable switch.
#define STM32_ICU_TIM1_IRQ_PRIORITY 7
ICUD1 interrupt priority level setting.
#define STM32_ICU_TIM2_IRQ_PRIORITY 7
ICUD2 interrupt priority level setting.
#define STM32_ICU_TIM3_IRQ_PRIORITY 7
ICUD3 interrupt priority level setting.
#define STM32_ICU_TIM4_IRQ_PRIORITY 7
ICUD4 interrupt priority level setting.
#define STM32_ICU_TIM5_IRQ_PRIORITY 7
ICUD5 interrupt priority level setting.
#define STM32_ICU_TIM8_IRQ_PRIORITY 7
ICUD8 interrupt priority level setting.
#define STM32_ICU_TIM9_IRQ_PRIORITY 7
ICUD9 interrupt priority level setting.
Macro Functions
#define icuStartCaptureI(icup)
Starts the input capture.
#define icuStopCaptureI(icup)
Stops the input capture.
#define icuEnableNotificationsI(icup) icu_lld_enable_notifications(icup)
Enables notifications.
#define icuDisableNotificationsI(icup) icu_lld_disable_notifications(icup)
Disables notifications.
#define icuAreNotificationsEnabledX(icup) icu_lld_are_notifications_enabled(icup)
Check on notifications status.
#define icuGetWidthX(icup) icu_lld_get_width(icup)
Returns the width of the latest pulse.
#define icuGetPeriodX(icup) icu_lld_get_period(icup)
Returns the width of the latest cycle.
Low level driver helper macros
#define _icu_isr_invoke_width_cb(icup)
Common ISR code, ICU width event.
#define _icu_isr_invoke_period_cb(icup)
Common ISR code, ICU period event.
#define _icu_isr_invoke_overflow_cb(icup)
Common ISR code, ICU timer overflow event.
Typedefs
typedef uint32_t icufreq_t
ICU frequency type.
typedef uint32_t icucnt_t
ICU counter type.
typedef struct ICUDriver ICUDriver
Type of a structure representing an ICU driver.
typedef void(* icucallback_t) (ICUDriver *icup)
ICU notification callback type.
Data Structures
struct ICUConfig
Driver configuration structure.
struct ICUDriver
Structure representing an ICU driver.
Functions
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM1 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM1_CC_HANDLER)
TIM1 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM8_CC_HANDLER)
TIM8 compare interrupt handler.
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
void icu_lld_init (void)
Low level ICU driver initialization.
void icu_lld_start (ICUDriver *icup)
Configures and activates the ICU peripheral.
void icu_lld_stop (ICUDriver *icup)
Deactivates the ICU peripheral.
void icu_lld_start_capture (ICUDriver *icup)
Starts the input capture.
bool icu_lld_wait_capture (ICUDriver *icup)
Waits for a completed capture.
void icu_lld_stop_capture (ICUDriver *icup)
Stops the input capture.
void icu_lld_enable_notifications (ICUDriver *icup)
Enables notifications.
void icu_lld_disable_notifications (ICUDriver *icup)
Disables notifications.
void icu_lld_serve_interrupt (ICUDriver *icup)
Shared IRQ handler.
void icuInit (void)
ICU Driver initialization.
void icuObjectInit (ICUDriver *icup)
Initializes the standard part of a ICUDriver structure.
void icuStart (ICUDriver *icup, const ICUConfig *config)
Configures and activates the ICU peripheral.
void icuStop (ICUDriver *icup)
Deactivates the ICU peripheral.
void icuStartCapture (ICUDriver *icup)
Starts the input capture.
bool icuWaitCapture (ICUDriver *icup)
Waits for a completed capture.
void icuStopCapture (ICUDriver *icup)
Stops the input capture.
void icuEnableNotifications (ICUDriver *icup)
Enables notifications.
void icuDisableNotifications (ICUDriver *icup)
Disables notifications.
Enumerations
Variables
ICUDriver ICUD1
ICUD1 driver identifier.
ICUDriver ICUD2
ICUD2 driver identifier.
ICUDriver ICUD3
ICUD3 driver identifier.
ICUDriver ICUD4
ICUD4 driver identifier.
ICUDriver ICUD5
ICUD5 driver identifier.
ICUDriver ICUD8
ICUD8 driver identifier.
ICUDriver ICUD9
ICUD9 driver identifier.
Macro Definition Documentation
#define STM32_ICU_USE_TIM1 FALSE
ICUD1 driver enable switch.
If set to TRUE the support for ICUD1 is included.
Note
The default is TRUE.
Definition at line 50 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM2 FALSE
ICUD2 driver enable switch.
If set to TRUE the support for ICUD2 is included.
Note
The default is TRUE.
Definition at line 59 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM3 FALSE
ICUD3 driver enable switch.
If set to TRUE the support for ICUD3 is included.
Note
The default is TRUE.
Definition at line 68 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM4 FALSE
ICUD4 driver enable switch.
If set to TRUE the support for ICUD4 is included.
Note
The default is TRUE.
Definition at line 77 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM5 FALSE
ICUD5 driver enable switch.
If set to TRUE the support for ICUD5 is included.
Note
The default is TRUE.
Definition at line 86 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM8 FALSE
ICUD8 driver enable switch.
If set to TRUE the support for ICUD8 is included.
Note
The default is TRUE.
Definition at line 95 of file hal_icu_lld.h.
#define STM32_ICU_USE_TIM9 FALSE
ICUD9 driver enable switch.
If set to TRUE the support for ICUD9 is included.
Note
The default is TRUE.
Definition at line 104 of file hal_icu_lld.h.
#define STM32_ICU_TIM1_IRQ_PRIORITY 7
ICUD1 interrupt priority level setting.
Definition at line 111 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM2_IRQ_PRIORITY 7
ICUD2 interrupt priority level setting.
Definition at line 118 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM3_IRQ_PRIORITY 7
ICUD3 interrupt priority level setting.
Definition at line 125 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM4_IRQ_PRIORITY 7
ICUD4 interrupt priority level setting.
Definition at line 132 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM5_IRQ_PRIORITY 7
ICUD5 interrupt priority level setting.
Definition at line 139 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM8_IRQ_PRIORITY 7
ICUD8 interrupt priority level setting.
Definition at line 146 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define STM32_ICU_TIM9_IRQ_PRIORITY 7
ICUD9 interrupt priority level setting.
Definition at line 153 of file hal_icu_lld.h.
Referenced by icu_lld_start().
#define icu_lld_get_width (icup) (*((icup)->wccrp) + 1)
Returns the width of the latest pulse.
The pulse width is defined as number of ticks between the start edge and the stop edge.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Not an API, this function is for internal use only.
Definition at line 408 of file hal_icu_lld.h.
#define icu_lld_get_period (icup) (*((icup)->pccrp) + 1)
Returns the width of the latest cycle.
The cycle width is defined as number of ticks between a start edge and the next start edge.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Not an API, this function is for internal use only.
Definition at line 420 of file hal_icu_lld.h.
#define icu_lld_are_notifications_enabled (icup) (bool)(((icup)->tim->DIER & STM32_TIM_DIER_IRQ_MASK) != 0)
Check on notifications status.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The notifications status.
Return values
false if notifications are not enabled.
true if notifications are enabled.
Function Class:
Not an API, this function is for internal use only.
Definition at line 432 of file hal_icu_lld.h.
#define icuStartCaptureI (icup)
Value:
do {                                         \
  icu_lld_start_capture(icup);                                              \
  (icup)->state = ICU_WAITING;                                              \
} while (false)
Starts the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 86 of file hal_icu.h.
Referenced by icuStartCapture().
#define icuStopCaptureI (icup)
Value:
do {                                          \
  icu_lld_stop_capture(icup);                                               \
  (icup)->state = ICU_READY;                                                \
} while (false)
Stops the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 98 of file hal_icu.h.
Referenced by icuStopCapture().
#define icuEnableNotificationsI (icup) icu_lld_enable_notifications(icup)
Enables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 112 of file hal_icu.h.
Referenced by icuEnableNotifications().
#define icuDisableNotificationsI (icup) icu_lld_disable_notifications(icup)
Disables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 123 of file hal_icu.h.
Referenced by icuDisableNotifications().
#define icuAreNotificationsEnabledX (icup) icu_lld_are_notifications_enabled(icup)
Check on notifications status.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The notifications status.
Return values
false if notifications are not enabled.
true if notifications are enabled.
Function Class:
Not an API, this function is for internal use only.
Definition at line 135 of file hal_icu.h.
Referenced by icuWaitCapture().
#define icuGetWidthX (icup) icu_lld_get_width(icup)
Returns the width of the latest pulse.
The pulse width is defined as number of ticks between the start edge and the stop edge.
Note
This function is meant to be invoked from the width capture callback.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 150 of file hal_icu.h.
#define icuGetPeriodX (icup) icu_lld_get_period(icup)
Returns the width of the latest cycle.
The cycle width is defined as number of ticks between a start edge and the next start edge.
Note
This function is meant to be invoked from the width capture callback.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 164 of file hal_icu.h.
#define _icu_isr_invoke_width_cb (icup)
Value:
do {                                 \
  if (((icup)->state == ICU_ACTIVE) &&                                      \
      ((icup)->config->width_cb != NULL))                                   \
    (icup)->config->width_cb(icup);                                         \
} while (0)
Common ISR code, ICU width event.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 178 of file hal_icu.h.
Referenced by icu_lld_serve_interrupt().
#define _icu_isr_invoke_period_cb (icup)
Value:
do {                                \
  if (((icup)->state == ICU_ACTIVE) &&                                      \
      ((icup)->config->period_cb != NULL))                                  \
    (icup)->config->period_cb(icup);                                        \
  (icup)->state = ICU_ACTIVE;                                               \
} while (0)
Common ISR code, ICU period event.
Note
A period event brings the driver into the ICU_ACTIVE state.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 192 of file hal_icu.h.
Referenced by icu_lld_serve_interrupt().
#define _icu_isr_invoke_overflow_cb (icup)
Value:
do {                              \
  (icup)->config->overflow_cb(icup);                                        \
  (icup)->state = ICU_WAITING;                                              \
} while (0)
Common ISR code, ICU timer overflow event.
Note
An overflow always brings the driver back to the ICU_WAITING state.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 208 of file hal_icu.h.
Referenced by icu_lld_serve_interrupt().
Typedef Documentation
typedef uint32_t icufreq_t
ICU frequency type.
Definition at line 304 of file hal_icu_lld.h.
typedef uint32_t icucnt_t
ICU counter type.
Definition at line 317 of file hal_icu_lld.h.
typedef struct ICUDriver ICUDriver
Type of a structure representing an ICU driver.
Definition at line 60 of file hal_icu.h.
typedef void(* icucallback_t) (ICUDriver *icup)
ICU notification callback type.
Parameters
[in] icup pointer to a ICUDriver object
Definition at line 67 of file hal_icu.h.
Enumeration Type Documentation
enum icumode_t
ICU driver mode.
Enumerator
ICU_INPUT_ACTIVE_HIGH
Trigger on rising edge.
ICU_INPUT_ACTIVE_LOW
Trigger on falling edge.
Definition at line 296 of file hal_icu_lld.h.
enum icuchannel_t
ICU channel type.
Enumerator
ICU_CHANNEL_1
Use TIMxCH1.
ICU_CHANNEL_2
Use TIMxCH2.
Definition at line 309 of file hal_icu_lld.h.
enum icustate_t
Driver state machine possible states.
Enumerator
ICU_UNINIT
Not initialized.
ICU_STOP
Stopped.
ICU_READY
Ready.
ICU_WAITING
Waiting for first front.
ICU_ACTIVE
First front detected.
Definition at line 49 of file hal_icu.h.
Function Documentation
OSAL_IRQ_HANDLER (STM32_TIM1_UP_HANDLER)
TIM1 compare interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 155 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM1_CC_HANDLER)
TIM1 compare interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 172 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM2_HANDLER)
TIM2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 193 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM3_HANDLER)
TIM3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 214 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM4_HANDLER)
TIM4 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 235 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM5_HANDLER)
TIM5 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 256 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM8_UP_HANDLER)
TIM8 compare interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 277 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM8_CC_HANDLER)
TIM8 compare interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 294 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_TIM9_HANDLER)
TIM9 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 315 of file hal_icu_lld.c.
References icu_lld_serve_interrupt(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
void icu_lld_init (void)
Low level ICU driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 335 of file hal_icu_lld.c.
References icuObjectInit(), and ICUDriver::tim.
Referenced by icuInit().
void icu_lld_start (ICUDriver * icup)
Configures and activates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 387 of file hal_icu_lld.c.
References ICUConfig::channel, ICUDriver::clock, ICUDriver::config, ICUConfig::dier, ICUConfig::frequency, ICU_CHANNEL_1, ICU_CHANNEL_2, ICU_INPUT_ACTIVE_HIGH, ICU_STOP, ICUConfig::mode, osalDbgAssert, ICUDriver::pccrp, rccEnableTIM1, rccEnableTIM2, rccEnableTIM3, rccEnableTIM4, rccEnableTIM5, rccEnableTIM8, rccEnableTIM9, rccResetTIM1, rccResetTIM2, rccResetTIM3, rccResetTIM4, rccResetTIM5, rccResetTIM8, rccResetTIM9, ICUDriver::state, STM32_ICU_TIM1_IRQ_PRIORITY, STM32_ICU_TIM2_IRQ_PRIORITY, STM32_ICU_TIM3_IRQ_PRIORITY, STM32_ICU_TIM4_IRQ_PRIORITY, STM32_ICU_TIM5_IRQ_PRIORITY, STM32_ICU_TIM8_IRQ_PRIORITY, STM32_ICU_TIM9_IRQ_PRIORITY, STM32_TIMCLK1, STM32_TIMCLK2, ICUDriver::tim, and ICUDriver::wccrp.
Referenced by icuStart().
void icu_lld_stop (ICUDriver * icup)
Deactivates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 581 of file hal_icu_lld.c.
References ICU_READY, rccDisableTIM1, rccDisableTIM2, rccDisableTIM3, rccDisableTIM4, rccDisableTIM5, rccDisableTIM8, rccDisableTIM9, ICUDriver::state, and ICUDriver::tim.
Referenced by icuStop().
void icu_lld_start_capture (ICUDriver * icup)
Starts the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 663 of file hal_icu_lld.c.
References ICUDriver::tim.
bool icu_lld_wait_capture (ICUDriver * icup)
Waits for a completed capture.
Note
The operation is performed in polled mode.
In order to use this function notifications must be disabled.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The capture status.
Return values
false if the capture is successful.
true if a timer overflow occurred.
Function Class:
Not an API, this function is for internal use only.
Definition at line 685 of file hal_icu_lld.c.
References ICU_WAITING, and ICUDriver::state.
Referenced by icuWaitCapture().
void icu_lld_stop_capture (ICUDriver * icup)
Stops the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 704 of file hal_icu_lld.c.
References ICUDriver::tim.
void icu_lld_enable_notifications (ICUDriver * icup)
Enables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 722 of file hal_icu_lld.c.
References ICUConfig::channel, ICUDriver::config, ICU_CHANNEL_1, ICUConfig::overflow_cb, ICUDriver::tim, and ICUConfig::width_cb.
void icu_lld_disable_notifications (ICUDriver * icup)
Disables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 768 of file hal_icu_lld.c.
References ICUDriver::tim.
void icu_lld_serve_interrupt (ICUDriver * icup)
Shared IRQ handler.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 781 of file hal_icu_lld.c.
References _icu_isr_invoke_overflow_cb, _icu_isr_invoke_period_cb, _icu_isr_invoke_width_cb, ICUConfig::channel, ICUDriver::config, ICU_CHANNEL_1, and ICUDriver::tim.
Referenced by OSAL_IRQ_HANDLER().
void icuInit (void)
ICU Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_icu.c.
References icu_lld_init().
Referenced by halInit().
void icuObjectInit (ICUDriver * icup)
Initializes the standard part of a ICUDriver structure.
Parameters
[out] icup pointer to the ICUDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_icu.c.
References ICUDriver::config, ICU_STOP, and ICUDriver::state.
Referenced by icu_lld_init().
void icuStart (ICUDriver * icup, const ICUConfig * config)
Configures and activates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
[in] config pointer to the ICUConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 82 of file hal_icu.c.
References ICUDriver::config, icu_lld_start(), ICU_READY, ICU_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
void icuStop (ICUDriver * icup)
Deactivates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 102 of file hal_icu.c.
References ICUDriver::config, icu_lld_stop(), ICU_READY, ICU_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
void icuStartCapture (ICUDriver * icup)
Starts the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 125 of file hal_icu.c.
References ICU_READY, icuStartCaptureI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
bool icuWaitCapture (ICUDriver * icup)
Waits for a completed capture.
Note
The operation could be performed in polled mode depending on.
In order to use this function notifications must be disabled.
Precondition
The driver must be in ICU_WAITING or ICU_ACTIVE states.
Postcondition
After the capture is available the driver is in ICU_ACTIVE state. If a capture fails then the driver is in ICU_WAITING state.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The capture status.
Return values
false if the capture is successful.
true if a timer overflow occurred.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 151 of file hal_icu.c.
References ICU_ACTIVE, icu_lld_wait_capture(), ICU_WAITING, icuAreNotificationsEnabledX, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
void icuStopCapture (ICUDriver * icup)
Stops the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 175 of file hal_icu.c.
References ICU_ACTIVE, ICU_READY, ICU_WAITING, icuStopCaptureI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
void icuEnableNotifications (ICUDriver * icup)
Enables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already enabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 196 of file hal_icu.c.
References ICU_ACTIVE, ICU_WAITING, icuEnableNotificationsI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
void icuDisableNotifications (ICUDriver * icup)
Disables notifications.
Precondition
The ICU unit must have been activated using icuStart().
Note
If the notification is already disabled then the call has no effect.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 216 of file hal_icu.c.
References ICU_ACTIVE, ICU_WAITING, icuDisableNotificationsI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ICUDriver::state.
Variable Documentation
ICUDriver ICUD1
ICUD1 driver identifier.
Note
The driver ICUD1 allocates the complex timer TIM1 when enabled.
Definition at line 46 of file hal_icu_lld.c.
ICUDriver ICUD2
ICUD2 driver identifier.
Note
The driver ICUD1 allocates the timer TIM2 when enabled.
Definition at line 54 of file hal_icu_lld.c.
ICUDriver ICUD3
ICUD3 driver identifier.
Note
The driver ICUD1 allocates the timer TIM3 when enabled.
Definition at line 62 of file hal_icu_lld.c.
ICUDriver ICUD4
ICUD4 driver identifier.
Note
The driver ICUD4 allocates the timer TIM4 when enabled.
Definition at line 70 of file hal_icu_lld.c.
ICUDriver ICUD5
ICUD5 driver identifier.
Note
The driver ICUD5 allocates the timer TIM5 when enabled.
Definition at line 78 of file hal_icu_lld.c.
ICUDriver ICUD8
ICUD8 driver identifier.
Note
The driver ICUD8 allocates the timer TIM8 when enabled.
Definition at line 86 of file hal_icu_lld.c.
ICUDriver ICUD9
ICUD9 driver identifier.
Note
The driver ICUD9 allocates the timer TIM9 when enabled.
Definition at line 94 of file hal_icu_lld.c.