ChibiOS/HAL: CAN Driver
CAN Driver
HAL » Normal Drivers
Generic CAN Driver.
Detailed Description
Generic CAN Driver.
This module implements a generic CAN (Controller Area Network) driver allowing the exchange of information at frame level.
Precondition
In order to use the CAN driver the HAL_USE_CAN option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
Macros
#define CAN_SUPPORTS_SLEEP TRUE
This switch defines whether the driver implementation supports a low power switch mode with automatic an wakeup feature.
#define CAN_TX_MAILBOXES 3
This implementation supports three transmit mailboxes.
#define CAN_RX_MAILBOXES 2
This implementation supports two receive mailboxes.
#define STM32_CAN_CAN2_IRQ_PRIORITY 11
CAN2 interrupt priority level setting.
#define CAN_ANY_MAILBOX 0U
Special mailbox identifier.
CAN registers helper macros
#define CAN_BTR_BRP(n) (n)
BRP field macro.
#define CAN_BTR_TS1(n) ((n) << 16)
TS1 field macro.
#define CAN_BTR_TS2(n) ((n) << 20)
TS2 field macro.
#define CAN_BTR_SJW(n) ((n) << 24)
SJW field macro.
#define CAN_IDE_STD 0
Standard id.
#define CAN_IDE_EXT 1
Extended id.
#define CAN_RTR_DATA 0
Data frame.
#define CAN_RTR_REMOTE 1
Remote frame.
Configuration options
#define STM32_CAN_REPORT_ALL_ERRORS FALSE
CAN pedantic errors report.
#define STM32_CAN_USE_CAN1 FALSE
CAN1 driver enable switch.
#define STM32_CAN_USE_CAN2 FALSE
CAN2 driver enable switch.
#define STM32_CAN_USE_CAN3 FALSE
CAN3 driver enable switch.
#define STM32_CAN_CAN1_IRQ_PRIORITY 11
CAN1 interrupt priority level setting.
CAN status flags
#define CAN_LIMIT_WARNING 1U
Errors rate warning.
#define CAN_LIMIT_ERROR 2U
Errors rate error.
#define CAN_BUS_OFF_ERROR 4U
Bus off condition reached.
#define CAN_FRAMING_ERROR 8U
Framing error of some kind on the CAN bus.
#define CAN_OVERFLOW_ERROR 16U
Overflow in receive queue.
CAN configuration options
#define CAN_USE_SLEEP_MODE TRUE
Sleep mode related APIs inclusion switch.
Macro Functions
#define CAN_MAILBOX_TO_MASK(mbx) (1U << ((mbx) - 1U))
Converts a mailbox index to a bit mask.
#define canTransmit(canp, mailbox, ctfp, timeout) canTransmitTimeout(canp, mailbox, ctfp, timeout)
Legacy name for canTransmitTimeout().
#define canReceive(canp, mailbox, crfp, timeout) canReceiveTimeout(canp, mailbox, crfp, timeout)
Legacy name for canReceiveTimeout().
Low level driver helper macros
#define _can_tx_empty_isr(canp, flags)
TX mailbox empty event.
#define _can_rx_full_isr(canp, flags)
RX mailbox empty full event.
#define _can_wakeup_isr(canp)
Error event.
#define _can_error_isr(canp, flags)
Error event.
Functions
static void can_lld_set_filters (CANDriver *canp, uint32_t can2sb, uint32_t num, const CANFilter *cfp)
Programs the filters of CAN 1 and CAN 2.
static void can_lld_tx_handler (CANDriver *canp)
Common TX ISR handler.
static void can_lld_rx0_handler (CANDriver *canp)
Common RX0 ISR handler.
static void can_lld_rx1_handler (CANDriver *canp)
Common RX1 ISR handler.
static void can_lld_sce_handler (CANDriver *canp)
Common SCE ISR handler.
OSAL_IRQ_HANDLER (STM32_CAN1_TX_HANDLER)
CAN1 TX interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN1_RX0_HANDLER)
CAN1 RX0 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN1_RX1_HANDLER)
CAN1 RX1 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN1_SCE_HANDLER)
CAN1 SCE interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN2_TX_HANDLER)
CAN2 TX interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN2_RX0_HANDLER)
CAN2 RX0 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN2_RX1_HANDLER)
CAN2 RX1 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN2_SCE_HANDLER)
CAN2 SCE interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN3_TX_HANDLER)
CAN3 TX interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN3_RX0_HANDLER)
CAN3 RX0 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN3_RX1_HANDLER)
CAN1 RX3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_CAN3_SCE_HANDLER)
CAN1 SCE interrupt handler.
void can_lld_init (void)
Low level CAN driver initialization.
void can_lld_start (CANDriver *canp)
Configures and activates the CAN peripheral.
void can_lld_stop (CANDriver *canp)
Deactivates the CAN peripheral.
bool can_lld_is_tx_empty (CANDriver *canp, canmbx_t mailbox)
Determines whether a frame can be transmitted.
void can_lld_transmit (CANDriver *canp, canmbx_t mailbox, const CANTxFrame *ctfp)
Inserts a frame into the transmit queue.
bool can_lld_is_rx_nonempty (CANDriver *canp, canmbx_t mailbox)
Determines whether a frame has been received.
void can_lld_receive (CANDriver *canp, canmbx_t mailbox, CANRxFrame *crfp)
Receives a frame from the input queue.
void can_lld_sleep (CANDriver *canp)
Enters the sleep mode.
void can_lld_wakeup (CANDriver *canp)
Enforces leaving the sleep mode.
void canSTM32SetFilters (CANDriver *canp, uint32_t can2sb, uint32_t num, const CANFilter *cfp)
Programs the filters.
void canInit (void)
CAN Driver initialization.
void canObjectInit (CANDriver *canp)
Initializes the standard part of a CANDriver structure.
void canStart (CANDriver *canp, const CANConfig *config)
Configures and activates the CAN peripheral.
void canStop (CANDriver *canp)
Deactivates the CAN peripheral.
bool canTryTransmitI (CANDriver *canp, canmbx_t mailbox, const CANTxFrame *ctfp)
Can frame transmission attempt.
bool canTryReceiveI (CANDriver *canp, canmbx_t mailbox, CANRxFrame *crfp)
Can frame receive attempt.
msg_t canTransmitTimeout (CANDriver *canp, canmbx_t mailbox, const CANTxFrame *ctfp, sysinterval_t timeout)
Can frame transmission.
msg_t canReceiveTimeout (CANDriver *canp, canmbx_t mailbox, CANRxFrame *crfp, sysinterval_t timeout)
Can frame receive.
void canSleep (CANDriver *canp)
Enters the sleep mode.
void canWakeup (CANDriver *canp)
Enforces leaving the sleep mode.
Enumerations
Variables
CANDriver CAND1
CAN1 driver identifier.
CANDriver CAND2
CAN2 driver identifier.
CANDriver CAND3
CAN3 driver identifier.
Macro Definition Documentation
#define CAN_SUPPORTS_SLEEP TRUE
This switch defines whether the driver implementation supports a low power switch mode with automatic an wakeup feature.
Definition at line 47 of file hal_can_lld.h.
#define CAN_TX_MAILBOXES 3
This implementation supports three transmit mailboxes.
Definition at line 52 of file hal_can_lld.h.
Referenced by canTransmitTimeout(), and canTryTransmitI().
#define CAN_RX_MAILBOXES 2
This implementation supports two receive mailboxes.
Definition at line 57 of file hal_can_lld.h.
Referenced by canReceiveTimeout(), and canTryReceiveI().
#define CAN_BTR_BRP (n) (n)
BRP field macro.
Definition at line 63 of file hal_can_lld.h.
#define CAN_BTR_TS1 (n) ((n) << 16)
TS1 field macro.
Definition at line 64 of file hal_can_lld.h.
#define CAN_BTR_TS2 (n) ((n) << 20)
TS2 field macro.
Definition at line 65 of file hal_can_lld.h.
#define CAN_BTR_SJW (n) ((n) << 24)
SJW field macro.
Definition at line 66 of file hal_can_lld.h.
#define CAN_IDE_STD 0
Standard id.
Definition at line 68 of file hal_can_lld.h.
#define CAN_IDE_EXT 1
Extended id.
Definition at line 69 of file hal_can_lld.h.
#define CAN_RTR_DATA 0
Data frame.
Definition at line 71 of file hal_can_lld.h.
#define CAN_RTR_REMOTE 1
Remote frame.
Definition at line 72 of file hal_can_lld.h.
#define STM32_CAN_REPORT_ALL_ERRORS FALSE
CAN pedantic errors report.
Use of this option is IRQ-intensive.
Definition at line 88 of file hal_can_lld.h.
#define STM32_CAN_USE_CAN1 FALSE
CAN1 driver enable switch.
If set to TRUE the support for CAN1 is included.
Definition at line 96 of file hal_can_lld.h.
#define STM32_CAN_USE_CAN2 FALSE
CAN2 driver enable switch.
If set to TRUE the support for CAN2 is included.
Definition at line 104 of file hal_can_lld.h.
#define STM32_CAN_USE_CAN3 FALSE
CAN3 driver enable switch.
If set to TRUE the support for CAN3 is included.
Definition at line 112 of file hal_can_lld.h.
#define STM32_CAN_CAN1_IRQ_PRIORITY 11
CAN1 interrupt priority level setting.
Definition at line 119 of file hal_can_lld.h.
Referenced by can_lld_init().
#define STM32_CAN_CAN2_IRQ_PRIORITY 11
CAN2 interrupt priority level setting.
Definition at line 127 of file hal_can_lld.h.
Referenced by can_lld_init().
#define CAN_LIMIT_WARNING 1U
Errors rate warning.
Definition at line 41 of file hal_can.h.
#define CAN_LIMIT_ERROR 2U
Errors rate error.
Definition at line 45 of file hal_can.h.
#define CAN_BUS_OFF_ERROR 4U
Bus off condition reached.
Definition at line 49 of file hal_can.h.
#define CAN_FRAMING_ERROR 8U
Framing error of some kind on the CAN bus.
Definition at line 53 of file hal_can.h.
Referenced by can_lld_sce_handler().
#define CAN_OVERFLOW_ERROR 16U
Overflow in receive queue.
Definition at line 57 of file hal_can.h.
Referenced by can_lld_rx0_handler(), and can_lld_rx1_handler().
#define CAN_ANY_MAILBOX 0U
Special mailbox identifier.
Definition at line 63 of file hal_can.h.
Referenced by can_lld_is_rx_nonempty(), can_lld_is_tx_empty(), can_lld_receive(), and can_lld_transmit().
#define CAN_USE_SLEEP_MODE TRUE
Sleep mode related APIs inclusion switch.
This option can only be enabled if the CAN implementation supports the sleep mode, see the macro CAN_SUPPORTS_SLEEP exported by the underlying implementation.
Definition at line 80 of file hal_can.h.
#define CAN_MAILBOX_TO_MASK (mbx) (1U << ((mbx) - 1U))
Converts a mailbox index to a bit mask.
Definition at line 116 of file hal_can.h.
Referenced by can_lld_rx0_handler(), can_lld_rx1_handler(), and can_lld_tx_handler().
#define canTransmit (canp, mailbox, ctfp, timeout) canTransmitTimeout(canp, mailbox, ctfp, timeout)
Legacy name for canTransmitTimeout().
Deprecated:
Definition at line 123 of file hal_can.h.
#define canReceive (canp, mailbox, crfp, timeout) canReceiveTimeout(canp, mailbox, crfp, timeout)
Legacy name for canReceiveTimeout().
Deprecated:
Definition at line 131 of file hal_can.h.
#define _can_tx_empty_isr (canp, flags)
Value:
{                                    \
  osalSysLockFromISR();                                                     \
  osalThreadDequeueAllI(&(canp)->txqueue, MSG_OK);                          \
  osalEventBroadcastFlagsI(&(canp)->txempty_event, flags);                  \
  osalSysUnlockFromISR();                                                   \
}
TX mailbox empty event.
Definition at line 143 of file hal_can.h.
Referenced by can_lld_tx_handler().
#define _can_rx_full_isr (canp, flags)
Value:
{                                     \
  osalSysLockFromISR();                                                     \
  osalThreadDequeueAllI(&(canp)->rxqueue, MSG_OK);                          \
  osalEventBroadcastFlagsI(&(canp)->rxfull_event, flags);                   \
  osalSysUnlockFromISR();                                                   \
}
RX mailbox empty full event.
Definition at line 153 of file hal_can.h.
Referenced by can_lld_rx0_handler(), and can_lld_rx1_handler().
#define _can_wakeup_isr (canp)
Value:
{                                             \
  osalSysLockFromISR();                                                     \
  osalEventBroadcastFlagsI(&(canp)->wakeup_event, 0U);                      \
  osalSysUnlockFromISR();                                                   \
}
Error event.
Definition at line 163 of file hal_can.h.
Referenced by can_lld_sce_handler().
#define _can_error_isr (canp, flags)
Value:
{                                       \
  osalSysLockFromISR();                                                     \
  osalEventBroadcastFlagsI(&(canp)->error_event, flags);                    \
  osalSysUnlockFromISR();                                                   \
}
Error event.
Definition at line 172 of file hal_can.h.
Referenced by can_lld_rx0_handler(), can_lld_rx1_handler(), and can_lld_sce_handler().
Enumeration Type Documentation
enum canstate_t
Driver state machine possible states.
Enumerator
CAN_UNINIT
Not initialized.
CAN_STOP
Stopped.
CAN_STARTING
Starting.
CAN_READY
Ready.
CAN_SLEEP
Sleep state.
Definition at line 95 of file hal_can.h.
Function Documentation
static void can_lld_set_filters (CANDriver * canp, uint32_t can2sb, uint32_t num, const CANFilter * cfp) static
Programs the filters of CAN 1 and CAN 2.
Parameters
[in] canp pointer to the CANDriver object
[in] can2sb number of the first filter assigned to CAN2
[in] num number of entries in the filters array, if zero then a default filter is programmed
[in] cfp pointer to the filters array, can be NULL if (num == 0)
Function Class:
Not an API, this function is for internal use only.
Definition at line 80 of file hal_can_lld.c.
References CANFilter::assignment, CANDriver::can, CAND1, CANFilter::filter, CANFilter::mode, rccDisableCAN1, rccEnableCAN1, CANFilter::register1, CANFilter::register2, and CANFilter::scale.
Referenced by can_lld_init(), and canSTM32SetFilters().
static void can_lld_tx_handler (CANDriver * canp) static
Common TX ISR handler.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 197 of file hal_can_lld.c.
References _can_tx_empty_isr, CANDriver::can, and CAN_MAILBOX_TO_MASK.
Referenced by can_lld_sce_handler(), and OSAL_IRQ_HANDLER().
static void can_lld_rx0_handler (CANDriver * canp) static
Common RX0 ISR handler.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 249 of file hal_can_lld.c.
References _can_error_isr, _can_rx_full_isr, CANDriver::can, CAN_MAILBOX_TO_MASK, and CAN_OVERFLOW_ERROR.
Referenced by can_lld_sce_handler(), and OSAL_IRQ_HANDLER().
static void can_lld_rx1_handler (CANDriver * canp) static
Common RX1 ISR handler.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 272 of file hal_can_lld.c.
References _can_error_isr, _can_rx_full_isr, CANDriver::can, CAN_MAILBOX_TO_MASK, and CAN_OVERFLOW_ERROR.
Referenced by can_lld_sce_handler(), and OSAL_IRQ_HANDLER().
static void can_lld_sce_handler (CANDriver * canp) static
Common SCE ISR handler.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 295 of file hal_can_lld.c.
References _can_error_isr, _can_wakeup_isr, CANDriver::can, CAN_FRAMING_ERROR, can_lld_rx0_handler(), can_lld_rx1_handler(), can_lld_tx_handler(), CAN_READY, OSAL_IRQ_EPILOGUE, OSAL_IRQ_HANDLER(), OSAL_IRQ_PROLOGUE, and CANDriver::state.
Referenced by OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_CAN1_TX_HANDLER)
CAN1 TX interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 371 of file hal_can_lld.c.
References can_lld_tx_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
Referenced by can_lld_sce_handler(), and OSAL_IRQ_HANDLER().
OSAL_IRQ_HANDLER (STM32_CAN1_RX0_HANDLER)
CAN1 RX0 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 385 of file hal_can_lld.c.
References can_lld_rx0_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN1_RX1_HANDLER)
CAN1 RX1 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 399 of file hal_can_lld.c.
References can_lld_rx1_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN1_SCE_HANDLER)
CAN1 SCE interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 413 of file hal_can_lld.c.
References can_lld_rx0_handler(), can_lld_rx1_handler(), can_lld_sce_handler(), can_lld_tx_handler(), OSAL_IRQ_EPILOGUE, OSAL_IRQ_HANDLER(), and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN2_TX_HANDLER)
CAN2 TX interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 462 of file hal_can_lld.c.
References can_lld_tx_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN2_RX0_HANDLER)
CAN2 RX0 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 476 of file hal_can_lld.c.
References can_lld_rx0_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN2_RX1_HANDLER)
CAN2 RX1 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 490 of file hal_can_lld.c.
References can_lld_rx1_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN2_SCE_HANDLER)
CAN2 SCE interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 504 of file hal_can_lld.c.
References can_lld_rx0_handler(), can_lld_rx1_handler(), can_lld_sce_handler(), can_lld_tx_handler(), OSAL_IRQ_EPILOGUE, OSAL_IRQ_HANDLER(), and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN3_TX_HANDLER)
CAN3 TX interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 553 of file hal_can_lld.c.
References can_lld_tx_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN3_RX0_HANDLER)
CAN3 RX0 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 567 of file hal_can_lld.c.
References can_lld_rx0_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN3_RX1_HANDLER)
CAN1 RX3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 581 of file hal_can_lld.c.
References can_lld_rx1_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER (STM32_CAN3_SCE_HANDLER)
CAN1 SCE interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 595 of file hal_can_lld.c.
References can_lld_sce_handler(), OSAL_IRQ_EPILOGUE, and OSAL_IRQ_PROLOGUE.
void can_lld_init (void)
Low level CAN driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 615 of file hal_can_lld.c.
References CANDriver::can, can_lld_set_filters(), canObjectInit(), STM32_CAN_CAN1_IRQ_PRIORITY, STM32_CAN_CAN2_IRQ_PRIORITY, and STM32_CAN_CAN3_IRQ_PRIORITY.
Referenced by canInit().
void can_lld_start (CANDriver * canp)
Configures and activates the CAN peripheral.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 680 of file hal_can_lld.c.
References CANConfig::btr, CANDriver::can, CAN_STOP, CANDriver::config, CANConfig::mcr, osalDbgAssert, osalThreadSleepS(), rccEnableCAN1, rccEnableCAN2, and CANDriver::state.
Referenced by canStart().
void can_lld_stop (CANDriver * canp)
Deactivates the CAN peripheral.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 732 of file hal_can_lld.c.
References CAN_READY, CAN_STOP, osalDbgAssert, rccDisableCAN1, rccDisableCAN2, and CANDriver::state.
Referenced by canStop().
bool can_lld_is_tx_empty (CANDriver * canp, canmbx_t mailbox)
Determines whether a frame can be transmitted.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
Returns
The queue space availability.
Return values
false no space in the transmit queue.
true transmit slot available.
Function Class:
Not an API, this function is for internal use only.
Definition at line 779 of file hal_can_lld.c.
References CANDriver::can, and CAN_ANY_MAILBOX.
Referenced by canTransmitTimeout(), and canTryTransmitI().
void can_lld_transmit (CANDriver * canp, canmbx_t mailbox, const CANTxFrame * ctfp)
Inserts a frame into the transmit queue.
Parameters
[in] canp pointer to the CANDriver object
[in] ctfp pointer to the CAN frame to be transmitted
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
Function Class:
Not an API, this function is for internal use only.
Definition at line 804 of file hal_can_lld.c.
References CANDriver::can, CAN_ANY_MAILBOX, CANTxFrame::data32, CANTxFrame::DLC, CANTxFrame::EID, CANTxFrame::IDE, CANTxFrame::RTR, and CANTxFrame::SID.
Referenced by canTransmitTimeout(), and canTryTransmitI().
bool can_lld_is_rx_nonempty (CANDriver * canp, canmbx_t mailbox)
Determines whether a frame has been received.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
Returns
The queue space availability.
Return values
false no space in the transmit queue.
true transmit slot available.
Function Class:
Not an API, this function is for internal use only.
Definition at line 852 of file hal_can_lld.c.
References CANDriver::can, and CAN_ANY_MAILBOX.
Referenced by canReceiveTimeout(), and canTryReceiveI().
void can_lld_receive (CANDriver * canp, canmbx_t mailbox, CANRxFrame * crfp)
Receives a frame from the input queue.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
[out] crfp pointer to the buffer where the CAN frame is copied
Function Class:
Not an API, this function is for internal use only.
Definition at line 876 of file hal_can_lld.c.
References CANDriver::can, CAN_ANY_MAILBOX, CANRxFrame::data32, CANRxFrame::DLC, CANRxFrame::EID, CANRxFrame::FMI, CANRxFrame::IDE, CANRxFrame::RTR, CANRxFrame::SID, and CANRxFrame::TIME.
Referenced by canReceiveTimeout(), and canTryReceiveI().
void can_lld_sleep (CANDriver * canp)
Enters the sleep mode.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 947 of file hal_can_lld.c.
References CANDriver::can.
Referenced by canSleep().
void can_lld_wakeup (CANDriver * canp)
Enforces leaving the sleep mode.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 959 of file hal_can_lld.c.
References CANDriver::can.
Referenced by canWakeup().
void canSTM32SetFilters (CANDriver * canp, uint32_t can2sb, uint32_t num, const CANFilter * cfp)
Programs the filters.
Note
This is an STM32-specific API.
Parameters
[in] canp pointer to the CANDriver object
[in] can2sb number of the first filter assigned to CAN2
[in] num number of entries in the filters array, if zero then a default filter is programmed
[in] cfp pointer to the filters array, can be NULL if (num == 0)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 978 of file hal_can_lld.c.
References can_lld_set_filters(), CAN_STOP, osalDbgAssert, osalDbgCheck, and CANDriver::state.
void canInit (void)
CAN Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_can.c.
References can_lld_init().
Referenced by halInit().
void canObjectInit (CANDriver * canp)
Initializes the standard part of a CANDriver structure.
Parameters
[out] canp pointer to the CANDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_can.c.
References CAN_STOP, CANDriver::config, CANDriver::error_event, osalEventObjectInit(), osalThreadQueueObjectInit(), CANDriver::rxfull_event, CANDriver::rxqueue, CANDriver::sleep_event, CANDriver::state, CANDriver::txempty_event, CANDriver::txqueue, and CANDriver::wakeup_event.
Referenced by can_lld_init().
void canStart (CANDriver * canp, const CANConfig * config)
Configures and activates the CAN peripheral.
Note
Activating the CAN bus can be a slow operation.
Unlike other drivers it is not possible to restart the CAN driver without first stopping it using canStop().
Parameters
[in] canp pointer to the CANDriver object
[in] config pointer to the CANConfig object. Depending on the implementation the value can be NULL.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 104 of file hal_can.c.
References can_lld_start(), CAN_READY, CAN_STARTING, CAN_STOP, CANDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and CANDriver::state.
void canStop (CANDriver * canp)
Deactivates the CAN peripheral.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 131 of file hal_can.c.
References can_lld_stop(), CAN_READY, CAN_STOP, CANDriver::config, osalDbgAssert, osalDbgCheck, osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), osalThreadDequeueAllI(), CANDriver::rxqueue, CANDriver::state, and CANDriver::txqueue.
bool canTryTransmitI (CANDriver * canp, canmbx_t mailbox, const CANTxFrame * ctfp)
Can frame transmission attempt.
The specified frame is queued for transmission, if the hardware queue is full then the function fails.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
[in] ctfp pointer to the CAN frame to be transmitted
Returns
The operation result.
Return values
false Frame transmitted.
true Mailbox full.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 166 of file hal_can.c.
References can_lld_is_tx_empty(), can_lld_transmit(), CAN_READY, CAN_SLEEP, CAN_TX_MAILBOXES, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and CANDriver::state.
bool canTryReceiveI (CANDriver * canp, canmbx_t mailbox, CANRxFrame * crfp)
Can frame receive attempt.
The function tries to fetch a frame from a mailbox.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
[out] crfp pointer to the buffer where the CAN frame is copied
Returns
The operation result.
Return values
false Frame fetched.
true Mailbox empty.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 200 of file hal_can.c.
References can_lld_is_rx_nonempty(), can_lld_receive(), CAN_READY, CAN_RX_MAILBOXES, CAN_SLEEP, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and CANDriver::state.
msg_t canTransmitTimeout (CANDriver * canp, canmbx_t mailbox, const CANTxFrame * ctfp, sysinterval_t timeout)
Can frame transmission.
The specified frame is queued for transmission, if the hardware queue is full then the invoking thread is queued.
Note
Trying to transmit while in sleep mode simply enqueues the thread.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
[in] ctfp pointer to the CAN frame to be transmitted
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation result.
Return values
MSG_OK the frame has been queued for transmission.
MSG_TIMEOUT The operation has timed out.
MSG_RESET The driver has been stopped while waiting.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 242 of file hal_can.c.
References can_lld_is_tx_empty(), can_lld_transmit(), CAN_READY, CAN_SLEEP, CAN_TX_MAILBOXES, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadEnqueueTimeoutS(), CANDriver::state, and CANDriver::txqueue.
msg_t canReceiveTimeout (CANDriver * canp, canmbx_t mailbox, CANRxFrame * crfp, sysinterval_t timeout)
Can frame receive.
The function waits until a frame is received.
Note
Trying to receive while in sleep mode simply enqueues the thread.
Parameters
[in] canp pointer to the CANDriver object
[in] mailbox mailbox number, CAN_ANY_MAILBOX for any mailbox
[out] crfp pointer to the buffer where the CAN frame is copied
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout (useful in an event driven scenario where a thread never blocks for I/O).
TIME_INFINITE no timeout.
Returns
The operation result.
Return values
MSG_OK a frame has been received and placed in the buffer.
MSG_TIMEOUT The operation has timed out.
MSG_RESET The driver has been stopped while waiting.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 290 of file hal_can.c.
References can_lld_is_rx_nonempty(), can_lld_receive(), CAN_READY, CAN_RX_MAILBOXES, CAN_SLEEP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), osalThreadEnqueueTimeoutS(), CANDriver::rxqueue, and CANDriver::state.
void canSleep (CANDriver * canp)
Enters the sleep mode.
This function puts the CAN driver in sleep mode and broadcasts the sleep_event event source.
Precondition
In order to use this function the option CAN_USE_SLEEP_MODE must be enabled and the CAN_SUPPORTS_SLEEP mode must be supported by the low level driver.
Parameters
[in] canp pointer to the CANDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 329 of file hal_can.c.
References can_lld_sleep(), CAN_READY, CAN_SLEEP, osalDbgAssert, osalDbgCheck, osalEventBroadcastFlagsI(), osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), CANDriver::sleep_event, and CANDriver::state.
void canWakeup (CANDriver * canp)
Enforces leaving the sleep mode.
Note
The sleep mode is supposed to be usually exited automatically by an hardware event.
Parameters
[in] canp pointer to the CANDriver object
Definition at line 354 of file hal_can.c.
References can_lld_wakeup(), CAN_READY, CAN_SLEEP, osalDbgAssert, osalDbgCheck, osalEventBroadcastFlagsI(), osalOsRescheduleS(), osalSysLock(), osalSysUnlock(), CANDriver::state, and CANDriver::wakeup_event.
Variable Documentation
CANDriver CAND1
CAN1 driver identifier.
Definition at line 48 of file hal_can_lld.c.
Referenced by can_lld_set_filters().
CANDriver CAND2
CAN2 driver identifier.
Definition at line 53 of file hal_can_lld.c.
CANDriver CAND3
CAN3 driver identifier.
Definition at line 58 of file hal_can_lld.c.