ChibiOS/HAL: MMC over SPI Driver
MMC over SPI Driver
HAL » Complex Drivers
Generic MMC driver.
Detailed Description
Generic MMC driver.
This module implements a portable MMC/SD driver that uses a SPI driver as physical layer. Hot plugging and removal are supported through kernel events.
Precondition
In order to use the MMC_SPI driver the HAL_USE_MMC_SPI and HAL_USE_SPI options must be enabled in halconf.h.
Driver State Machine
This driver implements a state machine internally, see the Abstract I/O Block Device module documentation for details.
Driver Operations
This driver allows to read or write single or multiple 512 bytes blocks on a SD Card.
Macros
#define _mmc_driver_methods _mmcsd_block_device_methods
MMCDriver specific methods.
MMC_SPI configuration options
#define MMC_NICE_WAITING TRUE
Delays insertions.
Macro Functions
#define mmcIsCardInserted(mmcp) mmc_lld_is_card_inserted(mmcp)
Returns the card insertion status.
#define mmcIsWriteProtected(mmcp) mmc_lld_is_write_protected(mmcp)
Returns the write protect status.
Data Structures
struct MMCConfig
MMC/SD over SPI driver configuration structure.
struct MMCDriverVMT
MMCDriver virtual methods table.
struct MMCDriver
Structure representing a MMC/SD over SPI driver.
Functions
static uint8_t crc7 (uint8_t crc, const uint8_t *buffer, size_t len)
Calculate the MMC standard CRC-7 based on a lookup table.
static void wait (MMCDriver *mmcp)
Waits an idle condition.
static void send_hdr (MMCDriver *mmcp, uint8_t cmd, uint32_t arg)
Sends a command header.
static uint8_t recvr1 (MMCDriver *mmcp)
Receives a single byte response.
static uint8_t recvr3 (MMCDriver *mmcp, uint8_t *buffer)
Receives a three byte response.
static uint8_t send_command_R1 (MMCDriver *mmcp, uint8_t cmd, uint32_t arg)
Sends a command an returns a single byte response.
static uint8_t send_command_R3 (MMCDriver *mmcp, uint8_t cmd, uint32_t arg, uint8_t *response)
Sends a command which returns a five bytes response (R3).
static bool read_CxD (MMCDriver *mmcp, uint8_t cmd, uint32_t cxd[4])
Reads the CSD.
static void sync (MMCDriver *mmcp)
Waits that the card reaches an idle state.
void mmcInit (void)
MMC over SPI driver initialization.
void mmcObjectInit (MMCDriver *mmcp)
Initializes an instance.
void mmcStart (MMCDriver *mmcp, const MMCConfig *config)
Configures and activates the MMC peripheral.
void mmcStop (MMCDriver *mmcp)
Disables the MMC peripheral.
bool mmcConnect (MMCDriver *mmcp)
Performs the initialization procedure on the inserted card.
bool mmcDisconnect (MMCDriver *mmcp)
Brings the driver in a state safe for card removal.
bool mmcStartSequentialRead (MMCDriver *mmcp, uint32_t startblk)
Starts a sequential read.
bool mmcSequentialRead (MMCDriver *mmcp, uint8_t *buffer)
Reads a block within a sequential read operation.
bool mmcStopSequentialRead (MMCDriver *mmcp)
Stops a sequential read gracefully.
bool mmcStartSequentialWrite (MMCDriver *mmcp, uint32_t startblk)
Starts a sequential write.
bool mmcSequentialWrite (MMCDriver *mmcp, const uint8_t *buffer)
Writes a block within a sequential write operation.
bool mmcStopSequentialWrite (MMCDriver *mmcp)
Stops a sequential write gracefully.
bool mmcSync (MMCDriver *mmcp)
Waits for card idle condition.
bool mmcGetInfo (MMCDriver *mmcp, BlockDeviceInfo *bdip)
Returns the media info.
bool mmcErase (MMCDriver *mmcp, uint32_t startblk, uint32_t endblk)
Erases blocks.
Variables
static const struct MMCDriverVMT mmc_vmt
Virtual methods table.
static const uint8_t crc7_lookup_table [256]
Lookup table for CRC-7 (based on polynomial x^7 + x^3 + 1).
Macro Definition Documentation
#define MMC_NICE_WAITING TRUE
Delays insertions.
If enabled this options inserts delays into the MMC waiting routines releasing some extra CPU time for the threads with lower priority, this may slow down the driver a bit however. This option is recommended also if the SPI driver does not use a DMA channel and heavily loads the CPU.
Definition at line 56 of file hal_mmc_spi.h.
#define _mmc_driver_methods _mmcsd_block_device_methods
MMCDriver specific methods.
Definition at line 93 of file hal_mmc_spi.h.
#define mmcIsCardInserted (mmcp) mmc_lld_is_card_inserted(mmcp)
Returns the card insertion status.
Note
This macro wraps a low level function named sdc_lld_is_card_inserted(), this function must be provided by the application because it is not part of the SDC driver.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The card state.
Return values
false card not inserted.
true card inserted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 148 of file hal_mmc_spi.h.
#define mmcIsWriteProtected (mmcp) mmc_lld_is_write_protected(mmcp)
Returns the write protect status.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The card state.
Return values
false card not inserted.
true card inserted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 160 of file hal_mmc_spi.h.
Function Documentation
static uint8_t crc7 (uint8_t crc, const uint8_t * buffer, size_t len) static
Calculate the MMC standard CRC-7 based on a lookup table.
Parameters
[in] crc start value for CRC
[in] buffer pointer to data buffer
[in] len length of data
Returns
Calculated CRC
Definition at line 148 of file hal_mmc_spi.c.
References crc7_lookup_table.
Referenced by send_hdr().
static void wait (MMCDriver * mmcp) static
Waits an idle condition.
Parameters
[in] mmcp pointer to the MMCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 164 of file hal_mmc_spi.c.
References MMCDriver::config, osalThreadSleepMilliseconds, MMCConfig::spip, and spiReceive().
Referenced by mmcSequentialWrite(), and send_hdr().
static void send_hdr (MMCDriver * mmcp, uint8_t cmd, uint32_t arg) static
Sends a command header.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] cmd the command id
[in] arg the command argument
Function Class:
Not an API, this function is for internal use only.
Definition at line 196 of file hal_mmc_spi.c.
References MMCDriver::config, crc7(), MMCConfig::spip, spiSend(), and wait().
Referenced by mmcStartSequentialRead(), mmcStartSequentialWrite(), read_CxD(), send_command_R1(), and send_command_R3().
static uint8_t recvr1 (MMCDriver * mmcp) static
Receives a single byte response.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The response as an uint8_t value.
Return values
0xFF timed out.
Function Class:
Not an API, this function is for internal use only.
Definition at line 222 of file hal_mmc_spi.c.
References MMCDriver::config, MMCConfig::spip, and spiReceive().
Referenced by mmcStartSequentialRead(), mmcStartSequentialWrite(), mmcStopSequentialRead(), read_CxD(), recvr3(), and send_command_R1().
static uint8_t recvr3 (MMCDriver * mmcp, uint8_t * buffer) static
Receives a three byte response.
Parameters
[in] mmcp pointer to the MMCDriver object
[out] buffer pointer to four bytes wide buffer
Returns
First response byte as an uint8_t value.
Return values
0xFF timed out.
Function Class:
Not an API, this function is for internal use only.
Definition at line 245 of file hal_mmc_spi.c.
References MMCDriver::config, recvr1(), MMCConfig::spip, and spiReceive().
Referenced by send_command_R3().
static uint8_t send_command_R1 (MMCDriver * mmcp, uint8_t cmd, uint32_t arg) static
Sends a command an returns a single byte response.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] cmd the command id
[in] arg the command argument
Returns
The response as an uint8_t value.
Return values
0xFF timed out.
Function Class:
Not an API, this function is for internal use only.
Definition at line 265 of file hal_mmc_spi.c.
References MMCDriver::config, recvr1(), send_hdr(), MMCConfig::spip, spiSelect(), and spiUnselect().
Referenced by mmcConnect(), and mmcErase().
static uint8_t send_command_R3 (MMCDriver * mmcp, uint8_t cmd, uint32_t arg, uint8_t * response) static
Sends a command which returns a five bytes response (R3).
Parameters
[in] mmcp pointer to the MMCDriver object
[in] cmd the command id
[in] arg the command argument
[out] response pointer to four bytes wide uint8_t buffer
Returns
The first byte of the response (R1) as an uint8_t value.
Return values
0xFF timed out.
Function Class:
Not an API, this function is for internal use only.
Definition at line 288 of file hal_mmc_spi.c.
References MMCDriver::config, recvr3(), send_hdr(), MMCConfig::spip, spiSelect(), and spiUnselect().
Referenced by mmcConnect().
static bool read_CxD (MMCDriver * mmcp, uint8_t cmd, uint32_t cxd[4]) static
Reads the CSD.
Parameters
[in] mmcp pointer to the MMCDriver object
[out] cmd command
[out] cxd pointer to the CSD/CID buffer
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 312 of file hal_mmc_spi.c.
References MMCDriver::config, recvr1(), send_hdr(), spiIgnore(), MMCConfig::spip, spiReceive(), spiSelect(), and spiUnselect().
Referenced by mmcConnect().
static void sync (MMCDriver * mmcp) static
Waits that the card reaches an idle state.
Parameters
[in] mmcp pointer to the MMCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 354 of file hal_mmc_spi.c.
References MMCDriver::config, osalThreadSleepMilliseconds, MMCConfig::spip, spiReceive(), spiSelect(), and spiUnselect().
Referenced by mmcDisconnect(), and mmcSync().
void mmcInit (void)
MMC over SPI driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 382 of file hal_mmc_spi.c.
Referenced by halInit().
void mmcObjectInit (MMCDriver * mmcp)
Initializes an instance.
Parameters
[out] mmcp pointer to the MMCDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 393 of file hal_mmc_spi.c.
References BLK_STOP, MMCDriver::config, mmc_vmt, and MMCDriver::vmt.
void mmcStart (MMCDriver * mmcp, const MMCConfig * config)
Configures and activates the MMC peripheral.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] config pointer to the MMCConfig object.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 409 of file hal_mmc_spi.c.
References BLK_ACTIVE, BLK_STOP, MMCDriver::config, osalDbgAssert, and osalDbgCheck.
void mmcStop (MMCDriver * mmcp)
Disables the MMC peripheral.
Parameters
[in] mmcp pointer to the MMCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 426 of file hal_mmc_spi.c.
References BLK_ACTIVE, BLK_STOP, MMCDriver::config, osalDbgAssert, osalDbgCheck, MMCConfig::spip, and spiStop().
bool mmcConnect (MMCDriver * mmcp)
Performs the initialization procedure on the inserted card.
This function should be invoked when a card is inserted and brings the driver in the MMC_READY state where it is possible to perform read and write operations.
Note
It is possible to invoke this function from the insertion event handler.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded and the driver is now in the MMC_READY state.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 454 of file hal_mmc_spi.c.
References _mmcsd_get_capacity(), BLK_ACTIVE, BLK_CONNECTING, BLK_READY, MMCDriver::config, MMCConfig::hscfg, MMCConfig::lscfg, MMCSD_BLOCK_SIZE, MMCSD_CMD8_PATTERN, osalDbgAssert, osalDbgCheck, osalThreadSleepMilliseconds, read_CxD(), send_command_R1(), send_command_R3(), spiIgnore(), MMCConfig::spip, spiStart(), and spiStop().
bool mmcDisconnect (MMCDriver * mmcp)
Brings the driver in a state safe for card removal.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded and the driver is now in the MMC_INSERTED state.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 576 of file hal_mmc_spi.c.
References BLK_ACTIVE, BLK_DISCONNECTING, BLK_READY, MMCDriver::config, MMCConfig::hscfg, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), MMCConfig::spip, spiStart(), spiStop(), and sync().
bool mmcStartSequentialRead (MMCDriver * mmcp, uint32_t startblk)
Starts a sequential read.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] startblk first block to read
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 611 of file hal_mmc_spi.c.
References BLK_READING, BLK_READY, MMCDriver::config, MMCConfig::hscfg, MMCSD_BLOCK_SIZE, osalDbgAssert, osalDbgCheck, recvr1(), send_hdr(), MMCConfig::spip, spiSelect(), spiStart(), and spiStop().
bool mmcSequentialRead (MMCDriver * mmcp, uint8_t * buffer)
Reads a block within a sequential read operation.
Parameters
[in] mmcp pointer to the MMCDriver object
[out] buffer pointer to the read buffer
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 651 of file hal_mmc_spi.c.
References BLK_READING, BLK_READY, MMCDriver::config, MMCSD_BLOCK_SIZE, osalDbgCheck, spiIgnore(), MMCConfig::spip, spiReceive(), spiStop(), and spiUnselect().
bool mmcStopSequentialRead (MMCDriver * mmcp)
Stops a sequential read gracefully.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 687 of file hal_mmc_spi.c.
References BLK_READING, BLK_READY, MMCDriver::config, osalDbgCheck, recvr1(), MMCConfig::spip, spiSend(), and spiUnselect().
bool mmcStartSequentialWrite (MMCDriver * mmcp, uint32_t startblk)
Starts a sequential write.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] startblk first block to write
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 721 of file hal_mmc_spi.c.
References BLK_READY, BLK_WRITING, MMCDriver::config, MMCConfig::hscfg, MMCSD_BLOCK_SIZE, osalDbgAssert, osalDbgCheck, recvr1(), send_hdr(), MMCConfig::spip, spiSelect(), spiStart(), and spiStop().
bool mmcSequentialWrite (MMCDriver * mmcp, const uint8_t * buffer)
Writes a block within a sequential write operation.
Parameters
[in] mmcp pointer to the MMCDriver object
[out] buffer pointer to the write buffer
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 759 of file hal_mmc_spi.c.
References BLK_READY, BLK_WRITING, MMCDriver::config, MMCSD_BLOCK_SIZE, osalDbgCheck, spiIgnore(), MMCConfig::spip, spiReceive(), spiSend(), spiStop(), spiUnselect(), and wait().
bool mmcStopSequentialWrite (MMCDriver * mmcp)
Stops a sequential write gracefully.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 796 of file hal_mmc_spi.c.
References BLK_READY, BLK_WRITING, MMCDriver::config, osalDbgCheck, MMCConfig::spip, spiSend(), and spiUnselect().
bool mmcSync (MMCDriver * mmcp)
Waits for card idle condition.
Parameters
[in] mmcp pointer to the MMCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 824 of file hal_mmc_spi.c.
References BLK_READY, BLK_SYNCING, MMCDriver::config, MMCConfig::hscfg, osalDbgCheck, MMCConfig::spip, spiStart(), and sync().
bool mmcGetInfo (MMCDriver * mmcp, BlockDeviceInfo * bdip)
Returns the media info.
Parameters
[in] mmcp pointer to the MMCDriver object
[out] bdip pointer to a BlockDeviceInfo structure
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 855 of file hal_mmc_spi.c.
References BlockDeviceInfo::blk_num, BLK_READY, BlockDeviceInfo::blk_size, MMCSD_BLOCK_SIZE, and osalDbgCheck.
bool mmcErase (MMCDriver * mmcp, uint32_t startblk, uint32_t endblk)
Erases blocks.
Parameters
[in] mmcp pointer to the MMCDriver object
[in] startblk starting block number
[in] endblk ending block number
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 882 of file hal_mmc_spi.c.
References BLK_READY, BLK_WRITING, MMCDriver::config, MMCSD_BLOCK_SIZE, osalDbgCheck, send_command_R1(), MMCConfig::spip, and spiStop().
Variable Documentation
const struct MMCDriverVMT mmc_vmt static
Initial value:
= {
  (bool (*)(void *))mmc_lld_is_card_inserted,
  (bool (*)(void *))mmc_lld_is_write_protected,
  (bool (*)(void *))mmcConnect,
  (bool (*)(void *))mmcDisconnect,
  mmc_read,
  mmc_write,
  (bool (*)(void *))mmcSync,
  (bool (*)(void *, BlockDeviceInfo *))mmcGetInfo
}
Virtual methods table.
Definition at line 55 of file hal_mmc_spi.c.
Referenced by mmcObjectInit().
const uint8_t crc7_lookup_table[256] static
Initial value:
= {
  0x00, 0x09, 0x12, 0x1b, 0x24, 0x2d, 0x36, 0x3f, 0x48, 0x41, 0x5a, 0x53,
  0x6c, 0x65, 0x7e, 0x77, 0x19, 0x10, 0x0b, 0x02, 0x3d, 0x34, 0x2f, 0x26,
  0x51, 0x58, 0x43, 0x4a, 0x75, 0x7c, 0x67, 0x6e, 0x32, 0x3b, 0x20, 0x29,
  0x16, 0x1f, 0x04, 0x0d, 0x7a, 0x73, 0x68, 0x61, 0x5e, 0x57, 0x4c, 0x45,
  0x2b, 0x22, 0x39, 0x30, 0x0f, 0x06, 0x1d, 0x14, 0x63, 0x6a, 0x71, 0x78,
  0x47, 0x4e, 0x55, 0x5c, 0x64, 0x6d, 0x76, 0x7f, 0x40, 0x49, 0x52, 0x5b,
  0x2c, 0x25, 0x3e, 0x37, 0x08, 0x01, 0x1a, 0x13, 0x7d, 0x74, 0x6f, 0x66,
  0x59, 0x50, 0x4b, 0x42, 0x35, 0x3c, 0x27, 0x2e, 0x11, 0x18, 0x03, 0x0a,
  0x56, 0x5f, 0x44, 0x4d, 0x72, 0x7b, 0x60, 0x69, 0x1e, 0x17, 0x0c, 0x05,
  0x3a, 0x33, 0x28, 0x21, 0x4f, 0x46, 0x5d, 0x54, 0x6b, 0x62, 0x79, 0x70,
  0x07, 0x0e, 0x15, 0x1c, 0x23, 0x2a, 0x31, 0x38, 0x41, 0x48, 0x53, 0x5a,
  0x65, 0x6c, 0x77, 0x7e, 0x09, 0x00, 0x1b, 0x12, 0x2d, 0x24, 0x3f, 0x36,
  0x58, 0x51, 0x4a, 0x43, 0x7c, 0x75, 0x6e, 0x67, 0x10, 0x19, 0x02, 0x0b,
  0x34, 0x3d, 0x26, 0x2f, 0x73, 0x7a, 0x61, 0x68, 0x57, 0x5e, 0x45, 0x4c,
  0x3b, 0x32, 0x29, 0x20, 0x1f, 0x16, 0x0d, 0x04, 0x6a, 0x63, 0x78, 0x71,
  0x4e, 0x47, 0x5c, 0x55, 0x22, 0x2b, 0x30, 0x39, 0x06, 0x0f, 0x14, 0x1d,
  0x25, 0x2c, 0x37, 0x3e, 0x01, 0x08, 0x13, 0x1a, 0x6d, 0x64, 0x7f, 0x76,
  0x49, 0x40, 0x5b, 0x52, 0x3c, 0x35, 0x2e, 0x27, 0x18, 0x11, 0x0a, 0x03,
  0x74, 0x7d, 0x66, 0x6f, 0x50, 0x59, 0x42, 0x4b, 0x17, 0x1e, 0x05, 0x0c,
  0x33, 0x3a, 0x21, 0x28, 0x5f, 0x56, 0x4d, 0x44, 0x7b, 0x72, 0x69, 0x60,
  0x0e, 0x07, 0x1c, 0x15, 0x2a, 0x23, 0x38, 0x31, 0x46, 0x4f, 0x54, 0x5d,
  0x62, 0x6b, 0x70, 0x79
}
Lookup table for CRC-7 (based on polynomial x^7 + x^3 + 1).
Definition at line 69 of file hal_mmc_spi.c.
Referenced by crc7().