ChibiOS/HAL: I2S Driver
I2S Driver
HAL » Normal Drivers
Generic I2S Driver.
Detailed Description
Generic I2S Driver.
This module implements a generic I2S driver.
Precondition
In order to use the I2S driver the HAL_USE_I2S option must be enabled in halconf.h.
Driver State Machine
Static I2S modes
#define STM32_I2S_MODE_SLAVE 0
#define STM32_I2S_MODE_MASTER 1
#define STM32_I2S_MODE_RX 2
#define STM32_I2S_MODE_TX 4
#define STM32_I2S_MODE_RXTX
Mode checks
#define STM32_I2S_IS_MASTER(mode) ((mode) & STM32_I2S_MODE_MASTER)
#define STM32_I2S_RX_ENABLED(mode) ((mode) & STM32_I2S_MODE_RX)
#define STM32_I2S_TX_ENABLED(mode) ((mode) & STM32_I2S_MODE_TX)
Configuration options
#define STM32_I2S_USE_SPI1 FALSE
I2S1 driver enable switch.
#define STM32_I2S_USE_SPI2 FALSE
I2S2 driver enable switch.
#define STM32_I2S_USE_SPI3 FALSE
I2S3 driver enable switch.
#define STM32_I2S_SPI1_MODE
I2S1 mode.
#define STM32_I2S_SPI2_MODE
I2S2 mode.
#define STM32_I2S_SPI3_MODE
I2S3 mode.
#define STM32_I2S_SPI1_IRQ_PRIORITY 10
I2S1 interrupt priority level setting.
#define STM32_I2S_SPI2_IRQ_PRIORITY 10
I2S2 interrupt priority level setting.
#define STM32_I2S_SPI3_IRQ_PRIORITY 10
I2S3 interrupt priority level setting.
#define STM32_I2S_SPI1_DMA_PRIORITY 1
I2S1 DMA priority (0..3|lowest..highest).
#define STM32_I2S_SPI2_DMA_PRIORITY 1
I2S2 DMA priority (0..3|lowest..highest).
#define STM32_I2S_SPI3_DMA_PRIORITY 1
I2S3 DMA priority (0..3|lowest..highest).
#define STM32_I2S_DMA_ERROR_HOOK(i2sp) osalSysHalt("DMA failure")
I2S DMA error hook.
I2S modes
#define I2S_MODE_SLAVE 0
#define I2S_MODE_MASTER 1
Macro Functions
#define i2sStartExchangeI(i2sp)
Starts a I2S data exchange.
#define i2sStopExchangeI(i2sp)
Stops the ongoing data exchange.
#define _i2s_isr_half_code(i2sp)
Common ISR code, half buffer event.
#define _i2s_isr_full_code(i2sp)
Common ISR code.
Typedefs
typedef struct I2SDriver I2SDriver
Type of a structure representing an I2S driver.
typedef void(* i2scallback_t) (I2SDriver *i2sp, size_t offset, size_t n)
I2S notification callback type.
Data Structures
struct I2SConfig
Driver configuration structure.
struct I2SDriver
Structure representing an I2S driver.
Functions
static void i2s_lld_serve_rx_interrupt (I2SDriver *i2sp, uint32_t flags)
Shared end-of-rx service routine.
static void i2s_lld_serve_tx_interrupt (I2SDriver *i2sp, uint32_t flags)
Shared end-of-tx service routine.
void i2s_lld_init (void)
Low level I2S driver initialization.
void i2s_lld_start (I2SDriver *i2sp)
Configures and activates the I2S peripheral.
void i2s_lld_stop (I2SDriver *i2sp)
Deactivates the I2S peripheral.
void i2s_lld_start_exchange (I2SDriver *i2sp)
Starts a I2S data exchange.
void i2s_lld_stop_exchange (I2SDriver *i2sp)
Stops the ongoing data exchange.
void i2sInit (void)
I2S Driver initialization.
void i2sObjectInit (I2SDriver *i2sp)
Initializes the standard part of a I2SDriver structure.
void i2sStart (I2SDriver *i2sp, const I2SConfig *config)
Configures and activates the I2S peripheral.
void i2sStop (I2SDriver *i2sp)
Deactivates the I2S peripheral.
void i2sStartExchange (I2SDriver *i2sp)
Starts a I2S data exchange.
void i2sStopExchange (I2SDriver *i2sp)
Stops the ongoing data exchange.
Enumerations
Variables
I2SDriver I2SD1
I2S1 driver identifier.
I2SDriver I2SD2
I2S2 driver identifier.
I2SDriver I2SD3
I2S3 driver identifier.
Macro Definition Documentation
#define STM32_I2S_USE_SPI1 FALSE
I2S1 driver enable switch.
If set to TRUE the support for I2S1 is included.
Note
The default is TRUE.
Definition at line 69 of file hal_i2s_lld.h.
#define STM32_I2S_USE_SPI2 FALSE
I2S2 driver enable switch.
If set to TRUE the support for I2S2 is included.
Note
The default is TRUE.
Definition at line 78 of file hal_i2s_lld.h.
#define STM32_I2S_USE_SPI3 FALSE
I2S3 driver enable switch.
If set to TRUE the support for I2S3 is included.
Note
The default is TRUE.
Definition at line 87 of file hal_i2s_lld.h.
#define STM32_I2S_SPI1_MODE
Value:
(STM32_I2S_MODE_MASTER |        \
                                             STM32_I2S_MODE_RX)
I2S1 mode.
Definition at line 94 of file hal_i2s_lld.h.
#define STM32_I2S_SPI2_MODE
Value:
(STM32_I2S_MODE_MASTER |        \
                                             STM32_I2S_MODE_RX)
I2S2 mode.
Definition at line 102 of file hal_i2s_lld.h.
#define STM32_I2S_SPI3_MODE
Value:
(STM32_I2S_MODE_MASTER |        \
                                             STM32_I2S_MODE_RX)
I2S3 mode.
Definition at line 110 of file hal_i2s_lld.h.
#define STM32_I2S_SPI1_IRQ_PRIORITY 10
I2S1 interrupt priority level setting.
Definition at line 118 of file hal_i2s_lld.h.
Referenced by i2s_lld_start().
#define STM32_I2S_SPI2_IRQ_PRIORITY 10
I2S2 interrupt priority level setting.
Definition at line 125 of file hal_i2s_lld.h.
Referenced by i2s_lld_start().
#define STM32_I2S_SPI3_IRQ_PRIORITY 10
I2S3 interrupt priority level setting.
Definition at line 132 of file hal_i2s_lld.h.
Referenced by i2s_lld_start().
#define STM32_I2S_SPI1_DMA_PRIORITY 1
I2S1 DMA priority (0..3|lowest..highest).
Definition at line 139 of file hal_i2s_lld.h.
Referenced by i2s_lld_init().
#define STM32_I2S_SPI2_DMA_PRIORITY 1
I2S2 DMA priority (0..3|lowest..highest).
Definition at line 146 of file hal_i2s_lld.h.
Referenced by i2s_lld_init().
#define STM32_I2S_SPI3_DMA_PRIORITY 1
I2S3 DMA priority (0..3|lowest..highest).
Definition at line 153 of file hal_i2s_lld.h.
Referenced by i2s_lld_init().
#define STM32_I2S_DMA_ERROR_HOOK (i2sp) osalSysHalt("DMA failure")
I2S DMA error hook.
Definition at line 160 of file hal_i2s_lld.h.
Referenced by i2s_lld_serve_rx_interrupt(), and i2s_lld_serve_tx_interrupt().
#define i2sStartExchangeI (i2sp)
Value:
{                                           \
  i2s_lld_start_exchange(i2sp);                                             \
  (i2sp)->state = I2S_ACTIVE;                                               \
}
Starts a I2S data exchange.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 82 of file hal_i2s.h.
Referenced by i2sStartExchange().
#define i2sStopExchangeI (i2sp)
Value:
{                                            \
  i2s_lld_stop_exchange(i2sp);                                              \
  (i2sp)->state = I2S_READY;                                                \
}
Stops the ongoing data exchange.
The ongoing data exchange, if any, is stopped, if the driver was not active the function does nothing.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 96 of file hal_i2s.h.
Referenced by i2sStopExchange().
#define _i2s_isr_half_code (i2sp)
Value:
{                                          \
  if ((i2sp)->config->end_cb != NULL) {                                     \
    (i2sp)->config->end_cb(i2sp, 0, (i2sp)->config->size / 2);              \
  }                                                                         \
}
Common ISR code, half buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] i2sp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 113 of file hal_i2s.h.
Referenced by i2s_lld_serve_rx_interrupt(), and i2s_lld_serve_tx_interrupt().
#define _i2s_isr_full_code (i2sp)
Value:
{                                               \
  if ((i2sp)->config->end_cb) {                                             \
    (i2sp)->state = I2S_COMPLETE;                                           \
    (i2sp)->config->end_cb(i2sp,                                            \
                           (i2sp)->config->size / 2,                        \
                           (i2sp)->config->size / 2);                       \
    if ((i2sp)->state == I2S_COMPLETE)                                      \
      (i2sp)->state = I2S_READY;                                            \
  }                                                                         \
  else                                                                      \
    (i2sp)->state = I2S_READY;                                              \
}
Common ISR code.
This code handles the portable part of the ISR code:
Callback invocation.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] i2sp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 132 of file hal_i2s.h.
Referenced by i2s_lld_serve_rx_interrupt(), and i2s_lld_serve_tx_interrupt().
Typedef Documentation
typedef struct I2SDriver I2SDriver
Type of a structure representing an I2S driver.
Definition at line 303 of file hal_i2s_lld.h.
typedef void(* i2scallback_t) (I2SDriver *i2sp, size_t offset, size_t n)
I2S notification callback type.
Parameters
[in] i2sp pointer to the I2SDriver object
[in] offset offset in buffers of the data to read/write
[in] n number of samples to read/write
Definition at line 312 of file hal_i2s_lld.h.
Enumeration Type Documentation
enum i2sstate_t
Driver state machine possible states.
Enumerator
I2S_UNINIT
Not initialized.
I2S_STOP
Stopped.
I2S_READY
Ready.
I2S_ACTIVE
Active.
I2S_COMPLETE
Transmission complete.
Definition at line 57 of file hal_i2s.h.
Function Documentation
static void i2s_lld_serve_rx_interrupt (I2SDriver * i2sp, uint32_t flags) static
Shared end-of-rx service routine.
Parameters
[in] i2sp pointer to the I2SDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 153 of file hal_i2s_lld.c.
References _i2s_isr_full_code, _i2s_isr_half_code, and STM32_I2S_DMA_ERROR_HOOK.
Referenced by i2s_lld_start().
static void i2s_lld_serve_tx_interrupt (I2SDriver * i2sp, uint32_t flags) static
Shared end-of-tx service routine.
Parameters
[in] i2sp pointer to the I2SDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 186 of file hal_i2s_lld.c.
References _i2s_isr_full_code, _i2s_isr_half_code, and STM32_I2S_DMA_ERROR_HOOK.
Referenced by i2s_lld_start().
void i2s_lld_init (void)
Low level I2S driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 223 of file hal_i2s_lld.c.
References I2SDriver::cfg, I2SDriver::dmarx, I2SDriver::dmatx, i2sObjectInit(), I2SDriver::rxdmamode, I2SDriver::spi, STM32_DMA_CR_DMEIE, STM32_DMA_STREAM, STM32_I2S_SPI1_DMA_PRIORITY, STM32_I2S_SPI2_DMA_PRIORITY, STM32_I2S_SPI3_DMA_PRIORITY, and I2SDriver::txdmamode.
Referenced by i2sInit().
void i2s_lld_start (I2SDriver * i2sp)
Configures and activates the I2S peripheral.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 353 of file hal_i2s_lld.c.
References I2SDriver::cfg, I2SDriver::config, I2SDriver::dmarx, dmaStreamAllocate(), I2SDriver::dmatx, i2s_lld_serve_rx_interrupt(), i2s_lld_serve_tx_interrupt(), I2S_STOP, I2SConfig::i2scfgr, I2SConfig::i2spr, osalDbgAssert, rccEnableSPI1, rccEnableSPI2, rccEnableSPI3, I2SDriver::spi, I2SDriver::state, STM32_I2S_SPI1_IRQ_PRIORITY, STM32_I2S_SPI2_IRQ_PRIORITY, and STM32_I2S_SPI3_IRQ_PRIORITY.
Referenced by i2sStart().
void i2s_lld_stop (I2SDriver * i2sp)
Deactivates the I2S peripheral.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 473 of file hal_i2s_lld.c.
References I2SDriver::dmarx, dmaStreamRelease(), I2SDriver::dmatx, I2S_READY, rccDisableSPI1, rccDisableSPI2, rccDisableSPI3, I2SDriver::spi, and I2SDriver::state.
Referenced by i2sStop().
void i2s_lld_start_exchange (I2SDriver * i2sp)
Starts a I2S data exchange.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 509 of file hal_i2s_lld.c.
References I2SDriver::config, I2SDriver::dmarx, dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetPeripheral, dmaStreamSetTransactionSize, I2SDriver::dmatx, I2SConfig::i2scfgr, I2SConfig::rx_buffer, I2SDriver::rxdmamode, I2SConfig::size, I2SDriver::spi, I2SConfig::tx_buffer, and I2SDriver::txdmamode.
void i2s_lld_stop_exchange (I2SDriver * i2sp)
Stops the ongoing data exchange.
The ongoing data exchange, if any, is stopped, if the driver was not active the function does nothing.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 555 of file hal_i2s_lld.c.
References I2SDriver::dmarx, dmaStreamDisable, I2SDriver::dmatx, and I2SDriver::spi.
void i2sInit (void)
I2S Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_i2s.c.
References i2s_lld_init().
Referenced by halInit().
void i2sObjectInit (I2SDriver * i2sp)
Initializes the standard part of a I2SDriver structure.
Parameters
[out] i2sp pointer to the I2SDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_i2s.c.
References I2SDriver::config, I2S_STOP, and I2SDriver::state.
Referenced by i2s_lld_init().
void i2sStart (I2SDriver * i2sp, const I2SConfig * config)
Configures and activates the I2S peripheral.
Parameters
[in] i2sp pointer to the I2SDriver object
[in] config pointer to the I2SConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 82 of file hal_i2s.c.
References I2SDriver::config, i2s_lld_start(), I2S_READY, I2S_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2SDriver::state.
void i2sStop (I2SDriver * i2sp)
Deactivates the I2S peripheral.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 102 of file hal_i2s.c.
References I2SDriver::config, i2s_lld_stop(), I2S_READY, I2S_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2SDriver::state.
void i2sStartExchange (I2SDriver * i2sp)
Starts a I2S data exchange.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 125 of file hal_i2s.c.
References I2S_READY, i2sStartExchangeI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2SDriver::state.
void i2sStopExchange (I2SDriver * i2sp)
Stops the ongoing data exchange.
The ongoing data exchange, if any, is stopped, if the driver was not active the function does nothing.
Parameters
[in] i2sp pointer to the I2SDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 144 of file hal_i2s.c.
References I2S_ACTIVE, I2S_COMPLETE, I2S_READY, i2sStopExchangeI, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and I2SDriver::state.
Variable Documentation
I2SDriver I2SD1
I2S1 driver identifier.
Definition at line 123 of file hal_i2s_lld.c.
I2SDriver I2SD2
I2S2 driver identifier.
Definition at line 128 of file hal_i2s_lld.c.
I2SDriver I2SD3
I2S3 driver identifier.
Definition at line 133 of file hal_i2s_lld.c.