ChibiOS/HAL: DAC Driver
DAC Driver
HAL » Normal Drivers
Generic DAC Driver.
Detailed Description
Generic DAC Driver.
This module implements a generic DAC (Digital to Analog Converter) driver.
Precondition
In order to use the MAC driver the HAL_USE_DAC option must be enabled in halconf.h.
Macros
#define DAC_MAX_CHANNELS 1
Max DAC channels.
DAC trigger modes
#define DAC_TRG_MASK 7U
#define DAC_TRG(n) (n)
#define DAC_TRG_EXT 6U
#define DAC_TRG_SW 7U
Configuration options
#define STM32_DAC_DUAL_MODE FALSE
Enables the DAC dual mode.
#define STM32_DAC_USE_DAC1_CH1 FALSE
DAC1 CH1 driver enable switch.
#define STM32_DAC_USE_DAC1_CH2 FALSE
DAC1 CH2 driver enable switch.
#define STM32_DAC_USE_DAC2_CH1 FALSE
DAC2 CH1 driver enable switch.
#define STM32_DAC_USE_DAC2_CH2 FALSE
DAC2 CH2 driver enable switch.
#define STM32_DAC_DAC1_CH1_IRQ_PRIORITY 10
DAC1 CH1 interrupt priority level setting.
#define STM32_DAC_DAC1_CH2_IRQ_PRIORITY 10
DAC1 CH2 interrupt priority level setting.
#define STM32_DAC_DAC2_CH1_IRQ_PRIORITY 10
DAC2 CH1 interrupt priority level setting.
#define STM32_DAC_DAC2_CH2_IRQ_PRIORITY 10
DAC2 CH2 interrupt priority level setting.
#define STM32_DAC_DAC1_CH1_DMA_PRIORITY 2
DAC1 CH1 DMA priority (0..3|lowest..highest).
#define STM32_DAC_DAC1_CH2_DMA_PRIORITY 2
DAC1 CH2 DMA priority (0..3|lowest..highest).
#define STM32_DAC_DAC2_CH1_DMA_PRIORITY 2
DAC2 CH1 DMA priority (0..3|lowest..highest).
#define STM32_DAC_DAC2_CH2_DMA_PRIORITY 2
DAC2 CH2 DMA priority (0..3|lowest..highest).
DAC configuration options
#define DAC_USE_WAIT TRUE
Enables synchronous APIs.
#define DAC_USE_MUTUAL_EXCLUSION TRUE
Enables the dacAcquireBus() and dacReleaseBus() APIs.
Low level driver helper macros
#define _dac_wait_s(dacp) osalThreadSuspendS(&(dacp)->thread)
Waits for operation completion.
#define _dac_reset_i(dacp) osalThreadResumeI(&(dacp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _dac_reset_s(dacp) osalThreadResumeS(&(dacp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _dac_wakeup_isr(dacp)
Wakes up the waiting thread.
#define _dac_timeout_isr(dacp)
Wakes up the waiting thread with a timeout message.
#define _dac_isr_half_code(dacp)
Common ISR code, half buffer event.
#define _dac_isr_full_code(dacp)
Common ISR code, full buffer event.
#define _dac_isr_error_code(dacp, err)
Common ISR code, error event.
Typedefs
typedef uint32_t dacchannel_t
Type of a DAC channel index.
typedef struct DACDriver DACDriver
Type of a structure representing an DAC driver.
typedef uint16_t dacsample_t
Type representing a DAC sample.
typedef void(* daccallback_t) (DACDriver *dacp, dacsample_t *buffer, size_t n)
DAC notification callback type.
typedef void(* dacerrorcallback_t) (DACDriver *dacp, dacerror_t err)
DAC error callback type.
Data Structures
struct dacparams_t
DAC channel parameters type.
struct DACConversionGroup
DAC Conversion group structure.
struct DACConfig
Driver configuration structure.
struct DACDriver
Structure representing a DAC driver.
Functions
static void dac_lld_serve_tx_interrupt (DACDriver *dacp, uint32_t flags)
Shared end/half-of-tx service routine.
void dac_lld_init (void)
Low level DAC driver initialization.
void dac_lld_start (DACDriver *dacp)
Configures and activates the DAC peripheral.
void dac_lld_stop (DACDriver *dacp)
Deactivates the DAC peripheral.
void dac_lld_put_channel (DACDriver *dacp, dacchannel_t channel, dacsample_t sample)
Outputs a value directly on a DAC channel.
void dac_lld_start_conversion (DACDriver *dacp)
Starts a DAC conversion.
void dac_lld_stop_conversion (DACDriver *dacp)
Stops an ongoing conversion.
void dacInit (void)
DAC Driver initialization.
void dacObjectInit (DACDriver *dacp)
Initializes the standard part of a DACDriver structure.
void dacStart (DACDriver *dacp, const DACConfig *config)
Configures and activates the DAC peripheral.
void dacStop (DACDriver *dacp)
Deactivates the DAC peripheral.
void dacPutChannelX (DACDriver *dacp, dacchannel_t channel, dacsample_t sample)
Outputs a value directly on a DAC channel.
void dacStartConversion (DACDriver *dacp, const DACConversionGroup *grpp, dacsample_t *samples, size_t depth)
Starts a DAC conversion.
void dacStartConversionI (DACDriver *dacp, const DACConversionGroup *grpp, dacsample_t *samples, size_t depth)
Starts a DAC conversion.
void dacStopConversion (DACDriver *dacp)
Stops an ongoing conversion.
void dacStopConversionI (DACDriver *dacp)
Stops an ongoing conversion.
msg_t dacConvert (DACDriver *dacp, const DACConversionGroup *grpp, dacsample_t *samples, size_t depth)
Performs a DAC conversion.
void dacAcquireBus (DACDriver *dacp)
Gains exclusive access to the DAC bus.
void dacReleaseBus (DACDriver *dacp)
Releases exclusive access to the DAC bus.
Enumerations
Variables
DACDriver DACD1
DAC1 CH1 driver identifier.
DACDriver DACD2
DAC1 CH2 driver identifier.
DACDriver DACD3
DAC2 CH1 driver identifier.
DACDriver DACD4
DAC2 CH2 driver identifier.
Macro Definition Documentation
#define STM32_DAC_DUAL_MODE FALSE
Enables the DAC dual mode.
Note
In dual mode DAC second channels cannot be accessed individually.
Definition at line 57 of file hal_dac_lld.h.
#define STM32_DAC_USE_DAC1_CH1 FALSE
DAC1 CH1 driver enable switch.
If set to TRUE the support for DAC1 channel 1 is included.
Note
The default is FALSE.
Definition at line 66 of file hal_dac_lld.h.
#define STM32_DAC_USE_DAC1_CH2 FALSE
DAC1 CH2 driver enable switch.
If set to TRUE the support for DAC1 channel 2 is included.
Note
The default is FALSE.
Definition at line 75 of file hal_dac_lld.h.
#define STM32_DAC_USE_DAC2_CH1 FALSE
DAC2 CH1 driver enable switch.
If set to TRUE the support for DAC2 channel 1 is included.
Note
The default is FALSE.
Definition at line 84 of file hal_dac_lld.h.
#define STM32_DAC_USE_DAC2_CH2 FALSE
DAC2 CH2 driver enable switch.
If set to TRUE the support for DAC2 channel 2 is included.
Note
The default is FALSE.
Definition at line 93 of file hal_dac_lld.h.
#define STM32_DAC_DAC1_CH1_IRQ_PRIORITY 10
DAC1 CH1 interrupt priority level setting.
Definition at line 100 of file hal_dac_lld.h.
#define STM32_DAC_DAC1_CH2_IRQ_PRIORITY 10
DAC1 CH2 interrupt priority level setting.
Definition at line 107 of file hal_dac_lld.h.
#define STM32_DAC_DAC2_CH1_IRQ_PRIORITY 10
DAC2 CH1 interrupt priority level setting.
Definition at line 114 of file hal_dac_lld.h.
#define STM32_DAC_DAC2_CH2_IRQ_PRIORITY 10
DAC2 CH2 interrupt priority level setting.
Definition at line 121 of file hal_dac_lld.h.
#define STM32_DAC_DAC1_CH1_DMA_PRIORITY 2
DAC1 CH1 DMA priority (0..3|lowest..highest).
Definition at line 128 of file hal_dac_lld.h.
#define STM32_DAC_DAC1_CH2_DMA_PRIORITY 2
DAC1 CH2 DMA priority (0..3|lowest..highest).
Definition at line 135 of file hal_dac_lld.h.
#define STM32_DAC_DAC2_CH1_DMA_PRIORITY 2
DAC2 CH1 DMA priority (0..3|lowest..highest).
Definition at line 142 of file hal_dac_lld.h.
#define STM32_DAC_DAC2_CH2_DMA_PRIORITY 2
DAC2 CH2 DMA priority (0..3|lowest..highest).
Definition at line 149 of file hal_dac_lld.h.
#define DAC_MAX_CHANNELS 1
Max DAC channels.
Definition at line 232 of file hal_dac_lld.h.
Referenced by dacPutChannelX().
#define DAC_USE_WAIT TRUE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 47 of file hal_dac.h.
#define DAC_USE_MUTUAL_EXCLUSION TRUE
Enables the dacAcquireBus() and dacReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 55 of file hal_dac.h.
#define _dac_wait_s (dacp) osalThreadSuspendS(&(dacp)->thread)
Waits for operation completion.
This function waits for the driver to complete the current operation.
Precondition
An operation must be running while the function is invoked.
Note
No more than one thread can wait on a DAC driver using this function.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 102 of file hal_dac.h.
#define _dac_reset_i (dacp) osalThreadResumeI(&(dacp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 111 of file hal_dac.h.
Referenced by dacStopConversionI().
#define _dac_reset_s (dacp) osalThreadResumeS(&(dacp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 120 of file hal_dac.h.
Referenced by dacStopConversion().
#define _dac_wakeup_isr (dacp)
Value:
{                                             \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(dacp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 129 of file hal_dac.h.
#define _dac_timeout_isr (dacp)
Value:
{                                            \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(dacp)->thread, MSG_TIMEOUT);                          \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread with a timeout message.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 142 of file hal_dac.h.
#define _dac_isr_half_code (dacp)
Value:
{                                          \
  if ((dacp)->grpp->end_cb != NULL) {                                       \
    (dacp)->grpp->end_cb(dacp, (dacp)->samples, (dacp)->depth / 2);         \
  }                                                                         \
}
Common ISR code, half buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 168 of file hal_dac.h.
Referenced by dac_lld_serve_tx_interrupt().
#define _dac_isr_full_code (dacp)
Value:
{                                          \
  if ((dacp)->grpp->end_cb != NULL) {                                       \
    if ((dacp)->depth > 1) {                                                \
      /* Invokes the callback passing the 2nd half of the buffer.*/         \
      size_t half = (dacp)->depth / 2;                                      \
      size_t half_index = half * (dacp)->grpp->num_channels;                \
      (dacp)->grpp->end_cb(dacp, (dacp)->samples + half_index, half);       \
    }                                                                       \
    else {                                                                  \
      /* Invokes the callback passing the whole buffer.*/                   \
      (dacp)->grpp->end_cb(dacp, (dacp)->samples, (dacp)->depth);           \
    }                                                                       \
  }                                                                         \
}
Common ISR code, full buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 188 of file hal_dac.h.
Referenced by dac_lld_serve_tx_interrupt().
#define _dac_isr_error_code (dacp, err)
Value:
{                                    \
  dac_lld_stop_conversion(dacp);                                            \
  if ((dacp)->grpp->error_cb != NULL) {                                     \
    (dacp)->state = DAC_ERROR;                                              \
    (dacp)->grpp->error_cb(dacp, err);                                      \
    if ((dacp)->state == DAC_ERROR)                                         \
      (dacp)->state = DAC_READY;                                            \
  }                                                                         \
  (dacp)->grpp = NULL;                                                      \
  _dac_timeout_isr(dacp);                                                   \
}
Common ISR code, error event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread timeout signaling, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] dacp pointer to the DACDriver object
[in] err platform dependent error code
Function Class:
Not an API, this function is for internal use only.
Definition at line 218 of file hal_dac.h.
Referenced by dac_lld_serve_tx_interrupt().
Typedef Documentation
typedef uint32_t dacchannel_t
Type of a DAC channel index.
Definition at line 244 of file hal_dac_lld.h.
typedef struct DACDriver DACDriver
Type of a structure representing an DAC driver.
Definition at line 283 of file hal_dac_lld.h.
typedef uint16_t dacsample_t
Type representing a DAC sample.
Definition at line 288 of file hal_dac_lld.h.
typedef void(* daccallback_t) (DACDriver *dacp, dacsample_t *buffer, size_t n)
DAC notification callback type.
Parameters
[in] dacp pointer to the DACDriver object triggering the
[in] buffer pointer to the next semi-buffer to be filled
[in] n number of buffer rows available starting from buffer callback
Definition at line 308 of file hal_dac_lld.h.
typedef void(* dacerrorcallback_t) (DACDriver *dacp, dacerror_t err)
DAC error callback type.
Parameters
[in] dacp pointer to the DACDriver object triggering the callback
[in] err DAC error code
Definition at line 317 of file hal_dac_lld.h.
Enumeration Type Documentation
enum dacerror_t
Possible DAC failure causes.
Note
Error codes are architecture dependent and should not relied upon.
Enumerator
DAC_ERR_DMAFAILURE
DMA operations failure.
DAC_ERR_UNDERFLOW
DAC overflow condition.
Definition at line 295 of file hal_dac_lld.h.
enum dacdhrmode_t
Samples alignment and size mode.
Definition at line 322 of file hal_dac_lld.h.
enum dacstate_t
Driver state machine possible states.
Enumerator
DAC_UNINIT
Not initialized.
DAC_STOP
Stopped.
DAC_READY
Ready.
DAC_ACTIVE
Exchanging data.
DAC_COMPLETE
Asynchronous operation complete.
DAC_ERROR
Error.
Definition at line 70 of file hal_dac.h.
Function Documentation
static void dac_lld_serve_tx_interrupt (DACDriver * dacp, uint32_t flags) static
Shared end/half-of-tx service routine.
Parameters
[in] dacp pointer to the DACDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 158 of file hal_dac_lld.c.
References _dac_isr_error_code, _dac_isr_full_code, _dac_isr_half_code, and DAC_ERR_DMAFAILURE.
Referenced by dac_lld_start_conversion().
void dac_lld_init (void)
Low level DAC driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 189 of file hal_dac_lld.c.
References dacObjectInit(), and DACDriver::params.
Referenced by dacInit().
void dac_lld_start (DACDriver * dacp)
Configures and activates the DAC peripheral.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 219 of file hal_dac_lld.c.
References DACDriver::config, DACConfig::cr, dacparams_t::dac, dac_lld_put_channel(), DAC_STOP, DACConfig::datamode, DACConfig::init, DACDriver::params, rccEnableDAC1, dacparams_t::regmask, dacparams_t::regshift, and DACDriver::state.
Referenced by dacStart().
void dac_lld_stop (DACDriver * dacp)
Deactivates the DAC peripheral.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 280 of file hal_dac_lld.c.
References dacparams_t::dac, DAC_READY, DACDriver::params, rccDisableDAC1, dacparams_t::regmask, and DACDriver::state.
Referenced by dacStop().
void dac_lld_put_channel (DACDriver * dacp, dacchannel_t channel, dacsample_t sample)
Outputs a value directly on a DAC channel.
Parameters
[in] dacp pointer to the DACDriver object
[in] channel DAC channel number
[in] sample value to be output
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 331 of file hal_dac_lld.c.
References DACDriver::config, dacparams_t::dac, DACConfig::datamode, dacparams_t::dataoffset, osalDbgAssert, and DACDriver::params.
Referenced by dac_lld_start(), and dacPutChannelX().
void dac_lld_start_conversion (DACDriver * dacp)
Starts a DAC conversion.
Starts an asynchronous conversion operation.
Note
In DAC_DHRM_8BIT_RIGHT mode the parameters passed to the callback are wrong because two samples are packed in a single dacsample_t element. This will not be corrected, do not rely on those parameters.
In DAC_DHRM_8BIT_RIGHT_DUAL mode two samples are treated as a single 16 bits sample and packed into a single dacsample_t element. The num_channels must be set to one in the group conversion configuration structure.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 409 of file hal_dac_lld.c.
References DACDriver::config, DACConfig::cr, dacparams_t::dac, dac_lld_serve_tx_interrupt(), DACConfig::datamode, dacparams_t::dataoffset, DACDriver::depth, dacparams_t::dma, dacparams_t::dmairqprio, dacparams_t::dmamode, dmaStreamAllocate(), dmaStreamEnable, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetPeripheral, dmaStreamSetTransactionSize, DACDriver::grpp, DACConversionGroup::num_channels, osalDbgAssert, DACDriver::params, dacparams_t::regmask, dacparams_t::regshift, DACDriver::samples, STM32_DMA_CR_DMEIE, and DACConversionGroup::trigger.
Referenced by dacStartConversionI().
void dac_lld_stop_conversion (DACDriver * dacp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the DAC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 513 of file hal_dac_lld.c.
References DACDriver::config, DACConfig::cr, dacparams_t::dac, DACConfig::datamode, dacparams_t::dma, dmaStreamDisable, dmaStreamRelease(), DACDriver::params, dacparams_t::regmask, and dacparams_t::regshift.
Referenced by dacStopConversion(), and dacStopConversionI().
void dacInit (void)
DAC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_dac.c.
References dac_lld_init().
Referenced by halInit().
void dacObjectInit (DACDriver * dacp)
Initializes the standard part of a DACDriver structure.
Parameters
[out] dacp pointer to the DACDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_dac.c.
References DACDriver::config, DAC_STOP, DACDriver::mutex, osalMutexObjectInit(), DACDriver::state, and DACDriver::thread.
Referenced by dac_lld_init().
void dacStart (DACDriver * dacp, const DACConfig * config)
Configures and activates the DAC peripheral.
Parameters
[in] dacp pointer to the DACDriver object
[in] config pointer to the DACConfig object, it can be NULL if the low level driver implementation supports a default configuration
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 93 of file hal_dac.c.
References DACDriver::config, dac_lld_start(), DAC_READY, DAC_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and DACDriver::state.
void dacStop (DACDriver * dacp)
Deactivates the DAC peripheral.
Note
Deactivating the peripheral also enforces a release of the slave select line.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 118 of file hal_dac.c.
References DACDriver::config, dac_lld_stop(), DAC_READY, DAC_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and DACDriver::state.
void dacPutChannelX (DACDriver * dacp, dacchannel_t channel, dacsample_t sample)
Outputs a value directly on a DAC channel.
Parameters
[in] dacp pointer to the DACDriver object
[in] channel DAC channel number
[in] sample value to be output
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 143 of file hal_dac.c.
References dac_lld_put_channel(), DAC_MAX_CHANNELS, DAC_READY, osalDbgAssert, osalDbgCheck, and DACDriver::state.
void dacStartConversion (DACDriver * dacp, const DACConversionGroup * grpp, dacsample_t * samples, size_t depth)
Starts a DAC conversion.
Starts an asynchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] dacp pointer to the DACDriver object
[in] grpp pointer to a DACConversionGroup object
[in] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 167 of file hal_dac.c.
References dacStartConversionI(), osalSysLock(), and osalSysUnlock().
void dacStartConversionI (DACDriver * dacp, const DACConversionGroup * grpp, dacsample_t * samples, size_t depth)
Starts a DAC conversion.
Starts an asynchronous conversion operation.
Postcondition
The callbacks associated to the conversion group will be invoked on buffer fill and error events.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] dacp pointer to the DACDriver object
[in] grpp pointer to a DACConversionGroup object
[in] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 195 of file hal_dac.c.
References DAC_ACTIVE, DAC_COMPLETE, DAC_ERROR, dac_lld_start_conversion(), DAC_READY, DACDriver::depth, DACDriver::grpp, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, DACDriver::samples, and DACDriver::state.
Referenced by dacConvert(), and dacStartConversion().
void dacStopConversion (DACDriver * dacp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the DAC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 225 of file hal_dac.c.
References _dac_reset_s, DAC_ACTIVE, dac_lld_stop_conversion(), DAC_READY, DACDriver::grpp, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and DACDriver::state.
void dacStopConversionI (DACDriver * dacp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the DAC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 255 of file hal_dac.c.
References _dac_reset_i, DAC_ACTIVE, DAC_COMPLETE, dac_lld_stop_conversion(), DAC_READY, DACDriver::grpp, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and DACDriver::state.
msg_t dacConvert (DACDriver * dacp, const DACConversionGroup * grpp, dacsample_t * samples, size_t depth)
Performs a DAC conversion.
Performs a synchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] dacp pointer to the DACDriver object
[in] grpp pointer to a DACConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Returns
The operation result.
Return values
MSG_OK Conversion finished.
MSG_RESET The conversion has been stopped using acdStopConversion() or acdStopConversionI(), the result buffer may contain incorrect data.
MSG_TIMEOUT The conversion has been stopped because an hardware error.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 296 of file hal_dac.c.
References dacStartConversionI(), osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), and DACDriver::thread.
void dacAcquireBus (DACDriver * dacp)
Gains exclusive access to the DAC bus.
This function tries to gain ownership to the DAC bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option DAC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 324 of file hal_dac.c.
References DACDriver::mutex, osalDbgCheck, and osalMutexLock().
void dacReleaseBus (DACDriver * dacp)
Releases exclusive access to the DAC bus.
Precondition
In order to use this function the option DAC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] dacp pointer to the DACDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 340 of file hal_dac.c.
References DACDriver::mutex, osalDbgCheck, and osalMutexUnlock().
Variable Documentation
DACDriver DACD1
DAC1 CH1 driver identifier.
Definition at line 62 of file hal_dac_lld.c.
DACDriver DACD2
DAC1 CH2 driver identifier.
Definition at line 67 of file hal_dac_lld.c.
DACDriver DACD3
DAC2 CH1 driver identifier.
Definition at line 72 of file hal_dac_lld.c.
DACDriver DACD4
DAC2 CH2 driver identifier.
Definition at line 77 of file hal_dac_lld.c.